/* ==========================================================
   Falas do Bugado — Memória (jogo de pares)
   Variáveis: {nome} = card/personagem · {a} {b} = os dois cards virados
              {n} = número (nível, sequência, vezes) · {tema} = tema escolhido
              {t} = tempo (mm:ss) · {m} = jogadas · {xp} = XP ganho
   Categorias com prefixo "mem". Falas por personagem em PERS (viram "memP:<nome>").
   ========================================================== */
(() => {
const L = {

/* ---------- abrindo a página ---------- */
memOi: [
  'Bem-vindo ao Memória! O jogo onde eu descubro que você não lembra nem onde deixou o celular. Que tá na sua mão.',
  'Memória! Vira dois cards, acha os pares, e eu comento cada vacilo. Combinado? Não perguntei.',
  'Chegou no jogo da memória. Espero que você tenha trazido a sua. Se não, eu empresto a minha. Mentira, é de 8 bits.',
  'Olha só, alguém veio treinar o cérebro. Ou fingir que treina enquanto enrola o trabalho.',
  'Jogo da memória: clássico de festa infantil, agora com um gato-fantasma sarcástico. Evolução.',
  'Pares escondidos, cards virados, e eu aqui de camarote. Bora.',
  'Se você lembrar onde tá cada card, parabéns. Se não, eu lembro. E vou jogar na sua cara.',
  'Memória de elefante ou de peixinho dourado? Vamos descobrir em três… dois… vira um card aí.'
],
memVoltou: [
  'Voltou! Eu lembrei de você. Diferente de você com os cards.',
  'Ah, você de novo. Os cards também sentiram saudade. Mentira, eles não sentem nada. São cards.',
  'De volta pra Jornada. Seu progresso tá salvo. Sua dignidade, nem tanto.',
  'Bem-vindo de volta. Eu guardei seu nível e suas estrelas. As vergonhas também, num arquivo separado.',
  'Voltou pra mais? Isso é vício ou treino? Não responde, eu já sei.',
  'Opa, retorno triunfal! Vamos ver se a memória voltou junto.',
  'Você sumiu e eu fiquei aqui contando cards. São muitos. Perdi a conta. Culpa sua.',
  'Retomando a Jornada. Última vez você tava indo bem. Mais ou menos. Tá, indo.'
],

/* ---------- embaralhando (carregando imagens) ---------- */
memEmbaralhando: [
  'Embaralhando… não olha! Tá, pode olhar, não dá pra ver nada mesmo.',
  'Misturando os cards. Com a pata. Não tenho mão. Não pergunta.',
  'Um momento, tô escondendo os Pokémon. Eles não colaboram.',
  'Baixando as figurinhas… mais rápido que completar álbum da Copa, pelo menos.',
  'Embaralhando igual crupiê de cassino. Só que bugado. E sem cassino.',
  'Carregando os cards… se demorar, a culpa é da internet. Sempre é da internet.',
  'Chamando os bichinhos pro tabuleiro. Uns vêm rápido, outros são o Slowpoke.',
  'Espera aí que eu tô tirando os cards do plástico. Cheirinho de card novo.',
  'Embaralhando com técnica secreta. A técnica é jogar tudo pro alto.',
  'Separando os pares e depois separando os pares de novo. Filosofia.',
  'Preparando o tabuleiro. Dá tempo de estalar os dedos. Os meus não estalam, são pixels.',
  'Colocando os cards virados pra baixo. É mais difícil do que parece quando você é um fantasma.'
],

/* ---------- primeira virada da partida ---------- */
memPrimeiro: [
  'Primeiro card! O começo de uma longa jornada de esquecimento.',
  'Virou o primeiro. Agora lembra dele. Pra sempre. Ou por uns dez segundos.',
  'E começou! Cronômetro rodando, cérebro… carregando.',
  'Primeira carta na mesa. Tô sentindo cheiro de recorde. Ou de queimado.',
  'Ó, abriu os trabalhos. Vai com calma que o card não foge.',
  'Primeiro card virado. Estatisticamente, o próximo vai ser errado. Sem pressão.',
  'Bom começo! Virar um card é fácil. O difícil é o segundo.',
  'Olha ele! Grava bem essa carinha, que ela vai sumir já já.',
  'Vamos lá! Memoriza a posição, a cor, o nome, o signo…',
  'Tá valendo! Eu tô contando as jogadas. E julgando cada uma.',
  'Primeira virada, primeira foto na memória. Tomara que não esteja tremida.',
  'Começou! Se errar, finge que foi de propósito. Eu finjo que acredito.',
  'Card número um! Guardou? Guarda. Eu vou perguntar depois. Mentira, eu só vou rir.',
  'Abriu com estilo. Quer dizer, abriu. Estilo é outra conversa.',
  'E lá vamos nós. Minha aposta: primeiro erro em três jogadas.',
  'Virou! Agora é só achar o irmão gêmeo dele. Fácil. Muito fácil. Né?',
  'Primeiro passo dado. O Ash também começou assim e demorou 25 anos.',
  'Um card virado. Faltam só uns milhões de neurônios trabalhando.',
  'Cronômetro ligado! A partir de agora cada segundo de dúvida vai pro seu currículo.',
  'Olha só, começou sem nem aquecer. Corajoso. Ou impaciente.'
],

/* ---------- acertou um par (com nome) ---------- */
memPar: [
  'Par de {nome}! Eles tavam com saudade um do outro.',
  '{nome} reencontrou o gêmeo. Chorei. Tá, não chorei. Mas quase.',
  'Achou os dois {nome}! Casal formado, pode sair do tabuleiro.',
  'Boa! {nome} e {nome}. Dupla dinâmica.',
  '{nome} achado! Esse cérebro às vezes funciona. Às vezes.',
  'Par de {nome} garantido. Anotei no seu boletim.',
  'Aí sim! Os {nome} agradecem a reunião familiar.',
  '{nome} + {nome} = ponto pra você. Matemática de fliperama.',
  'Achou o {nome}! Eu sabia que você lembrava. Eu não sabia, mas vou fingir.',
  'Que beleza, {nome} em dobro. Dobro de fofura, dobro de ponto.',
  'Mandou bem com o {nome}. Tá vendo? Quando quer, consegue.',
  'Par feito: {nome}. O tabuleiro ficou mais leve.',
  '{nome} encontrou o par antes de muita gente encontrar o amor.',
  'Olha o {nome} brilhando! Não, é só a animação. Mas bonito, né?',
  'Os dois {nome} se acharam. Você foi o cupido. Parabéns, cupido.',
  'Acertou {nome}! Minha aposta contra você perdeu. Eu apostei comigo mesmo.',
  '{nome} achado. Aposto que você decorou só esse.',
  'Isso! {nome} tava ali esperando você lembrar dele.',
  'Par de {nome}! O Professor Carvalho ficaria orgulhoso. Ou nem ligaria.',
  'Bateu! {nome} com {nome}. Match perfeito, melhor que app de namoro.',
  '{nome} fora do tabuleiro. Um a menos pra você esquecer.',
  'Boa memória com o {nome}. Agora faz isso com o resto.',
  'Olha quem achou o {nome}! Esse aí vai pro mural.',
  'Par de {nome}. Registrado, carimbado e comentado por mim.',
  'Acertou o {nome} e eu fiquei sem piada. Espera, achei uma: nenhuma. Tá bom.',
  '{nome} achou o par. Você tá virando uma Pokédex ambulante.',
  'Aeee, {nome}! Faz aquela dancinha. Eu faço por você: *dancinha*.',
  'Esse {nome} não escapou. Memória de caçador.',
  '{nome} reunido. Se tivesse trilha sonora, tocava agora.',
  'Achou {nome}. Eu tinha certeza que você ia errar esse. Ainda bem que ninguém me ouviu.',
  'Par de {nome}! Coloca no currículo: “encontra {nome} com eficiência”.',
  '{nome}, {nome}. Falando duas vezes pra comemorar.',
  'Isso aí, {nome} no bolso. Literalmente, se fosse Pokébola.',
  'Uhul, {nome}! Quem diria que essa cabeça guardava alguma coisa.',
  'Mais um par: {nome}. Tá ficando perigoso esse seu cérebro.',
  'Encontrou {nome}. Vou fingir que não fiquei impressionado.',
  '{nome} achado! O tabuleiro tá tremendo de medo.',
  'Boa! Os {nome} vão sair daqui de mãos dadas.',
  'Par de {nome}. Eu teria errado. Mentira. Mas você não sabe.',
  '{nome} garantido. Se continuar assim, eu vou ter que arrumar outro emprego.'
],
/* ---------- acertou (genérico, sem nome) ---------- */
memParGeral: [
  'Acertou! Guardou bem, hein.',
  'Par! Isso é memória ou chute? Não responde, deixa eu sonhar.',
  'Boa! Mais um fora da mesa.',
  'Tá vendo? Não era tão difícil.',
  'Clique, clique, par. Simples assim.',
  'Isso! Seu neurônio favorito tá trabalhando hoje.',
  'Mais um par. Tô começando a me preocupar com a sua memória. Ela tá boa demais.',
  'Acerto limpo. Sem sujeira, sem drama.',
  'Olha só quem lembra das coisas!',
  'Par feito. Posso até parar de zoar. Por uns cinco segundos.',
  'Muito bem! Recebe aí um carinho imaginário.',
  'Certinho! Parece até que você treina escondido.',
  'Bateu! O barulhinho de acerto é o som mais lindo do mundo, né?',
  'Pronto, mais um. O tabuleiro tá ficando vazio igual minha geladeira.',
  'Ótimo! Continua assim que eu fico quieto. Mentira. Eu nunca fico quieto.',
  'Belo par. Pendura na parede.',
  'Acertou! Aposto que tá com aquele sorrisinho agora.',
  'Boa jogada. Anotei. Vou usar contra você depois.',
  'Isso aí! Memória funcionando, sistema estável.',
  'Mais um! Tá rápido. Suspeito, até.',
  'Par! Seu cérebro acabou de ganhar um biscoito.',
  'Correto. Eu diria “uau”, mas não quero te deixar convencido.',
  'Acertou mais uma. Isso é memória ou você tá anotando num papel?',
  'Bingo! Não, espera, jogo errado. Par! Isso.',
  'Fechou mais um par. Clique de ouro.'
],

/* ---------- acertou de primeira os dois (nunca tinha visto nenhum) ---------- */
memSorte: [
  'Achou o par de primeira? Sorte ou memória? Eu aposto em sorte.',
  'Nunca tinha visto nenhum dos dois e acertou. Isso tem nome: sorte de principiante.',
  'Os dois de primeira?! Joga na loteria hoje. Sério.',
  'Acerto às cegas! Você tem visão de raio-X ou é bruxaria?',
  'Nem viu antes e acertou. Vou fingir que foi habilidade pra não te magoar.',
  'Sorte pura! Isso não conta pra memória, mas conta ponto. Injusto, mas conta.',
  'Chute certeiro no escuro. O Kuririn nunca teve essa sorte na vida.',
  'Tá com trevo de quatro folhas no bolso? Acertou sem ver nenhum antes!',
  'Sorte grande! Se você fosse Pokémon, seu ataque seria “Chute Abençoado”.',
  'Cara, isso foi sorte. Não adianta fazer pose.',
  'Primeira vez vendo os dois e já é par. O universo gosta de você hoje.',
  'Eu vi isso. Foi sorte. Todo mundo viu. Até o Magikarp viu.',
  'Acertou sem saber! É tipo passar na prova chutando tudo C.',
  'O destino juntou esses dois, não a sua memória. Só pra deixar claro.',
  'Isso é o que eu chamo de clique abençoado. Vai rezar pra quem, hein?',
  'Sorte nível Mr. Satan ganhando o torneio. Ninguém entende, mas aconteceu.',
  'Achou de primeira, sem pista nenhuma. Tô desconfiado de você.',
  'Uau. Pura sorte. Mas eu não posso provar. Ainda.',
  'Essa foi no chute e entrou no ângulo. Golaço de sorte.',
  'Se a sorte fosse um Pokémon, ela tava na sua party agora.',
  'Sorteou certinho! O Mestre Kame chamaria isso de “intuição”. Eu chamo de milagre.',
  'Ah, pronto. Agora vai achar que é gênio. Foi sorte, viu?',
  'Nem piscou e acertou. Olho de águia? Não. Sorte de galinha.',
  'Tá, essa eu vou deixar passar. Sorte também é talento. Tipo, um talento bem pequeno.',
  'Os deuses do embaralhamento sorriram pra você. Eu não. Eu só observo.'
],

/* ---------- errou (com os dois nomes) ---------- */
memErro: [
  '{a} e {b}? Nem parentes são.',
  '{a} com {b}? Isso aí nem no Tinder dá match.',
  'Errou. {a} tá olhando pro {b} com cara de “quem é você?”.',
  '{a} e {b}. Combinação criativa. Errada, mas criativa.',
  'Não, não. {a} não é par do {b}. Eles nem se falam.',
  'Você tentou juntar {a} com {b}. O universo recusou.',
  '{a} e {b}? Eu entendi a ideia. Não, mentira, não entendi.',
  'Ops. {a} e {b} vão voltar a se esconder agora.',
  'Mistura de {a} com {b}. Se existisse, seria um glitch. Tipo eu.',
  '{a} ≠ {b}. Matemática básica de memória.',
  'Errou! Mas pelo menos agora você sabe onde tá o {a}. E o {b}. Né? Né?',
  '{a} e {b}: dupla que ninguém pediu.',
  'Quase! Não, mentira. {a} e {b} não têm nada a ver.',
  'Tentou {a} com {b}. Gostei da ousadia. Não do resultado.',
  '{b}? Você queria o outro {a}. Faz de conta que eu não vi.',
  'Nope. {a} e {b} são tão diferentes quanto pizza e sorvete. Ambos bons, mas não é par.',
  '{a} e {b}. Anota aí: onde tá cada um. Por favor.',
  'Errou, mas errou bonito. {a} e {b} até posaram pra foto.',
  'Essa não! {a} voltou pro escuro e levou o {b} junto.',
  '{a} e {b}? Seu cérebro tava de férias nessa jogada.',
  'Nem perto. {a} e {b} nunca estiveram no mesmo episódio.',
  'Hmm, {a} e {b}. Uma escolha. Não a certa, mas uma escolha.',
  'O {a} esperava o gêmeo e veio o {b}. Decepção familiar.',
  'Não rolou! {a} e {b} vão fingir que isso não aconteceu.',
  'Errou. Mas agora você tem mais informação. Usa ela, pelo amor.',
  '{a} e {b} discordam da sua decisão.',
  'Essa foi um desastre elegante: {a} e {b}.',
  'Tentou o {b} pensando que era {a}? Oculista, talvez?',
  'Nãããão. {a} e {b} nem torcem pro mesmo time.',
  'Não é par. {a} e {b} se cumprimentaram e foram embora.',
  'Errou, mas eu gostei do {b}. Ele tem estilo.',
  '{a} com {b}: fusão falhou. Nem o Gotenks salvaria isso.',
  'Hmm, {a} e {b}. Seu cérebro chutou e o goleiro pegou.',
  'Negativo! {a} e {b} tão em times diferentes.',
  'Tadinho do {a}, achou que ia ter companhia. Veio o {b}.',
  'Não é par, mas é aprendizado. Lembra: {a} aqui, {b} ali.',
  'Errou de novo? Não, espera, essa é a primeira. Ainda.',
  '{a} e {b}. Esse erro vai pro meu caderninho.',
  'Os dois viraram e disseram: “não somos parentes”.',
  'Clique errado detectado. {a} e {b} protestam.',
  '{a} tava ali sozinho e você trouxe o {b}. Climão.',
  'Poxa, {a} e {b}. Nem de longe. Nem de perto também.',
  'Tentativa de juntar {a} e {b}: rejeitada pelo sistema.',
  'Errou! O {b} ficou até sem graça.',
  'Não, não e não. {a} e {b} nem se conhecem direito.'
],

/* ---------- errou algo que já tinha visto ("você já viu esse!") ---------- */
memJaViu: [
  'Você JÁ VIU o par do {nome}! Tava ali, olhando pra você!',
  'O outro {nome} já apareceu antes. Você só… esqueceu. Clássico.',
  'Ei! Você já tinha visto onde tava o {nome}. Memória de peixinho dourado detectada.',
  'O {nome} tá magoado. Você viu o gêmeo dele e fingiu que não.',
  'Cara, o par do {nome} já tinha aparecido! Eu vi. O tabuleiro viu. Só você não.',
  'Você já sabia onde tava o {nome}. Sabia! Eu tenho provas.',
  'Olha, eu não quero ser chato, mas o outro {nome} tava bem ali. Tá, quero ser chato.',
  'Esquecimento clássico: o {nome} já tinha aparecido e você deixou passar.',
  'Isso dói em mim: o {nome} já tinha sido revelado e você foi em outro.',
  'O par do {nome} já apareceu. Você viu. Seu cérebro não salvou o arquivo.',
  'Tu já viu o {nome}! Ctrl+Z na memória, por favor.',
  'O {nome} tá acenando desesperado: “eu tava aqui, lembra?”. Não lembrou.',
  'Hmm, o gêmeo do {nome} já tinha aparecido. Tá tudo bem aí dentro?',
  'Esse era fácil! O {nome} já tinha mostrado a cara antes.',
  'Você viu o {nome}, deu tchau e esqueceu. Relação complicada.',
  'Já tinha visto! JÁ TINHA VISTO! Tô gritando por dentro. E por fora.',
  'O outro {nome} ficou triste. Ele achou que tinha deixado uma boa impressão.',
  'Memória RAM cheia? O {nome} já tinha aparecido.',
  'Você passou pelo par do {nome} e nem cumprimentou. Mal-educado.',
  'O {nome} já estava revelado nesse tabuleiro. Isso não é sorte ruim, é esquecimento.',
  'Informação disponível, informação ignorada. O {nome} já tinha aparecido.',
  'Vou fingir que você não viu o {nome} antes. Não, não vou. Você viu.',
  'O par do {nome}! Você viu! Eu quase apertei o card por você.',
  'Tá jogando memória ou jogando sorte? Porque o {nome} já tinha aparecido.',
  'Esqueceu o {nome}. Ele não esqueceu de você. Isso é triste.',
  'Você tinha tudo pra acertar o {nome}. Tudo! E foi pro outro lado.',
  'O {nome} já tinha dado as caras. Seu cérebro deu “visualizou e não respondeu”.',
  'Anota aí: você JÁ viu o {nome}. A próxima vez vai ser vergonha dupla.',
  'Déjà vu? Não. Você realmente já viu o {nome}. E errou mesmo assim.',
  'Tava escrito na parede, na testa, no céu: o {nome} já tinha aparecido.'
],

memJaViuEvo: [
  'O {b} já tinha aparecido! Ele é o par do {a}. Família separada por esquecimento.',
  'Você já viu o {b}! E ele é justamente o parente do {a}. Dói, né?',
  'O {a} procurava o {b}. O {b} já tinha dado as caras. Você foi em outro.',
  'Árvore genealógica ignorada: o {b} já tinha aparecido e é o par do {a}.',
  'O {b} tava ali, revelado, esperando o {a}. Você deixou os dois no vácuo.',
  'Reunião de família cancelada: você já tinha visto o {b}, par do {a}.',
  'Ei! O {b} já apareceu! É dele que o {a} precisa.',
  'Memória de peixinho dourado: o {b}, par do {a}, já tinha sido virado.'
],

/* ---------- mesmo card virado muitas vezes ---------- */
memMesmaCarta: [
  'Você virou o {nome} {n} vezes. Ele já tá com dor de cabeça.',
  '{n} vezes o {nome}! Vocês estão namorando?',
  'Flipou o {nome} de novo. Memória de peixinho dourado detectada.',
  'O {nome} já decorou a sua cara. {n} visitas. Você ainda não decorou a dele.',
  '{nome} de novo?! Esse card vai pedir adicional de insalubridade.',
  'Virou o {nome} pela {n}ª vez. Ele vai começar a cobrar ingresso.',
  'O {nome} tá tonto de tanto girar. {n} vezes, gente.',
  'Esse {nome} já é de casa. {n} vezes. Oferece um café pra ele.',
  'Você e o {nome} têm uma relação estranha. Ele aparece, você esquece. {n} vezes.',
  'Olha o {nome} aí de novo! Pela {n}ª vez. E ainda sem par.',
  'O {nome} já tá gasto. Card de segunda mão agora.',
  '{n} vezes virando o {nome}. Eu já sei onde tá o par dele. Não vou contar.',
  'O {nome} tá pensando em se mudar pra outro tabuleiro. {n} vezes é demais.',
  'Esse {nome} já girou mais que pião. {n} vezes!',
  'Parabéns, você desbloqueou: “Fã número 1 do {nome}”. {n} viradas.',
  'Tá virando o {nome} pra ver se ele muda de ideia? Ele não muda.',
  'O {nome} pediu pra avisar: ele continua sendo o {nome}. {n} vezes confirmado.',
  '{n}ª visita ao {nome}. Já pode pedir música no Fantástico.',
  'O {nome} tá ficando tonto de tanto rodar. Tipo o Goku no treino de gravidade.',
  'Vira o {nome}, esquece o {nome}, vira o {nome}… Loop infinito detectado.'
],

/* ---------- sequência de acertos ---------- */
memSequenciaAcerto: [
  '{n} pares seguidos! Quem é você e o que fez com o jogador de antes?',
  'Sequência de {n}! Tá voando. Cuidado com o teto.',
  '{n} acertos em sequência. Tô ficando sem piada, para com isso.',
  'Combo x{n}! Se fosse jogo de luta, já tinha finalizado.',
  '{n} seguidos! Seu cérebro tá em modo Super Saiyajin.',
  'Sequência de {n}. Eu tô impressionado. Não conta pra ninguém.',
  '{n} na sequência. É o poder da memória! Ou de ter visto tudo antes. Mas conta.',
  'Uau, {n} seguidos! Você comeu peixe hoje? Dizem que faz bem pra memória.',
  'Combo de {n}! Até eu tô torcendo agora. Um pouco.',
  '{n} pares sem errar. Isso é memória fotográfica ou tá colando?',
  'Tá pegando fogo! {n} seguidos. Alguém chama o Squirtle.',
  'Sequência de {n}! O tabuleiro tá pedindo arrego.',
  '{n} seguidos. Isso já é assédio moral contra os cards.',
  'Olha isso, {n} acertos! Eu vou precisar de uns minutos pra me recuperar.',
  'Sequência x{n}! Se isso fosse Pokémon, seu Mewtwo tinha acabado de evoluir. E ele nem evolui.',
  '{n} de {n}! Perfeito até agora. Vou tentar não dar azar falando. Opa, falei.',
  'Máquina de pares! {n} seguidos sem piscar.',
  '{n} na sequência. Eu só sei assistir e ficar com inveja.',
  'Tá no modo instinto superior! {n} pares seguidos.',
  'Isso aqui virou show. {n} acertos seguidos. Cadê a pipoca?'
],

/* ---------- sequência de erros ---------- */
memSequenciaErro: [
  '{n} erros seguidos. Tá tudo bem em casa?',
  '{n} na sequência errando. Respira. Olha pros cards. Lembra.',
  'Sequência de {n} erros! Isso também é um combo. Um combo triste.',
  '{n} erros seguidos. Seu cérebro pediu demissão?',
  'Errou {n} vezes em seguida. Tô começando a achar que é de propósito.',
  '{n} vacilos seguidos. Dica: os cards não mudam de lugar. Quase nunca.',
  'Isso é uma estratégia? Errar {n} vezes pra confundir o inimigo?',
  '{n} seguidos errados. O Psyduck tá te olhando com empatia.',
  'Calma. {n} erros não é o fim. É só… bastante.',
  '{n} erros em fila! Nem o Yamcha perdia tão seguido. Tá, perdia.',
  'Tá virando card aleatório? {n} erros seguidos parecem roleta.',
  'Sequência de {n} erros. Quer que eu cante uma música pra dar sorte? Não? Ótimo, eu não canto.',
  'Tá difícil hoje, né? {n} erros seguidos. Toma uma água.',
  '{n} errados seguidos. Recomendo parar de clicar no desespero.',
  'Ó, {n} erros. Eu tô aqui torcendo. Tipo, bem lá no fundo.',
  '{n} erros seguidos. Seu recorde pessoal de erro? Vou anotar.',
  'Mais um erro! São {n}. O Magikarp tá mais eficiente que você.',
  'Essa sequência de {n} erros vai pro museu. Ala da vergonha.',
  'Dica de ouro: antes de virar o segundo, pensa onde você viu o primeiro. {n} erros pedem isso.',
  '{n} seguidos. Relaxa, até o Goku apanha no começo da saga.'
],

/* ---------- último par ---------- */
memUltimoPar: [
  'Último par! Esse nem precisa de memória. É só apertar.',
  'Sobrou um par só. Se errar esse, eu mudo de mascote.',
  'Último par encontrado! Vitória garantida. Pode comemorar.',
  'O último par é sempre o mais fácil. Por eliminação. Parabéns por saber eliminar.',
  'Fechou o tabuleiro! Último par, zero dúvida.',
  'E o último par cai! Final de temporada.',
  'Último par! Esse aí tava sozinho no mundo, era só pegar.',
  'Acabou! O último par se entregou sem resistência.',
  'O último par é tipo o último pedaço de pizza: ninguém briga por ele. Você pegou.',
  'Terminou! O último par nem precisou de esforço.',
  'Fim de tabuleiro! O último par agradece por não ter sido esquecido.',
  'O último card nem teve graça. Mas conta!',
  'Tabuleiro limpo! Último par capturado.',
  'Último par! Até eu acertaria esse. E eu não tenho dedo.',
  'Final! Os dois últimos se encontraram. Plateia chora.'
],

/* ---------- fim de nível por estrelas ---------- */
memFim3: [
  'Três estrelas! Memória de elefante confirmada.',
  '⭐⭐⭐! Nem eu, que sou um computador, faria melhor. Tá, faria. Mas bonito.',
  'Três estrelas cravadas! Pode mandar print pro grupo da família.',
  'Perfeição! Ou quase. Três estrelas é o máximo que eu dou.',
  'Três estrelas! O tabuleiro nem viu o que aconteceu.',
  'Olha isso, três estrelas. Vou ter que atualizar minha opinião sobre você. Pra cima. Um pouco.',
  'Três estrelas! Você deve ter comido muito peixe na infância.',
  'Cravou as três! Tá treinando escondido, confessa.',
  'Três estrelas brilhando. Tipo as esferas do dragão, só que menos úteis.',
  'Nível fechado com três estrelas. Essa é a memória que eu queria ter.',
  'Três estrelas! Aplausos. *clap clap*. Isso foi eu aplaudindo.',
  'Estrela, estrela, estrela! Ganhou o combo completo.',
  'Três estrelas. Eu ia fazer uma piada, mas você não deixou espaço.',
  'Nota máxima! Três estrelas pro cérebro mais afiado do fliperama.',
  'Três estrelas! Isso aqui tá virando tutorial de como jogar direito.'
],
memFim2: [
  'Duas estrelas. Bom! Mas eu sei que você consegue três.',
  'Duas estrelinhas. Nota 7. Passou, mas sem festa.',
  'Duas estrelas! Faltou pouco. Tipo, uns dois erros a menos.',
  'Duas estrelas. Honesto. Eu daria duas e meia, mas não existe meia.',
  'Passou com duas estrelas! A terceira ficou tímida.',
  'Duas estrelas. Tá no caminho. O caminho é longo, mas tá.',
  'Duas estrelas! Se tivesse lembrado daquele card lá… você sabe qual.',
  'Duas de três. O Vegeta chamaria isso de fracasso. Eu chamo de “ok”.',
  'Duas estrelas! Mediano com orgulho.',
  'Passou com duas. Pode repetir pra caçar a terceira, se quiser sofrer.',
  'Duas estrelas. Boa, mas o terceiro brilho ficou pro próximo.',
  'Duas estrelas e um gostinho de “quase”.'
],
memFim1: [
  'Uma estrela. Terminou, é o que importa. É o que eu digo pra me consolar.',
  'Uma estrelinha. Tadinha, sozinha. Quer repetir e dar companhia pra ela?',
  'Passou com uma estrela! Passou raspando, igual prova de física.',
  'Uma estrela. O importante é participar. Tá, e acertar menos errado.',
  'Terminou! Com uma estrela e muitos erros. Mas terminou.',
  'Uma estrela. O Magikarp também começa assim e vira Gyarados. Talvez.',
  'Ufa, acabou! Uma estrela. Eu já tava ficando com sono.',
  'Uma estrela. Cada erro virou uma história. Longa. Muito longa.',
  'Missão cumprida com uma estrela! O Yamcha teria orgulho.',
  'Uma estrela. Mas eu vi esforço. Vi muito esforço. Muito mesmo.',
  'Terminou com uma estrela. Próxima vez, olha os cards com mais carinho.',
  'Uma estrela! Não é bonito, mas é seu.'
],
memPerfeito: [
  'ZERO erros! Partida perfeita! Eu tô sem palavras. Olha só, eu sempre tenho palavras.',
  'Perfeito! Nenhum erro. Você é um robô? Pisca duas vezes se for robô.',
  'Sem errar uma vez sequer! Isso é memória fotográfica ou colou na testa?',
  'Partida perfeita! O Professor Carvalho vai querer te estudar.',
  'Nenhum erro! Isso foi mais limpo que a sala do Whis.',
  'Zero mismatch. Isso nem é mais jogo, é demonstração.',
  'Perfeição! Eu vou gravar isso e mostrar pros outros jogadores. Pra humilhar eles.',
  'Nenhum card virado à toa. Nível instinto superior da memória.',
  'Perfeito! Até os cards tão aplaudindo. Com as bordas.',
  'Não errou nada! Tá, admito: isso foi incrível. Não se acostuma.',
  'Jogo sem falhas! Isso é raro igual Pokémon shiny.',
  'Perfeição absoluta. Vou precisar deitar um pouco.'
],
memRapido: [
  'Rápido demais! Terminou em {t}. Tá com pressa pra quê?',
  '{t}! Foi mais rápido que o Flash. O Flash de câmera, digo.',
  'Terminou em {t}. Nem deu tempo de eu fazer as piadas que eu tinha preparado.',
  'Velocidade da luz! {t} e acabou. O Zapdos ficou com inveja.',
  'Em {t}?! Você piscou alguma vez durante isso?',
  'Voou! {t}. Tipo Goku no Kinto’un.',
  '{t} cravados. Isso é speedrun de memória.',
  'Rapidinho: {t}. Eu mal comecei a comer minha pipoca.',
  '{t}! Tão rápido que o cronômetro ficou tonto.',
  'Terminou em {t}. Tem certeza que não conhecia esse tabuleiro?',
  'Veloz! {t}. O Sonic mandou um abraço. Jogo errado, mas mandou.',
  'Em {t}, sem enrolação. Respeito.'
],
memDevagar: [
  'Terminou em {t}. Deu pra ir no mercado e voltar, né?',
  '{t}. Devagar e sempre. Mais devagar do que sempre.',
  'Levou {t}. O Slowpoke te chamou de lento. O SLOWPOKE.',
  '{t}! Eu envelheci aqui. Olha meus bigodes grisalhos.',
  'Terminou em {t}. Pensativo você, hein? Tipo estátua.',
  'Uau, {t}. Nesse tempo o Goku treinou num planeta inteiro.',
  'Fechou em {t}. Tudo bem, a pressa é inimiga da perfeição. E da sua memória também, pelo visto.',
  '{t}. Tava fazendo pausa pra café entre as jogadas?',
  'Levou {t}. Mas chegou! Tipo ônibus em dia de chuva.',
  '{t} de pura contemplação artística dos cards.',
  'Terminou em {t}. Na Sala do Tempo isso daria um ano inteiro.',
  '{t}. Com calma, estilo tartaruga do Mestre Kame.'
],

/* ---------- nível / jornada ---------- */
memNivel: [
  'Nível {n}! Bora ver se sua memória acompanha.',
  'Chegamos no nível {n}. Os cards estão mais confiantes.',
  'Nível {n} carregado. Mais cards, mais chances de você errar. Ops, de acertar.',
  'Nível {n}! Aqui o bicho começa a pegar. Tipo o Gyarados.',
  'Bem-vindo ao nível {n}. Deixe sua memória na entrada. Brincadeira, leva ela junto.',
  'Nível {n}. Eu já sei onde tá tudo. Você não. Hehe.',
  'Subiu pro nível {n}! Tá virando gente grande.',
  'Nível {n}. Respira, estala os dedos e vira o primeiro.',
  'Nível {n} na tela! Aposto duas estrelas. Talvez uma.',
  'Olha só, nível {n}. Quem te viu, quem te vê.',
  'Nível {n}! Mais pares, mais caos, mais piada minha.',
  'Nível {n} desbloqueado. Você é tipo o Ash: nunca desiste. E nunca envelhece.',
  'Nível {n}, pessoal! O público vai à loucura. O público sou eu.',
  'Entrando no nível {n}. Coloca o cinto que a memória vai decolar.',
  'Nível {n}. Se passar desse, eu te dou um biscoito. Imaginário.'
],
memNivelMaior: [
  'Tabuleiro maior! Agora são {n} pares. Seu cérebro tá pronto? O meu tá rindo.',
  '{n} pares agora! Cresceu o tabuleiro, cresceu o sofrimento.',
  'Mais cards na mesa: {n} pares. Hora de usar mais que dois neurônios.',
  'Olha o tamanho disso: {n} pares! Vai precisar de memória externa.',
  'Subiu pra {n} pares. Os cards se multiplicaram igual Gremlin molhado.',
  'Tabuleiro novo com {n} pares. Parece pouco, né? Espera pra ver.',
  'Agora são {n} pares. Eu contaria nos dedos, mas não tenho dedos.',
  '{n} pares! Isso aqui tá virando álbum de figurinha.'
],
memTwistEvolucao: [
  'Twist novo: EVOLUÇÃO! Agora o par não é igual: é a mesma linha evolutiva. Charmander combina com Charmeleon ou Charizard. Pensa em família!',
  'Modo Evolução ligado! Os pares são parentes, não gêmeos. Pokémon com a evolução, guerreiro com a dupla dele.',
  'EVOLUÇÃO! Achar o igual era fácil demais. Agora acha o parente.',
  'Twist Evolução: o card não tem gêmeo, tem pai, filho ou parceiro. Se liga na família.',
  'Nível com Evolução! Se ver um Bulbasaur, procura o bichão de planta que é a versão crescida dele.',
  'Evolução ativada! Agora eu quero ver se você conhece Pokémon de verdade.',
  'Sabe aquele Squirtle? O par dele é quem ele vira quando cresce. Ou a dupla, no caso do Dragon Ball. Evolução!',
  'Twist: EVOLUÇÃO. Esse aqui separa treinador de turista.'
],
memTwistSombra: [
  'Twist novo: SOMBRA! Um card de cada par vem só com a silhueta. É “Quem é esse Pokémon?” dentro do jogo da memória.',
  'Modo Sombra! Metade dos cards tá no escuro. Reconhece pelo formato, detetive.',
  'SOMBRA ligada! Um dos cards de cada par é só a silhueta. Boa sorte, olho de lince.',
  'Twist Sombra: sem cor, sem nome, só o contorno. Igual o intervalo do desenho.',
  'Nível com Sombra! Se a silhueta parecer um borrão, é porque é. Se vira.',
  'Sombra ativada! Agora o jogo é memória E reconhecimento. Dois cérebros pelo preço de um.',
  'Sombras no tabuleiro! Se você reconhecer o Pikachu só pela orelha, ganha meu respeito.',
  'Twist: SOMBRA. É tipo aquele quadro do intervalo, só que eu não vou te falar a resposta.'
],
memTwistBagunca: [
  'Twist novo: BAGUNÇA! A cada erro, dois cards escondidos trocam de lugar. Errar agora sai caro.',
  'Modo Bagunça! Errou? Eu embaralho dois cards. Na sua frente. Com gosto.',
  'BAGUNÇA ativada! Cada erro mexe o tabuleiro. Cuidado: sua memória vai ficar desatualizada.',
  'Twist Bagunça: os cards virados pra baixo podem trocar de lugar quando você erra. Fica de olho na dança!',
  'Nível com Bagunça! Eu vou mexer nos cards. Você vai me odiar. Eu vou adorar.',
  'Bagunça ligada! Se você errar, dois cards dão um passinho de dança e trocam de lugar.',
  'Bagunça! Agora errar tem consequência. Tipo a vida.',
  'Twist: BAGUNÇA. Acompanha a troca com o olho, senão já era.'
],
memTwistRelampago: [
  'Twist novo: RELÂMPAGO! Você vai ver todos os cards por 3 segundos. Depois, escuridão. Decora rápido!',
  'Modo Relâmpago! Três segundos de spoiler. Aproveita cada um.',
  'RELÂMPAGO ativado! Tudo virado pra cima por 3 segundos. Foto mental, agora!',
  'Twist Relâmpago: eu mostro tudo, depois escondo. Igual mágico ruim.',
  'Nível com Relâmpago! Três segundos. Não pisca. Sério, não pisca.',
  'Relâmpago! O Zapdos emprestou a energia pra esse twist. Três segundos de flash!',
  'Relâmpago ligado! É memória de curtíssimo prazo. Bem curto.',
  'Twist: RELÂMPAGO. Olha tudo, guarda tudo, erra tudo. Ou não.'
],
memTwistCombo: [
  'Dois twists de uma vez! Eu sou malvado. Eu sei. Eu gosto.',
  'Combo de twists! Esse nível foi desenhado por alguém que te odeia. Fui eu.',
  'Twist em dobro! Se sobreviver a esse, você merece um troféu. Eu não tenho troféu. Toma uma estrela.',
  'Olha só: twists empilhados. Tipo fusão, só que de sofrimento.',
  'Nível com mais de um twist. Isso aqui é a Sala do Tempo da memória.',
  'Combinação de twists! Nem o Grande Sacerdote passaria sem suar.',
  'Twists misturados. É tipo lasanha de dificuldade. Camadas e camadas.',
  'Esse nível tem twist, e twist, e… sim, mais twist. Boa sorte!'
],

/* ---------- falas durante os twists ---------- */
memEvolucao: [
  '{a} e {b}! Família reunida. Evolução é lindo.',
  'Isso! {a} cresceu e virou {b}. Ou é a dupla dele. Enfim, par!',
  '{a} com {b}. Você conhece a linha evolutiva! Treinador de verdade.',
  'Par evolutivo: {a} e {b}. O Professor Carvalho tá orgulhoso.',
  '{a} olhou pro {b} e disse: “eu vou ser assim quando crescer?”. Vai sim.',
  'Acertou a família: {a} e {b}. Almoço de domingo garantido.',
  '{a} e {b} juntos! Isso é conhecimento de Pokédex.',
  'Evolução reconhecida! {a} e {b}. Até a pedra evolutiva aplaudiu.',
  '{a} ↔ {b}. Você não só lembrou, você entendeu. Bonito.',
  'Linha evolutiva completa: {a} e {b}. Pode mandar pro Pokédex Oficial.',
  'Boa! {a} e {b} são parentes. Tipo pai e filho. Ou tipo Goku e o Gohan.',
  '{a} e {b}, os parentes que se encontraram. Novela das oito.',
  'Pegou! {a} e {b}. Quem disse que esse jogo era só de memória?',
  'Família detectada: {a} e {b}. Parabéns, geneticista.',
  'Isso aí! {a} e {b} têm o mesmo DNA. Ou a mesma saga.'
],
memEvolucaoErro: [
  '{a} e {b}? Não são da mesma família. Nem primos distantes.',
  'Hmm, {a} não evolui pra {b}. Por mais que você deseje.',
  '{a} e {b}: evolução inventada. O Professor Carvalho reprovaria.',
  'Não! {a} e {b} nem se cumprimentam na reunião de família.',
  '{a} virar {b}? Só em fanfic.',
  'Essa evolução não existe. Ainda. Manda pra Game Freak.',
  '{a} e {b}: parentesco zero. Faz o teste de DNA de novo.',
  'Nem com pedra da lua o {a} vira {b}.'
],
memSombra: [
  'Reconheceu pela sombra! {nome}! Olho de lince.',
  'A silhueta era {nome}! É o quadro do intervalo, versão memória.',
  'Quem é esse Pokémon?! É o {nome}! E você acertou pela sombra.',
  'Pela sombra! {nome} saiu do escuro e ganhou cor. Lindo.',
  'Silhueta decifrada: {nome}. Detetive de sombras, você.',
  '{nome} de sombra e {nome} colorido. Duas versões, um par.',
  'Você reconheceu o {nome} só pelo contorno. Isso é respeito.',
  'A sombra do {nome} não te enganou. Bom olho.',
  'Sombra identificada! {nome}. A lanterna mental funciona.',
  '{nome} saiu das trevas! Eu adoro esse momento.',
  'Olha a cor voltando pro {nome}! Mágico.',
  'Pela silhueta! Sério, {nome} tem um contorno bem marcante, mas mesmo assim, boa.'
],
memSombraErro: [
  'Errou a sombra! Aquela silhueta enganou você direitinho.',
  'A sombra não era essa. Olha o formato das orelhas, o rabo, o topete…',
  'Silhueta traiçoeira! Parecia, mas não era.',
  'Sombra errada. Aqui não tem narrador do intervalo pra te ajudar.',
  'Você já tinha visto esse contorno! A sombra tá rindo de você. Sem boca, mas rindo.',
  'Essa sombra não combina. Nem de longe. Nem no escuro.',
  'Hmm, no escuro todo Pokémon é pardo. Errou.',
  'A silhueta te enrolou. Presta atenção no formato, não na cor. Que nem tem.',
  'Errou pela sombra. Acontece. Acontece bastante, na verdade.',
  'A sombra fez cara de paisagem. Não era ela.'
],
memBagunca: [
  'Ops, errou! Hora da BAGUNÇA: dois cards trocaram de lugar.',
  'Bagunça! Mexi dois cards. Você viu? Espero que sim.',
  'Tchan! Dois cards dançaram e trocaram de lugar. Culpa sua.',
  'Errou, eu bagunço. Esse é o acordo.',
  'Trocando dois cards… pronto. Sua memória acabou de ficar desatualizada.',
  'Bagunça ativada! Dois cards mudaram de casa. Sem aviso prévio.',
  'Olha a dança! Dois cards trocaram. Acompanhou?',
  'Mexi! Hehehe. Quais? Ah, isso é problema seu.',
  'Bagunça! Se você piscou, já era.',
  'Dois cards trocaram de lugar. Tipo troca de lugar na sala de aula. Sem autorização.',
  'Mais um erro, mais uma bagunça. Tô adorando isso.',
  'Trocadinha básica. Olho vivo!',
  'Fiz uma bagunçinha. Pequena. Com amor.',
  'Pronto, troquei. Agora aquele lugar que você decorou… talvez não seja mais.',
  'A bagunça é minha linguagem do amor. Troquei dois cards.'
],
memRelampago: [
  'Olha tudo! Três segundos! DECORA!',
  'Flash! Tá tudo aberto. Fotografa com o cérebro, rápido!',
  'Relâmpago! Três… dois… (olha os cards, não eu!)',
  'Vê tudo agora! Depois escuridão total.',
  'Olho nos cards! Isso aqui é mais rápido que o Zapdos.',
  'Tá vendo? Tá vendo? Não vai ver mais! Decora!',
  'Todos à mostra! Memoriza pelo menos a posição dos bonitões.',
  'Spoiler de três segundos! Aproveita.',
  'Foto mental: click! Espero que o seu cérebro tenha memória no cartão.',
  'Rápido, rápido! Olha os cantos, os cantos são traiçoeiros.',
  'Relâmpago cai! Olha, olha, olha!',
  'Três segundos de vantagem. Não desperdiça olhando pra mim.'
],
memRelampagoFim: [
  'Apagou! Agora é com você. Lembrou de alguma coisa?',
  'Escuridão! Espero que o flash tenha ficado gravado.',
  'Acabou o spoiler. Agora é memória raiz.',
  'Cards escondidos. Quanto você guardou? Eu aposto… uns três.',
  'Fim do relâmpago. Agora vamos ver se foi foto ou borrão.',
  'Virei tudo. Vai, mostra o que você decorou!',
  'Pronto. Três segundos passaram voando, né?',
  'Luz apagada. Hora de acender a memória.'
],

/* ---------- diário ---------- */
memDiarioOi: [
  'Desafio do Dia! Mesmo tabuleiro pra todo mundo. Joga bem que tem gente comparando.',
  'Diário! Oito pares, um cronômetro e sua reputação em jogo.',
  'Esse tabuleiro é igual pro Brasil inteiro. Não passa vergonha nacional.',
  'Desafio do Dia carregado. Menos jogadas e menos tempo é melhor. Óbvio, mas vai que.',
  'O tabuleiro de hoje é o mesmo pra todos. Os erros, cada um tem os seus.',
  'Diário na área! Vale uma vez. Capricha.',
  'Mesmo tabuleiro pra todo mundo, sabe o que isso significa? Dá pra comparar. E zoar.',
  'Oito pares, um dia, uma chance de brilhar. Ou de virar meme.',
  'Desafio do Dia! Eu sei o resultado de todo mundo. Mentira, não sei. Mas finge que sei.',
  'Bora de diário! Cada jogada conta. Cada segundo também. Sem pressão. Muita pressão.'
],
memDiarioFeito: [
  'Diário concluído! {m} jogadas em {t}. Compartilha e se gaba.',
  'Desafio do Dia feito! {m} jogadas. Quero ver alguém bater isso. Ou não, sei lá.',
  'Pronto! Diário no bolso: {m} jogadas, {t}. Manda pros amigos.',
  'Fechou o diário em {t}! O placar tá salvo. Sua glória também.',
  'Diário resolvido! {m} jogadas. Amanhã tem outro, e eu vou estar aqui julgando.',
  'Concluído! {m} jogadas e {t} de relógio. Anota aí na geladeira.',
  'Desafio do Dia: CHECK. {m} jogadas. Tá liberado pra jogar a Jornada.',
  'Mandou o diário! {t}. Agora compartilha pra provocar a galera.',
  'Diário feito com {m} jogadas. Se for pouco, parabéns. Se for muito, amanhã tem outro.',
  'Terminou o diário! Eu guardei o resultado: {m} jogadas, {t}.',
  'Diário completo. Bora espalhar esse {t} pelo grupo da família.',
  'Pronto, diário concluído. Agora é esperar a meia-noite. Ou jogar a Jornada, viciado.'
],
memDiarioJaFeito: [
  'Você já fez o diário de hoje! Volta amanhã. Ou joga a Jornada.',
  'Diário já concluído. Pode jogar de novo, mas não conta. É só pra matar a saudade.',
  'Esse aí já foi! Resultado guardado. Amanhã tem tabuleiro novo.',
  'Já fez o de hoje, espertinho. Jogar de novo não muda o placar.',
  'O diário tá feito. Tá voltando pra admirar? Justo.',
  'Diário completo, placar salvo. Jornada tá ali chamando.',
  'Voltou pro diário já feito? Saudade dos cards, né?',
  'Esse tabuleiro você já venceu. Amanhã tem outro, prometo.',
  'Diário de hoje: concluído. Se jogar de novo, é por amor. Não vale ponto.',
  'Já tá feito! Compartilhou? Não? Compartilha, deixa de ser tímido.'
],

/* ---------- temas ---------- */
memTema: [
  'Tema trocado pra {tema}! Novos rostos, mesmos erros.',
  '{tema}! Boa escolha. Ou não. Vamos descobrir.',
  'Agora é {tema}. Os cards trocaram de roupa.',
  'Mudou pra {tema}. Espero que você conheça esse povo.',
  '{tema} na mesa! Os cards novos estão ansiosos.',
  'Tema {tema} ativado. Eu recomendaria esse. Recomendo todos. Sou fácil.',
  '{tema}! Troquei tudo. Até a minha opinião sobre você. Não, essa continua.',
  'Beleza, {tema}. Vai conhecer gente nova. Gente de card.',
  '{tema} selecionado! Os cards velhos foram pra caixa.',
  'Novo tema: {tema}. Minha piada nova: nenhuma. Tô guardando.'
],

/* ---------- ajuda / stats ---------- */
memAjuda: [
  'Leu tudo? Não leu. Mas tudo bem, eu explico de novo quando você errar.',
  'Regras são simples: vira dois, se forem iguais, sai. Se não, eu zoo.',
  'Dica pro(a) iniciante: começa pelos cantos. Não sei se ajuda, mas parece profissional.',
  'Pronto, agora você sabe tudo. Quer dizer, sabe o suficiente pra errar com propriedade.',
  'Pode fechar a ajuda. Eu vou estar aqui de assistente pessoal. Muito pessoal.'
],
memStats: [
  'Suas estatísticas! Números não mentem. Eu minto, os números não.',
  'Olha só os números. Tem coisa boa aí. Tem coisa feia também.',
  'Estatísticas: a prova documental da sua memória.',
  'Tá vendo o recorde? Eu vi. Eu sempre vejo.',
  'Números! Eu adoro números. São tipo cards, mas não viram.',
  'Seu histórico. Tem estrela, tem jogada, tem vergonha. Completo.',
  'Estatísticas abertas. Cuidado, pode dar orgulho. Ou crise.',
  'Esses números aí foram você que fez. Todos. Inclusive os ruins.'
],
memNiveis: [
  'Mapa da Jornada! Escolhe um nível pra repetir ou continua de onde parou.',
  'Olha quantos níveis! Uns com três estrelas, outros… nem tanto.',
  'Quer caçar estrela antiga? Escolhe o nível. Eu espero.',
  'Seu mapa de conquistas. Tem buraco de estrela aí, hein.',
  'Níveis desbloqueados. Os bloqueados ficam me olhando com cadeado.',
  'Escolhe um nível. Qualquer um. Menos o que você tá evitando. Esse mesmo.'
],
memRecomecar: [
  'Recomeçou! Fingindo que nada aconteceu, né?',
  'Reset! Os erros de antes foram pro limbo. Eu não esqueci.',
  'Recomeçando. Novo tabuleiro, velhas manias.',
  'Botão de recomeçar: o melhor amigo de quem errou demais.',
  'Tudo de novo! Cards novos, esperança renovada.',
  'Deletou a vergonha e começou de novo. Esperto.',
  'Novo embaralhamento! Dessa vez vai. Sério. Talvez.',
  'Recomeçar também é estratégia. Covarde, mas estratégia.'
],

/* ---------- parado no meio da partida ---------- */
memParado: [
  'Tá pensando onde tava aquele card? Eu sei onde tá. Não vou contar.',
  'Oi? O tabuleiro ainda tá aqui. Os cards tão esfriando.',
  'Tá parado olhando os cards virados pra baixo? Eles não vão se revelar sozinhos.',
  'Se ficar muito tempo parado, a memória evapora. Fato científico. Não é, mas parece.',
  'O cronômetro tá correndo e você tá… contemplando. Poético.',
  'Esqueceu que tava jogando? Acontece. Com peixinho dourado.',
  'Oi, tá aí? Os cards mandaram perguntar.',
  'Parado assim você parece o Metapod usando Endurecer.',
  'Tá esperando os cards se mexerem? Só no modo Bagunça, amigo.',
  'Tempo passando, memória apagando. Vira um card!',
  'Eu tô aqui contando os segundos. E zoando cada um.',
  'Pensando demais é igual Psyduck: dá dor de cabeça e não resolve nada.',
  'O Snorlax chamou, disse que você tá no ritmo dele.',
  'Se você não virar um card, eu viro. Mentira, não tenho mão. Mas a vontade tá aqui.',
  'Tá lembrando dos pares ou lembrando da conta de luz?'
]
};

/* ---------- falas por personagem (viram categorias "memP:<nome>") ---------- */
const PERS = {
  'Psyduck': ['Você virou o Psyduck. Ele já tá com dor de cabeça. Agora imagina se virar três vezes.', 'Psyduck no tabuleiro! A dor de cabeça dele é contagiosa, cuidado.'],
  'Pikachu': ['Pikachu! Todo mundo acerta esse. Não se ache.', 'Pika pika! Tradução: “demorou, hein”.'],
  'Magikarp': ['Magikarp! Não serve pra nada, mas pelo menos você achou ele.', 'Um par de Magikarp. Esplash! Nada acontece. Como sempre.'],
  'Gyarados': ['Gyarados! Lembra quando era Magikarp? Nem ele lembra.', 'Gyarados achado. Não irrita ele, pelo amor.'],
  'Charizard': ['Charizard! O card mais caro do recreio de 1999.', 'Achou o Charizard. Alguém guarda esse card num plástico, por favor.'],
  'Charmander': ['Charmander! Cuidado com a chama do rabo, os cards são de papel.', 'Charmander achado. Fofo agora, depois vira um dragão temperamental.'],
  'Bulbasaur': ['Bulbasaur! Plantinha nas costas e zero reclamação. Exemplo de vida.', 'Par de Bulbasaur. Rega ele, ele merece.'],
  'Squirtle': ['Squirtle! Coloca os óculos escuros, é a Esquadrão Squirtle.', 'Squirtle achado. Ele esguichou água de alegria. Seca o card aí.'],
  'Snorlax': ['Snorlax! Esse card levou três dias pra virar. Sono.', 'Achou o Snorlax. Ele nem acordou pra comemorar.'],
  'Ditto': ['Ditto! Espera… qual dos dois é o Ditto de verdade?', 'Par de Ditto. Ou um Ditto imitando o outro. Nunca saberemos.'],
  'Eevee': ['Eevee! Oito evoluções e você mal lembra onde ele tava.', 'Eevee achado. Esse aí tem mais opção de carreira que eu.'],
  'Mewtwo': ['Mewtwo! Ele lê mentes. Ele leu a sua. Tá vazia, ele disse.', 'Mewtwo achado. Clonado, igual esse par.'],
  'Mew': ['Mew! Existia um caminhão escondido com ele. Mentira. Mas a gente acreditava.', 'Achou o Mew. Raríssimo! Que nem você acertar de primeira.'],
  'Jigglypuff': ['Jigglypuff! Não deixa ele cantar, senão você dorme e esquece tudo.', 'Achou o Jigglypuff. Ele já tá pegando o microfone. Corre.'],
  'Meowth': ['Meowth! Esse é o único gato que fala mais que eu. Por pouco.', 'Meowth, é isso aí! Achou o par dele.'],
  'Slowpoke': ['Slowpoke! Ele vai perceber que foi achado daqui a uns cinco segundos.', 'Achou o Slowpoke. Ele ainda tá processando.'],
  'Gengar': ['Gengar! Um fantasma igual a mim, só que roxo e menos charmoso.', 'Achou o Gengar. Ele tá rindo de você. Eu também, mas por outros motivos.'],
  'Onix': ['Onix! Uma cobra de pedra. Pesada. Igual esse nível.', 'Achou o Onix. Precisou de dois cards pra caber ele inteiro.'],
  'Machamp': ['Machamp! Quatro braços. Viraria quatro cards de uma vez.', 'Machamp achado. Ele queria te dar um high-five quádruplo.'],
  'Voltorb': ['Voltorb! Ou é uma Pokébola? Ninguém nunca sabe.', 'Achou o Voltorb. Sorte que não explodiu.'],
  'Electrode': ['Electrode! Também parece Pokébola. Pegadinha clássica.', 'Electrode achado. Não aperta muito forte.'],
  'Mr. Mime': ['Mr. Mime! Ele tá fingindo que tem uma parede invisível entre os cards.', 'Achou o Mr. Mime. Ele aplaudiu em silêncio. Obviamente.'],
  'Porygon': ['Porygon! Um Pokémon digital. Meu primo distante.', 'Porygon achado. Somos da mesma família: pixels.'],
  'Dragonite': ['Dragonite! O dragão mais fofo da história. Queria um abraço dele.', 'Achou o Dragonite. Ele entrega carta, sabia? Carteiro de luxo.'],
  'Lapras': ['Lapras! Carona pra atravessar o mar. E o tabuleiro.', 'Achou a Lapras. Ela cantou uma música de agradecimento.'],
  'Butterfree': ['Butterfree! Lembra do episódio da despedida? Eu chorei. Pixel molhado.', 'Achou a Butterfree. Bye bye, Butterfree. Nunca supero.'],
  'Metapod': ['Metapod! Usou Endurecer. É só isso que ele sabe fazer.', 'Achou o Metapod. Ele não se mexeu. Nunca se mexe.'],
  'Caterpie': ['Caterpie! A lagartinha mais esforçada do mundo.', 'Caterpie achado. Ele vai contar pra mãe.'],
  'Zubat': ['Zubat! O Pokémon mais irritante de toda caverna. E você achou dois.', 'Achou o Zubat. Pelo menos aqui ele não aparece a cada três passos.'],
  'Abra': ['Abra! Se demorar, ele se teletransporta. Rápido!', 'Achou o Abra antes dele fugir! Isso é um feito.'],
  'Diglett': ['Diglett! Ninguém nunca viu o corpo dele. Nem nesse card.', 'Achou o Diglett. Ele só mostra a cabeça, igual eu na janela.'],
  'Cubone': ['Cubone… o capacete dele é… não quero falar sobre isso.', 'Achou o Cubone. Dá um abraço nele, ele precisa.'],
  'Chansey': ['Chansey! Enfermeira oficial. Cura até seus erros? Não, isso não.', 'Achou a Chansey. Pede um ovo pra ela, dizem que é bom.'],
  'Togepi': ['Togepi! Cascão de ovo e cara de quem vai aprontar.', 'Achou o Togepi. Cuidado, ele usa Metrônomo e sai qualquer coisa.'],
  'Sudowoodo': ['Sudowoodo! Parece árvore, mas é pedra. Igual esse jogo: parece fácil.', 'Achou o Sudowoodo. Ele fingiu que era planta pra você não perceber.'],
  'Wobbuffet': ['WOBBUFFET! Ele sempre grita o nome. Eu também grito.', 'Achou o Wobbuffet. Ele fez continência. Wobbuuuffet!'],
  'Lucario': ['Lucario! Ele sente a aura. A sua tá meio confusa.', 'Achou o Lucario. Ele respeita sua memória. Um pouco.'],
  'Bidoof': ['Bidoof! O Pokémon mais subestimado do mundo. Deus Bidoof.', 'Achou o Bidoof. Ele é simples e feliz. Seja como o Bidoof.'],
  'Arceus': ['Arceus! O criador do universo Pokémon tá no seu tabuleiro. Respeito.', 'Achou o Arceus. Tipo encontrar Deus embaixo de um card.'],
  'Rayquaza': ['Rayquaza! Um dragão enorme dentro de um cardzinho. Apertado.', 'Achou o Rayquaza. Ele mora no céu, você no sofá.'],
  'Goku': ['Goku! Ele tá com fome. Sempre tá.', 'Achou o Goku! Ele vai te chamar pra lutar. Diz que não.'],
  'Vegeta': ['Vegeta! O príncipe dos Saiyajins. Não chama ele de segundo lugar.', 'Achou o Vegeta. Ele diz que foi ele que te ajudou.'],
  'Kuririn': ['Kuririn! Tomara que ele sobreviva a esse tabuleiro.', 'Achou o Kuririn. Vivo! Por enquanto.'],
  'Yamcha': ['Yamcha! Pelo menos no jogo da memória ele não perde. Ou perde?', 'Achou o Yamcha. Ele já tá deitado naquela pose clássica.'],
  'Mr. Satan': ['Mr. Satan! Ele vai dizer que achou o par sozinho.', 'Achou o Mr. Satan. O campeão mundial agradece. Com pose.'],
  'Piccolo': ['Piccolo! Tira a capa, que ela pesa uma tonelada.', 'Achou o Piccolo. Ele quase sorriu. Quase.'],
  'Freeza': ['Freeza! Ele não gosta de perder. Nem de ser achado.', 'Achou o Freeza. Ele tá furioso na terceira forma.'],
  'Cell': ['Cell! Ele absorveu a memória de alguém. Não foi a sua, que tá igual.', 'Achou o Cell. Perfeito, ele diria.'],
  'Majin Boo': ['Majin Boo! Cuidado que ele transforma você em chocolate.', 'Achou o Majin Boo. Ele comemorou comendo o card. Brincadeira.'],
  'Bills': ['Bills! O Deus da Destruição. Se errar muito, ele destrói o tabuleiro.', 'Achou o Bills. Ele quer pudim como recompensa.'],
  'Whis': ['Whis! O anjo mais chique do multiverso. Achou fácil, ele diria.', 'Achou o Whis. Ele riu educadamente da sua demora.'],
  'Zeno Sama': ['Zeno Sama! Não faz barulho. Ele apaga universos por tédio.', 'Achou o Zeno Sama. Ele achou divertido. Você sobreviveu.'],
  'Mestre Kame': ['Mestre Kame! O velhinho tá mais interessado na revista do que no jogo.', 'Achou o Mestre Kame. Ele ensinou o Kamehameha e a comer bem.'],
  'Bulma': ['Bulma! Ela inventou uma cápsula que guarda o tabuleiro inteiro.', 'Achou a Bulma. Gênia reconhece gênio. Ou quase gênio.'],
  'Chi-Chi': ['Chi-Chi! Ela quer saber se você fez a lição de casa.', 'Achou a Chi-Chi. Ela vai mandar o Gohan estudar.'],
  'Gohan': ['Gohan! Metade Saiyajin, metade estudante, 100% nerd.', 'Achou o Gohan. Ele tá com a caneta na mão.'],
  'Capitão Ginyu': ['Capitão Ginyu! Ele trocou de corpo com o outro card. Por isso é igual.', 'Achou o Capitão Ginyu. Pose da Força Especial!'],
  'Androide 18': ['Androide 18! Ela tá cansada de você errar. Eu também.', 'Achou a 18. O Kuririn tá orgulhoso.'],
  'Broly': ['Broly! Um par lendário. Literalmente lendário.', 'Achou o Broly. Ele gritou KAKAROTTO por algum motivo.'],
  'Jiren': ['Jiren! Ele não fala nada. Eu falo por dois.', 'Achou o Jiren. Força é tudo, ele diria. Memória também, eu digo.'],
  'Kaio do Norte': ['Kaio do Norte! Conta uma piada pra ele. Ele adora piada ruim.', 'Achou o Kaio do Norte. O Bubbles e o Gregory também comemoraram.']
};
for (const k in PERS) L['memP:' + k] = PERS[k];
window.MEM_PERS = Object.keys(PERS);

/* ---------- cutucar o mascote aqui ---------- */
L.cutucarMemoria = [
  'Ei! Me cutucar não revela card nenhum. Eu tentei.',
  'Cutucou. Anotei. Agora eu lembro de você. Diferente de você com os cards.',
  'Se você cutucar em mim com a mesma frequência que vira card errado, eu vou ficar roxo.',
  'Tô ocupado decorando o tabuleiro. Pra zoar você depois.',
  'Me cutucar é tipo virar o mesmo card de novo: não muda nada.',
  'Para! Eu sou um gato-fantasma, não um card do tabuleiro.',
  'Você sabia que eu tenho memória de 8 bits? E ainda assim lembro mais que você.',
  'Cutucada registrada. Se fosse um par, seria o par “irritação” com “irritação”.',
  'Se eu virar, você me acha? Não sou card. Mas sou fofo.',
  'Me deixa! Eu tô contando quantas vezes você esqueceu o mesmo card.',
  'Aí! Isso doeu no meu pixel preferido.',
  'Me cutucou pra me distrair? Eu não tô jogando. Você tá.',
  'Tá procurando meu par? Não existe. Sou único. Graças a Deus, você diria.',
  'Eu sou o card coringa. Não combino com nada. Só com o caos.',
  'Cutucar mascote não conta como jogada. Mas eu conto. Tô contando.',
  'Se eu fosse um card, eu seria o raro holográfico. Óbvio.',
  'Olha os cards, não eu! Tá, pode olhar um pouquinho.',
  'Você me cutuca e esquece. Igual os cards. Eu tô vendo um padrão.',
  'Não me vira! Eu fico tonto. Igual o card que você virou 7 vezes.',
  'Quer uma dica? Tá. Dica: presta atenção. Grátis.',
  'Cutuca de novo e eu viro um Ditto. Ditto de você. Aí quero ver.',
  'Eu tô de olho em você. E nos cards. Mais nos cards.',
  'Tá me usando de pausa? Tudo bem. Eu sou uma pausa muito charmosa.',
  'Sabe por que eu não jogo memória? Porque eu lembro de tudo. Fica chato.',
  'Ai! Isso vai pro relatório de estatísticas. “Cutucadas: muitas.”',
  'Me cutucou? Eu cutuco de volta. Mentalmente. Tá sentindo?',
  'Eu não sou um par. Eu sou um ímpar. E me orgulho disso.',
  'Tá bom, você me achou. Parabéns. Não ganha estrela.',
  'Se me cutucar mais três vezes, eu troco dois cards de lugar. Brincadeira. Ou não.',
  'O Psyduck me contou que você é gente boa. Ele tava com dor de cabeça, então não confio.',
  'Cutucar mascote não é estratégia comprovada de memória.',
  'Meu nome é Bugado, não “card extra”.',
  'Esse card aqui (eu) não vira. Ele só fala.',
  'Sabia que eu lembro onde tão todos os pares? Sabia. E não vou contar. Tá gostoso ver você sofrer.',
  'Ei, isso faz cócegas. Faz de novo. Não, para. Faz. Não.',
  'Você me cutuca igual o Goku cutuca inimigo: sem motivo e com força.',
  'Pode me cutucar à vontade, mas os pares não vão se achar sozinhos.',
  'Eu sou a sua memória externa. Uma memória que zoa você. Premium.',
  'Tá procurando o Bugado igual? Não tem. Eu sou edição limitada.',
  'Cutucar em vez de jogar. Clássico. Eu faria o mesmo.',
  'Se eu fosse Pokémon, seria tipo Fantasma/Sarcástico. Super efetivo contra você.',
  'Vai lá, vira dois cards. Eu fico aqui torcendo. Contra. Mentira. A favor. Talvez.'
];

/* ---------- 'aleatorio' temático (soma às falas gerais) ---------- */
const ALEA = [
  'Curiosidade: o jogo da memória mais antigo que se conhece era com conchas no Japão. Chama kai-awase. Juro.',
  'Você sabia que o polvo tem uma memória ótima? Oito braços e ainda lembra onde deixou as coisas.',
  'Peixinho dourado tem memória de mais de três segundos, sabia? Então não tem desculpa.',
  'Dizem que elefante nunca esquece. Nunca vi um elefante jogar memória, então não sei.',
  'Eu tenho uma memória de 8 bits. Cabe umas 256 coisas. 200 são piadas sobre você.',
  'Uma vez eu esqueci onde guardei minha memória. Irônico, né?',
  'Se você esquecer um card, não se preocupa. Eu esqueço onde deixo meu rabo o tempo todo.',
  'Pensamento profundo: se eu virasse um card, qual seria meu par? Um espelho, provavelmente.',
  'Os cards têm sentimentos? Não. Mas se tivessem, estariam tontos de tanto girar.',
  'Sabia que o Ditto consegue se transformar em qualquer card? Ia estragar todo jogo da memória.',
  'O Alakazam tem QI de 5000. Ia zerar esse jogo em dois minutos. Humilhante pra todo mundo.',
  'Imagina um jogo da memória só de Magikarp. Cem cards iguais. O caos.',
  'Tô pensando em lançar a coleção de cards “Bugado Holográfico”. Um card só. Eu.',
  'Fato: seu cérebro guarda umas 7 coisas por vez. Hoje você tá usando umas 3.',
  'Minha memória favorita? Quando você errou o mesmo par três vezes. Guardo com carinho.',
  'Sabe o Kinto’un? Nuvem voadora. Ia ser ótimo pra buscar card embaixo do sofá.',
  'Existe um recorde mundial de memorizar baralho: menos de 15 segundos. Relaxa, você não é concorrência.',
  'Às vezes eu viro de ponta-cabeça só pra ver o mundo como um card virado.',
  'O Mestre Kame tem uns 300 anos. Imagina a memória dele. Deve lembrar de todos os cards desde a Idade Média.',
  'Dica de sabedoria: se esquecer tudo, sorria. Os cards não sabem que você esqueceu.',
  'Uma vez eu joguei memória com o Snorlax. Ele dormiu na segunda jogada. Ganhei por W.O.',
  'Você já reparou que todo card virado pra baixo parece o mesmo? É proposital. Maldade pura.',
  'Se a memória fosse um Pokémon, seria tipo Psíquico. A sua seria tipo Normal. Sem ofensa.',
  'Eu queria ter memória fotográfica. Tenho memória de print desfocado.',
  'Curiosidade: esquilos esquecem onde enterraram muitas nozes. E aí nascem árvores. Seu esquecimento podia plantar uma floresta.',
  'Tô desenhando um card meu. Vou chamar de “Bugado Estampa Ilustrada Rara Nível Deus”.',
  'Sabe qual é o card mais raro do mundo? O que você lembrou de primeira.',
  'Os cards desse jogo foram embaralhados por mim, com a pata, com muito amor e um pouco de maldade.',
  'Pergunta séria: se o Gengar e eu jogássemos memória, quem ganharia? Eu. Obviamente.',
  'Eu contei: tem mais de mil Pokémon aqui dentro. Fiquei até tonto. Contei de novo. Mil e vinte e cinco.',
  'O Shenlong podia realizar o desejo de “memória perfeita”. Mas todo mundo pede imortalidade. Desperdício.',
  'Fato inútil: o cérebro humano pesa 1,4 kg. O meu pesa 3 kilobytes. Eficiente.',
  'Você sabia que dormir bem melhora a memória? Por isso o Snorlax é gênio. Suspeito.',
  'Uma vez eu vi um card virando sozinho. Era eu. Tava entediado.',
  'Se eu tivesse que escolher um par pra mim, seria um pastel. Pastel e eu. Par perfeito.',
  'Ó, se você quer treinar memória, lembra o meu nome: Bugado. Pronto, primeiro exercício feito.',
  'O Kuririn já morreu tantas vezes que deve ter memória de reencarnação. Ia ser bom nesse jogo.',
  'Me sinto um card virado pra baixo às vezes. Ninguém sabe o que tem dentro. Spoiler: é mais piada.',
  'Pesquisas dizem que jogar memória ajuda o cérebro. Pesquisas também dizem que eu sou fofo. Confia nas pesquisas.',
  'Os cards de hoje estão bem-comportados. Suspeito. Muito suspeito.'
];

window.Bugado.addLines(L);
window.Bugado.extendLines({ aleatorio: ALEA });
window.Bugado.addLines({
  memParadoMix: window.Bugado.lines('parado').concat(L.memParado),
  // quando o evento não tem fala própria, mistura personagem + genérico
});
})();
