/* ==========================================================
   Falas do Bugado · Memória (jogo de pares)
   Variáveis: {nome} = card/personagem · {a} {b} = os dois cards virados
              {n} = número (nível, sequência, vezes) · {tema} = tema escolhido
              {t} = tempo (mm:ss) · {m} = jogadas · {xp} = XP ganho
   Categorias com prefixo "mem". Falas por personagem em PERS (viram "memP:<nome>").
   Voz: ver VOZ.md na raiz (curto, zoeira de resenha, sem cara de IA).
   ========================================================== */
(() => {
const L = {

/* ---------- abrindo a página ---------- */
memOi: [
  'Memória! Vira dois cards e acha os pares. Eu vou comentar cada vacilo',
  'Chegou no jogo da memória. Espero que cê tenha trazido a sua',
  'Bora treinar o cérebro. Ou fingir que treina',
  'Pares escondidos e eu de camarote. Vambora',
  'Se lembrar onde tá cada card, top. Se não, eu lembro e vou jogar na sua cara',
  'Memória de elefante ou de peixinho dourado? Vira um card aí',
  'Jogo da memória de festa infantil, só que com um mascote bugado zoando. Evoluiu',
  'Toca num card, depois em outro. Se for par, fica aberto. Simples'
],
memVoltou: [
  'Voltou! Eu lembrei de você, diferente de você com os cards',
  'Você de novo. Os cards tavam com saudade',
  'De volta pra Jornada. Progresso salvo, dignidade nem tanto',
  'Guardei seu nível e suas estrelas. As vergonhas também',
  'Voltou pra mais? Vício ou treino?',
  'Retorno triunfal. Vamo ver se a memória voltou junto',
  'Sumiu e eu fiquei aqui contando card. Perdi a conta',
  'Retomando a Jornada. Da última vez tava indo bem. Mais ou menos'
],

/* ---------- embaralhando (carregando imagens) ---------- */
memEmbaralhando: [
  'Embaralhando... não olha. Pode olhar, não dá pra ver nada mesmo',
  'Misturando os cards aqui',
  'Pera que tô escondendo os Pokémon, eles não colaboram',
  'Baixando as figurinhas. Mais rápido que completar álbum da Copa',
  'Embaralhando igual crupiê, só que bugado',
  'Carregando os cards. Se demorar a culpa é da internet',
  'Chamando os bichos pro tabuleiro. Uns vêm rápido, outros são o Slowpoke',
  'Tirando os cards do plástico. Cheirinho de card novo',
  'Técnica secreta de embaralhar: tacar tudo pro alto',
  'Separando os pares e separando de novo',
  'Montando o tabuleiro. Dá tempo de estalar os dedos',
  'Virando tudo pra baixo, pera aí'
],

/* ---------- primeira virada da partida ---------- */
memPrimeiro: [
  'Primeiro card! Começou a jornada do esquecimento',
  'Virou o primeiro. Agora lembra dele',
  'Começou! Cronômetro rodando, cérebro carregando',
  'Primeira carta na mesa. Cheiro de recorde. Ou de queimado',
  'Abriu os trabalhos. Vai com calma que o card não foge',
  'Primeiro card virado. Pela estatística o próximo vai ser errado KKKKK',
  'Virar um é fácil, o difícil é o segundo',
  'Grava bem essa carinha que ela vai sumir já já',
  'Memoriza a posição, a cor, o nome, o signo',
  'Tá valendo. Tô contando as jogadas e julgando cada uma',
  'Primeira foto na memória. Tomara que não saia tremida',
  'Começou. Se errar, finge que foi de propósito',
  'Card número um. Guardou? Guarda',
  'Abriu com estilo. Quer dizer, abriu',
  'Aposto: primeiro erro em 3 jogadas',
  'Agora é só achar o gêmeo dele. Fácil demais né',
  'O Ash também começou assim e demorou 25 anos',
  'Um card virado. Faltam uns milhões de neurônio trabalhando',
  'Cronômetro ligado. Cada segundo de dúvida vai pro seu currículo',
  'Começou sem nem aquecer. Corajoso'
],

/* ---------- acertou um par (com nome) ---------- */
memPar: [
  'Par de {nome}! Tavam com saudade um do outro',
  '{nome} achou o gêmeo. Quase chorei',
  'Achou os dois {nome}. Podem sair do tabuleiro',
  'Boa! {nome} e {nome}, dupla dinâmica',
  '{nome} achado. Esse cérebro às vezes funciona',
  'Par de {nome} garantido',
  'Os {nome} agradecem a reunião de família',
  '{nome} + {nome} = ponto pra você',
  'Achou o {nome}! Sabia que cê lembrava',
  '{nome} em dobro, dobro de ponto',
  'Mandou bem no {nome}. Quando quer, consegue',
  'Par feito: {nome}. Tabuleiro mais leve',
  '{nome} achou o par antes de muita gente achar o amor',
  'Os dois {nome} se acharam. Cê foi o cupido',
  'Acertou {nome}. Eu tinha apostado contra',
  '{nome} achado. Aposto que decorou só esse KKKKK',
  '{nome} tava ali esperando cê lembrar dele',
  'Par de {nome}. O Professor Carvalho ficaria orgulhoso',
  'Bateu! {nome} com {nome}. Match melhor que app de namoro',
  '{nome} fora. Um a menos pra esquecer',
  'Boa memória com o {nome}. Agora faz isso com o resto',
  '{nome} vai pro mural',
  'Par de {nome}. Registrado e comentado',
  'Acertou o {nome} e eu fiquei sem piada',
  '{nome} achado. Tá virando Pokédex ambulante',
  'AEEE {nome}',
  'Esse {nome} não escapou',
  '{nome} reunido. Se tivesse trilha sonora tocava agora',
  'Achou {nome}. Tinha certeza que cê ia errar esse',
  'Coloca no currículo: acha {nome} com eficiência',
  '{nome}, {nome}. Falei duas vezes pra comemorar',
  '{nome} no bolso. Se fosse Pokébola, no bolso mesmo',
  'Uhul, {nome}! Quem diria',
  'Mais um par: {nome}. Tá ficando perigoso',
  'Achou {nome}. Não fiquei impressionado não. Fiquei sim',
  '{nome} achado. O tabuleiro tá com medo',
  'Os {nome} vão sair daqui de mão dada',
  'Par de {nome}. Eu teria errado esse, papo reto',
  '{nome} garantido. Continua assim que eu perco o emprego',
  'Mano, {nome} saiu liso demais'
],
/* ---------- acertou (genérico, sem nome) ---------- */
memParGeral: [
  'Acertou! Guardou bem hein',
  'Par! Memória ou chute? Nem responde',
  'Boa, mais um fora da mesa',
  'Viu? Nem era tão difícil',
  'Clique, clique, par. Simples',
  'Isso! Seu neurônio favorito tá trabalhando hoje',
  'Mais um par. Tá boa demais essa memória, tô preocupado',
  'Acerto limpo, sem drama',
  'Olha só quem lembra das coisas',
  'Par feito. Vou parar de zoar por uns 5 segundos',
  'Muito bem, toma um carinho imaginário',
  'Certinho! Treina escondido né',
  'O barulhinho de acerto é o som mais lindo do mundo',
  'Mais um. O tabuleiro tá ficando vazio igual minha geladeira',
  'Continua assim que eu fico quieto. Não fico não',
  'Belo par, pendura na parede',
  'Acertou. Tá com aquele sorrisinho agora né',
  'Boa jogada. Vou usar contra você depois',
  'Memória funcionando, sistema estável',
  'Mais um! Rápido até demais',
  'Par! Seu cérebro ganhou um biscoito',
  'Correto. Tá jogando demais mano',
  'Isso é memória ou tá anotando num papel?',
  'Bingo! Jogo errado. Par! Isso',
  'Fechou mais um. Clique de ouro'
],

/* ---------- acertou de primeira os dois (nunca tinha visto nenhum) ---------- */
memSorte: [
  'Achou o par de primeira? Sorte, certeza',
  'Nunca tinha visto nenhum dos dois e acertou. Sorte de principiante',
  'Os dois de primeira?? Joga na loteria hoje',
  'Acertou às cegas. Visão de raio-x ou bruxaria?',
  'Nem viu antes e acertou. Vou fingir que foi habilidade',
  'Sorte pura. Não conta pra memória mas conta ponto',
  'Chute certeiro no escuro. O Kuririn nunca teve essa sorte',
  'Tá com trevo de quatro folhas no bolso?',
  'Se cê fosse Pokémon, seu golpe seria Chute Abençoado',
  'Foi sorte, não adianta fazer pose',
  'O universo gosta de você hoje',
  'Foi sorte. Todo mundo viu, até o Magikarp',
  'Acertou sem saber. Tipo passar na prova chutando tudo C',
  'O destino juntou esses dois, não sua memória',
  'Clique abençoado. Reza pra quem hein?',
  'Sorte nível Mr. Satan ganhando torneio',
  'De primeira sem pista nenhuma. Tô desconfiado',
  'Pura sorte, mas não tenho como provar',
  'Chute no escuro que entrou no ângulo. Golaço',
  'Se sorte fosse Pokémon tava no seu time agora',
  'Sorte! O Mestre Kame chamaria de intuição, eu chamo de milagre',
  'Pronto, agora vai achar que é gênio. Foi sorte viu',
  'Nem piscou e acertou. Sorte de galinha',
  'Sorte também é talento. Um talento bem pequeno',
  'Os deuses do embaralhamento sorriram pra você'
],

/* ---------- errou (com os dois nomes) ---------- */
memErro: [
  '{a} e {b}? Nem parente são',
  '{a} com {b}? Nem em app de namoro dá match',
  'Errou. {a} olhando pro {b} tipo quem é você',
  '{a} e {b}. Combinação criativa. Errada, mas criativa',
  '{a} não é par do {b}. Eles nem se falam',
  'Tentou juntar {a} com {b}. O universo recusou',
  '{a} e {b}? Entendi nada',
  'Ops. {a} e {b} vão se esconder de novo',
  '{a} com {b}. Se existisse era um glitch igual eu',
  '{a} ≠ {b}. Matemática básica',
  'Errou! Mas agora cê sabe onde tá o {a}. E o {b}. Né?',
  '{a} e {b}: dupla que ninguém pediu',
  '{a} e {b} não têm nada a ver mano',
  'Gostei da ousadia de {a} com {b}. Do resultado não',
  'Era pra ser outro {a} e veio {b}. Faz de conta que eu não vi',
  '{a} e {b}, pizza e sorvete. Os dois bons, mas não é par',
  '{a} e {b}. Grava onde tá cada um, por favor',
  'Errou bonito. {a} e {b} até posaram pra foto',
  '{a} voltou pro escuro e levou o {b} junto',
  '{a} e {b}? Cérebro de férias nessa',
  '{a} e {b} nunca estiveram no mesmo episódio',
  '{a} e {b}. Uma escolha. Errada, mas uma escolha',
  'O {a} esperava o gêmeo e veio o {b}. Decepção',
  '{a} e {b} vão fingir que isso não aconteceu',
  'Errou. Mas agora tem mais informação, usa ela',
  '{a} e {b} discordam da sua decisão',
  'Desastre elegante: {a} e {b}',
  'Virou o {b} achando que era {a}? Oculista urgente',
  '{a} e {b} nem torcem pro mesmo time',
  '{a} e {b} se cumprimentaram e foram embora',
  'Errou, mas o {b} tem estilo, gostei',
  '{a} com {b}: fusão falhou. Nem o Gotenks salvava',
  '{a} e {b}. Chutou e o goleiro pegou',
  'Negativo, {a} e {b} tão em times diferentes',
  'Tadinho do {a}, achou que ia ter companhia e veio o {b}',
  'Lembra: {a} aqui, {b} ali',
  '{a} e {b} KKKKKK que isso',
  '{a} e {b}. Vai pro meu caderninho',
  '{a} e {b} viraram e disseram: não somos parentes',
  '{a} e {b} protestam contra esse clique',
  '{a} tava ali sozinho e cê trouxe o {b}. Climão',
  '{a} e {b}. Nem de longe, nem de perto',
  'Juntar {a} e {b}: rejeitado',
  'Errou! O {b} ficou até sem graça',
  '{a} e {b} nem se conhecem direito uai'
],

/* ---------- errou algo que já tinha visto ("você já viu esse!") ---------- */
memJaViu: [
  'Cê JÁ VIU o par do {nome}! Tava ali olhando pra você',
  'O outro {nome} já tinha aparecido. Esqueceu, clássico',
  'Cê já sabia onde tava o {nome}. Memória de peixinho dourado',
  'O {nome} tá magoado. Cê viu o gêmeo dele e fingiu que não',
  'Mano, o par do {nome} já tinha aparecido. Eu vi, o tabuleiro viu, só cê não',
  'Cê sabia onde tava o {nome}. SABIA',
  'Não quero ser chato, mas o outro {nome} tava bem ali',
  'Esquecimento clássico: o {nome} já tinha aparecido',
  'Isso dói em mim: o {nome} já tinha sido revelado e cê foi em outro',
  'Viu o par do {nome}, mas o cérebro não salvou o arquivo',
  'Tu já viu o {nome}! Ctrl+Z na memória',
  'O {nome} tava acenando: eu tava aqui, lembra? Não lembrou',
  'O gêmeo do {nome} já tinha aparecido. Tá tudo bem aí dentro?',
  'Esse era fácil, o {nome} já tinha mostrado a cara',
  'Viu o {nome}, deu tchau e esqueceu. Relação complicada',
  'JÁ TINHA VISTO! Tô gritando por dentro e por fora',
  'O outro {nome} achou que tinha deixado uma boa impressão',
  'Memória cheia? O {nome} já tinha aparecido',
  'Passou pelo par do {nome} e nem cumprimentou',
  'O {nome} já tava revelado. Isso não é azar, é esquecimento',
  'Informação disponível, informação ignorada. O {nome} já tinha aparecido',
  'Vou fingir que cê não viu o {nome} antes. Vou não, cê viu',
  'O par do {nome}! Quase apertei o card por você',
  'Tá jogando memória ou sorte? O {nome} já tinha aparecido',
  'Esqueceu o {nome}. Ele não esqueceu de você',
  'Tinha tudo pra acertar o {nome} e foi pro outro lado',
  'O {nome} já tinha dado as caras e seu cérebro deixou no visto',
  'Cê JÁ viu o {nome}. Da próxima é vergonha dupla',
  'Não é déjà vu não, cê viu o {nome} mesmo. E errou',
  'Tava escrito na testa: o {nome} já tinha aparecido mds'
],

memJaViuEvo: [
  'O {b} já tinha aparecido e ele é o par do {a}. Família separada',
  'Cê já viu o {b}, e ele é justamente o parente do {a}',
  'O {a} procurava o {b}. O {b} já tinha dado as caras',
  'Árvore genealógica ignorada: o {b} já tinha aparecido e é par do {a}',
  'O {b} tava revelado esperando o {a}. Deixou os dois no vácuo',
  'Reunião de família cancelada: cê já viu o {b}, par do {a}',
  'Ei! O {b} já apareceu, é dele que o {a} precisa',
  'Memória de peixinho: o {b}, par do {a}, já tinha sido virado'
],

/* ---------- mesmo card virado muitas vezes ---------- */
memMesmaCarta: [
  'Cê virou o {nome} {n} vezes. Ele já tá com dor de cabeça',
  '{n} vezes o {nome}. Tão namorando?',
  'O {nome} de novo mds',
  'O {nome} já decorou sua cara depois de {n} visitas. Cê ainda não decorou a dele',
  '{nome} de novo? Esse card vai pedir adicional de insalubridade',
  '{n}ª vez no {nome}. Ele vai começar a cobrar entrada',
  'O {nome} tá tonto de tanto girar. {n} vezes',
  'O {nome} já é de casa. {n} vezes, oferece um café',
  'Cê e o {nome}: ele aparece, cê esquece. {n} vezes',
  'Olha o {nome} de novo, pela {n}ª vez. E sem par',
  'O {nome} já tá gasto. Card de segunda mão',
  '{n} vezes virando o {nome}. Eu sei onde tá o par dele. Não conto',
  'O {nome} tá pensando em mudar de tabuleiro',
  'Esse {nome} já girou mais que pião. {n} vezes',
  'Desbloqueou: fã número 1 do {nome}. {n} viradas',
  'Tá virando o {nome} pra ver se ele muda? Ele não muda',
  'O {nome} continua sendo o {nome}. Confirmado {n} vezes',
  '{n}ª visita ao {nome}. Pede música no Fantástico já',
  'O {nome} tá tonto igual o Goku no treino de gravidade',
  'Vira o {nome}, esquece o {nome}, vira o {nome}. Loop infinito'
],

/* ---------- sequência de acertos ---------- */
memSequenciaAcerto: [
  '{n} pares seguidos! Quem é você e o que fez com o jogador de antes?',
  'Sequência de {n}. Tá voando',
  '{n} acertos seguidos. Tô ficando sem piada, para',
  'x{n} que isso mano, tá jogando demais',
  '{n} seguidos. Cérebro no modo Super Saiyajin',
  'Sequência de {n}. Printa isso',
  '{n} na sequência. Memória ou já tinha visto tudo? Conta igual',
  '{n} seguidos. Comeu peixe hoje?',
  'Combo de {n}! Até eu tô torcendo',
  '{n} pares sem errar. Memória fotográfica ou tá colando?',
  'Pegando fogo! {n} seguidos. Chama o Squirtle',
  'Sequência de {n}. O tabuleiro tá pedindo arrego',
  '{n} seguidos. Isso já é covardia com os cards',
  '{n} acertos! Preciso de uns minutos pra me recuperar',
  'COMBO x{n} MDSSSS',
  '{n} seguidos. Vou ficar quieto pra não dar azar. Opa, falei',
  'Máquina de par! {n} seguidos',
  '{n} na sequência. Só me resta assistir',
  'Modo Instinto Superior: {n} pares seguidos',
  '{n} seguidos. Virou show, cadê a pipoca'
],

/* ---------- sequência de erros ---------- */
memSequenciaErro: [
  '{n} erros seguidos. Tá tudo bem em casa?',
  '{n} errando na sequência. Respira e olha os cards',
  'Sequência de {n} erros. Também é combo, um combo triste',
  '{n} erros seguidos. O cérebro pediu demissão?',
  'Errou {n} vezes seguidas. Tá de propósito?',
  '{n} vacilos seguidos. Os cards não mudam de lugar. Quase nunca',
  'Errar {n} vezes pra confundir o inimigo? Tática nova?',
  '{n} seguidos errados. O Psyduck tá com dó de você',
  'Calma. {n} erros não é o fim. É só bastante',
  '{n} erros em fila. Nem o Yamcha perdia tão seguido',
  '{n} erros seguidos, parece roleta',
  'Sequência de {n} erros. Marcação bizarra, toda vez a mesma coisa',
  'Tá difícil hoje né. {n} erros, toma uma água',
  '{n} errados seguidos. Para de clicar no desespero',
  '{n} erros. Tô torcendo, lá no fundo',
  '{n} erros seguidos. Recorde pessoal?',
  'Mais um! São {n}. O Magikarp tá mais eficiente',
  '{n} erros seguidos. Patético KKKKK',
  'Antes de virar o segundo, pensa onde cê viu o primeiro. {n} erros pedem isso',
  '{n} seguidos. Relaxa, o Goku também apanha no começo da saga'
],

/* ---------- último par ---------- */
memUltimoPar: [
  'Último par! Esse nem precisa de memória',
  'Sobrou um par só. Se errar esse eu mudo de mascote',
  'Último par achado. Pode comemorar',
  'O último é sempre o mais fácil, por eliminação',
  'Fechou o tabuleiro!',
  'E cai o último par. Fim de temporada',
  'Último par! Tava sozinho no mundo, era só pegar',
  'Acabou! O último se entregou sem resistência',
  'Último par é tipo último pedaço de pizza, ninguém briga. Cê pegou',
  'Terminou! O último nem precisou de esforço',
  'Fim de tabuleiro. O último par agradece',
  'O último card nem teve graça, mas conta',
  'Tabuleiro limpo!',
  'Último par. Até eu acertava esse',
  'ACABOUUU. Os dois últimos se encontraram'
],

/* ---------- fim de nível por estrelas ---------- */
memFim3: [
  'Três estrelas! Memória de elefante confirmada',
  'TRÊS ESTRELAS MDSSSS',
  'Três estrelas cravadas. Printa e manda no grupo',
  'Três estrelas é o máximo que eu dou, e cê pegou',
  'Três estrelas! O tabuleiro nem viu o que aconteceu',
  'Três estrelas. Vou ter que mudar minha opinião sobre você',
  'Três estrelas. Comeu muito peixe na infância',
  'Cravou as três. Treina escondido, confessa',
  'Três estrelas brilhando igual esfera do dragão',
  'Nível fechado com três. Essa memória eu queria',
  'Três estrelas, que isso mano',
  'Estrela, estrela, estrela! Combo completo',
  'Três estrelas. Ia zoar mas cê não deixou espaço',
  'Nota máxima pro cérebro mais afiado do fliperama',
  'Três estrelas. Isso aqui virou tutorial'
],
memFim2: [
  'Duas estrelas. Boa, mas cê consegue três',
  'Duas estrelinhas. Passou, mas sem festa',
  'Duas estrelas! Faltou uns 2 erros a menos',
  'Duas estrelas. Honesto',
  'Passou com duas. A terceira ficou tímida',
  'Duas estrelas. Tá no caminho',
  'Duas! Se tivesse lembrado daquele card lá. Cê sabe qual',
  'Duas de três. O Vegeta chamaria de fracasso, eu chamo de ok',
  'Duas estrelas, mediano com orgulho',
  'Passou com duas. Repete pra caçar a terceira se quiser sofrer',
  'Duas estrelas. O terceiro brilho fica pra próxima',
  'Duas estrelas e um gostinho de quase'
],
memFim1: [
  'Uma estrela. Terminou, é o que importa',
  'Uma estrelinha sozinha. Repete pra dar companhia pra ela',
  'Passou com uma, raspando igual prova de física',
  'Uma estrela. O importante é participar',
  'Terminou! Uma estrela e muito erro, mas terminou',
  'Uma estrela. O Magikarp também começa assim',
  'Ufa, acabou. Uma estrela. Eu já tava com sono',
  'Uma estrela. Cada erro virou uma história. Longa',
  'Uma estrela. O Yamcha teria orgulho',
  'Uma estrela, mas eu vi esforço. Muito esforço',
  'Uma estrela. Da próxima olha os cards com mais carinho',
  'Uma estrela. Não é bonito, mas é seu'
],
memPerfeito: [
  'ZERO ERROS! Partida perfeita, fiquei sem palavras',
  'Perfeito! Cê é robô? Pisca duas vezes',
  'Sem errar nenhuma. Memória fotográfica ou colou na testa?',
  'Partida perfeita. O Professor Carvalho vai querer te estudar',
  'Nenhum erro. Mais limpo que a sala do Whis',
  'Zero erro. Isso nem é mais jogo, é demonstração',
  'PERFEITO. Vou gravar e mostrar pros outros jogadores',
  'Nenhum card virado à toa. Instinto Superior da memória',
  'Perfeito! Até os cards tão aplaudindo',
  'Não errou nada. Isso foi absurdo, não se acostuma',
  'Jogo sem falha, raro igual Pokémon shiny',
  'Perfeição absoluta. Vou precisar deitar'
],
memRapido: [
  'Terminou em {t}. Tá com pressa pra quê?',
  '{t}! Mais rápido que o Flash. O da câmera',
  'Em {t}, nem deu tempo de eu fazer as piadas que eu tinha preparado',
  '{t} e acabou. O Zapdos ficou com inveja',
  'Em {t}?? Cê piscou alguma vez?',
  'Voou, {t}. Tipo Goku na Nuvem Voadora',
  '{t} cravados. Speedrun de memória',
  'Rapidinho: {t}. Mal comecei minha pipoca',
  '{t}! O cronômetro ficou tonto',
  'Terminou em {t}. Já conhecia esse tabuleiro?',
  'Veloz! {t}. O Sonic mandou um abraço',
  'Em {t}, sem enrolação. Respeito'
],
memDevagar: [
  'Terminou em {t}. Deu pra ir no mercado e voltar',
  '{t}. Devagar e sempre, mais devagar que sempre',
  'Levou {t}. O Slowpoke te chamou de lento. O SLOWPOKE',
  '{t}! Envelheci aqui',
  'Terminou em {t}. 700 séculos',
  'Nesse tempo o Goku treinava num planeta inteiro. {t}',
  'Fechou em {t}. A pressa é inimiga da perfeição, e da sua memória também',
  '{t}. Tava fazendo pausa pro café?',
  'Levou {t}, mas chegou. Tipo 330 em dia de chuva',
  '{t} contemplando os cards',
  'Terminou em {t}. Na Sala do Tempo isso dava um ano',
  '{t}. Com calma, estilo tartaruga do Mestre Kame'
],

/* ---------- nível / jornada ---------- */
memNivel: [
  'Nível {n}! Vamo ver se a memória acompanha',
  'Chegamos no nível {n}',
  'Nível {n}. Mais card, mais chance de errar. De acertar, digo',
  'Nível {n}! Aqui o bicho pega',
  'Nível {n}. Leva a memória junto',
  'Nível {n}. Eu já sei onde tá tudo, cê não',
  'Nível {n}! Tá crescendo',
  'Nível {n}. Respira, estala os dedos e vira o primeiro',
  'Nível {n} na tela. Aposto duas estrelas',
  'Nível {n}. Quem te viu, quem te vê',
  'Nível {n}! Mais par, mais caos',
  'Nível {n}. Igual o Ash: nunca desiste e nunca envelhece',
  'NÍVEL {n}, a torcida vai à loucura. A torcida sou eu',
  'Nível {n}. Aperta o cinto',
  'Nível {n}. Passou desse, ganha um biscoito imaginário'
],
memNivelMaior: [
  'Tabuleiro maior! Agora são {n} pares',
  '{n} pares agora. Cresceu o tabuleiro, cresceu o sofrimento',
  '{n} pares na mesa. Usa mais que dois neurônios',
  'Olha o tamanho disso: {n} pares',
  'Subiu pra {n} pares. Os cards se multiplicaram',
  '{n} pares. Parece pouco né? Espera',
  'Agora são {n} pares. Contaria nos dedos se eu tivesse',
  '{n} pares! Virou álbum de figurinha'
],
memTwistEvolucao: [
  'Twist novo: EVOLUÇÃO! O par agora não é igual, é da mesma família. Charmander faz par com Charmeleon ou Charizard',
  'EVOLUÇÃO ligada! Os pares são parentes, não gêmeos. Pokémon com a evolução dele, guerreiro com a dupla famosa',
  'EVOLUÇÃO: achar igual tava fácil demais. Agora acha o parente',
  'Twist Evolução: o card não tem gêmeo, tem a evolução dele. No Dragon Ball é a dupla famosa, tipo Kuririn e 18',
  'Nível com Evolução! Viu um Bulbasaur? Procura a versão crescida dele',
  'Evolução ativada. O par é a mesma linha evolutiva, quero ver se cê conhece Pokémon de verdade',
  'O par do Squirtle é quem ele vira quando cresce. No Dragon Ball, a dupla dele. Isso é a EVOLUÇÃO',
  'Twist EVOLUÇÃO: esse separa treinador de turista. O par é a mesma linha evolutiva'
],
memTwistSombra: [
  'Twist novo: SOMBRA! Um card de cada par aparece só a silhueta. Reconhece pelo formato',
  'SOMBRA ligada! Metade dos cards vem no escuro. Olha o contorno',
  'SOMBRA: um card de cada par é só silhueta, sem nome. Olho de lince',
  'Twist Sombra: sem cor, sem nome, só o contorno. Igual o intervalo do desenho',
  'Nível com Sombra! Um dos dois cards do par é só a sombra preta',
  'Sombra ativada. Um card de cada par vem só o contorno, é memória e reconhecimento junto',
  'SOMBRA! Um card de cada par é silhueta. Se reconhecer o Pikachu só pela orelha ganha meu respeito',
  'Twist SOMBRA: é o Quem é esse Pokémon dentro do jogo da memória. Um card de cada par é só a sombra'
],
memTwistBagunca: [
  'Twist novo: BAGUNÇA! A cada erro, dois cards virados pra baixo trocam de lugar. Fica de olho',
  'BAGUNÇA ligada! Errou, eu troco dois cards de lugar na sua frente',
  'BAGUNÇA: cada erro mexe o tabuleiro. Acompanha a troca com o olho',
  'Twist Bagunça: quando cê erra, dois cards escondidos dançam e trocam de lugar',
  'Nível com Bagunça! A cada erro eu mexo em dois cards e cê vai me odiar',
  'BAGUNÇA! Dois cards dão um passinho e trocam de lugar a cada erro',
  'Bagunça: agora errar tem consequência. Dois cards trocam de lugar',
  'Twist BAGUNÇA: a cada erro dois cards trocam. Olho neles, senão já era'
],
memTwistRelampago: [
  'Twist novo: RELÂMPAGO! Cê vai ver todos os cards por 3 segundos. Decora rápido',
  'RELÂMPAGO! Três segundos com tudo aberto no começo. Aproveita',
  'RELÂMPAGO ligado: tudo virado pra cima por 3 segundos. Foto mental agora',
  'Twist Relâmpago: eu mostro tudo por 3 segundos e depois escondo',
  'Nível com Relâmpago! Tudo aberto por 3 segundos. Não pisca',
  'RELÂMPAGO! O Zapdos emprestou a energia. Três segundos de flash',
  'Relâmpago: memória de curtíssimo prazo, 3 segundos com tudo aberto',
  'Twist RELÂMPAGO: olha tudo, guarda tudo, 3 segundos'
],
memTwistCombo: [
  'Dois twists juntos. Eu sou ruim, eu sei',
  'Combo de twist. Esse nível foi feito por alguém que te odeia. Eu',
  'Twist em dobro. Sobreviveu, ganha estrela',
  'Twist empilhado, tipo fusão de sofrimento',
  'Mais de um twist. Sala do Tempo da memória',
  'Combinação de twist. Nem o Grande Sacerdote passa sem suar',
  'Twist misturado, lasanha de dificuldade',
  'Esse nível tem twist, e twist, e mais twist. Boa sorte'
],

/* ---------- falas durante os twists ---------- */
memEvolucao: [
  '{a} e {b}! Família reunida',
  'Isso! {a} e {b}, evolução ou dupla, tanto faz, é par',
  '{a} com {b}. Conhece a linha evolutiva, treinador de verdade',
  'Par evolutivo: {a} e {b}',
  '{a} olhou pro {b}: vou ser assim quando crescer? Vai',
  'Acertou a família: {a} e {b}. Almoço de domingo garantido',
  '{a} e {b} juntos. Conhecimento de Pokédex',
  '{a} e {b}! Até a pedra evolutiva aplaudiu',
  '{a} ↔ {b}. Não só lembrou, entendeu',
  '{a} e {b}. Manda pro Professor Carvalho',
  'Boa! {a} e {b}, tipo pai e filho. Ou tipo Goku e Gohan',
  '{a} e {b}, parentes que se encontraram. Novela das oito',
  'Pegou! {a} e {b}',
  'Família detectada: {a} e {b}. Geneticista',
  '{a} e {b}. Mesmo DNA ou mesma saga'
],
memEvolucaoErro: [
  '{a} e {b}? Não são da mesma família',
  '{a} não evolui pra {b}, por mais que cê queira',
  '{a} e {b}: evolução inventada',
  '{a} e {b} nem se cumprimentam no almoço de família',
  '{a} virar {b}? Só em fanfic',
  'Essa evolução não existe. Manda pra Game Freak',
  '{a} e {b}: parentesco zero',
  'Nem com pedra da lua o {a} vira {b}'
],
memSombra: [
  'Reconheceu pela sombra! {nome}. Olho de lince',
  'A silhueta era {nome}! Versão memória do intervalo do desenho',
  'Quem é esse Pokémon? É o {nome}! Acertou pela sombra',
  'Pela sombra! {nome} saiu do escuro e ganhou cor',
  'Silhueta decifrada: {nome}',
  '{nome} de sombra e {nome} colorido. Duas versões, um par',
  'Reconheceu o {nome} só pelo contorno. Respeito',
  'A sombra do {nome} não te enganou',
  'Sombra identificada: {nome}',
  '{nome} saiu das trevas KKKKK',
  'Olha a cor voltando pro {nome}',
  'Pela silhueta! {nome} tem um contorno marcante, mas mesmo assim, boa'
],
memSombraErro: [
  'Errou a sombra. A silhueta te enganou',
  'Não era essa sombra. Olha orelha, rabo, topete',
  'Silhueta traiçoeira. Parecia, mas não era',
  'Sombra errada. Aqui não tem narrador do intervalo pra ajudar',
  'Cê já tinha visto esse contorno! A sombra tá rindo de você',
  'Essa sombra não combina nem no escuro',
  'No escuro todo Pokémon é pardo. Errou',
  'Olha o formato, não a cor. Que nem tem',
  'Errou pela sombra. Acontece bastante',
  'A sombra fez cara de paisagem. Não era ela'
],
memBagunca: [
  'Errou! BAGUNÇA: dois cards trocaram de lugar',
  'Bagunça! Mexi dois cards. Viu?',
  'Dois cards dançaram e trocaram de lugar. Culpa sua',
  'Errou, eu bagunço. É o acordo',
  'Troquei dois. Sua memória ficou desatualizada',
  'Bagunça! Dois cards mudaram de casa',
  'Olha a dança! Acompanhou?',
  'Mexi KKKKK quais? Problema seu',
  'Bagunça! Se piscou já era',
  'Dois cards trocaram de lugar igual troca de carteira na sala',
  'Mais um erro, mais uma bagunça',
  'Trocadinha básica. Olho vivo',
  'Fiz uma bagunçinha pequena',
  'Troquei. Aquele lugar que cê decorou pode não ser mais',
  'Troquei dois cards. Amo muito tudo isso tá maluco'
],
memRelampago: [
  'Olha tudo! Três segundos! DECORA',
  'Flash! Tá tudo aberto, fotografa com o cérebro',
  'Relâmpago! Olha os cards, não eu',
  'Vê tudo agora, depois some',
  'Olho nos cards, mais rápido que o Zapdos',
  'Tá vendo? Não vai ver mais! Decora',
  'Tudo à mostra. Grava pelo menos os cantos',
  'Três segundos de spoiler. Aproveita',
  'Foto mental: click!',
  'Rápido rápido! Os cantos são traiçoeiros',
  'RELÂMPAGO! Olha olha olha',
  'Três segundos de vantagem. Não gasta olhando pra mim'
],
memRelampagoFim: [
  'Apagou! Agora é com você',
  'Escuridão. Tomara que o flash tenha ficado gravado',
  'Acabou o spoiler. Agora é memória raiz',
  'Cards escondidos. Guardou quantos? Aposto uns 3',
  'Fim do relâmpago. Foi foto ou borrão?',
  'Virei tudo. Mostra o que cê decorou',
  'Três segundos passaram voando né',
  'Luz apagada. Acende a memória'
],

/* ---------- diário ---------- */
memDiarioOi: [
  'Desafio do Dia! Mesmo tabuleiro pra todo mundo',
  'Diário: 8 pares, um cronômetro e sua reputação em jogo',
  'Esse tabuleiro é igual pro Brasil inteiro. Não passa vergonha nacional',
  'Desafio do Dia. Menos jogada e menos tempo é melhor',
  'O tabuleiro de hoje é o mesmo pra geral. Os erros cada um tem os seus',
  'Diário na área. Só a primeira vez vale, capricha',
  'Mesmo tabuleiro pra todo mundo. Dá pra comparar. E zoar',
  'Oito pares, uma chance de brilhar ou virar meme',
  'Diário! Joga bem que o grupo vai ver',
  'Bora de diário. Cada jogada conta, cada segundo também'
],
memDiarioFeito: [
  'Diário feito! {m} jogadas em {t}. Manda no grupo',
  'Desafio do Dia feito: {m} jogadas. Quero ver alguém bater',
  'Diário no bolso: {m} jogadas, {t}',
  'Fechou o diário em {t}. Placar salvo',
  'Diário resolvido! {m} jogadas. Amanhã tem outro',
  '{m} jogadas e {t} de relógio. Anota na geladeira',
  'Diário: CHECK. {m} jogadas. Jornada liberada',
  'Mandou o diário em {t}. Compartilha pra provocar a galera',
  'Diário feito com {m} jogadas. Se foi pouco, top. Se foi muito, amanhã tem outro',
  'Terminou o diário. Guardei: {m} jogadas, {t}',
  'Diário completo. Espalha esse {t} no grupo',
  'Diário feito. Agora espera a meia-noite ou vai pra Jornada, viciado'
],
memDiarioJaFeito: [
  'Cê já fez o diário de hoje. Volta amanhã ou joga a Jornada',
  'Diário já feito. Pode jogar de novo, mas não conta',
  'Esse já foi! Resultado guardado',
  'Já fez o de hoje. Jogar de novo não muda o placar',
  'O diário tá feito. Voltou pra admirar?',
  'Diário completo. A Jornada tá chamando',
  'Voltou pro diário que já acabou? Saudade dos cards',
  'Esse tabuleiro cê já venceu. Amanhã tem outro',
  'Diário de hoje concluído. Jogar de novo é por amor, não vale ponto',
  'Já tá feito. Compartilhou? Não? Compartilha'
],

/* ---------- temas ---------- */
memTema: [
  'Tema trocado: {tema}. Cara nova, erro velho',
  '{tema}! Boa escolha. Ou não',
  'Agora é {tema}. Os cards trocaram de roupa',
  'Mudou pra {tema}. Espero que cê conheça esse povo',
  '{tema} na mesa',
  'Tema {tema} ativado',
  '{tema}! Troquei tudo, menos minha opinião sobre você',
  'Beleza, {tema}. Gente nova',
  '{tema} selecionado. Os cards velhos foram pra caixa',
  'Tema novo: {tema}. Bora'
],

/* ---------- ajuda / stats ---------- */
memAjuda: [
  'Leu tudo? Não leu. Relaxa, eu explico de novo quando cê errar',
  'Resumo: vira dois, se forem par ficam abertos. Se não, eu zoo',
  'Dica: começa pelos cantos. Não sei se ajuda, mas parece profissional',
  'Pronto, agora cê sabe o suficiente pra errar com propriedade',
  'Pode fechar a ajuda, eu fico aqui de assistente'
],
memStats: [
  'Suas estatísticas. Número não mente',
  'Olha os números. Tem coisa boa e coisa feia',
  'A prova documental da sua memória',
  'Tá vendo o recorde? Eu vi',
  'Números! Tipo card, só que não vira',
  'Seu histórico: estrela, jogada e vergonha. Completo',
  'Cuidado, pode dar orgulho ou crise',
  'Esses números foi cê que fez. Todos'
],
memNiveis: [
  'Mapa da Jornada. Escolhe um nível pra repetir ou continua de onde parou',
  'Olha quanto nível! Uns com três estrelas, outros nem tanto',
  'Quer caçar estrela antiga? Escolhe o nível',
  'Tem buraco de estrela aí hein',
  'Os bloqueados ficam me olhando com cadeado',
  'Escolhe um. Menos aquele que cê tá evitando'
],
memRecomecar: [
  'Recomeçou. Fingindo que nada aconteceu né',
  'Reset! Os erros foram pro limbo. Eu não esqueci',
  'Recomeçando. Tabuleiro novo, manias velhas',
  'Botão de recomeçar, melhor amigo de quem errou demais',
  'Tudo de novo, esperança renovada',
  'Apagou a vergonha e começou de novo. Esperto',
  'Embaralhei de novo. Dessa vez vai',
  'Recomeçar também é tática. Covarde, mas é'
],

/* ---------- parado no meio da partida ---------- */
memParado: [
  'Pensando onde tava aquele card? Eu sei onde tá. Não conto',
  'Oi? Os cards tão esfriando',
  'Os cards não vão virar sozinhos não',
  'Se ficar parado a memória evapora. Não é ciência, mas parece',
  'O cronômetro correndo e cê contemplando',
  'Esqueceu que tava jogando? Acontece com peixinho dourado',
  'Ô, cê tá vivo?',
  'Parado assim parece o Metapod usando Endurecer',
  'Esperando os cards se mexerem? Só no Bagunça',
  'Tempo passando, memória apagando. Vira um card',
  'Tô aqui contando os segundos. E zoando cada um',
  'Pensar demais dá dor de cabeça igual o Psyduck',
  'O Snorlax ligou, disse que cê tá no ritmo dele',
  'Se cê não virar um card eu viro. Não tenho mão, mas a vontade tá aqui',
  'Tá lembrando dos pares ou da conta de luz?'
]
};

/* ---------- falas por personagem (viram categorias "memP:<nome>") ---------- */
const PERS = {
  'Psyduck': ['Virou o Psyduck. A dor de cabeça dele é contagiosa', 'Psyduck! Mesma cara que cê faz quando erra'],
  'Pikachu': ['Pikachu! Todo mundo acerta esse, não se acha', 'Pika pika. Tradução: demorou hein'],
  'Magikarp': ['Magikarp! Não serve pra nada, mas cê achou', 'Par de Magikarp. Usou Splash, nada aconteceu'],
  'Gyarados': ['Gyarados! Lembra quando era Magikarp? Nem ele lembra', 'Gyarados achado. Não irrita ele pelo amor'],
  'Charizard': ['Charizard! O card mais caro do recreio de 1999', 'Achou o Charizard. Guarda num plástico isso aí'],
  'Charmander': ['Charmander! Cuidado com o rabo, os cards são de papel', 'Charmander achado. Fofo agora, depois vira dragão estressado'],
  'Bulbasaur': ['Bulbasaur! Planta nas costas e zero reclamação', 'Par de Bulbasaur. Rega ele que ele merece'],
  'Squirtle': ['Squirtle! Põe o óculos escuro, é o Esquadrão Squirtle', 'Squirtle achado. Seca o card que ele molhou tudo'],
  'Snorlax': ['Snorlax! Esse card levou 3 dias pra virar', 'Achou o Snorlax. Ele nem acordou pra comemorar'],
  'Ditto': ['Ditto! Pera, qual dos dois é o Ditto de verdade?', 'Par de Ditto. Ou um Ditto imitando o outro, nunca vamos saber'],
  'Eevee': ['Eevee! Oito evoluções e cê mal lembrava onde ele tava', 'Eevee achado. Tem mais opção de carreira que eu'],
  'Mewtwo': ['Mewtwo! Ele leu sua mente e disse que tava vazia', 'Mewtwo achado. Clonado igual esse par'],
  'Mew': ['Mew! A gente jurava que tinha um caminhão escondendo ele', 'Achou o Mew. Raríssimo, igual cê acertar de primeira'],
  'Jigglypuff': ['Jigglypuff! Não deixa cantar senão cê dorme e esquece tudo', 'Achou o Jigglypuff. Ele já pegou o microfone, corre'],
  'Meowth': ['Meowth! Único gato que fala mais que eu', 'Meowth, é isso aí! Achou o par dele'],
  'Slowpoke': ['Slowpoke! Ele vai perceber que foi achado daqui a uns 5 segundos', 'Achou o Slowpoke. Ele ainda tá processando'],
  'Gengar': ['Gengar! Fantasma roxo e mais debochado que eu', 'Achou o Gengar. Ele tá rindo de você, eu também'],
  'Onix': ['Onix! Cobra de pedra, pesada igual esse nível', 'Achou o Onix. Precisou de dois cards pra caber ele'],
  'Machamp': ['Machamp! Quatro braços, virava quatro cards de uma vez', 'Machamp achado. Ele queria um high-five quádruplo'],
  'Voltorb': ['Voltorb! Ou é Pokébola? Ninguém nunca sabe', 'Achou o Voltorb. Sorte que não explodiu'],
  'Electrode': ['Electrode! Outro que parece Pokébola', 'Electrode achado. Não aperta forte'],
  'Mr. Mime': ['Mr. Mime! Tá fingindo que tem uma parede invisível entre os cards', 'Achou o Mr. Mime. Ele aplaudiu em silêncio'],
  'Porygon': ['Porygon! Pokémon digital, meu primo distante', 'Porygon achado. Somos da mesma família: pixel'],
  'Dragonite': ['Dragonite! O dragão mais fofo da história', 'Achou o Dragonite. Ele entrega carta, carteiro de luxo'],
  'Lapras': ['Lapras! Carona pra atravessar o mar', 'Achou a Lapras. Ela cantou de alegria'],
  'Butterfree': ['Butterfree! Lembra do episódio da despedida? Nunca superei', 'Achou a Butterfree. Bye bye Butterfree, mds que episódio'],
  'Metapod': ['Metapod! Usou Endurecer. Só sabe isso', 'Achou o Metapod. Ele não se mexeu, nunca se mexe'],
  'Caterpie': ['Caterpie! Lagartinha mais esforçada do mundo', 'Caterpie achado. Vai contar pra mãe'],
  'Zubat': ['Zubat! O mais chato de toda caverna, e cê achou dois', 'Achou o Zubat. Pelo menos aqui ele não aparece a cada 3 passos'],
  'Abra': ['Abra! Se demorar ele teleporta, rápido', 'Achou o Abra antes dele fugir. Feito histórico'],
  'Diglett': ['Diglett! Ninguém nunca viu o corpo dele', 'Achou o Diglett. Só mostra a cabeça, igual eu na janela'],
  'Cubone': ['Cubone! Dá um abraço nele, ele precisa', 'Achou o Cubone. Esse aí tem história triste, respeita'],
  'Chansey': ['Chansey! Enfermeira oficial. Cura seus erros? Não', 'Achou a Chansey. Pede um ovo pra ela'],
  'Togepi': ['Togepi! Cara de quem vai aprontar', 'Achou o Togepi. Cuidado que ele usa Metrônomo e sai qualquer coisa'],
  'Sudowoodo': ['Sudowoodo! Parece árvore e é pedra. Igual esse jogo, parece fácil', 'Achou o Sudowoodo. Fingiu que era planta pra cê não perceber'],
  'Wobbuffet': ['WOBBUFFET! Ele sempre grita o nome, eu também', 'Achou o Wobbuffet. Wobbuuuffet!'],
  'Lucario': ['Lucario! Ele sente aura. A sua tá meio confusa', 'Achou o Lucario. Ele respeitou sua memória, um pouco'],
  'Bidoof': ['Bidoof! O Pokémon mais subestimado do mundo', 'Achou o Bidoof. Simples e feliz, seja igual o Bidoof'],
  'Arceus': ['Arceus! O criador do universo Pokémon no seu tabuleiro', 'Achou o Arceus. Tipo achar Deus embaixo de um card'],
  'Rayquaza': ['Rayquaza! Dragão enorme num cardzinho, apertado', 'Achou o Rayquaza. Ele mora no céu, cê no sofá'],
  'Goku': ['Goku! Tá com fome, sempre tá', 'Achou o Goku! Ele vai te chamar pra lutar, fala que não'],
  'Vegeta': ['Vegeta! Não chama ele de segundo lugar', 'Achou o Vegeta. Ele vai dizer que te ajudou'],
  'Kuririn': ['Kuririn! Tomara que sobreviva a esse tabuleiro', 'Achou o Kuririn. Vivo! Por enquanto'],
  'Yamcha': ['Yamcha! Pelo menos na memória ele não perde', 'Achou o Yamcha. Já tá deitado naquela pose'],
  'Mr. Satan': ['Mr. Satan! Vai dizer que achou o par sozinho', 'Achou o Mr. Satan. O campeão agradece, com pose'],
  'Piccolo': ['Piccolo! Tira a capa que ela pesa uma tonelada', 'Achou o Piccolo. Quase sorriu'],
  'Freeza': ['Freeza! Não gosta de perder nem de ser achado', 'Achou o Freeza. Tá bolado na terceira forma'],
  'Cell': ['Cell! Absorveu a memória de alguém. Não a sua, que tá igual', 'Achou o Cell. Perfeito, ele diria'],
  'Majin Boo': ['Majin Boo! Cuidado que ele te vira chocolate', 'Achou o Majin Boo. Ele já quer comer o card'],
  'Bills': ['Bills! Errar muito aqui e ele destrói o tabuleiro', 'Achou o Bills. Ele quer pudim de recompensa'],
  'Whis': ['Whis! Anjo mais chique do multiverso', 'Achou o Whis. Ele riu educadamente da sua demora'],
  'Zeno Sama': ['Zeno Sama! Não faz barulho que ele apaga universo por tédio', 'Achou o Zeno Sama. Ele achou divertido, cê sobreviveu'],
  'Mestre Kame': ['Mestre Kame! Mais interessado na revista que no jogo', 'Achou o Mestre Kame. O véio mandou um joinha'],
  'Bulma': ['Bulma! Ela tem uma cápsula que guarda o tabuleiro inteiro', 'Achou a Bulma. Gênia reconhece gênio. Quase gênio'],
  'Chi-Chi': ['Chi-Chi! Quer saber se cê fez o dever de casa', 'Achou a Chi-Chi. Ela vai mandar o Gohan estudar'],
  'Gohan': ['Gohan! Meio Saiyajin, meio estudante, 100% nerd', 'Achou o Gohan. Ele tá de caneta na mão'],
  'Capitão Ginyu': ['Capitão Ginyu! Trocou de corpo com o outro card, por isso é igual', 'Achou o Ginyu. Pose das Forças Especiais!'],
  'Androide 18': ['Androide 18! Ela tá cansada de você errar. Eu também', 'Achou a 18. O Kuririn tá orgulhoso'],
  'Broly': ['Broly! Par lendário', 'Achou o Broly. Ele gritou KAKAROTTO do nada'],
  'Jiren': ['Jiren! Ele não fala nada, eu falo por dois', 'Achou o Jiren. Força é tudo, ele diria. Memória também, eu digo'],
  'Kaio do Norte': ['Kaio do Norte! Conta uma piada ruim pra ele, ele ama', 'Achou o Kaio do Norte. O Bubbles e o Gregory comemoraram']
};
for (const k in PERS) L['memP:' + k] = PERS[k];
window.MEM_PERS = Object.keys(PERS);

/* ---------- cutucar o mascote aqui ---------- */
L.cutucarMemoria = [
  'Ei! Me cutucar não revela card nenhum',
  'Cutucou. Agora eu lembro de você, diferente de você com os cards',
  'Cutuca menos e vira mais card',
  'Tô ocupado decorando o tabuleiro pra te zoar depois',
  'Me cutucar é igual virar o mesmo card de novo: não muda nada',
  'Para! Não sou card do tabuleiro',
  'Tenho memória de 8 bits e ainda lembro mais que você',
  'Se fosse par seria irritação com irritação',
  'Não sou card, mas sou fofo',
  'Me deixa, tô contando quantas vezes cê esqueceu o mesmo card',
  'Ai! Doeu no meu pixel preferido',
  'Me cutucou pra me distrair? Eu não tô jogando, cê tá',
  'Procurando meu par? Não existe, sou único',
  'Sou o coringa. Não combino com nada, só com o caos',
  'Cutucar mascote não conta como jogada. Mas eu tô contando',
  'Se eu fosse card eu era o holográfico raro',
  'Olha os cards, não eu. Tá, pode olhar um pouquinho',
  'Cê me cutuca e esquece, igual os cards. Tô vendo um padrão',
  'Não me vira que eu fico tonto',
  'Dica grátis: presta atenção',
  'Cutuca de novo que eu viro um Ditto de você',
  'Tô de olho em você. E nos cards. Mais nos cards',
  'Tá me usando de pausa? Pausa charmosa pelo menos',
  'Eu não jogo memória porque lembro de tudo, fica sem graça',
  'Ai! Vai pras estatísticas: cutucadas, muitas',
  'Cutuquei de volta mentalmente. Sentiu?',
  'Não sou par, sou ímpar e me orgulho',
  'Me achou. Parabéns. Não ganha estrela',
  'Mais 3 cutucadas e eu troco dois cards de lugar. Tô zoando. Tô?',
  'O Psyduck falou que cê é gente boa, mas ele tava com dor de cabeça',
  'Cutucar mascote não é técnica de memória comprovada',
  'Meu nome é Bugado, não card extra',
  'Esse card aqui não vira, ele só fala',
  'Eu sei onde tão todos os pares e não vou contar. Tá bom demais te ver sofrer',
  'Isso faz cócegas. Faz de novo. Não, para',
  'Cê me cutuca igual o Goku bate: sem motivo e com força',
  'Pode cutucar à vontade, os pares não vão se achar sozinhos',
  'Sou sua memória externa. A que zoa você',
  'Bugado igual não tem, edição limitada',
  'Cutucar em vez de jogar. Eu faria o mesmo',
  'Se eu fosse Pokémon eu era tipo Fantasma/Debochado',
  'Vai lá, vira dois. Tô torcendo. A favor, juro'
];

/* ---------- 'aleatorio' temático (soma às falas gerais) ---------- */
const ALEA = [
  'O jogo da memória mais antigo que se conhece era com concha no Japão. Chama kai-awase, juro',
  'Polvo tem memória ótima. Oito braços e lembra onde deixou tudo',
  'Peixinho dourado lembra de coisa por meses, então nem tem desculpa',
  'Dizem que elefante nunca esquece. Nunca vi um jogar memória, então sla',
  'Minha memória é de 8 bits. Cabe umas 256 coisas, 200 são piada sobre você',
  'Uma vez esqueci onde guardei minha memória',
  'Se eu virasse card qual seria meu par? Um espelho, provavelmente',
  'Se card tivesse sentimento tava tonto de tanto girar',
  'O Ditto ia estragar qualquer jogo da memória',
  'O Alakazam tem QI de 5000. Zerava isso em dois minutos',
  'Imagina um jogo da memória só de Magikarp. Cem cards iguais',
  'Vou lançar a coleção Bugado Holográfico. Um card só: eu',
  'Cérebro guarda umas 7 coisas por vez. Hoje cê tá usando umas 3',
  'Minha memória favorita é cê errando o mesmo par 3 vezes',
  'A Nuvem Voadora ia ser ótima pra buscar card embaixo do sofá',
  'O recorde de decorar um baralho é menos de 15 segundos. Relaxa, cê não é concorrência',
  'Às vezes eu fico de ponta-cabeça só pra ver o mundo como card virado',
  'O Mestre Kame tem uns 300 anos. Imagina quanta coisa ele esqueceu',
  'Se esquecer tudo, sorri. Os cards não sabem',
  'Joguei memória com o Snorlax uma vez. Ele dormiu na segunda jogada, ganhei de W.O.',
  'Todo card virado pra baixo parece igual. É de propósito, maldade pura',
  'Se memória fosse tipo de Pokémon a sua era Normal. Sem ofensa',
  'Queria memória fotográfica. Tenho memória de print desfocado',
  'Esquilo esquece onde enterrou noz e nasce árvore. Seu esquecimento plantava uma floresta',
  'O card mais raro do mundo é o que cê lembrou de primeira',
  'Embaralhei esses cards com muito amor e um pouco de maldade',
  'Eu contra o Gengar no jogo da memória? Eu ganho fácil',
  'Tem mais de mil Pokémon aqui dentro. Contei e fiquei tonto',
  'Todo mundo pede imortalidade pro Shenlong. Ninguém pede memória boa. Desperdício',
  'Cérebro humano pesa 1,4 kg. O meu pesa 3 kilobytes',
  'Dormir bem melhora a memória. Por isso o Snorlax é gênio',
  'Uma vez vi um card virando sozinho. Era eu, tava entediado',
  'Meu par perfeito é um pastel',
  'Quer treinar memória? Lembra meu nome: Bugado. Pronto',
  'O Kuririn morreu tanto que deve ter memória de reencarnação',
  'Pesquisa diz que jogar memória faz bem pro cérebro. Pesquisa também diz que eu sou fofo',
  'Os cards hoje tão comportados demais. Suspeito',
  'O Duolingo quebrou minha ofensiva de novo. Minha memória é igual',
  'Papo reto, auge do meu dia é ver cê errando par fácil',
  'Decorei o itinerário do 330 inteiro mas não decoro onde deixo a chave'
];

window.Bugado.addLines(L);
window.Bugado.extendLines({ aleatorio: ALEA });
window.Bugado.addLines({
  memParadoMix: window.Bugado.lines('parado').concat(L.memParado),
  // quando o evento não tem fala própria, mistura personagem + genérico
});
})();
