/* ==========================================================
   Quem é esse Guerreiro? — banco de personagens (Dragon Ball)
   Nomes como na dublagem brasileira.

   Colunas de cada linha (mapeadas pra objeto no fim do arquivo):
   nome, apelidos, raca, genero, afiliacao, estreia, saga, planeta,
   cabelo, transforma, poder, img, frase

   Convenções (decisões pra deixar o jogo justo):
   - estreia: 1 Dragon Ball · 2 Dragon Ball Z · 3 Filmes Z (inclui especiais de TV)
              4 Dragon Ball GT · 5 Dragon Ball Super (inclui filmes/mangás da era Super)
   - planeta: planeta natal; se a origem é desconhecida mas o lar é conhecido
              (deuses, anjos), vale o lar. Senão, "Desconhecido".
   - cabelo: cor na forma base mais conhecida. Carecas e quem não tem cabelo = "Nenhum".
   - transforma: tem transformação/forma alternativa mostrada em cena
              (Oozaru só conta se aparece transformado na obra).
   - poder: pico canônico, escala 1–10:
       1 gente comum (Mr. Satan) · 2 lutador fraco/soldado · 3 mestre do DB clássico
       4 início do Z (Raditz) · 5 elite de Namekusei · 6 era Androides
       7 era Cell/Boo forte · 8 elite do Super · 9 topo (Goku, Vegeta, Bills, Jiren)
       10 anjos e Zeno Sama
   - afiliação: a mais marcante do personagem.
   ========================================================== */
(() => {
const A = 'https://dragonball-api.com/characters/';
const T = 'https://dragonball-api.com/transformaciones/';
const M = 'Masculino', F = 'Feminino', O = 'Outro';
const S = 'Sim', N = 'Não';

const rows = [
/* ----------------------------- DRAGON BALL (1) ----------------------------- */
['Goku', ['Kakarotto','Kakaroto','Son Goku','Goku Criança'], 'Saiyajin', M, 'Guerreiros Z', 1, 'Saga Pilaf', 'Vegeta', 'Preto', S, 9, A+'goku_normal.webp',
 'Bateu a cabeça quando bebê e virou o sujeito mais gente boa do universo. Come por dez e some por anos.'],
['Bulma', ['Buma'], 'Humano', F, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Azul', N, 1, A+'bulma.webp',
 'Gênia da Corporação Cápsula. Inventou o radar e, sem ela, ninguém achava esfera nenhuma.'],
['Mestre Kame', ['Mestre Roshi','Kame-Sennin','Muten Roshi','Jackie Chun','Roshi'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Pilaf', 'Terra', 'Nenhum', S /* forma MAX POWER */, 5, A+'roshi.webp',
 'Velho safado de óculos escuros que inventou o golpe mais famoso do anime. Mora numa ilha com uma tartaruga.'],
['Oolong', ['Ulong','Porco'], 'Animal', M, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Nenhum', S /* se transforma em qualquer coisa por 5 min */, 1, '',
 'Porquinho que se transforma em qualquer coisa por cinco minutos. Fez o pedido mais famoso da história: uma calcinha.'],
['Puar', ['Pual'], 'Animal', O /* gênero nunca definido */, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Nenhum', S, 1, '',
 'Gatinho azul voador que muda de forma e vive grudado num certo ex-bandido do deserto.'],
['Yamcha', ['Iamcha','Yamucha'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 5, A+'Final_Yamcha.webp',
 'Ex-bandido do deserto que tinha medo de mulher. Ficou famoso por uma pose deitado numa cratera.'],
['Chi-Chi', ['Chichi','Chi Chi','Xixi'], 'Humano', F, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 2, A+'ChiChi_DBS.webp',
 'Quer o filho estudando, não lutando. Casou com um cara que prometeu casamento achando que era comida.'],
['Rei Cutelo', ['Ox King','Gyuu Maou','Rei Gyuumao','Cutelo'], 'Humano', M, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 2, '',
 'Gigante barbudo da Montanha de Fogo, ex-aluno do velho da ilha. Sogro mais tranquilo do anime.'],
['Imperador Pilaf', ['Pilaf','Pilaf Sama'], 'Outro', M, 'Vilão', 1, 'Saga Pilaf', 'Terra', 'Nenhum', N, 1, '',
 'Diabinho azul que queria dominar o mundo com as esferas e sempre perdia pra uma criança.'],
['Mai', ['Mai Pilaf'], 'Humano', F, 'Vilão', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 1, '',
 'Braço direito de um imperador baixinho. No Super virou criança e arrumou um namoradinho do futuro.'],
['Tartaruga Umigame', ['Umigame','Tartaruga','Tartaruga Marinha'], 'Animal', M, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Nenhum', N, 1, '',
 'Foi salva por um menino perdido e agradeceu levando ele até um velho tarado. Tem mil anos.'],
['Launch', ['Lunch','Lanchi'], 'Humano', F, 'Aliados', 1, 'Saga Torneio (21º Torneio)', 'Terra', 'Azul' /* loira quando espirra */, S /* muda de personalidade ao espirrar */, 2, A+'Lunch_traje_de_sirvienta_en_el_manga.webp',
 'Um espirro e ela vira outra pessoa: some a menina doce, chega a loira de metralhadora.'],
['Kuririn', ['Krillin','Kulilin','Kurilin'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Torneio (21º Torneio)', 'Terra', 'Nenhum' /* careca clássico; cabelo só no fim do Z */, N, 6, A+'Krilin_Universo7.webp',
 'Careca de seis pontinhos na testa, melhor amigo do protagonista e recordista mundial em morrer.'],
['Tenshinhan', ['Tien','Ten Shin Han','Tenshin','Tien Shinhan'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Tenshinhan (22º Torneio)', 'Terra', 'Nenhum', N, 6, A+'Tenshinhan_Universo7.webp',
 'Três olhos, careca, ex-aluno da Escola Garça. Inventou um canhão em formato de triângulo.'],
['Chaos', ['Chiaotzu','Chaozu','Chaoz'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Tenshinhan (22º Torneio)', 'Terra', 'Nenhum', N, 4, '',
 'Pequenininho, branquinho, bochecha vermelha e telecinese. Se explodiu agarrado num Saiyajin. Não adiantou nada.'],
['Tao Pai Pai', ['Mercenário Tao','Taopaipai','Tao'], 'Humano', M, 'Exército Red Ribbon', 1, 'Saga Red Ribbon', 'Terra', 'Preto', N, 3, '',
 'Assassino de aluguel que viajava em cima do tronco que ele mesmo arremessou.'],
['General Blue', ['Blue','General Azul'], 'Humano', M, 'Exército Red Ribbon', 1, 'Saga Red Ribbon', 'Terra', 'Loiro', N, 2, '',
 'Oficial loiro e vaidoso do exército da fita vermelha, com poder de paralisar com o olhar. Perdeu pra uma menininha de óculos.'],
['Comandante Red', ['Red','Comandante Vermelho'], 'Humano', M, 'Exército Red Ribbon', 1, 'Saga Red Ribbon', 'Terra', 'Ruivo', N, 1, '',
 'Líder baixinho de tapa-olho. Queria as esferas não pra dominar o mundo, mas pra ficar mais alto.'],
['Androide 8', ['Hatchan','Número 8','Oito','Android 8'], 'Androide', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Azul', N, 2, '',
 'Gigante de parafuso no pescoço criado pra ser arma, mas era bonzinho demais pra machucar alguém.'],
['Arale', ['Arale Norimaki','Arale-chan'], 'Androide', F, 'Neutro', 1, 'Saga Red Ribbon', 'Terra', 'Roxo', N, 3 /* no Dr. Slump ela racha planeta, mas aqui é participação */, '',
 'Robozinha de óculos da Vila Pinguim que cutuca cocô com um graveto. Nchaa!'],
['Karin', ['Korin','Mestre Karin','Sábio Karin','Gato Karin'], 'Animal', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Branco', N, 3, '',
 'Gato sábio no topo de uma torre altíssima. Guarda as sementes dos deuses e a água sagrada.'],
['Upa', ['Upá'], 'Humano', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Preto', N, 1, '',
 'Menino da Torre Sagrada que viu o pai morrer pra um assassino e depois teve ele de volta com as esferas.'],
['Dr. Brief', ['Doutor Brief','Brief','Pai da Bulma'], 'Humano', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Branco' /* grisalho azulado */, N, 1, '',
 'Fundador da Corporação Cápsula. Construiu uma nave pra Namekusei com câmara de gravidade e ainda cuida de um gatinho no ombro.'],
['Yajirobe', ['Yajirobi','Yajiro'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Piccolo Daimaoh', 'Terra', 'Preto', N, 3, '',
 'Samurai guloso e covarde que cortou o rabo de um príncipe e depois se escondeu no mato.'],
['Piccolo Daimaoh', ['Rei Piccolo','King Piccolo','Piccolo Daimao','Grande Rei Demônio'], 'Namekuseijin', M, 'Vilão', 1, 'Saga Piccolo Daimaoh', 'Namekusei', 'Nenhum', N, 3, '',
 'Rei Demônio que ficou selado numa panela de arroz elétrica. Colocou a letra "Ma" nas costas dos filhos.'],
['Tamborim', ['Tambourine','Tamborine'], 'Namekuseijin' /* "mazoku", filho mutante do Rei Demônio */, M, 'Vilão', 1, 'Saga Piccolo Daimaoh', 'Terra', 'Nenhum', N, 3, '',
 'Filho demoníaco com asas, cuspido de um ovo pelo pai. Matou o careca melhor amigo do herói.'],
['Kami-Sama', ['Kami','Deus da Terra','Kamisama','Deus'], 'Namekuseijin', M, 'Deuses', 1, 'Saga Piccolo Daimaoh', 'Namekusei', 'Nenhum', N, 4, '',
 'Guardião da Terra lá no templo sagrado. Expulsou o próprio lado mau e acabou fundido com ele de novo.'],
['Mr. Popo', ['Senhor Popo','Popo'], 'Outro', M, 'Deuses', 1, 'Saga Piccolo Daimaoh', 'Desconhecido', 'Nenhum', N, 3, '',
 'Assistente eterno do deus da Terra. Cuida do jardim do templo e é assustadoramente educado.'],
['Shenlong', ['Shenron','Dragão','Dragão Shenlong','Shen Long'], 'Dragão', O, 'Neutro', 1, 'Saga Pilaf', 'Terra', 'Nenhum', N, 5 /* não luta; nota média */, '',
 'Diga seu desejo e eu realizarei! Surge das sete esferas e odeia pedido complicado.'],
['Piccolo', ['Piccolo Jr.','Ma Junior','Majunior','Piccolo Junior','Piccolo Laranja'], 'Namekuseijin', M, 'Guerreiros Z', 1, 'Saga Piccolo Jr. (23º Torneio)', 'Terra' /* nasceu na Terra, filho do Rei Demônio */, 'Nenhum', S, 8, A+'picolo_normal.webp',
 'Começou querendo dominar o mundo e terminou de babá, levando o filho do rival pra escola.'],

/* ----------------------------- DRAGON BALL Z (2) ----------------------------- */
['Raditz', ['Radditz','Raditzu','Irmão do Goku'], 'Saiyajin', M, 'Forças do Freeza', 2, 'Saga Saiyajin', 'Vegeta', 'Preto', N, 4, A+'Raditz_artwork_Dokkan.webp',
 'Chegou na Terra dizendo que era irmão do protagonista, sequestrou o sobrinho e durou dois episódios.'],
['Gohan', ['Son Gohan','Grande Saiyaman','Gohanzinho','Gohan Besta','Gohan Beast'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Saiyajin', 'Terra', 'Preto', S, 9, A+'gohan.webp',
 'Filho mais velho do herói. Estudioso, super poder escondido e, nas horas vagas, justiceiro de capacete.'],
['Nappa', ['Napa'], 'Saiyajin', M, 'Forças do Freeza', 2, 'Saga Saiyajin', 'Vegeta', 'Nenhum', N, 4, '',
 'Careca de bigode que acompanhava o príncipe. Plantou os Saibaman e foi "dispensado" pelo próprio chefe.'],
['Vegeta', ['Príncipe dos Saiyajins','Principe Vegeta','Vegeta Ultra Ego'], 'Saiyajin', M, 'Guerreiros Z', 2, 'Saga Saiyajin', 'Vegeta', 'Preto', S, 9, A+'vegeta_normal.webp',
 'Príncipe de uma raça guerreira. Orgulho do tamanho de um planeta e eterno segundo lugar.'],
['Saibaman', ['Saibamen','Saibamans','Saibaiman'], 'Outro', O, 'Vilão', 2, 'Saga Saiyajin', 'Desconhecido', 'Nenhum', N, 3, '',
 'Brotinho verde plantado na terra que nasce, pula e explode. Tem um cadáver famoso no currículo.'],
['Kaio do Norte', ['Senhor Kaioh','Kaioh','Sr. Kaioh','King Kai','Kaio','Kaioh do Norte'], 'Kaio', M, 'Deuses', 2, 'Saga Saiyajin', 'Outro Mundo', 'Nenhum', N, 3, A+'Kaio_del_Norte.webp',
 'Deus de antenas que mora num planetinha com um macaco e um grilo. Ninguém ri das piadas dele.'],
['Freeza', ['Frieza','Freezer','Lord Freeza','Freeza Dourado','Black Freeza','Golden Freeza'], 'Raça do Freeza', M, 'Forças do Freeza', 2, 'Saga Namekusei', 'Desconhecido', 'Nenhum', S, 9, A+'Freezer.webp',
 'Imperador do universo que destruiu uma raça inteira de guerreiros. Educado, cruel e colecionador de formas.'],
['Zarbon', ['Zabon'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Namekusei', 'Desconhecido', 'Verde', S, 4, A+'zarbon.webp',
 'Guerreiro vaidoso de trança verde e brincos. Quando luta sério fica feio de doer.'],
['Dodoria', ['Dodorian'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Namekusei', 'Desconhecido', 'Nenhum', N, 4, A+'dodoria.webp',
 'Rosa, redondo e cheio de espinhos. Soldado do imperador que caiu na conversa de um príncipe.'],
['Capitão Ginyu', ['Ginyu','Ginyuu','Captain Ginyu'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Nenhum', N /* troca de corpo não é transformação */, 5, A+'ginyu.webp',
 'Líder de um esquadrão que faz pose de balé antes de brigar. Especialidade: trocar de corpo. Terminou virando sapo.'],
['Recoome', ['Recoom','Rikum'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Ruivo', N, 5, '',
 'Brutamontes ruivo das Forças Especiais que faz dancinha antes de socar. Destruiu metade do time e caiu com um golpe na barriga.'],
['Jeice', ['Jace','Jiise'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Brench', 'Branco', N, 4, '',
 'Pele vermelha, cabelão branco. Membro das Forças Especiais que fugiu no meio da luta pra chamar o chefe.'],
['Burter', ['Butter','Baata'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Nenhum', N, 4, '',
 'Grandão azul que se achava o mais rápido do universo. Até conhecer um Super Saiyajin.'],
['Guldo', ['Gurdo'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Nenhum', N, 4, '',
 'Baixinho verde de quatro olhos que para o tempo… desde que consiga prender a respiração.'],
['Dende', ['Dendê','Deus da Terra Jovem'], 'Namekuseijin', M, 'Deuses', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 1, A+'Dende_Artwork.webp',
 'Garotinho que cura qualquer ferida. Saiu de Namekusei pra virar o novo guardião da Terra.'],
['Nail', ['Neiru'], 'Namekuseijin', M, 'Aliados', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 5, A+'Nail_Artwork.webp',
 'Guerreiro mais forte do seu planeta, guarda-costas do Patriarca. Terminou fundido com um velho conhecido.'],
['Grande Patriarca', ['Guru','Grande Ancião','Patriarca','Grande Guru'], 'Namekuseijin', M, 'Aliados', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 2, '',
 'Pai de todo um planeta, enorme e sentado. Desperta o poder escondido com um toque na cabeça.'],
['Porunga', ['Polunga','Dragão de Namekusei'], 'Dragão', O, 'Neutro', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 5 /* não luta; nota média */, '',
 'Dragão musculoso que concede três desejos, mas só se você pedir na língua certa.'],
['Rei Cold', ['King Cold','Cold'], 'Raça do Freeza', M, 'Forças do Freeza', 2, 'Saga Trunks', 'Desconhecido', 'Nenhum', N, 5, '',
 'Pai de dois imperadores tiranos. Chegou na Terra achando que ia se vingar e conheceu uma espada do futuro.'],
['Trunks do Futuro', ['Mirai Trunks','Future Trunks','Trunks Futuro','Trunks do futuro'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Trunks', 'Terra', 'Lilás', S, 8, '',
 'Viajou numa máquina do tempo pra avisar dos androides. Chegou de espada e cortou um imperador em fatias.'],
['Trunks', ['Trunks Criança','Kid Trunks','Trunks Pequeno'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Androides', 'Terra', 'Lilás', S, 7, A+'Trunks_Buu_Artwork.webp',
 'Herdeiro da Corporação Cápsula, filho do príncipe. Aprontava com o melhor amigo e virou Super Saiyajin antes dos 8 anos.'],
['Dr. Gero', ['Androide 20','Android 20','Doutor Gero','Gero','Número 20'], 'Androide', M, 'Exército Red Ribbon', 2, 'Saga Androides', 'Terra', 'Branco', N, 5, A+'Dr._Gero%20nadroide%2020.webp',
 'Cientista do exército da fita vermelha que transformou o próprio cérebro em máquina só pra se vingar de uma criança.'],
['Androide 19', ['Android 19','Número 19','C-19','Dezenove'], 'Androide', M, 'Exército Red Ribbon', 2, 'Saga Androides', 'Terra', 'Nenhum', N, 5, A+'Android19.webp',
 'Gorducho branco de chapéu que absorvia energia pelas mãos. Perdeu os braços pro príncipe recém-transformado.'],
['Androide 18', ['Android 18','Número 18','C-18','Lazuli','Dezoito'], 'Androide', F, 'Guerreiros Z', 2, 'Saga Androides', 'Terra', 'Loiro', N, 7, A+'Androide_18_Artwork.webp',
 'Loira de energia infinita que quebrou o braço de um príncipe e depois casou com o careca mais simpático da Terra.'],
['Androide 17', ['Android 17','Número 17','C-17','Lapis','Dezessete'], 'Androide', M, 'Guerreiros Z', 2, 'Saga Androides', 'Terra', 'Preto', N, 8, A+'17_Artwork.webp',
 'Rebelde de lenço laranja que virou guarda-florestal e salvou o universo inteiro no último segundo do torneio.'],
['Androide 16', ['Android 16','Número 16','C-16','Dezesseis'], 'Androide', M, 'Exército Red Ribbon', 2, 'Saga Androides', 'Terra', 'Ruivo', N, 6, A+'Androide_16.webp',
 'Gigante ruivo que amava passarinhos e a natureza. Sua cabeça, esmagada, pediu pro menino liberar a fúria.'],
['Cell', ['Célula','Cell Perfeito','Cell Imperfeito'], 'Bio-Androide', M, 'Vilão', 2, 'Saga Cell', 'Terra', 'Nenhum', S, 7, A+'celula.webp',
 'Criado com células dos melhores guerreiros. Absorveu dois androides pra ficar perfeito e organizou o próprio torneio.'],
['Cell Jr.', ['Cell Junior','Cells Jr','Filhos do Cell','Cell Jr'], 'Bio-Androide', M, 'Vilão', 2, 'Saga Cell', 'Terra', 'Nenhum', N, 6, '',
 'Miniaturas azuis de um vilão perfeito. Sete deles deram uma surra nos guerreiros no torneio do pai.'],
['Mr. Satan', ['Hercule','Satan','Mister Satan','Campeão Mundial','Mr Satan'], 'Humano', M, 'Aliados', 2, 'Saga Cell', 'Terra', 'Preto', N, 1, A+'Mr_Satan_DBSuper.webp',
 'Campeão mundial de artes marciais que levou o crédito por salvar o mundo. Duas vezes.'],
['Videl', ['Videl Satan'], 'Humano', F, 'Guerreiros Z', 2, 'Saga Grande Saiyaman', 'Terra', 'Preto', N, 3, '',
 'Filha do campeão mundial. Descobriu a identidade secreta de um justiceiro de capacete e aprendeu a voar com ele.'],
['Goten', ['Son Goten','Gotenzinho'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Grande Saiyaman', 'Terra', 'Preto', S, 7, '',
 'Cópia em miniatura do pai. Virou Super Saiyajin brincando, antes mesmo de entender o que era isso.'],
['Kaioshin', ['Shin','Supremo Senhor Kaioh','Kaioshin do Leste','Supreme Kai','Senhor Kaioshin'], 'Kaioshin', M, 'Deuses', 2, 'Saga Torneio Mundial (25º Torneio)', 'Mundo dos Kaioshins', 'Branco', N, 6, A+'Kaio-shin_del_este_Artwork.webp',
 'Deus supremo baixinho de moicano branco que apareceu disfarçado num torneio avisando sobre um mago.'],
['Kibito', ['Kibitto'], 'Kaioshin', M, 'Deuses', 2, 'Saga Torneio Mundial (25º Torneio)', 'Mundo dos Kaioshins', 'Branco', N, 5, A+'Kibito_Artwork.webp',
 'Assistente alto e sério de um deus supremo. Teleportava todo mundo e morreu com um estalo.'],
['Kibito-Shin', ['Kibitoshin','Kibito Kai','Kibito Shin'], 'Kaioshin', M, 'Deuses', 2, 'Saga Kid Boo', 'Mundo dos Kaioshins', 'Branco', N, 6, A+'Kibito_shin_Artwork.webp',
 'Resultado de um par de brincos usado por um deus e seu assistente. Não dá pra desfazer.'],
['Ancião Kaioshin', ['Velho Kaioshin','Old Kai','Kaioshin Ancião','Supremo Kaioshin Ancião','Velho Supremo'], 'Kaioshin', M, 'Deuses', 2, 'Saga Fusão', 'Mundo dos Kaioshins', 'Branco', N, 3, '',
 'Ficou preso numa espada por 15 gerações. Troca o ritual de despertar poder por revista de mulher pelada.'],
['Grande Kaioshin', ['Dai Kaioshin','Grand Supreme Kai','Daikaioshin'], 'Kaioshin', M, 'Deuses', 2, 'Saga Babidi', 'Mundo dos Kaioshins', 'Lilás', N, 5, A+'Gran_Kaio-shin_Artwork.webp',
 'Deus supremo gordinho que foi absorvido por um Majin e acabou deixando ele fofinho.'],
['Grande Kaio', ['Dai Kaioh','Grand Kai','Grande Senhor Kaioh','Grande Kaioh'], 'Kaio', M, 'Deuses', 2, 'Saga Torneio do Outro Mundo', 'Outro Mundo', 'Branco', N, 4, A+'Gran_kaio_sama12.webp',
 'Chefe dos Kaios, de óculos escuros, fã de rock e organizador do torneio dos mortos.'],
['Pikkon', ['Paikuhan','Pikon'], 'Alienígena', M, 'Neutro', 2, 'Saga Torneio do Outro Mundo', 'Desconhecido', 'Nenhum', N, 6, '',
 'Guerreiro verde do Kaio do Oeste que treina com roupas pesadas no Outro Mundo. Rival do herói depois de morto.'],
['Babidi', ['Bibidi Babidi','Mago Babidi','Babid'], 'Outro', M, 'Clã de Babidi', 2, 'Saga Babidi', 'Desconhecido', 'Nenhum', N, 1, A+'Babidi_Artwork.webp',
 'Mago baixinho e enrugado que coloca um "M" na testa dos outros. Fez a pior escolha de bicho de estimação.'],
['Dabura', ['Rei Demônio Dabura','Dabra'], 'Demônio', M, 'Clã de Babidi', 2, 'Saga Babidi', 'Mundo Demoníaco', 'Nenhum', N, 6, '',
 'Rei do Mundo Demoníaco controlado por um mago. Cospe e transforma as pessoas em pedra.'],
['Spopovich', ['Spopovitch','Popovich'], 'Humano', M, 'Clã de Babidi', 2, 'Saga Torneio Mundial (25º Torneio)', 'Terra', 'Nenhum', N, 3, '',
 'Careca inchado e controlado por um mago. Espancou a filha do campeão no torneio e roubou energia de um menino.'],
['Majin Boo', ['Majin Buu','Boo','Buu','Boo Gordo','Fat Buu','Boo Gordinho'], 'Majin', M, 'Guerreiros Z', 2, 'Saga Majin Boo', 'Desconhecido', 'Nenhum', N, 7, A+'BuuGordo_Universo7.webp',
 'Rosa, fofinho, transforma gente em chocolate. Melhor amigo do campeão mundial e dono de um cachorrinho.'],
['Super Boo', ['Super Buu','Boo Malvado','Evil Buu','Boo Maligno'], 'Majin', M, 'Vilão', 2, 'Saga Majin Boo', 'Desconhecido', 'Nenhum', S /* absorções mudam a forma */, 8, '',
 'Metade malvada que engoliu a metade boazinha. Absorve os inimigos e ganha a roupa deles.'],
['Kid Boo', ['Kid Buu','Majin Boo Puro','Boo Magro','Boo Original','Boo Criança'], 'Majin', M, 'Vilão', 2, 'Saga Kid Boo', 'Desconhecido', 'Nenhum', N, 7, '',
 'A forma original, pequena e completamente insana. Destruiu a Terra só por diversão e morreu pra uma Genki Dama.'],
['Gotenks', ['Gotenks SSJ3','Gotrunks'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Majin Boo', 'Terra', 'Preto', S, 8, A+'Gotenks_Artwork.webp',
 'Fusão de duas crianças via dancinha. Arrogante, dá nome ridículo pros golpes e solta fantasmas kamikazes.'],
['Vegetto', ['Vegito','Vegerot','Vegetto Blue'], 'Saiyajin', M, 'Guerreiros Z', 2, 'Saga Fusão', 'Vegeta', 'Preto', S, 9, T+'Vegetto.webp',
 'Fusão feita com brincos de deus. Transformou o vilão numa bala de goma.'],
['Uub', ['Oob','Ub','Majuub'], 'Humano', M, 'Guerreiros Z', 2, 'Saga Kid Boo', 'Terra', 'Preto', S /* vira Majuub no GT */, 6, '',
 'Menino de vila pobre que é a reencarnação de um monstro. Terminou a série indo embora como aluno do herói.'],
['Pan', ['Pan Son','Neta do Goku'], 'Descendente Saiyajin', F, 'Guerreiros Z', 2, 'Saga Kid Boo', 'Terra', 'Preto', N, 5, '',
 'Neta do protagonista, voa desde bebê e é a única garota a viajar pelo espaço no GT.'],
['Bra', ['Bulla','Bura','Filha do Vegeta'], 'Meio-Saiyajin', F, 'Aliados', 2, 'Saga Kid Boo', 'Terra', 'Azul', N, 1, '',
 'Filha do príncipe, cabelo azul da mãe. O pai orgulhoso vira um bobo perto dela.'],

/* ----------------------------- FILMES / ESPECIAIS Z (3) ----------------------------- */
['Garlic Jr.', ['Garlic Junior','Garlic','Garlic Jr'], 'Demônio', M, 'Vilão', 3, 'Filme "A Zona Morta" (1989)', 'Estrela Makyo', 'Nenhum', S, 5, '',
 'Baixinho imortal que queria ser o deus da Terra e acabou sugado pro próprio buraco negro.'],
['Bardock', ['Bardack','Pai do Goku','Burdock'], 'Saiyajin', M, 'Forças do Freeza', 3, 'Especial "O Pai de Goku" (1990)', 'Vegeta', 'Preto', S, 4, A+'Bardock_Artwork.webp',
 'Soldado de classe baixa que teve visões do futuro e encarou o imperador sozinho, com uma faixa vermelha na testa.'],
['Turles', ['Tullece','Turlez'], 'Saiyajin', M, 'Vilão', 3, 'Filme "A Árvore do Poder" (1990)', 'Vegeta', 'Preto', N, 5, '',
 'Saiyajin igualzinho ao protagonista, mas de pele morena e mau. Plantou uma árvore que suga planetas.'],
['Slug', ['Lord Slug','Lorde Slug','Slug Gigante'], 'Namekuseijin', M, 'Vilão', 3, 'Filme "Lord Slug" (1991)', 'Namekusei', 'Nenhum', S, 5, '',
 'Namekuseijin velho e malvado que usou as esferas pra ficar jovem e queria transformar a Terra numa nave.'],
['Cooler', ['Coola','Metal Cooler','Irmão do Freeza'], 'Raça do Freeza', M, 'Vilão', 3, 'Filme "A Vingança de Cooler" (1991)', 'Desconhecido', 'Nenhum', S, 6, '',
 'Irmão mais velho do imperador, com uma forma a mais que ele. Voltou depois como máquina.'],
['Androide 13', ['Android 13','Número 13','Super 13','Treze'], 'Androide', M, 'Exército Red Ribbon', 3, 'Filme "Androide 13" (1992)', 'Terra', 'Branco', S, 6, A+'Androide13normal.webp',
 'Androide caipira de boné que absorveu as peças dos colegas e ficou azul e enorme.'],
['Androide 14', ['Android 14','Número 14','Quatorze','Catorze'], 'Androide', M, 'Exército Red Ribbon', 3, 'Filme "Androide 13" (1992)', 'Terra', 'Preto', N, 5, A+'14Dokkan.webp',
 'Grandalhão de pele pálida e trança preta, construído pelo computador de um cientista já morto.'],
['Broly', ['Broli','Lendário Super Saiyajin','Brolly'], 'Saiyajin', M, 'Vilão', 3, 'Filme "O Lendário Super Saiyajin" (1993)', 'Vegeta', 'Preto', S, 9, T+'Broly_DBS_Base.webp',
 'O lendário que chorou de trauma no berço ao lado do herói. Grita "Kakarotto!" até perder a voz.'],
['Paragus', ['Paragasu','Paragas'], 'Saiyajin', M, 'Vilão', 3, 'Filme "O Lendário Super Saiyajin" (1993)', 'Vegeta', 'Preto', N, 4, '',
 'Pai do lendário. Controlava o filho com um anel na cabeça e morreu esmagado dentro de uma nave.'],
['Bojack', ['Boujack','Bo Jack'], 'Alienígena', M, 'Vilão', 3, 'Filme "Bojack" (1993)', 'Desconhecido', 'Ruivo', S, 6, '',
 'Pirata espacial de pele verde-azulada libertado quando um Kaio morreu. Invadiu um torneio na Terra.'],
['Janemba', ['Super Janemba','Janenba'], 'Demônio', O, 'Vilão', 3, 'Filme "Fusão" (1995)', 'Outro Mundo', 'Nenhum', S, 8, T+'Janemba_artwork_SDBH.webp',
 'Nasceu da maldade acumulada numa máquina de purificar almas e deixou o Outro Mundo do avesso.'],
['Gogeta', ['Gojeta','Gogeta Blue','Gogeta SSJ4'], 'Saiyajin', M, 'Guerreiros Z', 3, 'Filme "Fusão" (1995)', 'Vegeta', 'Preto', S, 9, T+'gogeta.webp',
 'Fusão pela dança, com colete e calça branca. Resolveu tudo antes de o tempo de fusão acabar.'],
['Tapion', ['Tapiom','Tapio'], 'Alienígena', M, 'Aliados', 3, 'Filme "O Ataque do Dragão" (1995)', 'Konats', 'Ruivo', N, 5, '',
 'Herói de outro planeta que ficou preso numa caixa de música com metade de um monstro dentro. Toca uma ocarina triste.'],

/* ----------------------------- DRAGON BALL GT (4) ----------------------------- */
['Baby', ['Baby Vegeta','Bebi','Bebê'], 'Tsufurujin', M, 'Vilão', 4, 'Saga Baby', 'M-2', 'Nenhum', S, 8, '',
 'Parasita criado pra vingar uma raça extinta. Possuiu o príncipe e virou um macaco gigante dourado.'],
['Super 17', ['Super Androide 17','Super C-17','Super Número 17'], 'Androide', M, 'Vilão', 4, 'Saga Super 17', 'Terra', 'Preto', N, 8, '',
 'Resultado de dois androides iguais, um da Terra e outro do Inferno, se juntando.'],
['Giru', ['Gill','Gil'], 'Androide' /* máquina mutante */, M, 'Aliados', 4, 'Saga Esferas do Dragão Negras', 'Desconhecido', 'Nenhum', N, 1, '',
 'Robozinho que comeu o radar e virou o radar. Repete o próprio nome sem parar.'],
['Omega Shenlong', ['Omega Shenron','Ii Shenron','Syn Shenron','Li Shenron','Dragão Maligno'], 'Dragão', M, 'Vilão', 4, 'Saga Dragões Malignos', 'Terra', 'Branco', S, 8, '',
 'Dragão maligno nascido do abuso das esferas. Engoliu as outras seis e virou a versão final.'],
['Goku Jr.', ['Goku Junior','Goku Jr'], 'Descendente Saiyajin', M, 'Neutro', 4, 'Episódio final (100 anos depois)', 'Terra', 'Preto', S, 5, '',
 'Tataraneto chorão do herói. Cem anos depois, virou Super Saiyajin pra defender a avó.'],

/* ----------------------------- DRAGON BALL SUPER (5) ----------------------------- */
['Bills', ['Beerus','Birusu','Deus da Destruição','Lorde Bills'], 'Deus', M, 'Deuses', 5, 'Saga A Batalha dos Deuses', 'Planeta de Bills', 'Nenhum', N, 9, A+'Beerus_DBS_Broly_Artwork.webp',
 'Gato roxo que dorme por décadas, acorda com fome e ameaça destruir a Terra por causa de um pudim.'],
['Whis', ['Uisu','Wiss','Anjo do Universo 7'], 'Anjo', M, 'Deuses', 5, 'Saga A Batalha dos Deuses', 'Planeta de Bills', 'Branco', N, 10, A+'Whis_DBS_Broly_Artwork.webp',
 'Assistente e mestre de um deus. Educadíssimo, volta o tempo em três minutos e ama comida da Terra.'],
['Champa', ['Shanpa','Deus da Destruição do Universo 6'], 'Deus', M, 'Deuses', 5, 'Saga Torneio do Universo 6', 'Planeta de Champa', 'Nenhum', N, 9, '',
 'Gêmeo gordinho e birrento de um deus gato. Organizou um torneio só pra roubar a Terra do irmão.'],
['Vados', ['Vadosu','Anjo do Universo 6'], 'Anjo', F, 'Deuses', 5, 'Saga Torneio do Universo 6', 'Planeta de Champa', 'Branco', N, 10, '',
 'Irmã mais velha de um anjo famoso. Serve a um deus guloso e acha tudo muito divertido.'],
['Hit', ['Assassino Hit','Hitto'], 'Alienígena', M, 'Universo 6', 5, 'Saga Torneio do Universo 6', 'Desconhecido', 'Nenhum', N, 8, '',
 'Assassino roxo mais temido do seu universo. Pula o tempo por frações de segundo e evolui a cada luta.'],
['Cabba', ['Kyabe','Cabbe'], 'Saiyajin', M, 'Universo 6', 5, 'Saga Torneio do Universo 6', 'Sadala', 'Preto', S, 7, '',
 'Saiyajin educado de outro universo que chamou o príncipe de "mestre" e aprendeu a se transformar na base da raiva.'],
['Frost', ['Frosto','Freeza do Universo 6'], 'Raça do Freeza', M, 'Vilão', 5, 'Saga Torneio do Universo 6', 'Desconhecido', 'Nenhum', S, 7, '',
 'Parece herói, é pirata. A versão de outro universo do imperador, com agulha escondida no braço.'],
['Monaka', ['Monaca'], 'Alienígena', M, 'Neutro', 5, 'Saga Torneio do Universo 6', 'Wagashi', 'Nenhum', N, 1, '',
 'O "guerreiro mais forte" do deus gato, que na verdade é um entregador que desmaia de medo.'],
['Zeno Sama', ['Zeno','Zen-Oh','Zenoh','Rei de Tudo','Zeno-sama','Zen Oh Sama'], 'Deus', M, 'Deuses', 5, 'Saga Torneio do Universo 6', 'Palácio do Zeno', 'Nenhum', N, 10, A+'Zeno_Artwork.webp',
 'Rei de tudo, com cara de criança e botão pra apagar universos. Chamou o herói de amigo.'],
['Grande Sacerdote', ['Daishinkan','Grand Priest','Sumo Sacerdote','Grande Sacerdote Anjo'], 'Anjo', M, 'Deuses', 5, 'Saga Trunks do Futuro (Black)', 'Palácio do Zeno', 'Branco', N, 10, A+'Grand%20priest.webp',
 'Pai de todos os anjos e mediador do torneio que apagava universos. Sorriso gentil, poder absurdo.'],
['Goku Black', ['Black','Black Goku','Goku Negro'], 'Saiyajin' /* alma de Kaioshin, corpo Saiyajin */, M, 'Vilão', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Preto', S, 8, '',
 'Rosto do herói, alma de um deus aprendiz que odeia os mortais. Transformação cor-de-rosa.'],
['Zamasu', ['Zamas','Zamasu do Universo 10'], 'Kaioshin', M, 'Vilão', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Branco', N, 7, '',
 'Aprendiz de deus supremo com um plano de "justiça": exterminar todos os mortais. Bebia chá enquanto julgava.'],
['Zamasu Fundido', ['Zamasu Fusão','Fused Zamasu','Zamasu Fusionado'], 'Kaioshin', M, 'Vilão', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Branco', S, 8, '',
 'Fusão imortal de dois vilões com brincos. Terminou apagado junto com o futuro inteiro.'],
['Gowasu', ['Gowas'], 'Kaioshin', M, 'Deuses', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Branco', N, 3, '',
 'Velho deus supremo do Universo 10 que achou que o aprendiz ia melhorar com chá.'],
['Jiren', ['Jiren o Cinza','Giren'], 'Alienígena', M, 'Tropa do Orgulho', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Nenhum', N, 9, A+'Jiren.webp',
 'Guerreiro cinza de braços cruzados que meditava enquanto todos lutavam. Só acredita na força.'],
['Toppo', ['Top'], 'Alienígena', M, 'Tropa do Orgulho', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Nenhum', S, 8, A+'Toppo.webp',
 'Bigodudo da justiça que faz pose e, na hora do aperto, revela ser candidato a deus da destruição.'],
['Dyspo', ['Dispo','Diseo'], 'Alienígena', M, 'Tropa do Orgulho', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Nenhum', N, 7, A+'Dispo_render.webp',
 'O mais rápido da tropa da justiça, orelhudo e roxo. Irritou um careca com o jeito de falar.'],
['Marcarita', ['Marcarita Anjo','Anjo do Universo 11'], 'Anjo', F, 'Deuses', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Branco', N, 10, A+'Marcarita.webp',
 'Anjo de maria-chiquinha que acompanha um deus palhaço e sempre mantém a calma.'],
['Vermoud', ['Belmod','Beerus do Universo 11'], 'Deus', M, 'Deuses', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Ruivo', N, 9, A+'Vermoud.webp',
 'Deus da destruição com cara de palhaço e cabelo em dois tufos. Discursa sobre justiça antes de apagar alguém.'],
['Caulifla', ['Kaulifla','Colifla'], 'Saiyajin', F, 'Universo 6', 5, 'Saga Sobrevivência do Universo', 'Sadala', 'Preto', S, 7, '',
 'Chefe de gangue que aprendeu a virar Super Saiyajin em minutos e queria aprender com o herói.'],
['Kale', ['Kalé','Kale Berserker'], 'Saiyajin', F, 'Universo 6', 5, 'Saga Sobrevivência do Universo', 'Sadala', 'Preto', S, 7, '',
 'Tímida, insegura e, quando perde o controle, uma lendária descontrolada com cabelo verde.'],
['Kefla', ['Kaufla','Kefura'], 'Saiyajin', F, 'Universo 6', 5, 'Saga Sobrevivência do Universo', 'Sadala', 'Preto', S, 8, '',
 'Fusão com brincos de duas garotas do Universo 6. Deu trabalho até pro instinto superior.'],
['Gamma 1', ['Gama 1','Gamma Um'], 'Androide', M, 'Exército Red Ribbon', 5, 'Filme "Super Hero" (2022)', 'Terra', 'Preto', N, 7, '',
 'Androide de capa vermelha que se acha super-herói. Foi enganado pra achar que os heróis eram vilões.'],
['Gamma 2', ['Gama 2','Gamma Dois'], 'Androide', M, 'Exército Red Ribbon', 5, 'Filme "Super Hero" (2022)', 'Terra', 'Preto', N, 7, '',
 'Androide de capa azul, o mais brincalhão da dupla. Se sacrificou pra deter um monstro gigante.'],
['Cheelai', ['Chilai','Cheela'], 'Alienígena', F, 'Aliados', 5, 'Filme "Broly" (2018)', 'Desconhecido', 'Branco', N, 2, '',
 'Ex-soldada do imperador, pele verde e cabelo branco, que fez amizade com um Saiyajin gigante e perdido.'],
['Gine', ['Gin','Mãe do Goku'], 'Saiyajin', F, 'Neutro', 5, 'Mangá "Dragon Ball Minus" (2014)', 'Vegeta', 'Preto', N, 2, '',
 'Saiyajin gentil que trabalhava num açougue e mandou o filho numa cápsula pra Terra.']
];

window.DB_CHARS = rows.map(r => ({
  nome:r[0], apelidos:r[1], raca:r[2], genero:r[3], afiliacao:r[4], estreia:r[5], saga:r[6],
  planeta:r[7], cabelo:r[8], transforma:r[9], poder:r[10], img:r[11], frase:r[12]
}));
})();
