/* ==========================================================
   Quem é esse Guerreiro? · banco de personagens (Dragon Ball)
   Nomes como na dublagem brasileira.

   Colunas de cada linha (mapeadas pra objeto no fim do arquivo):
   nome, apelidos, raca, genero, afiliacao, estreia, saga, planeta,
   cabelo, transforma, poder, img, frase

   Campos extras no objeto final (outros jogos podem ignorar):
   - img2:   foto reserva (Dragon Ball Wiki) pra quando a img principal falhar
   - render: true = imagem recortada com fundo transparente (serve pra silhueta)
             false = print do anime com fundo (NÃO serve pra silhueta)

   Imagens: dragonball-api.com (recortes) e, pra quem não tem lá, a imagem
   principal da página do personagem na Dragon Ball Wiki (static.wikia.nocookie.net).

   Convenções (decisões pra deixar o jogo justo):
   - estreia: 1 Dragon Ball · 2 Dragon Ball Z · 3 Filmes Z (inclui especiais de TV)
              4 Dragon Ball GT · 5 Dragon Ball Super (inclui filmes/mangás da era Super)
   - planeta: planeta natal; se a origem é desconhecida mas o lar é conhecido
              (deuses, anjos), vale o lar. Senão, "Desconhecido".
   - cabelo: cor na forma base mais conhecida. Carecas e quem não tem cabelo = "Nenhum".
   - transforma: tem transformação/forma alternativa mostrada em cena
              (Oozaru só conta se aparece transformado na obra).
   - poder: pico canônico, escala 1 a 10:
       1 gente comum (Mr. Satan) · 2 lutador fraco/soldado · 3 mestre do DB clássico
       4 início do Z (Raditz) · 5 elite de Namekusei · 6 era Androides
       7 era Cell/Boo forte · 8 elite do Super · 9 topo (Goku, Vegeta, Bills, Jiren)
       10 anjos e Zeno Sama
   - afiliação: a mais marcante do personagem.
   ========================================================== */
(() => {
const A = 'https://dragonball-api.com/characters/';
const T = 'https://dragonball-api.com/transformaciones/';
const M = 'Masculino', F = 'Feminino', O = 'Outro';
const S = 'Sim', N = 'Não';

const rows = [
/* ----------------------------- DRAGON BALL (1) ----------------------------- */
['Goku', ['Kakarotto','Kakaroto','Son Goku','Goku Criança'], 'Saiyajin', M, 'Guerreiros Z', 1, 'Saga Pilaf', 'Vegeta', 'Preto', S, 9, A+'goku_normal.webp',
 'Bateu a cabeça quando era bebê e virou o cara mais gente boa do universo. Come por dez e some por anos'],
['Bulma', ['Buma'], 'Humano', F, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Azul', N, 1, A+'bulma.webp',
 'Gênia da Corporação Cápsula. Inventou o radar, sem ela ninguém achava esfera nenhuma'],
['Mestre Kame', ['Mestre Roshi','Kame-Sennin','Muten Roshi','Jackie Chun','Roshi'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Pilaf', 'Terra', 'Nenhum', S /* forma MAX POWER */, 5, A+'roshi.webp',
 'Véio safado de óculos escuro que inventou o golpe mais famoso do anime. Mora numa ilha com uma tartaruga'],
['Oolong', ['Ulong','Porco'], 'Animal', M, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Nenhum', S /* se transforma em qualquer coisa por 5 min */, 1, '',
 'Porquinho que vira qualquer coisa por 5 minutos. Fez o pedido mais famoso da história: uma calcinha'],
['Puar', ['Pual'], 'Animal', O /* gênero nunca definido */, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Nenhum', S, 1, '',
 'Gatinho azul voador que muda de forma e vive grudado num ex-bandido do deserto'],
['Yamcha', ['Iamcha','Yamucha'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 5, A+'Final_Yamcha.webp',
 'Ex-bandido do deserto que tinha medo de mulher. Ficou famoso deitado numa cratera'],
['Chi-Chi', ['Chichi','Chi Chi','Xixi'], 'Humano', F, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 2, A+'ChiChi_DBS.webp',
 'Quer o filho estudando, não lutando. Casou com um cara que achou que casamento era comida'],
['Rei Cutelo', ['Ox King','Gyuu Maou','Rei Gyuumao','Cutelo'], 'Humano', M, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 2, '',
 'Gigante barbudo da Montanha de Fogo, ex-aluno do véio da ilha. Sogro mais tranquilo do anime'],
['Imperador Pilaf', ['Pilaf','Pilaf Sama'], 'Outro', M, 'Vilão', 1, 'Saga Pilaf', 'Terra', 'Nenhum', N, 1, '',
 'Diabinho azul que queria dominar o mundo com as esferas e perdia toda vez pra uma criança'],
['Mai', ['Mai Pilaf'], 'Humano', F, 'Vilão', 1, 'Saga Pilaf', 'Terra', 'Preto', N, 1, '',
 'Braço direito de um imperador baixinho. No Super virou criança e arrumou um namoradinho do futuro'],
['Tartaruga Umigame', ['Umigame','Tartaruga','Tartaruga Marinha'], 'Animal', M, 'Aliados', 1, 'Saga Pilaf', 'Terra', 'Nenhum', N, 1, '',
 'Foi salva por um menino perdido e agradeceu levando ele num véio tarado. Tem mil anos'],
['Launch', ['Lunch','Lanchi'], 'Humano', F, 'Aliados', 1, 'Saga Torneio (21º Torneio)', 'Terra', 'Azul' /* loira quando espirra */, S /* muda de personalidade ao espirrar */, 2, A+'Lunch_traje_de_sirvienta_en_el_manga.webp',
 'Um espirro e pronto, some a menina boazinha e chega a loira de metralhadora'],
['Kuririn', ['Krillin','Kulilin','Kurilin'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Torneio (21º Torneio)', 'Terra', 'Nenhum' /* careca clássico; cabelo só no fim do Z */, N, 6, A+'Krilin_Universo7.webp',
 'Careca de 6 pontinhos na testa, melhor amigo do protagonista e recordista mundial de morrer'],
['Tenshinhan', ['Tien','Ten Shin Han','Tenshin','Tien Shinhan'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Tenshinhan (22º Torneio)', 'Terra', 'Nenhum', N, 6, A+'Tenshinhan_Universo7.webp',
 'Três olhos, careca, ex-aluno da Escola Garça. Inventou um canhão em formato de triângulo'],
['Chaos', ['Chiaotzu','Chaozu','Chaoz'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Tenshinhan (22º Torneio)', 'Terra', 'Nenhum', N, 4, '',
 'Pequenininho, branquinho, bochecha vermelha e telecinese. Se explodiu agarrado num Saiyajin e não adiantou nada'],
['Tao Pai Pai', ['Mercenário Tao','Taopaipai','Tao'], 'Humano', M, 'Exército Red Ribbon', 1, 'Saga Red Ribbon', 'Terra', 'Preto', N, 3, '',
 'Assassino de aluguel que viajava em cima do tronco que ele mesmo tacou'],
['General Blue', ['Blue','General Azul'], 'Humano', M, 'Exército Red Ribbon', 1, 'Saga Red Ribbon', 'Terra', 'Loiro', N, 2, '',
 'Oficial loiro e vaidoso da fita vermelha que paralisa com o olhar. Perdeu pra uma menininha de óculos'],
['Comandante Red', ['Red','Comandante Vermelho'], 'Humano', M, 'Exército Red Ribbon', 1, 'Saga Red Ribbon', 'Terra', 'Ruivo', N, 1, '',
 'Chefe baixinho de tapa-olho. Queria as esferas pra ficar mais alto, sério mesmo'],
['Androide 8', ['Hatchan','Número 8','Oito','Android 8'], 'Androide', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Azul', N, 2, '',
 'Gigante de parafuso no pescoço feito pra ser arma, mas era bonzinho demais pra bater em alguém'],
['Arale', ['Arale Norimaki','Arale-chan'], 'Androide', F, 'Neutro', 1, 'Saga Red Ribbon', 'Terra', 'Roxo', N, 3 /* no Dr. Slump ela racha planeta, mas aqui é participação */, '',
 'Robozinha de óculos da Vila Pinguim que cutuca cocô com graveto. Nchaa!'],
['Karin', ['Korin','Mestre Karin','Sábio Karin','Gato Karin'], 'Animal', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Branco', N, 3, '',
 'Gato sábio no topo de uma torre altíssima. Quem guarda as sementes dos deuses é ele'],
['Upa', ['Upá'], 'Humano', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Preto', N, 1, '',
 'Menino da Torre Sagrada que viu o pai morrer pra um assassino e depois teve ele de volta com as esferas'],
['Dr. Brief', ['Doutor Brief','Brief','Pai da Bulma'], 'Humano', M, 'Aliados', 1, 'Saga Red Ribbon', 'Terra', 'Branco' /* grisalho azulado */, N, 1, '',
 'Dono da Corporação Cápsula. Fez uma nave pra Namekusei com câmara de gravidade e anda com um gatinho no ombro'],
['Yajirobe', ['Yajirobi','Yajiro'], 'Humano', M, 'Guerreiros Z', 1, 'Saga Piccolo Daimaoh', 'Terra', 'Preto', N, 3, '',
 'Samurai guloso e medroso que cortou o rabo de um príncipe e depois foi se esconder no mato'],
['Piccolo Daimaoh', ['Rei Piccolo','King Piccolo','Piccolo Daimao','Grande Rei Demônio'], 'Namekuseijin', M, 'Vilão', 1, 'Saga Piccolo Daimaoh', 'Namekusei', 'Nenhum', N, 3, '',
 'Rei Demônio que ficou preso numa panela de arroz elétrica. Botava a letra Ma nas costas dos filhos'],
['Tamborim', ['Tambourine','Tamborine'], 'Namekuseijin' /* "mazoku", filho mutante do Rei Demônio */, M, 'Vilão', 1, 'Saga Piccolo Daimaoh', 'Terra', 'Nenhum', N, 3, '',
 'Filho demoníaco com asa, cuspido num ovo pelo pai. Matou o careca melhor amigo do herói'],
['Kami-Sama', ['Kami','Deus da Terra','Kamisama','Deus'], 'Namekuseijin', M, 'Deuses', 1, 'Saga Piccolo Daimaoh', 'Namekusei', 'Nenhum', N, 4, '',
 'Guardião da Terra lá no templo. Expulsou o próprio lado ruim e depois acabou fundido com ele de novo'],
['Mr. Popo', ['Senhor Popo','Popo'], 'Outro', M, 'Deuses', 1, 'Saga Piccolo Daimaoh', 'Desconhecido', 'Nenhum', N, 3, '',
 'Ajudante eterno do deus da Terra. Cuida do jardim do templo e é educado de um jeito que dá medo'],
['Shenlong', ['Shenron','Dragão','Dragão Shenlong','Shen Long'], 'Dragão', O, 'Neutro', 1, 'Saga Pilaf', 'Terra', 'Nenhum', N, 5 /* não luta; nota média */, '',
 'Sai das sete esferas, realiza um desejo e odeia pedido complicado'],
['Piccolo', ['Piccolo Jr.','Ma Junior','Majunior','Piccolo Junior','Piccolo Laranja'], 'Namekuseijin', M, 'Guerreiros Z', 1, 'Saga Piccolo Jr. (23º Torneio)', 'Terra' /* nasceu na Terra, filho do Rei Demônio */, 'Nenhum', S, 8, A+'picolo_normal.webp',
 'Começou querendo dominar o mundo e terminou de babá, levando o filho do rival pra escola'],

/* ----------------------------- DRAGON BALL Z (2) ----------------------------- */
['Raditz', ['Radditz','Raditzu','Irmão do Goku'], 'Saiyajin', M, 'Forças do Freeza', 2, 'Saga Saiyajin', 'Vegeta', 'Preto', N, 4, A+'Raditz_artwork_Dokkan.webp',
 'Chegou na Terra dizendo que era irmão do protagonista, sequestrou o sobrinho e durou 2 episódios'],
['Gohan', ['Son Gohan','Grande Saiyaman','Gohanzinho','Gohan Besta','Gohan Beast'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Saiyajin', 'Terra', 'Preto', S, 9, A+'gohan.webp',
 'Filho mais velho do herói. Estudioso, poder escondido e nas horas vagas justiceiro de capacete'],
['Nappa', ['Napa'], 'Saiyajin', M, 'Forças do Freeza', 2, 'Saga Saiyajin', 'Vegeta', 'Nenhum', N, 4, '',
 'Careca de bigode que andava com o príncipe. Plantou os Saibaman e foi descartado pelo próprio chefe'],
['Vegeta', ['Príncipe dos Saiyajins','Principe Vegeta','Vegeta Ultra Ego'], 'Saiyajin', M, 'Guerreiros Z', 2, 'Saga Saiyajin', 'Vegeta', 'Preto', S, 9, A+'vegeta_normal.webp',
 'Príncipe de uma raça guerreira. Orgulho do tamanho de um planeta e eterno segundo lugar'],
['Saibaman', ['Saibamen','Saibamans','Saibaiman'], 'Outro', O, 'Vilão', 2, 'Saga Saiyajin', 'Desconhecido', 'Nenhum', N, 3, '',
 'Brotinho verde plantado na terra que nasce, pula e explode. Tem um cadáver famoso no currículo'],
['Kaio do Norte', ['Senhor Kaioh','Kaioh','Sr. Kaioh','King Kai','Kaio','Kaioh do Norte'], 'Kaio', M, 'Deuses', 2, 'Saga Saiyajin', 'Outro Mundo', 'Nenhum', N, 3, A+'Kaio_del_Norte.webp',
 'Deus de antena que mora num planetinha com um macaco e um grilo. Ninguém ri das piadas dele'],
['Freeza', ['Frieza','Freezer','Lord Freeza','Freeza Dourado','Black Freeza','Golden Freeza'], 'Raça do Freeza', M, 'Forças do Freeza', 2, 'Saga Namekusei', 'Desconhecido', 'Nenhum', S, 9, A+'Freezer.webp',
 'Imperador do universo que acabou com uma raça guerreira inteira. Educado, cruel e colecionador de forma'],
['Zarbon', ['Zabon'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Namekusei', 'Desconhecido', 'Verde', S, 4, A+'zarbon.webp',
 'Vaidoso de trança verde e brinco. Quando luta sério fica feio de doer'],
['Dodoria', ['Dodorian'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Namekusei', 'Desconhecido', 'Nenhum', N, 4, A+'dodoria.webp',
 'Rosa, redondo e cheio de espinho. Soldado do imperador que caiu na lábia de um príncipe'],
['Capitão Ginyu', ['Ginyu','Ginyuu','Captain Ginyu'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Nenhum', N /* troca de corpo não é transformação */, 5, A+'ginyu.webp',
 'Chefe de um esquadrão que faz pose de balé antes da briga. Especialidade: trocar de corpo. Terminou virando sapo'],
['Recoome', ['Recoom','Rikum'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Ruivo', N, 5, '',
 'Brutamontes ruivo que faz dancinha antes de socar. Amassou meio time e caiu com um golpe na barriga'],
['Jeice', ['Jace','Jiise'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Brench', 'Branco', N, 4, '',
 'Pele vermelha e cabelão branco. Fugiu no meio da luta pra chamar o chefe'],
['Burter', ['Butter','Baata'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Nenhum', N, 4, '',
 'Grandão azul que se achava o mais rápido do universo. Até conhecer um Super Saiyajin'],
['Guldo', ['Gurdo'], 'Alienígena', M, 'Forças do Freeza', 2, 'Saga Forças Especiais Ginyu', 'Desconhecido', 'Nenhum', N, 4, '',
 'Baixinho verde de 4 olhos que para o tempo, mas só enquanto aguenta prender a respiração'],
['Dende', ['Dendê','Deus da Terra Jovem'], 'Namekuseijin', M, 'Deuses', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 1, A+'Dende_Artwork.webp',
 'Moleque que cura qualquer machucado. Saiu de Namekusei pra virar o novo guardião da Terra'],
['Nail', ['Neiru'], 'Namekuseijin', M, 'Aliados', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 5, A+'Nail_Artwork.webp',
 'Guerreiro mais forte do planeta dele, guarda-costas do Patriarca. Terminou fundido com um velho conhecido'],
['Grande Patriarca', ['Guru','Grande Ancião','Patriarca','Grande Guru'], 'Namekuseijin', M, 'Aliados', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 2, '',
 'Pai de um planeta inteiro, enorme e sempre sentado. Desperta o poder escondido com a mão na cabeça'],
['Porunga', ['Polunga','Dragão de Namekusei'], 'Dragão', O, 'Neutro', 2, 'Saga Namekusei', 'Namekusei', 'Nenhum', N, 5 /* não luta; nota média */, '',
 'Dragão marombado que dá 3 desejos, mas só se pedir na língua certa'],
['Rei Cold', ['King Cold','Cold'], 'Raça do Freeza', M, 'Forças do Freeza', 2, 'Saga Trunks', 'Desconhecido', 'Nenhum', N, 5, '',
 'Pai de dois imperadores tiranos. Veio na Terra se vingar e deu de cara com uma espada do futuro'],
['Trunks do Futuro', ['Mirai Trunks','Future Trunks','Trunks Futuro','Trunks do futuro'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Trunks', 'Terra', 'Lilás', S, 8, '',
 'Veio numa máquina do tempo avisar dos androides. Chegou de espada e fatiou um imperador'],
['Trunks', ['Trunks Criança','Kid Trunks','Trunks Pequeno'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Androides', 'Terra', 'Lilás', S, 7, A+'Trunks_Buu_Artwork.webp',
 'Herdeiro da Corporação Cápsula e filho do príncipe. Aprontava com o melhor amigo e virou Super Saiyajin antes dos 8'],
['Dr. Gero', ['Androide 20','Android 20','Doutor Gero','Gero','Número 20'], 'Androide', M, 'Exército Red Ribbon', 2, 'Saga Androides', 'Terra', 'Branco', N, 5, A+'Dr._Gero%20nadroide%2020.webp',
 'Cientista da fita vermelha que virou máquina só pra se vingar de uma criança'],
['Androide 19', ['Android 19','Número 19','C-19','Dezenove'], 'Androide', M, 'Exército Red Ribbon', 2, 'Saga Androides', 'Terra', 'Nenhum', N, 5, A+'Android19.webp',
 'Gorducho branco de chapéu que sugava energia pela mão. Perdeu os braços pro príncipe recém-transformado'],
['Androide 18', ['Android 18','Número 18','C-18','Lazuli','Dezoito'], 'Androide', F, 'Guerreiros Z', 2, 'Saga Androides', 'Terra', 'Loiro', N, 7, A+'Androide_18_Artwork.webp',
 'Loira de energia infinita que quebrou o braço de um príncipe e depois casou com o careca mais gente boa da Terra'],
['Androide 17', ['Android 17','Número 17','C-17','Lapis','Dezessete'], 'Androide', M, 'Guerreiros Z', 2, 'Saga Androides', 'Terra', 'Preto', N, 8, A+'17_Artwork.webp',
 'Rebelde de lenço laranja que virou guarda-florestal e salvou o universo no último segundo do torneio'],
['Androide 16', ['Android 16','Número 16','C-16','Dezesseis'], 'Androide', M, 'Exército Red Ribbon', 2, 'Saga Androides', 'Terra', 'Ruivo', N, 6, A+'Androide_16.webp',
 'Gigante ruivo que amava passarinho. Com a cabeça esmagada ainda pediu pro menino soltar a raiva'],
['Cell', ['Célula','Cell Perfeito','Cell Imperfeito'], 'Bio-Androide', M, 'Vilão', 2, 'Saga Cell', 'Terra', 'Nenhum', S, 7, A+'celula.webp',
 'Feito com célula dos melhores guerreiros. Engoliu dois androides pra ficar perfeito e fez o próprio torneio'],
['Cell Jr.', ['Cell Junior','Cells Jr','Filhos do Cell','Cell Jr'], 'Bio-Androide', M, 'Vilão', 2, 'Saga Cell', 'Terra', 'Nenhum', N, 6, '',
 'Miniaturas azuis de um vilão perfeito. Sete deles deram um coro nos guerreiros no torneio do pai'],
['Mr. Satan', ['Hercule','Satan','Mister Satan','Campeão Mundial','Mr Satan'], 'Humano', M, 'Aliados', 2, 'Saga Cell', 'Terra', 'Preto', N, 1, A+'Mr_Satan_DBSuper.webp',
 'Campeão mundial que levou o crédito por salvar o mundo. Duas vezes'],
['Videl', ['Videl Satan'], 'Humano', F, 'Guerreiros Z', 2, 'Saga Grande Saiyaman', 'Terra', 'Preto', N, 3, '',
 'Filha do campeão mundial. Descobriu quem era o justiceiro de capacete e aprendeu a voar com ele'],
['Goten', ['Son Goten','Gotenzinho'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Grande Saiyaman', 'Terra', 'Preto', S, 7, '',
 'Cópia em miniatura do pai. Virou Super Saiyajin brincando, antes de saber o que era isso'],
['Kaioshin', ['Shin','Supremo Senhor Kaioh','Kaioshin do Leste','Supreme Kai','Senhor Kaioshin'], 'Kaioshin', M, 'Deuses', 2, 'Saga Torneio Mundial (25º Torneio)', 'Mundo dos Kaioshins', 'Branco', N, 6, A+'Kaio-shin_del_este_Artwork.webp',
 'Deus supremo baixinho de moicano branco que apareceu disfarçado num torneio avisando de um mago'],
['Kibito', ['Kibitto'], 'Kaioshin', M, 'Deuses', 2, 'Saga Torneio Mundial (25º Torneio)', 'Mundo dos Kaioshins', 'Branco', N, 5, A+'Kibito_Artwork.webp',
 'Ajudante alto e sério de um deus supremo. Teleportava geral e morreu num estalo'],
['Kibito-Shin', ['Kibitoshin','Kibito Kai','Kibito Shin'], 'Kaioshin', M, 'Deuses', 2, 'Saga Kid Boo', 'Mundo dos Kaioshins', 'Branco', N, 6, A+'Kibito_shin_Artwork.webp',
 'Deu nisso quando um deus e o ajudante dele colocaram os brincos. Não tem volta'],
['Ancião Kaioshin', ['Velho Kaioshin','Old Kai','Kaioshin Ancião','Supremo Kaioshin Ancião','Velho Supremo'], 'Kaioshin', M, 'Deuses', 2, 'Saga Fusão', 'Mundo dos Kaioshins', 'Branco', N, 3, '',
 'Ficou preso numa espada por 15 gerações. Troca o ritual de poder por revista de mulher pelada'],
['Grande Kaioshin', ['Dai Kaioshin','Grand Supreme Kai','Daikaioshin'], 'Kaioshin', M, 'Deuses', 2, 'Saga Babidi', 'Mundo dos Kaioshins', 'Lilás', N, 5, A+'Gran_Kaio-shin_Artwork.webp',
 'Deus supremo gordinho que foi absorvido por um Majin e acabou deixando ele fofinho'],
['Grande Kaio', ['Dai Kaioh','Grand Kai','Grande Senhor Kaioh','Grande Kaioh'], 'Kaio', M, 'Deuses', 2, 'Saga Torneio do Outro Mundo', 'Outro Mundo', 'Branco', N, 4, A+'Gran_kaio_sama12.webp',
 'Chefe dos Kaios, de óculos escuro, fã de rock e dono do torneio dos mortos'],
['Pikkon', ['Paikuhan','Pikon'], 'Alienígena', M, 'Neutro', 2, 'Saga Torneio do Outro Mundo', 'Desconhecido', 'Nenhum', N, 6, '',
 'Guerreiro verde do Kaio do Oeste que treina de roupa pesada no Outro Mundo. Rival do herói depois de morto'],
['Babidi', ['Bibidi Babidi','Mago Babidi','Babid'], 'Outro', M, 'Clã de Babidi', 2, 'Saga Babidi', 'Desconhecido', 'Nenhum', N, 1, A+'Babidi_Artwork.webp',
 'Mago baixinho e enrugado que taca um M na testa dos outros. Escolheu o pior bicho de estimação possível'],
['Dabura', ['Rei Demônio Dabura','Dabra'], 'Demônio', M, 'Clã de Babidi', 2, 'Saga Babidi', 'Mundo Demoníaco', 'Nenhum', N, 6, '',
 'Rei do Mundo Demoníaco mandado por um mago. Cospe em você e você vira pedra'],
['Spopovich', ['Spopovitch','Popovich'], 'Humano', M, 'Clã de Babidi', 2, 'Saga Torneio Mundial (25º Torneio)', 'Terra', 'Nenhum', N, 3, '',
 'Careca inchado e controlado por um mago. Espancou a filha do campeão no torneio e roubou energia de um moleque'],
['Majin Boo', ['Majin Buu','Boo','Buu','Boo Gordo','Fat Buu','Boo Gordinho'], 'Majin', M, 'Guerreiros Z', 2, 'Saga Majin Boo', 'Desconhecido', 'Nenhum', N, 7, A+'BuuGordo_Universo7.webp',
 'Rosa, fofinho e transforma gente em chocolate. Melhor amigo do campeão mundial e dono de um cachorrinho'],
['Super Boo', ['Super Buu','Boo Malvado','Evil Buu','Boo Maligno'], 'Majin', M, 'Vilão', 2, 'Saga Majin Boo', 'Desconhecido', 'Nenhum', S /* absorções mudam a forma */, 8, '',
 'A metade malvada que engoliu a metade boazinha. Absorve os inimigos e ainda fica com a roupa deles'],
['Kid Boo', ['Kid Buu','Majin Boo Puro','Boo Magro','Boo Original','Boo Criança'], 'Majin', M, 'Vilão', 2, 'Saga Kid Boo', 'Desconhecido', 'Nenhum', N, 7, '',
 'A forma original, pequena e doida de pedra. Explodiu a Terra por diversão e caiu pra uma Genki Dama'],
['Gotenks', ['Gotenks SSJ3','Gotrunks'], 'Meio-Saiyajin', M, 'Guerreiros Z', 2, 'Saga Majin Boo', 'Terra', 'Preto', S, 8, A+'Gotenks_Artwork.webp',
 'Fusão de dois moleques na dancinha. Metido, dá nome ridículo pros golpes e solta fantasma kamikaze'],
['Vegetto', ['Vegito','Vegerot','Vegetto Blue'], 'Saiyajin', M, 'Guerreiros Z', 2, 'Saga Fusão', 'Vegeta', 'Preto', S, 9, T+'Vegetto.webp',
 'Fusão feita com brinco de deus. Transformou o vilão numa bala de goma'],
['Uub', ['Oob','Ub','Majuub'], 'Humano', M, 'Guerreiros Z', 2, 'Saga Kid Boo', 'Terra', 'Preto', S /* vira Majuub no GT */, 6, '',
 'Moleque de vila pobre que é a reencarnação de um monstro. No fim foi embora como aluno do herói'],
['Pan', ['Pan Son','Neta do Goku'], 'Descendente Saiyajin', F, 'Guerreiros Z', 2, 'Saga Kid Boo', 'Terra', 'Preto', N, 5, '',
 'Neta do protagonista, voa desde bebê e é a única menina que rodou o espaço no GT'],
['Bra', ['Bulla','Bura','Filha do Vegeta'], 'Meio-Saiyajin', F, 'Aliados', 2, 'Saga Kid Boo', 'Terra', 'Azul', N, 1, '',
 'Filha do príncipe, cabelo azul da mãe. O pai orgulhoso vira um bobão perto dela'],

/* ----------------------------- FILMES / ESPECIAIS Z (3) ----------------------------- */
['Garlic Jr.', ['Garlic Junior','Garlic','Garlic Jr'], 'Demônio', M, 'Vilão', 3, 'Filme "A Zona Morta" (1989)', 'Estrela Makyo', 'Nenhum', S, 5, '',
 'Baixinho imortal que queria ser o deus da Terra e foi sugado pro próprio buraco negro'],
['Bardock', ['Bardack','Pai do Goku','Burdock'], 'Saiyajin', M, 'Forças do Freeza', 3, 'Especial "O Pai de Goku" (1990)', 'Vegeta', 'Preto', S, 4, A+'Bardock_Artwork.webp',
 'Soldado de classe baixa que via o futuro e encarou o imperador sozinho, de faixa vermelha na testa'],
['Turles', ['Tullece','Turlez'], 'Saiyajin', M, 'Vilão', 3, 'Filme "A Árvore do Poder" (1990)', 'Vegeta', 'Preto', N, 5, '',
 'Saiyajin igualzinho ao protagonista, só que moreno e ruim. Plantou uma árvore que suga planeta'],
['Slug', ['Lord Slug','Lorde Slug','Slug Gigante'], 'Namekuseijin', M, 'Vilão', 3, 'Filme "Lord Slug" (1991)', 'Namekusei', 'Nenhum', S, 5, '',
 'Namekuseijin véio e malvado que usou as esferas pra ficar novo e queria transformar a Terra numa nave'],
['Cooler', ['Coola','Metal Cooler','Irmão do Freeza'], 'Raça do Freeza', M, 'Vilão', 3, 'Filme "A Vingança de Cooler" (1991)', 'Desconhecido', 'Nenhum', S, 6, '',
 'Irmão mais velho do imperador, com uma forma a mais que ele. Depois voltou como máquina'],
['Androide 13', ['Android 13','Número 13','Super 13','Treze'], 'Androide', M, 'Exército Red Ribbon', 3, 'Filme "Androide 13" (1992)', 'Terra', 'Branco', S, 6, A+'Androide13normal.webp',
 'Androide caipira de boné que absorveu as peças dos colegas e ficou azulão e enorme'],
['Androide 14', ['Android 14','Número 14','Quatorze','Catorze'], 'Androide', M, 'Exército Red Ribbon', 3, 'Filme "Androide 13" (1992)', 'Terra', 'Preto', N, 5, A+'14Dokkan.webp',
 'Grandalhão pálido de trança preta, montado pelo computador de um cientista que já tinha morrido'],
['Broly', ['Broli','Lendário Super Saiyajin','Brolly'], 'Saiyajin', M, 'Vilão', 3, 'Filme "O Lendário Super Saiyajin" (1993)', 'Vegeta', 'Preto', S, 9, T+'Broly_DBS_Base.webp',
 'O lendário que ficou traumatizado no berço do lado do herói. Grita o nome dele até perder a voz'],
['Paragus', ['Paragasu','Paragas'], 'Saiyajin', M, 'Vilão', 3, 'Filme "O Lendário Super Saiyajin" (1993)', 'Vegeta', 'Preto', N, 4, '',
 'Pai do lendário. Controlava o filho com um anel na cabeça e morreu esmagado dentro de uma nave'],
['Bojack', ['Boujack','Bo Jack'], 'Alienígena', M, 'Vilão', 3, 'Filme "Bojack" (1993)', 'Desconhecido', 'Ruivo', S, 6, '',
 'Pirata espacial verde-azulado que ficou solto quando um Kaio morreu. Invadiu um torneio na Terra'],
['Janemba', ['Super Janemba','Janenba'], 'Demônio', O, 'Vilão', 3, 'Filme "Fusão" (1995)', 'Outro Mundo', 'Nenhum', S, 8, T+'Janemba_artwork_SDBH.webp',
 'Nasceu da maldade acumulada numa máquina de limpar alma e virou o Outro Mundo do avesso'],
['Gogeta', ['Gojeta','Gogeta Blue','Gogeta SSJ4'], 'Saiyajin', M, 'Guerreiros Z', 3, 'Filme "Fusão" (1995)', 'Vegeta', 'Preto', S, 9, T+'gogeta.webp',
 'Fusão da dança, de colete e calça branca. Resolveu tudo antes do tempo da fusão acabar'],
['Tapion', ['Tapiom','Tapio'], 'Alienígena', M, 'Aliados', 3, 'Filme "O Ataque do Dragão" (1995)', 'Konats', 'Ruivo', N, 5, '',
 'Herói de outro planeta que ficou preso numa caixinha de música com meio monstro dentro. Toca uma ocarina triste'],

/* ----------------------------- DRAGON BALL GT (4) ----------------------------- */
['Baby', ['Baby Vegeta','Bebi','Bebê'], 'Tsufurujin', M, 'Vilão', 4, 'Saga Baby', 'M-2', 'Nenhum', S, 8, '',
 'Parasita feito pra vingar uma raça extinta. Possuiu o príncipe e virou um macacão dourado gigante'],
['Super 17', ['Super Androide 17','Super C-17','Super Número 17'], 'Androide', M, 'Vilão', 4, 'Saga Super 17', 'Terra', 'Preto', N, 8, '',
 'Deu nisso quando dois androides iguais se juntaram, um da Terra e outro do Inferno'],
['Giru', ['Gill','Gil'], 'Androide' /* máquina mutante */, M, 'Aliados', 4, 'Saga Esferas do Dragão Negras', 'Desconhecido', 'Nenhum', N, 1, '',
 'Robozinho que comeu o radar e virou o radar. Fica repetindo o próprio nome'],
['Omega Shenlong', ['Omega Shenron','Ii Shenron','Syn Shenron','Li Shenron','Dragão Maligno'], 'Dragão', M, 'Vilão', 4, 'Saga Dragões Malignos', 'Terra', 'Branco', S, 8, '',
 'Dragão ruim que nasceu de tanto abusarem das esferas. Engoliu as outras seis e virou a versão final'],
['Goku Jr.', ['Goku Junior','Goku Jr'], 'Descendente Saiyajin', M, 'Neutro', 4, 'Episódio final (100 anos depois)', 'Terra', 'Preto', S, 5, '',
 'Tataraneto chorão do herói. Cem anos depois virou Super Saiyajin pra defender a vó'],

/* ----------------------------- DRAGON BALL SUPER (5) ----------------------------- */
['Bills', ['Beerus','Birusu','Deus da Destruição','Lorde Bills'], 'Deus', M, 'Deuses', 5, 'Saga A Batalha dos Deuses', 'Planeta de Bills', 'Nenhum', N, 9, A+'Beerus_DBS_Broly_Artwork.webp',
 'Gato roxo que dorme por décadas, acorda com fome e ameaça explodir a Terra por causa de um pudim'],
['Whis', ['Uisu','Wiss','Anjo do Universo 7'], 'Anjo', M, 'Deuses', 5, 'Saga A Batalha dos Deuses', 'Planeta de Bills', 'Branco', N, 10, A+'Whis_DBS_Broly_Artwork.webp',
 'Ajudante e mestre de um deus. Educado demais, volta o tempo em 3 minutos e ama comida da Terra'],
['Champa', ['Shanpa','Deus da Destruição do Universo 6'], 'Deus', M, 'Deuses', 5, 'Saga Torneio do Universo 6', 'Planeta de Champa', 'Nenhum', N, 9, '',
 'Gêmeo gordinho e birrento de um deus gato. Fez um torneio só pra roubar a Terra do irmão'],
['Vados', ['Vadosu','Anjo do Universo 6'], 'Anjo', F, 'Deuses', 5, 'Saga Torneio do Universo 6', 'Planeta de Champa', 'Branco', N, 10, '',
 'Irmã mais velha de um anjo famoso. Trabalha pra um deus guloso e acha tudo engraçado'],
['Hit', ['Assassino Hit','Hitto'], 'Alienígena', M, 'Universo 6', 5, 'Saga Torneio do Universo 6', 'Desconhecido', 'Nenhum', N, 8, '',
 'Assassino roxo mais temido do universo dele. Pula o tempo por um tiquinho de segundo e fica mais forte a cada luta'],
['Cabba', ['Kyabe','Cabbe'], 'Saiyajin', M, 'Universo 6', 5, 'Saga Torneio do Universo 6', 'Sadala', 'Preto', S, 7, '',
 'Saiyajin educadinho de outro universo que chamou o príncipe de mestre e aprendeu a se transformar na raiva'],
['Frost', ['Frosto','Freeza do Universo 6'], 'Raça do Freeza', M, 'Vilão', 5, 'Saga Torneio do Universo 6', 'Desconhecido', 'Nenhum', S, 7, '',
 'Pinta de herói, mas é pirata. A versão de outro universo do imperador, com agulha escondida no braço'],
['Monaka', ['Monaca'], 'Alienígena', M, 'Neutro', 5, 'Saga Torneio do Universo 6', 'Wagashi', 'Nenhum', N, 1, '',
 'O guerreiro mais forte do deus gato, que na real é um entregador que desmaia de medo'],
['Zeno Sama', ['Zeno','Zen-Oh','Zenoh','Rei de Tudo','Zeno-sama','Zen Oh Sama'], 'Deus', M, 'Deuses', 5, 'Saga Torneio do Universo 6', 'Palácio do Zeno', 'Nenhum', N, 10, A+'Zeno_Artwork.webp',
 'Rei de tudo, cara de criança e botão pra apagar universo. Chamou o herói de amigo'],
['Grande Sacerdote', ['Daishinkan','Grand Priest','Sumo Sacerdote','Grande Sacerdote Anjo'], 'Anjo', M, 'Deuses', 5, 'Saga Trunks do Futuro (Black)', 'Palácio do Zeno', 'Branco', N, 10, A+'Grand%20priest.webp',
 'Pai de todos os anjos e juiz do torneio que apagava universo. Sorriso gentil e poder absurdo'],
['Goku Black', ['Black','Black Goku','Goku Negro'], 'Saiyajin' /* alma de Kaioshin, corpo Saiyajin */, M, 'Vilão', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Preto', S, 8, '',
 'Cara do herói com alma de um deus aprendiz que odeia mortal. Transformação cor-de-rosa'],
['Zamasu', ['Zamas','Zamasu do Universo 10'], 'Kaioshin', M, 'Vilão', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Branco', N, 7, '',
 'Aprendiz de deus supremo com um plano de justiça: acabar com todos os mortais. Tomava chá enquanto julgava'],
['Zamasu Fundido', ['Zamasu Fusão','Fused Zamasu','Zamasu Fusionado'], 'Kaioshin', M, 'Vilão', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Branco', S, 8, '',
 'Fusão imortal de dois vilões com brinco. Foi apagado junto com o futuro inteiro'],
['Gowasu', ['Gowas'], 'Kaioshin', M, 'Deuses', 5, 'Saga Trunks do Futuro (Black)', 'Mundo dos Kaioshins', 'Branco', N, 3, '',
 'Véio deus supremo do Universo 10 que achou que o aprendiz ia melhorar com chá'],
['Jiren', ['Jiren o Cinza','Giren'], 'Alienígena', M, 'Tropa do Orgulho', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Nenhum', N, 9, A+'Jiren.webp',
 'Cinzento de braço cruzado que meditava enquanto geral saía na mão. Só acredita na força'],
['Toppo', ['Top'], 'Alienígena', M, 'Tropa do Orgulho', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Nenhum', S, 8, A+'Toppo.webp',
 'Bigodudo da justiça que faz pose e, no aperto, revela que é candidato a deus da destruição'],
['Dyspo', ['Dispo','Diseo'], 'Alienígena', M, 'Tropa do Orgulho', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Nenhum', N, 7, A+'Dispo_render.webp',
 'O mais rápido da tropa da justiça, orelhudo e roxo. Irritou um careca com o jeito de falar'],
['Marcarita', ['Marcarita Anjo','Anjo do Universo 11'], 'Anjo', F, 'Deuses', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Branco', N, 10, A+'Marcarita.webp',
 'Anjo de maria-chiquinha que acompanha um deus palhaço e nunca perde a calma'],
['Vermoud', ['Belmod','Beerus do Universo 11'], 'Deus', M, 'Deuses', 5, 'Saga Sobrevivência do Universo', 'Desconhecido', 'Ruivo', N, 9, A+'Vermoud.webp',
 'Deus da destruição com cara de palhaço e cabelo em dois tufos. Faz discurso de justiça antes de apagar alguém'],
['Caulifla', ['Kaulifla','Colifla'], 'Saiyajin', F, 'Universo 6', 5, 'Saga Sobrevivência do Universo', 'Sadala', 'Preto', S, 7, '',
 'Chefe de gangue que aprendeu a virar Super Saiyajin em minutos e queria aprender mais com o herói'],
['Kale', ['Kalé','Kale Berserker'], 'Saiyajin', F, 'Universo 6', 5, 'Saga Sobrevivência do Universo', 'Sadala', 'Preto', S, 7, '',
 'Tímida e insegura, mas quando perde o controle vira uma lendária de cabelo verde'],
['Kefla', ['Kaufla','Kefura'], 'Saiyajin', F, 'Universo 6', 5, 'Saga Sobrevivência do Universo', 'Sadala', 'Preto', S, 8, '',
 'Fusão de brinco de duas meninas do Universo 6. Deu trabalho até pro instinto superior'],
['Gamma 1', ['Gama 1','Gamma Um'], 'Androide', M, 'Exército Red Ribbon', 5, 'Filme "Super Hero" (2022)', 'Terra', 'Preto', N, 7, '',
 'Androide de capa vermelha que se acha super-herói. Foi enganado e achou que os heróis eram os vilões'],
['Gamma 2', ['Gama 2','Gamma Dois'], 'Androide', M, 'Exército Red Ribbon', 5, 'Filme "Super Hero" (2022)', 'Terra', 'Preto', N, 7, '',
 'Androide de capa azul, o mais zoeiro da dupla. Se sacrificou pra parar um monstro gigante'],
['Cheelai', ['Chilai','Cheela'], 'Alienígena', F, 'Aliados', 5, 'Filme "Broly" (2018)', 'Desconhecido', 'Branco', N, 2, '',
 'Ex-soldada do imperador, pele verde e cabelo branco, que virou amiga de um Saiyajin grandão e perdido'],
['Gine', ['Gin','Mãe do Goku'], 'Saiyajin', F, 'Neutro', 5, 'Mangá "Dragon Ball Minus" (2014)', 'Vegeta', 'Preto', N, 2, '',
 'Saiyajin boazinha que trabalhava num açougue e mandou o filho numa cápsula pra Terra']
];

/* ---------- fotos da Dragon Ball Wiki (miniatura de 400px) ----------
   Quem não tem imagem da dragonball-api usa essa como img.
   Quem tem, ganha essa como img2 (reserva). Formato: 'caminho|cb' */
const W = 'https://static.wikia.nocookie.net/dragonball/images/';
const WIKI = {
  'Goku':'b/ba/Goku_anime_profile.png|20250723190513',
  'Bulma':'a/a6/Bulma_anime_profile.png|20250617190824',
  'Mestre Kame':'5/5f/Master_roshi_enhanced.jpg|20210310020858',
  'Oolong':'7/79/OolongWMATEp17.png|20241219021741',
  'Puar':'1/1c/Puar_Episode_9.png|20250306174509',
  'Yamcha':'5/59/Yamcha_DB_Episode_138.png|20250201193345',
  'Chi-Chi':'e/e2/Chi-Chi_DBZ_Ep_04_001.png|20201226004235',
  'Rei Cutelo':'5/5b/Ox-KingPresentsEp05.png|20250401030059',
  'Imperador Pilaf':'6/6a/Emperor_Pilaf_DB_Ep_32_002.png|20241214224943',
  'Mai':'c/cf/Mai_DB_Episode_10.png|20241217045134',
  'Tartaruga Umigame':'b/bf/Turtles.png|20250308170636',
  'Launch':'9/99/Launch_Combined_DB_Episode_15.png|20250119032837',
  'Kuririn':'5/54/Krillin_DB_Episode_134.png|20241210001054',
  'Tenshinhan':'5/56/Tien_DBZ_Kai.png|20250318211443',
  'Chaos':'b/bb/Chiaotzu_DB_Ep_134_002.png|20231013025758',
  'Tao Pai Pai':'8/87/Mercenary_Tao_Dragon_Ball_Episode_59.png|20241209224259',
  'General Blue':'5/5a/General_Blue_DB_Ep_48_001.png|20241005211129',
  'Comandante Red':'7/7b/Commander_Red_DB_Ep_67_003.png|20241213021920',
  'Androide 8':'f/f6/Android_8_DB_Ep_38_002.png|20241213025200',
  'Arale':'7/7a/AraleNorimaki01.png|20241217001133',
  'Karin':'f/fe/KorinBuuSagaNV.png|20100513171706',
  'Upa':'4/46/Upa_DB_Ep_58_001.png|20250311140014',
  'Dr. Brief':'2/24/Dr.BriefNV.png|20100428134828',
  'Yajirobe':'6/64/Yajirobe_DBZ_Episode_46.png|20241207133549',
  'Piccolo Daimaoh':'3/3b/King_Piccolo_Episode_112.png|20260911022953',
  'Tamborim':'f/f8/Tambourine_Dragon_Ball_Episode_103.png|20241213233411',
  'Kami-Sama':'a/a2/KamiGarlicJuniorSagaNV.png|20250325021450',
  'Mr. Popo':'9/98/Mrpopo.png|20241221193238',
  'Shenlong':'2/26/Shenron_DBZ_Episode_240.png|20210429121425',
  'Piccolo':'b/b7/Super_Hero_-_Piccolo_artwork_3.png|20250923210449',
  'Raditz':'8/86/Raditz_arrives_at_Kame_House.png|20260822192657',
  'Gohan':'3/3b/Gohan_anime_profile_3.png|20250617191059',
  'Nappa':'b/b9/FighterZ_-_Nappa_artwork.jpg|20171026062143',
  'Vegeta':'9/94/Vegeta_anime_profile.png|20250723190507',
  'Saibaman':'1/1c/Saibamen_Anime.png|20241210023700',
  'Kaio do Norte':'6/61/KingKaiNV.png|20200219185209',
  'Freeza':'e/ee/DBS_Broly_Frieza_Render.png|20221019232854',
  'Zarbon':'0/0f/Zarbon_DBZ_Ep_56_002.png|20180804213413',
  'Dodoria':'f/fd/Dodoria_DBZ_Ep_49_002.png|20170827051359',
  'Capitão Ginyu':'2/28/CaptainGinyuVsGoku.png|20260822002603',
  'Recoome':'8/8a/RecoomeTGFP.png|20100409151048',
  'Jeice':'3/35/Jeice_DBZ_Episode_71.png|20210519195015',
  'Burter':'f/f5/Big_Blue_Snake_Guy.png|20210319195352',
  'Guldo':'c/cb/GULDO.jpg|20140228015925',
  'Dende':'0/0d/DendeIllFightToo.png|20110906232642',
  'Nail':'4/40/Nail.png|20260822134102',
  'Grande Patriarca':'d/de/Guru_DBZ_Ep_76_001.png|20170915040925',
  'Porunga':'8/88/Porunga_is_summoned_by_Dende.png|20250214203821',
  'Rei Cold':'2/22/King_Cold_episode_122.png|20241217033208',
  'Trunks do Futuro':'4/4f/Future_Trunks_DBZ_Episode_131.png|20241206021927',
  'Trunks':'d/d1/Super_Hero_-_Trunks_artwork.jpg|20250904060656',
  'Dr. Gero':'7/71/Dr.GeroEp130.png|20160922141535',
  'Androide 19':'1/1f/Android_19_DBZ_Episode_130.png|20210904181928',
  'Androide 18':'e/e6/Android_18_anime_profile.png|20250617190842',
  'Androide 17':'2/27/Android_17_%28DBZ_ep.148%29.jpg|20250410044432',
  'Androide 16':'b/b2/Android_16.png|20210331024540',
  'Cell':'2/27/Cell_%28DBZ_ep_177%29.png|20260801130819',
  'Cell Jr.':'e/ef/Cell_Junior_episode_184.png|20211023035521',
  'Mr. Satan':'e/ef/Mr_Satan_at_the_Cell_Games.png|20260315145605',
  'Videl':'d/de/Videl_Episode_207.png|20210406214244',
  'Goten':'c/c9/Super_Hero_-_Goten_artwork.jpg|20220920183551',
  'Kaioshin':'1/17/KaiSupremeNV.png|20120111094205',
  'Kibito':'c/ce/Kibito-0.jpg|20170521172437',
  'Kibito-Shin':'1/12/KibitoKaiNV.png|20100424162026',
  'Ancião Kaioshin':'f/ff/Old_Kai_DBZ_Ep_250.jpg|20210316155139',
  'Grande Kaioshin':'1/13/DaikaiohEndOfEarth.png|20100702061918',
  'Grande Kaio':'a/ab/Grand_Kai_DBZ_Episode_195.png|20210601223816',
  'Pikkon':'b/b1/Pikkon_DBZ_Ep_198_003.png|20170916231851',
  'Babidi':'5/5c/BabidiDBZ.png|20091210131219',
  'Dabura':'a/ab/Dabura_becoming_Supreme_Demon_King_after_usurping_Abura.png|20250124223335',
  'Spopovich':'b/b3/Spopovich_25th_BT.png|20211004205424',
  'Majin Boo':'4/4a/All_Majin_Buu_forms_%28Daiz4%29.jpg|20130605020823',
  'Super Boo':'3/32/MajinBuuSuperVsGohan02.png|20260820190521',
  'Kid Boo':'5/53/Kid_Buu.png|20260821150947',
  'Gotenks':'0/08/Gotenks.png|20260821150453',
  'Vegetto':'5/53/Vegito.jpg|20250317214139',
  'Uub':'1/1b/Cvanon.jpg|20171214122930',
  'Pan':'1/1c/Super_Hero_-_Pan_artwork_2.png|20250923210359',
  'Bra':'8/8e/BullaDBGTmad.png|20240927043737',
  'Garlic Jr.':'1/15/Garlic_Jr_anime.png|20260521233638',
  'Bardock':'d/d5/Bardock_-_The_Father_of_Goku_-_Bardock_after_landing_on_Planet_Meat.png|20250121192318',
  'Turles':'0/0b/The_Tree_of_Might_-_Turles_looking_down_at_Gohan.jpg|20210927023245',
  'Slug':'8/88/Lord_Slug_-_Lord_Slug_-_007.png|20250308100918',
  'Cooler':'f/f2/Cooler_Artwork.png|20170801165857',
  'Androide 13':'3/35/Android_13_-_Super_Android_13_-_005.png|20240906012340',
  'Androide 14':'9/99/A-14.jpg|20081128213355',
  'Broly':'c/cd/Broly_Infobox_image.png|20170525181624',
  'Paragus':'a/ab/ParagusDVD.png|20100809114554',
  'Bojack':'2/29/Bojack.BojackUnbound.png|20230626181902',
  'Janemba':'b/bf/Myth.jpg|20170104141124',
  'Gogeta':'7/7b/Gogeta_Base_Full.jpg|20191027075547',
  'Tapion':'8/8c/FMSv13dXwAY3f4a.jpg|20220223171217',
  'Baby':'a/a3/Baby_confronting_Goten.png|20241227021316',
  'Super 17':'6/67/S17_infobox.PNG|20251109135152',
  'Giru':'8/89/Giru.Ep.16.GT.png|20240918052135',
  'Omega Shenlong':'6/6a/Omega_Shenron_Dbox.png|20210904220600',
  'Goku Jr.':'e/e6/GokuJr.01.png|20250103023037',
  'Bills':'7/7d/BeerusWikia_%283%29.jpg|20240224003806',
  'Whis':'b/bd/Whis_%28DBS_ep67%29.png|20170629161500',
  'Champa':'6/6a/Champa_Artwork.png|20180325175221',
  'Vados':'4/41/VadosWikia_%281%29.jpg|20170625154835',
  'Hit':'e/ec/Hit_Profile.jpg|20160404221157',
  'Cabba':'8/8c/Cabba_Dragon_Ball_Super_Episode_37.png|20210419202430',
  'Frost':'4/4b/FrostFinalForm.png|20170724232039',
  'Monaka':'d/df/Monaka_%28anime%29.png|20250218193951',
  'Zeno Sama':'c/c1/Zeno.png|20170805000223',
  'Grande Sacerdote':'7/78/Daishinkan1.png|20170815212212',
  'Goku Black':'1/13/Screenshot_%282%29.png|20190211123553',
  'Zamasu':'5/59/Zamasu_DBS_Ep_53_006.png|20180820041712',
  'Zamasu Fundido':'5/51/FighterZ_-_Fused_Zamasu_artwork.png|20180424074001',
  'Gowasu':'7/75/Gowasu_Render.png|20180602211354',
  'Jiren':'3/33/Jiren1.png|20170723224647',
  'Toppo':'8/87/Top.png|20180123150059',
  'Dyspo':'f/f4/Dyspoo.png|20170823113011',
  'Marcarita':'0/02/U11Angel.png|20170823155611',
  'Vermoud':'0/03/Belmod.png|20170823160402',
  'Caulifla':'6/6b/Caulif.png|20170721060144',
  'Kale':'d/df/Kale_01.png|20171227051452',
  'Kefla':'a/af/Kefla_01.png|20171105024801',
  'Gamma 1':'e/eb/Gamma_1_movie_profile.png|20220910033102',
  'Gamma 2':'d/df/Gamma_2_movie_profile.png|20220910033256',
  'Cheelai':'7/70/Cheelai_Artwork.png|20190204004112',
  'Gine':'a/a4/Gine_artwork_in_Extreme_Butoden.jpg|20170309081330'
};
// fotos da wiki que são recorte com fundo transparente (servem pra silhueta)
const WIKI_RENDER = new Set(['Gamma 1','Gamma 2','Champa','Cheelai','Cooler','Zamasu Fundido','Gowasu']);
const wikiUrl = nome => { const v = WIKI[nome]; if (!v) return ''; const [p, cb] = v.split('|'); return `${W}${p}/revision/latest/scale-to-width-down/400?cb=${cb}`; };

window.DB_CHARS = rows.map(r => {
  const api = r[11], wiki = wikiUrl(r[0]);
  return {
    nome:r[0], apelidos:r[1], raca:r[2], genero:r[3], afiliacao:r[4], estreia:r[5], saga:r[6],
    planeta:r[7], cabelo:r[8], transforma:r[9], poder:r[10],
    img: api || wiki,
    img2: api ? wiki : '',
    render: api ? true : WIKI_RENDER.has(r[0]),
    frase:r[12]
  };
});
})();
