/* ==========================================================
   Falas do Bugado no Termo (voz: ver VOZ.md na raiz).
   Variáveis: {palavra}, {letra}, {n}, preenchidas pelo jogo.
   O sorteio (Bugado.line) só repete depois de esgotar a categoria.
   ========================================================== */
window.FALAS_TERMO = {

/* ---------- chegada / retorno ---------- */
termoOi: [
  "bora de Termo. 5 letras, 6 chances e zero desculpa",
  "a palavra do dia tá escondida aí. eu sei qual é e não conto nem sob tortura",
  "hora de ver se cê sabe português ou só finge no grupo",
  "hoje a palavra é... quase que eu conto KKKKK joga aí",
  "verde é bom, amarelo é mais ou menos, cinza é vergonha",
  "6 chances parece muito né. confia, não é",
  "escondi uma palavra aqui. não é palavrão. acho",
  "estala os dedo e bora, o Termo não espera ninguém",
  "mais um dia, mais uma palavra pra cê passar raiva",
  "sem colar no Google hein, tô vendo tudo daqui",
  "palavra nova saindo do forno, cuidado que tá quente",
  "tá pronto? ninguém tá pronto pro Termo não, relaxa",
  "namoral, a de hoje tá boa. boa pra te humilhar",
  "e aí, vai de primeira hoje ou vai sofrer até a última linha?"
],
termoVoltou: [
  "voltou uai. achei que tinha fugido da palavra",
  "a palavra ficou aqui te esperando igual cachorro na porta",
  "salvei tudo, pode continuar de onde parou",
  "foi pensar lá fora né. não vale mas eu finjo que não vi",
  "voltou pra terminar o serviço, respeito",
  "teus chutes de antes tão aí te encarando ainda",
  "saiu pra pensar ou pra pesquisar? fala a verdade",
  "ó ele de volta. bora que a linha tá esperando",
  "a partida tava parada igual jogo com VAR. bora",
  "demorou hein, a palavra quase criou raiz"
],
termoDiarioFeito: [
  "o de hoje cê já matou. amanhã tem outro, hoje tem treino",
  "já acertou hoje mano, ficar olhando não dá XP não",
  "diário feito. printa e manda no grupo, ninguém vai entender mas manda",
  "a próxima palavra tá no forno, só amanhã",
  "voltou pra admirar a vitória né. entendo demais",
  "já foi, acabou, ganhou. volta amanhã",
  "voltou no diário resolvido? isso é saudade ou vaidade?",
  "quer mais? o treino é infinito, palavra nova toda hora",
  "ganhou hoje. guarda a energia pra amanhã ou gasta tudo no treino, cê que sabe",
  "tá feito. vai beber uma água que o Termo espera",
  "papo reto, o de hoje já era. amanhã tem mais",
  "diário no bolso. agora é treino e resenha"
],
termoDiarioPerdido: [
  "o diário de hoje... a gente não fala sobre o diário de hoje",
  "perdeu hoje, mas amanhã tem outra palavra pra te humilhar",
  "hoje não deu. o treino tá aí pra cê se vingar",
  "voltou na cena do crime? só tem cinza aqui",
  "a palavra ganhou hoje. amanhã tem revanche",
  "ainda de luto pelo diário? tá certo, eu também tô",
  "dicionário 1 x 0 você. volta amanhã e vira esse jogo",
  "perdeu o diário. bola pra frente, igual torcedor do Cruzeiro"
],

/* ---------- modos ---------- */
termoModoTermo: [
  "modo clássico. uma palavra, 6 chances, arroz com feijão",
  "Termo raiz. só cê, 5 letras e tua dignidade",
  "voltou pro básico. uma palavra só, menos coisa pra errar",
  "modo solo, não tem ninguém pra dividir a culpa",
  "o clássico nunca sai de moda, igual chinelo",
  "uma palavrinha só. fácil né? todo mundo fala isso no começo",
  "uma palavra, foco total. eu vou ficar quieto. vou nada",
  "Termo normal, pra quem gosta de sofrer em dose pequena"
],
termoModoDueto: [
  "Dueto: 2 palavras, 7 chances. cada chute vale pros dois quadros",
  "duas palavras e um cérebro só. boa sorte pro teu neurônio",
  "Dueto é igual dupla sertaneja, se um desafina o outro segura",
  "7 chances pra 2 palavras. a conta não tá do teu lado",
  "cada letra que cê digita vai pros dois quadros, aproveita",
  "Dueto ativado. vou comentar em dobro também",
  "olho no da esquerda, olho no da direita. fica vesgo mas ganha",
  "duas palavras escondidas e nenhuma é socorro. acho",
  "Dueto é o Termo de quem acha que o Termo tá fácil",
  "dois quadros, uma cabeça, zero paz"
],
termoModoQuarteto: [
  "QUARTETO. 4 palavras, 9 chances. cê é corajoso ou não leu direito?",
  "4 palavras de uma vez. isso é teste de sanidade mano",
  "Quarteto é onde os fortes choram e os fracos também",
  "9 chutes pra 4 palavras. sem pressão. muita pressão",
  "4 quadros. se errar, erra em 4 lugares. eficiência",
  "teu cérebro acabou de pedir demissão",
  "Quarteto! vou torcer calado. vou nada, vou gritar",
  "modo difícil. não tem voltar no tempo, só chorar",
  "isso aqui é mais apertado que o 330 às 18h",
  "4 palavras, nem o Duolingo te preparou pra isso"
],
termoTreino: [
  "treino: palavra aleatória e sem ranking. erra à vontade",
  "treino infinito. ninguém vê teus erros, só eu. e eu conto pra geral",
  "treino é academia de palavra, só que cê não sua. ou sua",
  "palavra nova sorteada. eu sei qual é, óbvio",
  "aqui a sequência não quebra. o ego sim",
  "palavra fresquinha saindo agora",
  "treinando pro diário de amanhã? gosto da dedicação",
  "mais uma! mais uma! (sou eu na arquibancada)",
  "sorteei outra. tem cara de difícil. ou de fácil. tem cara de palavra",
  "treino não vale ranking mas vale XP. farma aí",
  "próxima! cê tá viciado né. continua",
  "bora de treino, errar aqui é de graça"
],
termoNovaPalavra: [
  "desistiu dessa? era <b>{palavra}</b>, tava na tua cara",
  "pulou a palavra e ela ficou ofendida. era <b>{palavra}</b>",
  "trocou no meio? virou o tabuleiro KKKKK era <b>{palavra}</b>",
  "largou pra trás. só pra constar, era <b>{palavra}</b>",
  "fugiu da <b>{palavra}</b>. entendo, ela era meio assustadora",
  "desistência registrada. a resposta era <b>{palavra}</b>",
  "ok, próxima. era <b>{palavra}</b>, nem era tão difícil",
  "abandonou <b>{palavra}</b> no meio da rua, coitada"
],

/* ---------- primeiro chute ---------- */
termoAbertura: [
  "<b>{palavra}</b>? todo mundo começa com <b>{palavra}</b> mano",
  "abriu com <b>{palavra}</b>. clássico e previsível",
  "<b>{palavra}</b>? leu isso num tutorial né, fala",
  "<b>{palavra}</b> é a abertura do povo. tá tudo bem ser do povo",
  "eu sabia que vinha <b>{palavra}</b>, ganhei uma aposta comigo mesmo",
  "começou com <b>{palavra}</b>, junto com metade da internet",
  "<b>{palavra}</b>: abertura de quem pesquisou melhor palavra pra começar",
  "abrir com <b>{palavra}</b> é pedir frango no restaurante, seguro e sem emoção",
  "<b>{palavra}</b> pra caçar vogal. sem graça mas funciona",
  "cê é do time <b>{palavra}</b>. julgado e arquivado",
  "<b>{palavra}</b> de primeira. tanta vogal que parece um grito",
  "lá vem o <b>{palavra}</b>, nem sei pq ainda me surpreendo",
  "<b>{palavra}</b>: jogada de manual. o manual agradece",
  "o Brasil inteiro abre com <b>{palavra}</b>, cê não é especial não KKKK",
  "<b>{palavra}</b>? jogou no seguro igual técnico retranqueiro"
],
termoAberturaDeNovo: [
  "<b>{palavra}</b> DE NOVO? cê tem um relacionamento sério com essa palavra",
  "mesma abertura da última vez: <b>{palavra}</b>. constância ou preguiça?",
  "<b>{palavra}</b> outra vez. é a única palavra que cê conhece?",
  "<b>{palavra}</b>, <b>{palavra}</b>, <b>{palavra}</b>. faz logo uma tatuagem",
  "repetiu <b>{palavra}</b>. fiel demais, respeito",
  "eu apostava que era <b>{palavra}</b> e ganhava fácil",
  "<b>{palavra}</b> de novo. se fosse gente já tinha pedido medida protetiva",
  "tradição é tradição: <b>{palavra}</b> na abertura, igual pão de queijo no café"
],
termoPrimeiro: [
  "primeiro chute: <b>{palavra}</b>. ousado, bora ver no que dá",
  "abriu com <b>{palavra}</b>. eu não faria isso, mas eu sou um gato fantasma né",
  "<b>{palavra}</b> pra começar? intuição ou chute puro?",
  "<b>{palavra}</b>? diferentão. gostei",
  "começou com <b>{palavra}</b>. isso diz muito sobre você, só não sei o quê",
  "<b>{palavra}</b> na abertura. hipster do Termo",
  "primeiro tiro no escuro. tá vivo?",
  "chute inicial feito. agora a coisa fica séria",
  "<b>{palavra}</b>? escolha estranha, vou guardar essa",
  "primeira linha. tudo é possível, inclusive perder",
  "começar com <b>{palavra}</b> foi coragem",
  "ninguém começa com <b>{palavra}</b>. cê começou. pioneiro",
  "agora olha as cores e finge que entendeu",
  "abriu. agora é ler as cores igual cartomante",
  "<b>{palavra}</b> de abertura, sem medo de ser feliz"
],

/* ---------- resultado do chute ---------- */
termoZero: [
  "nada. zero letra. pelo menos agora cê sabe o que ela não é",
  "tudo cinza, parece segunda de manhã",
  "5 letras e nenhuma serviu. isso é quase um talento",
  "zero acerto, mas cortou 5 letras do teclado. vai",
  "a palavra olhou teu chute e falou não te conheço",
  "cinza total, igual meu humor depois de derrota do Cruzeiro",
  "errou as 5. estatisticamente bizarro",
  "chute mais honesto do dia: não sabia nada e provou",
  "nada, nadinha. mas informação é informação",
  "5 cinzas. podia ser pior, não sei como mas podia",
  "zero pro chute, dez pra coragem",
  "se fosse bingo cê nem tinha cartela",
  "nem uma letrinha KKKKKK a palavra tá rindo",
  "tudo cinza. sobraram só umas 20 letras, moleza",
  "totalmente errado e totalmente útil, vai entender",
  "nenhum acerto. o cinza ensina humildade",
  "mds, zero. apagou geral",
  "chute limpinho, nada grudou"
],
termoSoAmarelo: [
  "umas amarelas. as letras tão lá, só não onde cê botou",
  "amarelo é o quase do Termo e cê é o rei do quase",
  "letra certa no lugar errado, tipo você em festa",
  "amarelinhas! agora é só mudar de lugar. parece fácil",
  "tá morno, igual café esquecido na mesa",
  "acertou a letra e errou o endereço. correios feelings",
  "{n} no amarelo e nenhuma verde. tá chegando devagar igual Move de domingo",
  "as letras tão lá dentro, agora é jogar Tetris com elas",
  "tudo amarelo e nada verde, semáforo indeciso",
  "pista boa. só não bota as amarelas no mesmo lugar pelo amor",
  "letra certa, lugar errado. história da minha vida",
  "amarelo é progresso. tímido mas é",
  "troca as amarelas de posição e vê o que acontece",
  "tem coisa aí! verde ainda não, mas tem",
  "{n} letra no amarelo, bora arrumar a casa"
],
termoVerde1: [
  "uma verde! uma! comemora baixinho pra não assustar",
  "uma no lugar certo. pouco mas honesto",
  "um verdinho, tipo feijão no algodão. vai crescer",
  "achou uma, faltam 4. conta fácil, execução difícil",
  "um verde sozinho ali, arruma companhia pra ele",
  "uma letra fixada, começo de uma bela amizade",
  "verde! um só mas é verde, não desperdiça",
  "uma no alvo, agora é paciência",
  "primeira peça do quebra-cabeça",
  "uma verde. nem bom nem ruim, neutro igual Suíça",
  "protege essa verde igual o último pão de queijo",
  "um verde. o caminho é longo mas tem caminho",
  "1 verde. já é mais que o ataque do Cruzeiro em alguns jogos",
  "uma cravada, bora pras outras"
],
termoVerde2: [
  "duas verdes, tá esquentando",
  "2 verdes! ficando interessante",
  "duas no lugar, já dá pra sentir o cheiro da palavra",
  "quase metade. quase, não arredonda não",
  "dois acertos em cheio, tô começando a acreditar em você",
  "duas cravadas. agora completa sem inventar moda",
  "dupla dinâmica, falta o resto da Liga da Justiça",
  "duas certas. pegou o jeito ou foi sorte? aceito os dois",
  "2 verdes, mas ainda tem muita palavra que encaixa. calma",
  "continua que tá bonito",
  "o esqueleto da palavra tá aparecendo",
  "meio caminho andado. ou quase isso",
  "dois verdinhos, parece bandeira de time. torce aí",
  "esquentando igual pastel saindo da fritura"
],
termoVerde3: [
  "3 verdes! agora é só não fazer besteira. sei que é pedir muito",
  "três certinhas, a palavra tá quase pelada",
  "3 de 5! tá quente, tá quente, TÁ QUENTE",
  "três verdes, já dá pra ver o formato. pensa",
  "3 no lugar e eu tô nervoso. cê tá nervoso? eu tô",
  "cuidado que tem umas 500 palavras que terminam igual",
  "3 verdes e o coração a mil",
  "faltam 2 letras. DUAS. dá pra sentir o gosto",
  "o dicionário começou a suar",
  "olha isso, 3 verdes. tô quase orgulhoso",
  "agora é pensar antes de digitar, tenta aí",
  "tão perto que dá pra ouvir a palavra respirando",
  "mais um pouquinho e eu solto o confete",
  "3 já foram, faltam 2. cê sabe quais?"
],
termoVerde4: [
  "QUATRO VERDES. falta UMA. não me faz passar vergonha",
  "4! só falta uma, começa a roleta russa",
  "4 verdes e aquela dúvida cruel, era essa ou aquela",
  "cara de armadilha. 4 certas e mil opções pra última",
  "uma letra entre você e a glória. escolhe bem",
  "4 verdes, tô roendo a unha. nem tenho unha",
  "falta UMA. pensa em todas as palavras, rápido",
  "se errar agora eu finjo que não te conheço",
  "a quinta tá ali escondidinha rindo da tua cara",
  "quase! a quinta tá fazendo charme",
  "uma letra de distância, o Termo testando teu coração",
  "4 de 5. hora de pensar e não sair chutando",
  "olha o teclado e vê as letras que sobraram",
  "TÃO perto mds. se não acertar eu choro",
  "só não cai na armadilha do _ARRO, todo mundo cai"
],
termoAnagrama: [
  "todas as letras certas, só a ordem que tá bagunçada. tipo meu quarto",
  "5 letras certas e ordem errada. embaralha aí",
  "cê tem todas as peças, agora monta o Lego",
  "tá tudo aí dentro, só não tá onde devia",
  "acertou os ingredientes e errou a receita",
  "todas na palavra, agora é dança das cadeiras",
  "as letras são essas. troca de lugar e corre pro abraço",
  "anagrama! embaralha igual carta de truco",
  "letra 100%, posição nem tanto",
  "tá tudo aí, é só organizar igual gaveta de meia"
],
termoPiorou: [
  "esse foi pior que o anterior. evolução ao contrário",
  "menos verde que antes. tá andando de ré?",
  "piorou. foi pra testar letra nova né? fala que foi",
  "tinha mais verde antes, saudade daquele chute",
  "chute de exploração. exploração do fracasso KKKKK",
  "o anterior tava melhor, só falando",
  "andou pra trás igual caranguejo",
  "caiu de produção igual time nosso no segundo tempo"
],

/* ---------- vacilos de lógica ---------- */
termoCinza: [
  "usou o <b>{letra}</b> que já tava cinza. pra ter certeza?",
  "<b>{letra}</b> de novo? ele já falou que não tá. respeita o não do {letra}",
  "o <b>{letra}</b> é cinza. foi cinza, é cinza, vai morrer cinza",
  "olha o teclado, o <b>{letra}</b> tá apagadinho. apagado é NÃO",
  "reciclando letra cinza? ecológico mas inútil, né <b>{letra}</b>",
  "cê insistiu no <b>{letra}</b>. ele agradece mas continua fora",
  "o <b>{letra}</b> já tinha sido eliminado e cê ressuscitou ele",
  "letra cinza repetida: <b>{letra}</b>. chute gasto com amor",
  "usando o <b>{letra}</b> por nostalgia? pq por lógica não é",
  "geral viu esse <b>{letra}</b>. o teclado viu. vergonha coletiva",
  "o <b>{letra}</b> é tipo ex: cê sabe que não dá e volta",
  "botou o <b>{letra}</b> queimado. achou que o jogo mudou de ideia?",
  "o <b>{letra}</b> não vai ficar verde por insistência não",
  "às vezes letra cinza serve pra testar as outras. foi isso, <b>{letra}</b>?",
  "teimoso ou estrategista com esse <b>{letra}</b>? aposto em teimoso",
  "não quero apontar nada mas... <b>{letra}</b>. cinza. cê já sabia",
  "tecla cinza é tecla morta. cê chutou um cadáver, o <b>{letra}</b>",
  "<b>{letra}</b> de novo mano? tá maluco"
],
termoIgnorouVerde: [
  "tinha um <b>{letra}</b> verde ali e cê simplesmente tirou. pq?",
  "abandonou o <b>{letra}</b> verde? ele tava tão feliz no lugar dele",
  "o <b>{letra}</b> tava certinho e cê trocou. ousadia ou esquecimento?",
  "verde não se mexe! deixa o <b>{letra}</b> lá",
  "largou letra verde pra testar outra coisa. modo difícil ao contrário",
  "tirou o <b>{letra}</b> do lugar certo, tô magoado",
  "chutou sem o <b>{letra}</b> verde. vou fingir que foi plano",
  "esqueceu do <b>{letra}</b> que já tava cravado",
  "cadê o <b>{letra}</b>? era verde! verde é sagrado",
  "tirou o <b>{letra}</b> verde. isso é tirar o goleiro no pênalti"
],
termoAmareloTeimoso: [
  "botou o <b>{letra}</b> onde ele já deu amarelo. não vira verde por pena",
  "o <b>{letra}</b> já falou que não é nessa casa. muda ele",
  "amarelo no mesmo lugar de novo? o <b>{letra}</b> cansou de avisar",
  "o <b>{letra}</b> ali já foi testado. deu amarelo e vai dar amarelo",
  "teimou com o <b>{letra}</b> no mesmo lugar, continua não sendo ali",
  "o <b>{letra}</b> tá na palavra mas NÃO ali. essa dica foi de graça",
  "mesma letra, mesmo lugar, mesmo amarelo. cê tá bem?",
  "o <b>{letra}</b> tá gritando me muda de lugar. escuta ele",
  "botou o <b>{letra}</b> onde ele já falhou. esperando milagre?",
  "amarelo é pra mudar de lugar, não pra fazer ninho. sai daí <b>{letra}</b>"
],
termoIgnorouAmarelo: [
  "cadê o <b>{letra}</b>? ele era amarelo, ele TÁ na palavra",
  "deixou o <b>{letra}</b> de fora, ele vai voltar pra te assombrar",
  "esqueceu o <b>{letra}</b>. letra amarela existe mano",
  "o <b>{letra}</b> tá na palavra e cê fingiu que não. avestruz",
  "chutou sem o <b>{letra}</b> amarelo. gênio ou esquecido? aposto no segundo",
  "o <b>{letra}</b> ficou de fora da festa e ele tava convidado",
  "o <b>{letra}</b> não some só pq cê não olha pra ele",
  "faltou o <b>{letra}</b>. a palavra PRECISA dele"
],

/* ---------- chute recusado ---------- */
termoInvalida: [
  "<b>{palavra}</b>? essa aí cê inventou agora né",
  "<b>{palavra}</b> é palavra em qual idioma? élfico?",
  "não conheço <b>{palavra}</b>. o dicionário também não",
  "<b>{palavra}</b> não existe, mas vai pro meu caderninho de invenções suas",
  "bonita essa, pena que não existe",
  "<b>{palavra}</b> parece nome de remédio. palavra não é",
  "palavra inválida. tentativa não gasta, a dignidade um pouco",
  "isso aí é nome de Pokémon? pq palavra não é",
  "<b>{palavra}</b> ainda não existe. manda email pra Academia de Letras",
  "procurei <b>{palavra}</b> em tudo quanto é lugar. nada",
  "tem 5 letras, tem cara de palavra, mas não é",
  "<b>{palavra}</b>? bateu a cabeça no teclado?",
  "não vale inventar, isso aqui não é batalha de rima",
  "<b>{palavra}</b> não passou no controle de qualidade",
  "essa não existe nem na gíria do teu primo",
  "<b>{palavra}</b> não é palavra. tenta outra que essa não conta",
  "até queria aceitar <b>{palavra}</b>, mas tenho princípios. poucos",
  "<b>{palavra}</b> é o barulho que eu faço quando tropeço",
  "isso foi chute ou espirro no teclado?",
  "<b>{palavra}</b>... não. só não",
  "até o corretor do celular ia rir dessa KKKKK",
  "criatividade 10, existência 0",
  "<b>{palavra}</b>? palavra de outro universo, aqui não rola",
  "invalidíssima. tenta uma do dicionário vai",
  "<b>{palavra}</b> não, mano. nem o Google conhece isso",
  "que isso <b>{palavra}</b> KKKKKKK inventou com força"
],
termoInvalidaDeNovo: [
  "mais uma inventada. tá criando idioma novo?",
  "segunda seguida que não existe. testando meu dicionário ou minha paciência?",
  "cê tá digitando de olho fechado? pode abrir",
  "outra inválida. não tô contando. tô sim",
  "chutando letra aleatória pra ver se dá sorte? não funciona assim",
  "de novo não existe. pensa numa palavra de verdade, tipo bolo. tem 4 letras mas pensa",
  "mais uma pro museu das palavras que nunca existiram",
  "vou começar a cobrar taxa por palavra inventada"
],
termoCurta: [
  "5 letras. CINCO. conta nos dedos",
  "faltou letra, é 5 e não mais ou menos 5",
  "palavra pela metade não vale",
  "tá faltando letra aí chefe",
  "isso tem menos de 5 letras, eu sei contar",
  "completa a palavra primeiro, pressa é inimiga do verde",
  "apertou ENTER cedo demais, ansiedade é fogo",
  "menos de 5 não vai, nem com jeitinho",
  "mandou com buraco, isso não é queijo suíço",
  "tem quadradinho vazio aí, ele tá triste",
  "4 letras? isso é outro jogo, aqui é 5",
  "calma, termina de escrever que eu espero"
],
termoRepetida: [
  "cê já chutou <b>{palavra}</b>. a resposta não mudou não",
  "<b>{palavra}</b> de novo? a cor vai ser a mesma, prometo",
  "chute repetido, o jogo não aceita reprise",
  "déjà vu! <b>{palavra}</b> já foi. eu lembro de TUDO",
  "mesma palavra duas vezes? tá testando se eu presto atenção?",
  "<b>{palavra}</b> já foi, não gasta tentativa com reprise",
  "reprise da Sessão da Tarde, já vimos <b>{palavra}</b>",
  "cê chutou <b>{palavra}</b> agorinha. a memória tá boa?",
  "repetir chute não conta nem ajuda. e me preocupa",
  "olha pra cima: <b>{palavra}</b> tá lá. já tentou"
],

/* ---------- detalhes do chute ---------- */
termoAcento: [
  "botei o acento pra você: <b>{palavra}</b>",
  "viu? não precisa digitar acento, eu cuido disso",
  "<b>{palavra}</b> com acento e tudo, serviço completo",
  "<b>{palavra}</b>, acentuada. a professora de português ia gostar",
  "cê digitou sem acento e eu arrumei. somos um time. eu trabalho mais, mas somos",
  "olha que chique: <b>{palavra}</b> com acentinho, de graça",
  "acento é por minha conta, o resto é contigo",
  "<b>{palavra}</b> ficou mais bonita com acento né",
  "til, agudo, cedilha, eu boto tudo. cê só digita",
  "arrumei a grafia: <b>{palavra}</b>. pode agradecer",
  "aqui C vale Ç e A vale Ã, democracia das letras",
  "acento automático, pode digitar igual no zap"
],
termoVogais: [
  "chute cheio de vogal, caçando vogal igual Pokémon",
  "4 vogais? isso não é palavra, é um grito",
  "muita vogal nesse chute. quem ama A E I O U",
  "vogal, vogal, vogal. tá fazendo aquecimento vocal?",
  "mais vogal que consoante, parece nome de filho de famoso",
  "varreu as vogais, agora pelo menos cê sabe quais tem",
  "AEIOU feelings. útil, admito",
  "essa palavra é praticamente só vogal, tá cantando"
],
termoLetraDupla: [
  "letra repetida no chute. arriscado, mas às vezes a palavra tem mesmo",
  "duas letras iguais. cê sabe algo que eu não sei?",
  "chutou com letra dobrada, economia de alfabeto",
  "letra repetida é pedir dois pastel do mesmo sabor. às vezes funciona",
  "repetir letra é ousado. às vezes genial, às vezes desperdício",
  "investigando letra repetida? detetive",
  "se a palavra também tiver letra dobrada cê é bruxo",
  "letra em dobro, menos letra nova testada. mas quem sou eu pra julgar. eu julgo"
],
termoPalavrao: [
  "olha a boca! tem criança jogando. tem eu, que sou uma criança emocional",
  "palavrão de chute? tá descontando a raiva no Termo né",
  "vou fingir que não li <b>{palavra}</b>",
  "chutou <b>{palavra}</b>. vou contar pra tua mãe",
  "é palavra de verdade mas não é palavra de gente educada",
  "<b>{palavra}</b> KKKKKKK o desespero chegou nesse nível já",
  "válida mas feia, tipo meu desenho de gato",
  "tá xingando ou chutando? os dois, eficiente"
],
termoMeta: [
  "chutou TERMO no Termo. tô sem palavras e eu sou um jogo de palavras",
  "TERMO no jogo Termo? isso é pedir água na piscina",
  "chutou o nome do jogo. achou que ia ser fácil assim? às vezes é",
  "TERMO. o jogo agradece a homenagem, a palavra nem tanto"
],
termoCursor: [
  "sabia que dá pra clicar no quadradinho e escrever direto nele? agora sabe",
  "mudou o cursor de lugar. usuário avançado",
  "clicando nos quadradinhos, pro player",
  "pulando de casa em casa igual amarelinha",
  "cursor movido, agora escreve ali",
  "editando no meio da palavra, cirurgião de letra"
],
termoUltima: [
  "última tentativa. respira ou chora, os dois valem",
  "é agora ou nunca. na real é agora ou amanhã, mas soa menos dramático",
  "última chance. sem pressão. MUITA pressão",
  "última linha, olha o teclado e digita com fé",
  "hora da verdade. tô tampando os olhos mas tô espiando",
  "uma chance só. se errar a gente fala que foi falha técnica",
  "última! pensa em TODAS que encaixam e escolhe a melhor",
  "último chute, imagina uma música de suspense",
  "tudo ou nada, faz valer",
  "pênalti aos 49 do segundo tempo. bate firme",
  "fim da linha chegando, é a última linha mesmo",
  "acredito em você. uns 60%. vai lá",
  "nada de chute aleatório agora hein",
  "coração na mão e dedo no teclado"
],

/* ---------- dueto / quarteto ---------- */
termoQuadroResolvido: [
  "<b>{palavra}</b> resolvida! faltam {n}",
  "um quadro fechado, <b>{palavra}</b> no papo. bora pra próxima",
  "<b>{palavra}</b>! verdinha. foca nas outras {n}",
  "caiu uma! <b>{palavra}</b>. as outras {n} tão tremendo",
  "resolveu <b>{palavra}</b>. vitória pequena numa guerra grande",
  "olha aí, <b>{palavra}</b>! risca da lista, faltam {n}",
  "menos uma. <b>{palavra}</b> era a mais fácil? espero que não",
  "acertou <b>{palavra}</b>, quadro verdinho. próximo",
  "<b>{palavra}</b> fechada, não perde o ritmo",
  "uma já foi: <b>{palavra}</b>. continua que tá indo",
  "<b>{palavra}</b> dominada. faltam {n}, força",
  "<b>{palavra}</b>! guarda essa energia pras outras",
  "pegou <b>{palavra}</b>. as outras tão com ciúme",
  "<b>{palavra}</b> check. próxima vítima",
  "AÍ SIM <b>{palavra}</b>! um quadro a menos"
],
termoDuetoJogada: [
  "olha os dois quadros. um ajuda o outro. às vezes atrapalha, igual irmão",
  "chute bom pra um e ruim pro outro. vida de dueto",
  "pensa num chute que sirva pros dois. difícil? sim",
  "um quadro te olha com esperança e o outro com pena",
  "no dueto, letra cinza nos dois é ouro, sabia?",
  "esse chute foi pro da esquerda ou da direita? acho que foi pro nada",
  "dueto é xadrez de palavra. cê tá jogando dama mas tá jogando",
  "um esquentando e o outro congelado",
  "olha o teclado dividido, metade de cada palavra. usa isso",
  "tá indo. devagar, mas no dueto é normal",
  "cada chute tem que trabalhar dobrado, tipo você na segunda",
  "dueto é isso aí, dois problema pelo preço de um"
],
termoQuartetoJogada: [
  "4 quadros, 1 chute. algum gostou",
  "no quarteto qualquer amarelo é festa",
  "olha os 4, um deles tá mais perto. foca nele",
  "esse chute espalhou pista pra todo lado, agora junta",
  "quarteto é maratona, respira",
  "o teclado tá parecendo arte moderna. isso é bom. acho",
  "resolve um de cada vez. ou todos. eu não mando em você",
  "4 palavras te encarando, não pisca",
  "sobrando tentativa? nunca sobra no quarteto",
  "chute de reconhecimento, os 4 agradecem",
  "cada tecla mostra as 4 palavras de uma vez, aproveita",
  "parece impossível até que do nada cai tudo"
],

/* ---------- vitória ---------- */
termoGanhou1: [
  "DE PRIMEIRA?? MDSSSS QUE ISSO",
  "acertou de primeira. tô com os pixel arrepiado",
  "primeira tentativa. isso é bruxaria e eu respeito",
  "DE CARA! printa e manda no grupo AGORA",
  "um chute, uma palavra, uma lenda",
  "de primeira e eu nem tive tempo de zoar. que desaforo",
  "sorte absurda, sorte que devia ser proibida. parabéns",
  "de primeira? cê olhou o código né KKKKKK"
],
termoGanhou2: [
  "em DUAS? tá maluco, nível profissional",
  "duas tentativas, eu mal aqueci as piadas",
  "acertou na segunda. Sherlock de chinelo",
  "em 2! pode ir no grupo se gabar, eu deixo",
  "segunda tentativa. não tô chorando, é bug no olho",
  "em duas. cê tem um dicionário no lugar do cérebro?",
  "dois chutes, precisão de cirurgião",
  "na segunda! vai direto pro meu mural",
  "duas e já era. tá perigoso te deixar jogar",
  "segunda! arrasou. só não deixa subir pra cabeça"
],
termoGanhou3: [
  "em 3! muito bom, sem ironia. estranho né",
  "terceira tentativa, rápido e limpo",
  "3 chutes, coisa de quem sabe o que tá fazendo",
  "na terceira, nota 9. o 1 que falta é pq eu sou exigente",
  "3! acima da média. da minha pelo menos",
  "o dicionário se curvou pra você",
  "3 tentativas, pode botar no currículo",
  "terceira! isso foi bonito de ver",
  "em 3. tô impressionado e eu sou difícil de impressionar",
  "3 e pronto, sem drama. eu adoro drama mas beleza"
],
termoGanhou4: [
  "na quarta! sólido, feijão com arroz da vitória",
  "4 tentativas, nem mais nem menos",
  "acertou na quarta. tava suando né, eu vi",
  "quarta! não é recorde mas vitória é vitória",
  "4 chutes, a média nacional agradece",
  "na quarta. honesto e trabalhador, merece um café",
  "deu uma enrolada mas chegou",
  "nem herói nem vilão, só vencedor",
  "ninguém lembra quantas foram. eu lembro: 4",
  "quarta tentativa, garantiu. pode respirar"
],
termoGanhou5: [
  "na quinta! meu coração digital quase deu tela azul",
  "quinta tentativa, sofrido igual final de campeonato",
  "acertou na quinta. dramático, gosto",
  "5 chutes, suado mas valeu. bebe uma água",
  "na quinta! deu frio na barriga né",
  "cê gosta de viver no limite né",
  "chegou na quinta, devagar e sempre",
  "eu já tava preparando o discurso de consolo. guardei",
  "ufa, na quinta. tava roendo o fio do mouse",
  "vitória com cheirinho de desespero, o melhor tipo"
],
termoGanhou6: [
  "NA ÚLTIMA! aos 49 do segundo tempo! QUE ISSOOOO",
  "sexta tentativa. cê gosta de sofrer, mas ganhou. perdoado",
  "no último suspiro, isso foi cinema",
  "acertou na sexta, meu coração quase saiu pela orelha",
  "última chance e ACERTOUUUU. os vizinhos tão reclamando",
  "na raça, na sexta! isso é garra. e sorte",
  "sexta tentativa, quase travei de emoção",
  "tipo pagar boleto no último dia. mas pagou",
  "na última! se fosse filme tinha câmera lenta agora",
  "VAMOOOOO na sexta mds, gol no último lance"
],
duetoGanhou: [
  "DUETO RESOLVIDO em {n}! as duas caíram",
  "as duas em {n} tentativas. dupla perfeita: você e você",
  "dueto vencido, {n} chutes pra duas palavras",
  "duas palavras em {n}. tô sem piada, tô com orgulho",
  "resolveu o dueto em {n}! tua cabeça tem dois processadores?",
  "dueto no papo em {n}. não é pra qualquer um não",
  "{n} tentativas e as duas dominadas. que isso mano",
  "os dois quadros verdinhos, coisa linda",
  "duas de duas em {n} chutes",
  "duplo verde, dupla alegria e eu comemorando em dobro",
  "resolveu as duas em {n}! o dicionário pediu arrego",
  "dueto conquistado. agora tenta o quarteto se tiver coragem"
],
quartetoGanhou: [
  "QUARTETO RESOLVIDO em {n}! gênio ou maluco? os dois",
  "as QUATRO em {n}! tô de pé aplaudindo",
  "quarteto vencido, cê é uma máquina de palavra",
  "4 palavras em {n} chutes, vai pro hall da fama",
  "zerou o quarteto! MDSSSS",
  "quarteto limpo em {n}. devia cobrar ingresso pra ver você jogar",
  "4 de 4! grand slam do Termo",
  "resolveu o quarteto, teu cérebro merece férias. ou um pastel",
  "{n} tentativas e o quarteto caiu. os 4 quadros te respeitam agora",
  "QUARTETO! cê é um dicionário com perna",
  "venceu as quatro. eu nunca duvidei. duvidei muito",
  "quarteto zerado, pode botar na bio"
],
termoGanhouLimite: [
  "na última tentativa! resolveu tudo aos 49 do segundo tempo",
  "usou TODAS as chances e ganhou, aproveitou até o último centavo",
  "no limite do limite, meu coração de pixel quase explodiu",
  "última linha, última chance, vitória. filme de ação",
  "ganhou no sufoco, e no sufoco tem mais gosto",
  "eu já tava escrevendo o obituário. apaguei",
  "venceu com zero tentativa sobrando, emoção máxima",
  "no último chute! se fosse corrida ganhou na foto"
],

/* ---------- derrota ---------- */
termoPerdeu: [
  "era <b>{palavra}</b>. dói, deixa doer",
  "a palavra era <b>{palavra}</b>, tava ali o tempo todo rindo",
  "não deu. <b>{palavra}</b> ganhou hoje, amanhã tem revanche",
  "<b>{palavra}</b>. às vezes a palavra ganha",
  "perdeu. era <b>{palavra}</b>. perdeu normal, sem drama",
  "era <b>{palavra}</b>! como cê não pensou nisso? eu pensei. eu já sabia, mas pensei",
  "<b>{palavra}</b>. guarda essa palavra e vinga ela depois",
  "fim de jogo, era <b>{palavra}</b>. minuto de silêncio",
  "game over, <b>{palavra}</b> humilhou mais um",
  "era <b>{palavra}</b>. eu também teria errado. teria nada",
  "a secreta era <b>{palavra}</b>. agora não é mais secreta",
  "não rolou. <b>{palavra}</b>, anota no caderninho das traiçoeiras",
  "perdeu pra <b>{palavra}</b>. não é vergonha. é um pouquinho",
  "<b>{palavra}</b>! era tão óbvio. sempre é óbvio depois",
  "ai, era <b>{palavra}</b>. quer um abraço? sou fantasma, vai ser gelado",
  "6 chances e nada. era <b>{palavra}</b>",
  "<b>{palavra}</b> ganhou essa, mas a guerra continua",
  "deu ruim. era <b>{palavra}</b>. faz parte, no teu caso faz muita parte KKKKK",
  "resposta: <b>{palavra}</b>. palavra 1 x 0 você",
  "era <b>{palavra}</b>. perdeu igual time grande em casa, com a torcida olhando"
],
duetoPerdeu: [
  "dueto perdido, faltou <b>{palavra}</b>. duas palavras é muita coisa pra uma cabeça",
  "não fechou o dueto. <b>{palavra}</b> escapou",
  "faltou <b>{palavra}</b>. quase! quase no dueto é meio sanduíche",
  "dueto 1 x 0 você. faltou <b>{palavra}</b>",
  "7 tentativas não bastaram. <b>{palavra}</b> fugiu pelos fundos",
  "perdeu o dueto, era <b>{palavra}</b>. dueto é difícil, relaxa",
  "quem te venceu foi <b>{palavra}</b>. a outra tá rindo junto",
  "faltou <b>{palavra}</b>. treina e volta, o dueto não vai sair daqui"
],
quartetoPerdeu: [
  "quarteto perdido, faltou <b>{palavra}</b>. 4 palavras é covardia, eu sei",
  "não fechou o quarteto, escapou <b>{palavra}</b>. respeito quem tenta",
  "o quarteto venceu. faltou <b>{palavra}</b>, ninguém sai ileso",
  "9 tentativas e ainda sobrou <b>{palavra}</b>. o quarteto é um monstro",
  "perdeu o quarteto mas ganhou experiência. e trauma. faltou <b>{palavra}</b>",
  "quarteto 1 x 0 você. ficou faltando <b>{palavra}</b>",
  "quase! faltou <b>{palavra}</b>. quase no quarteto já é muito",
  "ninguém zera o quarteto sempre, hoje faltou <b>{palavra}</b>"
],

/* ---------- pós-jogo ---------- */
termoSequencia: [
  "{n} dias seguidos acertando. tá viciado ou tá bom? os dois",
  "sequência de {n}! não quebra hein, tô contando",
  "{n} vitórias seguidas. disciplina ou falta do que fazer",
  "sequência de {n}. se quebrar eu faço drama",
  "mais uma pra conta, {n} seguidas. ficando lendário",
  "{n} seguidas! o dicionário tá com medo de você",
  "{n} dias sem errar mano, placa na parede",
  "sequência {n}, virou rotina. rotina boa",
  "{n} seguidas. tô achando que cê tem o gabarito",
  "{n} dias seguidos, mais constante que o Duolingo me cobrando"
],
termoSequenciaPerdida: [
  "sequência de {n} quebrada. ouvi o crec daqui",
  "foi-se a sequência de {n}. minuto de silêncio",
  "adeus sequência de {n}, cê foi linda",
  "perdeu a sequência de {n}. dói mais que perder o diário",
  "eram {n}, agora é zero. matemática cruel",
  "{n} dias de glória e agora recomeço",
  "quebrou a sequência de {n}. igual ofensiva do Duolingo, dói na alma",
  "descansa em paz sequência de {n}"
],
termoRapido: [
  "resolveu em {n} segundos. calma velocista",
  "rapidinho hein, {n} segundos. nem deu tempo de eu zoar",
  "{n} segundos! speedrun de Termo",
  "tão rápido que achei que era bug",
  "nem piscou, {n} segundos. treinando pra olimpíada?",
  "eu ainda tava carregando a primeira piada",
  "rápido demais. suspeito. parabéns, mas suspeito",
  "{n} segundos. eu demoro mais pra decidir o que falar"
],
termoDemorou: [
  "levou {n} minutos mas chegou",
  "{n} minutos! fez pausa pro almoço no meio?",
  "demorou 700 séculos mas foi",
  "{n} minutos pensando, eu envelheci aqui",
  "{n} minutos, uma novela inteira",
  "acertou depois de {n} minutos, pensamento profundo",
  "{n} minutos, isso foi uma temporada",
  "{n} minutos, mais demorado que o 330 no horário de pico"
],
termoCompartilhou: [
  "copiado! cola no grupo e espera ninguém entender os quadradinho",
  "copiado, manda praquele amigo que se acha bom no Termo",
  "tá copiado. vai lá ostentar",
  "copiado! se perguntarem fala que foi fácil",
  "copiei, os quadradinhos tão prontos pra humilhar alguém",
  "copiado. manda o resultado, a palavra não hein"
],
termoStats: [
  "olhando as estatística? vaidade detectada",
  "teus números. eu já tinha visto, sem comentários. comento: interessante",
  "estatística é tipo espelho, às vezes melhor não olhar",
  "os números tão aí. bonitos? honestos pelo menos",
  "conferindo a sequência né, eu vi",
  "gráfico de barra! parece prédio"
],
termoAjuda: [
  "precisa de ajuda? normal, todo mundo precisa",
  "regras abertas. lê com calma, a prova é o jogo",
  "manual de instrução, o documento mais ignorado do mundo",
  "leu? beleza, agora esquece e joga no instinto",
  "fui eu que escrevi essas regras. com erro. não vou corrigir",
  "se ainda tiver dúvida me cutuca. não ajuda mas cutuca"
],

/* ---------- parado ---------- */
termoParadoMeio: [
  "parou no meio da palavra? esqueceu o resto?",
  "tem letra digitada e mais nada. esperando inspiração?",
  "metade da palavra tá aí, a outra metade tá na tua cabeça",
  "travou no meio. normal, cérebro também tem tela de carregamento",
  "as letras que cê digitou tão esperando as amiguinhas",
  "tá com medo? chuta. palavra inválida não gasta tentativa",
  "palavra pela metade, tô roendo o suspense",
  "termina a palavra vai, o ENTER tá com saudade",
  "tá pensando ou dormiu no teclado?",
  "cadê o resto? chama ele de volta",
  "começou bem, agora termina",
  "congelou? pisca duas vezes",
  "digitou e parou. suspense de novela",
  "fala a palavra em voz alta. os vizinhos vão estranhar mas ajuda",
  "o cursor tá piscando pra você, impaciente igual eu"
],
termoParado: [
  "tá pensando ou foi fazer café?",
  "tô aqui esperando, contando pixel",
  "quer dica? não tenho. mas tenho companhia",
  "dá pra ouvir teus neurônios daqui. um tá de folga",
  "parado muito tempo a palavra cria raiz",
  "tá lendo o dicionário escondido né",
  "pensa em palavra do dia a dia, tipo pizza. tô com fome. foca",
  "a palavra não vai se digitar sozinha",
  "olha as letras do teclado que ainda não foram usadas",
  "ô, cê tá vivo?",
  "chuta qualquer coisa, chute também é informação",
  "eu podia tá assombrando uma casa agora mas tô aqui contigo",
  "o teclado tá esperando, eu tô esperando e a palavra tá rindo",
  "parado demais, vou começar a cantar. cê não quer isso",
  "essas horas é respirar, ter paciência e chutar uma palavra"
],

/* ---------- aleatórias (de palavra, de língua, de nada) ---------- */
termoAleatorio: [
  "todo gringo acha que saudade só existe em português. orgulho",
  "a letra mais comum do português é o A, depois vem E e O",
  "palavra de 5 letras que eu odeio: prova. trauma de escola",
  "radar, arara, reter. lê de trás pra frente que dá igual",
  "ósculo existe e é beijo. português é bizarro",
  "minha palavra favorita é bugado. tem 6 letras, injustiça",
  "dica de ouro: palavra em português adora terminar em A, O ou E",
  "o Q quase sempre vem com U. relação mais estável que muita gente",
  "plural de pão é pães. o português já é um jogo difícil por si só",
  "arara tem 3 A em 5 letras, guarda essa pra um dia de desespero",
  "K, W e Y quase nunca aparecem no Termo. coitados",
  "li o dicionário inteiro uma vez, achei o final previsível",
  "pq abreviatura é uma palavra tão grande? pensa nisso",
  "alguém inventou a palavra palavra. como essa pessoa falava antes?",
  "nenhuma palavra começa com Ç. eterno reserva",
  "gringo paga caro pra aprender português e cê aprende de graça comigo",
  "uma vez eu chutei ABCDE. não deu certo, não tenta",
  "tem gente que joga Termo no banheiro. não julgo. julgo um pouco",
  "sonhei que eu era uma letra amarela. passei a noite no lugar errado",
  "palavra mais bonita de 5 letras? voto nuvem",
  "o português tem umas 400 mil palavras e cê usa umas mil",
  "verde, amarelo e cinza. bandeira de um país muito triste",
  "se a palavra do dia fosse gatos eu ia me sentir representado",
  "vovó e vovô têm 4 letras, ninguém pensou nos avós aqui",
  "o X é aquele primo que só aparece no Natal e causa",
  "imagina Termo com 6 letras. caos total",
  "às vezes eu torço pra palavra ganhar. só às vezes",
  "dica séria: começa com 5 letras diferentes, repetir no início é desperdício",
  "avó e avô. um acento e muda a família inteira",
  "decorei 12 mil palavras de 5 letras e não sirvo pra mais nada",
  "se letra fosse comida o A era arroz, aparece em tudo",
  "tem palavra tão comum que ninguém pensa nela. tipo coisa",
  "Tame Impala no fone e Termo na tela, combinação perfeita",
  "a passagem tá 5,75 e o Termo é de graça. aproveita",
  "jogar Termo no 330 lotado com uma mão só, esse é o modo difícil de verdade",
  "se o Cruzeiro jogasse Termo ia chutar tudo pra fora",
  "papo reto, palavra com Z é sempre a mais chata",
  "quem joga Termo toda manhã tem mais disciplina que eu no Duolingo",
  "já pensou o Gabigol comemorando palavra certa? eu pensei",
  "tem dia que a palavra é tão fácil que dá raiva de errar"
],

/* ---------- cutucar o mascote ---------- */
cutucarTermo: [
  "ei, eu sou o mascote, não o teclado. as letras ficam lá embaixo",
  "me cutucar não revela a palavra, já testei",
  "cutucando de nervoso? entendo, Termo dá nervoso",
  "cutuca mais uma vez que eu viro letra cinza",
  "ai! eu tava cochilando",
  "cutuca a palavra, não eu",
  "quer dica? não dou. quer carinho? também não. tá, um pouco",
  "eu sou verde-água, não verde de acerto. não adianta",
  "cutucada registrada, nenhuma letra revelada",
  "isso não é botão de dica mano",
  "me cutucando pra passar o tempo? joga que passa mais rápido",
  "sou feito de pixel e carência. continua. para. sla",
  "se eu fosse letra agora eu era amarela, fora do lugar",
  "eu sei a palavra e não vou contar, muahaha",
  "cutucou o mascote. ganhou nada e perdeu tempo",
  "toda vez que cê me cutuca uma letra verde chora",
  "tá me testando? aqui quem testa sou eu",
  "eu não sou o ENTER, não confunde",
  "toc toc. quem é? alguém que devia tá jogando",
  "se eu ganhasse uma moeda por cutucada eu comprava uma vogal",
  "me cutuca não, me cutuca não... tá, pode",
  "cutucar não gasta tentativa, só gasta minha paciência",
  "quer atenção? acerta a palavra",
  "a palavra tem 5 letras e eu tenho 2 orelhas. coincidência",
  "tô ocupado julgando teus chutes, volto já",
  "cuidado, eu sou bug. cutuca muito que eu viro feature",
  "psiu, a palavra tá ouvindo. disfarça",
  "suporte técnico emocional do Termo, como posso ajudar? não posso",
  "a palavra começa com... não. quase caí nessa",
  "me cutucou de novo, vai pro relatório",
  "tentando me hackear? eu sou SVG, não tem nada aqui dentro",
  "tô de olho no teu teclado, principalmente nas teclas cinza",
  "cutuca 7 vezes que nada acontece, pode testar",
  "quer saber a palavra? ela tem letras. pronto",
  "oi, tudo bem? não? é o Termo né, te entendo",
  "eu não mordo, só zoo",
  "PARA de me cutucar KKKKKK",
  "desse jeito cê cutuca mais do que chuta",
  "a cutucada me deu uma ideia de palavra. esqueci",
  "sou meio gato meio fantasma. gato odeia cutucada e fantasma nem liga",
  "pedido de ajuda? olha as letras amarelas",
  "parabéns, achou o botão mais inútil do jogo: eu",
  "cutucou, agora vou narrar teu próximo chute igual locutor de rádio",
  "sabe quem não cutuca mascote? quem já acertou",
  "tá bom, uma dica: a palavra é em português"
]
};

(function(){
  const T = window.FALAS_TERMO, G = window.FALAS || {};
  // bancos combinados: falas gerais + falas do Termo no mesmo saco sem repetição
  T.termoMisto = [...(G.aleatorio || []), ...T.termoAleatorio];
  T.termoParadoMix = [...(G.parado || []), ...T.termoParado];
  if (window.Bugado) Bugado.addLines(T);
})();
