/* ==========================================================
   Falas do Bugado no Termo.
   Variáveis: {palavra}, {letra}, {n} — preenchidas pelo jogo.
   O sorteio (Bugado.line) só repete depois de esgotar a categoria.
   ========================================================== */
window.FALAS_TERMO = {

/* ---------- chegada / retorno ---------- */
termoOi: [
  "Bora de Termo. Cinco letras, seis chances e zero desculpas.",
  "Palavra do dia escolhida. Eu sei qual é. Não vou contar. Nem sob tortura. Talvez sob petisco.",
  "Chegou a hora de descobrir se você sabe português ou só finge bem na internet.",
  "Hoje a palavra é... ah, quase. Quase que eu conto. Joga aí.",
  "Termo do dia na mesa. Verde é bom, amarelo é mais ou menos, cinza é vergonha.",
  "Seis chances. Parece muito. Não é. Confia.",
  "Eu escondi uma palavra aqui. Não é palavra feia. Acho.",
  "Aquece os dedos. Estala o pescoço. Esquece que existe dicionário.",
  "Bem-vindo ao único lugar onde errar em cinza dói mais que errar em vermelho.",
  "Cinco quadradinhos te esperando. Eles não mordem. Eu mordo.",
  "Mais um dia, mais uma palavra, mais uma chance de você me decepcionar lindamente.",
  "Regra da casa: sem colar. Eu tô vendo. Eu sempre tô vendo.",
  "Palavra nova no forno. Saiu quentinha. Cuidado pra não queimar a língua.",
  "Tá pronto? Não precisa responder. Ninguém tá pronto pro Termo."
],
termoVoltou: [
  "Voltou! Achei que tinha fugido de medo da palavra.",
  "Olha quem apareceu. A palavra continua aqui, esperando, igual cachorro na porta.",
  "Salvei teu progresso. Não precisa agradecer. Mas pode.",
  "Foi pensar lá fora? Pensar lá fora não vale, mas eu finjo que não vi.",
  "Voltou pra terminar o que começou. Respeito. Pouca gente faz isso na vida.",
  "Tua partida tava aqui congeladinha. Descongelei. Tá morninha ainda.",
  "Deu uma saída estratégica? Eu chamo de fuga, mas tudo bem.",
  "Os chutes de antes continuam aí, te julgando em silêncio. Eu julgo em voz alta.",
  "Pausa pro café? Espero que tenha voltado com ideias. Ou pelo menos com café.",
  "Retomando de onde parou. Igual novela, só que com menos traição."
],
termoDiarioFeito: [
  "Diário feito, campeão. Amanhã tem outro. Hoje tem o treino, se a abstinência bater.",
  "Você já zerou o de hoje. Quer o quê? Uma medalha? Toma: 🏅. Pronto.",
  "Já acertou hoje. Ficar olhando pro resultado não dá mais XP. Eu testei.",
  "Diário concluído. Agora você pode ir viver a vida. Ou jogar treino. Eu sei qual você vai escolher.",
  "Missão cumprida. Printa e manda no grupo da família. Ninguém vai entender, mas manda.",
  "O de hoje já foi. A próxima palavra tá no forno. Sem spoiler.",
  "Voltou pra admirar tua vitória? Eu entendo. Eu também admiro as minhas. Todas imaginárias.",
  "Já foi. Acabou. Game over do bom. Amanhã tem mais.",
  "Voltou pro diário resolvido? Isso é saudade ou é vaidade?",
  "Terminou o de hoje. Quer desafio? O treino infinito tá ali. Palavra nova toda hora.",
  "Ganhou hoje. Guarda essa energia pra amanhã. Ou gasta tudo no treino, sem juízo.",
  "Tá feito. Relaxa. Bebe uma água. Termo não é tudo na vida. É quase tudo."
],
termoDiarioPerdido: [
  "O diário de hoje... bem. A gente não fala sobre o diário de hoje.",
  "Você perdeu hoje. Mas amanhã é outro dia e outra palavra pra te humilhar.",
  "Hoje não deu. O treino tá aí pra você se vingar de palavras aleatórias.",
  "Perdeu o diário. Acontece com os melhores. E com você também.",
  "Ainda de luto pelo diário? Eu trouxe flores. Imaginárias. Pixeladas.",
  "O diário te venceu hoje. Treina aí que amanhã a gente revida.",
  "Voltou na cena do crime? Não tem mais nada aqui, só cinzas. Cinzas cinzas.",
  "A palavra de hoje ganhou. Placar: dicionário 1, você 0. Amanhã tem revanche."
],

/* ---------- modos ---------- */
termoModoTermo: [
  "Modo clássico. Uma palavra, seis tentativas. O arroz com feijão do chute.",
  "Termo raiz. Sem firula. Só você, cinco letras e a tua dignidade.",
  "De volta pro básico. Uma palavra só. Menos coisa pra você errar.",
  "Uma palavra. Seis chances. Foco total. Eu vou ficar quieto. Mentira.",
  "Modo solo. Ninguém pra dividir a culpa.",
  "O clássico nunca sai de moda. Igual chinelo de dedo.",
  "Termo normal. Pra quem gosta de sofrer em doses pequenas.",
  "Uma palavrinha só. Fácil, né? Todo mundo diz isso no começo."
],
termoModoDueto: [
  "Dueto! Duas palavras, sete tentativas. Cada chute vale pros dois. Pensa duplo.",
  "Modo dueto: é tipo namorar duas palavras ao mesmo tempo. Complicado.",
  "Duas palavras. Um cérebro. Boa sorte pro teu neurônio de plantão.",
  "Dueto é igual dupla sertaneja: se uma desafina, a outra segura.",
  "Sete tentativas pra duas palavras. A matemática não tá do teu lado.",
  "Cada letra que você digita vale pros dois quadros. Economia de chute.",
  "Modo dueto ativado. Eu vou comentar em dobro também.",
  "Duas palavras escondidas. Nenhuma delas é 'socorro'. Eu acho.",
  "Dueto é o Termo de quem acha que o Termo é fácil.",
  "Olho no quadro da esquerda, olho no da direita. Fica vesgo, mas ganha."
],
termoModoQuarteto: [
  "QUARTETO. Quatro palavras, nove tentativas. Você é corajoso ou só não leu direito?",
  "Quatro palavras ao mesmo tempo. Isso não é jogo, é teste de sanidade.",
  "Modo quarteto: onde os fortes choram e os fracos também.",
  "Nove chutes pra quatro palavras. Sem pressão. Muita pressão.",
  "Quarteto é malabarismo com palavras. Só que as palavras mordem.",
  "Quatro quadros. Se você errar, erra em quatro lugares. Eficiência.",
  "Bem-vindo ao quarteto. Deixa a vergonha na porta, você vai precisar de espaço.",
  "Quatro palavras. Teu cérebro acabou de pedir demissão.",
  "Quarteto! Eu vou torcer por você. Em silêncio. Mentira, vou gritar.",
  "Modo difícil ativado. Não tem botão de voltar no tempo. Tem botão de chorar."
],
termoTreino: [
  "Modo treino: palavra aleatória, sem ranking. Só o prazer de errar à vontade.",
  "Treino infinito! Pode errar que ninguém vê. Só eu. E eu conto pra todo mundo.",
  "Treino é academia de palavra. Só que você não sua. Talvez sue.",
  "Palavra nova sorteada. Nem eu sei qual é. Mentira, eu sei. Eu sempre sei.",
  "Treino liberado. Aqui a sequência não quebra. O ego sim.",
  "Palavra fresquinha, saída do forno do dicionário.",
  "Treinando pra amanhã? Gosto da dedicação. Preocupante, mas gosto.",
  "Mais uma! Mais uma! Mais uma! (sou eu gritando da arquibancada)",
  "Sorteei outra. Essa tem cara de difícil. Ou de fácil. Tem cara de palavra.",
  "Treino não vale ranking, mas vale XP. Farma aí, gamer.",
  "Rodada nova. A palavra anterior já foi pro céu das palavras.",
  "Próxima! Você tá viciado ou é impressão minha? É impressão minha. Continua."
],
termoNovaPalavra: [
  "Desistiu dessa? Tudo bem, eu finjo que ela era impossível. Era <b>{palavra}</b>.",
  "Pulou a palavra. Ela ficou ofendida. Palavras têm sentimentos. Era <b>{palavra}</b>.",
  "Trocou no meio? Isso é virar o tabuleiro. Respeito a coragem. Era <b>{palavra}</b>.",
  "Largou essa pra trás. Ela vai contar pras outras que você é medroso. Era <b>{palavra}</b>.",
  "Nova palavra! A antiga era <b>{palavra}</b>, se quer saber. Agora sabe.",
  "Fugiu da <b>{palavra}</b>. Eu entendo. Ela era meio assustadora mesmo.",
  "Desistência registrada no livro sagrado das vergonhas. A resposta era <b>{palavra}</b>.",
  "Ok, próxima. Pra constar: era <b>{palavra}</b>. Tava na tua cara. Mais ou menos."
],

/* ---------- primeiro chute ---------- */
termoAbertura: [
  "<b>{palavra}</b>? Todo mundo começa com <b>{palavra}</b>. Seja diferente. Ou não.",
  "Abriu com <b>{palavra}</b>. Clássico. Previsível. Eficiente. Chato.",
  "<b>{palavra}</b>? Você leu isso num tutorial, né? Pode falar.",
  "<b>{palavra}</b> é a abertura do povo. Tá tudo bem ser do povo.",
  "Ah, o famoso <b>{palavra}</b>. Eu tinha certeza. Ganhei uma aposta comigo mesmo.",
  "Começou com <b>{palavra}</b>. Metade da internet também. Parabéns por ser metade da internet.",
  "<b>{palavra}</b>: a abertura oficial de quem pesquisou 'melhor palavra pra começar'.",
  "Abrir com <b>{palavra}</b> é tipo pedir frango no restaurante. Seguro. Sem emoção.",
  "<b>{palavra}</b> pra caçar vogal. Estratégia. Sem graça, mas estratégia.",
  "Tu é do time <b>{palavra}</b>. Anotado. Julgado. Arquivado.",
  "<b>{palavra}</b> de primeira! Tem vogal pra todo lado. Parece um grito.",
  "Eu sabia que vinha <b>{palavra}</b>. Eu sempre sei. Sou onisciente e levemente irritante.",
  "Lá vem o <b>{palavra}</b>. Nem sei por que ainda me surpreendo.",
  "<b>{palavra}</b>: movimento de manual. O manual agradece.",
  "Abertura <b>{palavra}</b>. Eficiente como fila de banco num dia bom. Raro, mas acontece."
],
termoAberturaDeNovo: [
  "<b>{palavra}</b> DE NOVO? Você tem um relacionamento sério com essa palavra.",
  "Mesma abertura da última vez: <b>{palavra}</b>. Consistência ou falta de criatividade? Os dois.",
  "Outra vez <b>{palavra}</b>. Tô achando que é a única palavra que você conhece.",
  "<b>{palavra}</b>, <b>{palavra}</b>, <b>{palavra}</b>. Faz logo uma tatuagem.",
  "Repetiu <b>{palavra}</b>. Pelo menos você é fiel. Com palavras, pelo menos.",
  "Eu podia ter apostado que era <b>{palavra}</b>. Ganhava uma fortuna. Em petisco.",
  "<b>{palavra}</b> outra vez. Se essa palavra fosse gente, já tinha pedido medida protetiva.",
  "Tradição é tradição: <b>{palavra}</b> na abertura. Tipo peru no Natal."
],
termoPrimeiro: [
  "Primeiro chute: <b>{palavra}</b>. Ousado. Vamos ver no que dá.",
  "Abriu com <b>{palavra}</b>. Não é o que eu faria, mas eu sou um fantasma, então.",
  "<b>{palavra}</b> pra começar? Cheira a intuição. Ou a chute puro.",
  "Primeiro chute dado. A jornada de mil letras começa com cinco.",
  "<b>{palavra}</b>? Diferentão. Gostei. Não conta pra ninguém que eu gostei.",
  "Começou com <b>{palavra}</b>. Isso diz muito sobre você. Não sei o quê, mas diz.",
  "Abertura criativa: <b>{palavra}</b>. Hipster do Termo.",
  "O primeiro chute é um salto no escuro. Você pulou. Tá vivo?",
  "Chute inicial registrado. Agora a coisa fica séria. Mentira, continua boba.",
  "<b>{palavra}</b> como abertura. Anotei no meu caderninho de coisas estranhas.",
  "Primeira tentativa. Tudo é possível. Inclusive o fracasso. Mas sobretudo o possível.",
  "Começar com <b>{palavra}</b> foi uma escolha. Uma escolha corajosa.",
  "Ninguém começa com <b>{palavra}</b>. Você começou. Pioneiro.",
  "Primeiro tiro no escuro. Agora olha as cores e finge que entendeu.",
  "Abriu. Agora é ler as cores igual cartomante lê mão."
],

/* ---------- resultado do chute ---------- */
termoZero: [
  "Nada. Zero. Nenhuma letra. Pelo menos agora você sabe o que a palavra NÃO é.",
  "Tudo cinza. Parece segunda-feira de manhã.",
  "Cinco letras e nenhuma serviu. Isso é quase um talento.",
  "Zero acertos. Mas olha o lado bom: cortou cinco letras do teclado.",
  "Cinza total. A palavra olhou pro teu chute e disse 'não te conheço'.",
  "Nenhuma letra certa. Eu chamo de eliminação estratégica. Você chama de quê?",
  "Tá tudo cinza. Igual céu de São Paulo.",
  "Errou todas as cinco. Estatisticamente impressionante.",
  "Cinzento. Sem vida. Sem cor. Tipo meu humor antes do café.",
  "Foi o chute mais honesto: não sabia nada e provou que não sabia nada.",
  "Nada, nadinha. Mas informação é informação. Até a triste.",
  "Cinco cinzas. Podia ser pior. Não sei como, mas podia.",
  "Zero pontos pro chute, dez pontos pra coragem.",
  "Tudo apagado. Se isso fosse bingo, você nem tinha cartela.",
  "Nem uma letrinha. A palavra tá rindo de você. Eu também, mas com carinho.",
  "Cinza no quadro inteiro. Ótimo, agora sobram só umas vinte letras. Moleza.",
  "Totalmente errado. Totalmente útil. Totalmente cinza.",
  "Nenhum acerto. Respira. O cinza também ensina. Principalmente humildade."
],
termoSoAmarelo: [
  "Umas amarelas. As letras estão na palavra, só não onde você colocou. Clássico.",
  "Amarelo é o 'quase' do Termo. E você é o rei do quase.",
  "Tem letra certa no lugar errado. Tipo você numa festa.",
  "Amarelinhas! Agora é só mudar de lugar. Parece fácil. Não é.",
  "Algumas amarelas. Tá morno. Café esquecido na mesa.",
  "Acertou as letras, errou o endereço. Correios feelings.",
  "Amarelo significa: 'eu existo, mas não aqui'. Profundo, né?",
  "{n} amarela(s) e nenhuma verde. Tá chegando. Devagar, igual ônibus de domingo.",
  "As letras estão lá dentro. Agora é jogar Tetris com elas.",
  "Tudo amarelo, nada verde. Um semáforo indeciso.",
  "Pista boa! Agora não coloca as amarelas no mesmo lugar, pelo amor.",
  "Letra certa, lugar errado. A história da minha vida.",
  "Amarelo é progresso. Um progresso tímido, mas progresso.",
  "Hmm, amarelas. Troca elas de posição e vê no que dá.",
  "Tem coisa aí! Sem verde ainda, mas tem coisa."
],
termoVerde1: [
  "Uma verde! Uma! Comemora baixinho pra não assustar a palavra.",
  "Uma letra no lugar certo. É pouco, mas é honesto.",
  "Um verdinho. Tipo feijão no algodão. Vai crescer.",
  "Uma verde já é alguma coisa. Guarda ela com carinho.",
  "Achou uma. Faltam quatro. Matemática simples, execução difícil.",
  "Um verde solitário. Ele tá se sentindo sozinho. Arruma companhia pra ele.",
  "Uma letra fixada. É o começo de uma bela amizade.",
  "Verde! Um só, mas verde. Não desperdiça.",
  "Uma no alvo. Agora é igual pescaria: paciência.",
  "Um acerto na mosca. As outras letras tão rindo, mas não por muito tempo.",
  "Primeira pecinha do quebra-cabeça. Faltam as que dão trabalho.",
  "Uma verde. Nada mal. Também nada bem. Neutro. Suíço.",
  "Tem uma verdinha aí. Protege ela como o último pão de queijo.",
  "Um verde. O caminho é longo, mas pelo menos tem caminho."
],
termoVerde2: [
  "Duas letras verdes. Tá esquentando. Eu tô suando junto.",
  "Dois verdes! Tá ficando interessante.",
  "Duas no lugar. Já dá pra sentir o cheiro da palavra.",
  "Duas verdes. Quase metade. Quase. Não arredonda.",
  "Dois acertos em cheio. Tô começando a acreditar em você.",
  "Duas letras cravadas. Agora preenche o resto sem inventar moda.",
  "Duas verdinhas. Dupla dinâmica. Falta o resto da Liga da Justiça.",
  "Ó, duas certas. Você tá pegando o jeito. Ou teve sorte. Aceito os dois.",
  "Duas verdes! Ainda tem muita palavra que encaixa, então calma.",
  "Dois verdes na conta. Continua que tá bonito.",
  "Duas já foram. O esqueleto da palavra tá aparecendo.",
  "Duas certas. Meio caminho andado. Meio caminho é muito caminho.",
  "Dois quadradinhos verdes. Parece bandeira de time. Torce aí.",
  "Duas no alvo. Tá esquentando igual pastel saindo da fritura."
],
termoVerde3: [
  "Três verdes! Agora é só não fazer besteira. Sei que é pedir muito.",
  "Três certinhas. A palavra tá quase pelada.",
  "Três de cinco! Tá quente, tá quente, TÁ QUENTE.",
  "Três verdes. Já dá pra ver o formato. Pensa, pensa.",
  "Três letras no lugar. Eu tô nervoso. Você tá nervoso? Eu tô.",
  "Três! Cuidado: tem umas quinhentas palavras que terminam igual.",
  "Três verdes e o coração a mil. Vai com calma.",
  "Faltam duas letras. Duas! Dá pra sentir o gosto da vitória. Gosto de pixel.",
  "Três certinhas. O dicionário tá começando a suar.",
  "Olha isso! Três verdes. Tô quase orgulhoso. Quase.",
  "Três no lugar. Agora é aquele momento de pensar antes de digitar. Tenta.",
  "Tá tão perto que eu consigo ouvir a palavra respirando.",
  "Três verdes! Mais um pouquinho e eu solto confete.",
  "Três já tão. Duas faltam. Uma dúvida me consome: você sabe quais?"
],
termoVerde4: [
  "QUATRO VERDES. Uma letra. UMA. Não me faz passar vergonha.",
  "Quatro! Só falta uma. Começa a roleta russa das letras.",
  "Quatro verdes e uma dúvida cruel. O famoso 'era essa ou aquela'.",
  "Tá com cara de armadilha. Quatro certas e mil opções pra última.",
  "Uma letra separa você da glória. Ou do desespero. Escolhe bem.",
  "Quatro verdes. Eu tô roendo as unhas. Eu nem tenho unha.",
  "Falta UMA letra. Pensa em todas as palavras. Todas. Rápido.",
  "Quatro! Se errar agora eu vou fingir que não te conheço.",
  "Quatro verdes. O quinto tá ali, escondidinho, rindo da tua cara.",
  "Quase! Quatro letras certas. A quinta tá fazendo charme.",
  "Uma letra de distância. O Termo tá testando teu coração.",
  "Quatro de cinco. Hora dos fortes brilharem e dos fracos chutarem sem pensar.",
  "Quatro verdes. Respira, olha o teclado, vê as letras que sobraram.",
  "Tá TÃO perto. Se não acertar agora, eu choro. Choro binário.",
  "Quatro! Só não cai na armadilha do _ARRO. Todo mundo cai."
],
termoAnagrama: [
  "Todas as letras estão certas! Só a ordem que tá bagunçada. Tipo meu quarto.",
  "Cinco letras certas, ordem errada. É um anagrama! Embaralha aí.",
  "Você tem todas as peças. Agora é montar o Lego.",
  "Todas as letras estão aí. Tá tudo aí! Só não tá onde devia.",
  "Acertou os ingredientes, errou a receita. Mexe essas letras.",
  "Todas estão na palavra. Agora é dança das cadeiras.",
  "As letras são essas. Só essas. Troca de lugar e corre pro abraço.",
  "Anagrama detectado! Hora de embaralhar igual carta de truco.",
  "Letras 100%, posição nem tanto. Quase um sudoku de letras.",
  "Tá tudo aí dentro. É só organizar. Igual gaveta de meia."
],
termoPiorou: [
  "Esse chute foi pior que o anterior. Evolução ao contrário.",
  "Menos verdes que antes. Tá andando de ré?",
  "Hmm, piorou. Foi pra testar letras novas, né? Diz que foi.",
  "Regrediu. Às vezes a gente dá um passo atrás pra pular mais longe. Às vezes.",
  "Tinha mais verde antes. Saudades daquele chute.",
  "Esse foi um chute de exploração. Exploração do fracasso.",
  "O anterior tava melhor. Não conta pra ele que eu disse isso.",
  "Andou pra trás. Tipo caranguejo. Caranguejo também chega, devagar."
],

/* ---------- vacilos de lógica ---------- */
termoCinza: [
  "Usou o <b>{letra}</b> que já tava cinza. Pra ter certeza que ele continua cinza?",
  "<b>{letra}</b> de novo? Ele já disse que não tá na palavra. Respeita o não do {letra}.",
  "O <b>{letra}</b> é cinza. Foi cinza antes, é cinza agora, vai ser cinza pra sempre.",
  "Olha o teclado: o <b>{letra}</b> tá apagadinho. Apagado significa NÃO.",
  "Reciclando letra cinza? Ecológico, mas inútil. Né, <b>{letra}</b>?",
  "Você insistiu no <b>{letra}</b>. Ele agradece o carinho, mas continua fora.",
  "O <b>{letra}</b> já tinha sido eliminado. Você ressuscitou ele só pra matar de novo.",
  "Letra cinza repetida: <b>{letra}</b>. Um chute desperdiçado com amor.",
  "Tá usando o <b>{letra}</b> por nostalgia? Porque por lógica não é.",
  "Eu vi esse <b>{letra}</b>. Todo mundo viu. O teclado viu. Vergonha coletiva.",
  "O <b>{letra}</b> é tipo ex: você já sabe que não dá, mas volta.",
  "Colocou o <b>{letra}</b> que já tava queimado. Testando se o jogo mudou de ideia?",
  "<b>{letra}</b>, a letra que não tá na palavra, apareceu de novo. Clássico.",
  "Mais uma do <b>{letra}</b>. Ele não vai ficar verde por insistência.",
  "Às vezes a gente usa letra cinza pra testar outras. Às vezes é distração. Qual foi, <b>{letra}</b>?",
  "O <b>{letra}</b> cinza voltou. Teimoso ou estrategista? Aposto na teimosia.",
  "Não quero apontar nada, mas... <b>{letra}</b>. Cinza. Já sabia.",
  "Tecla cinza é tecla morta. Você acabou de chutar um cadáver. O <b>{letra}</b>."
],
termoIgnorouVerde: [
  "Tinha um <b>{letra}</b> verde ali e você simplesmente... tirou. Por quê? Me explica.",
  "Abandonou o <b>{letra}</b> verde? Ele tava tão feliz no lugar dele.",
  "O <b>{letra}</b> tava certinho, verdinho, e você trocou. Ousadia ou esquecimento?",
  "Verde não se mexe! O <b>{letra}</b> tava no lugar certo, deixa ele lá.",
  "Largou uma letra verde pra testar outra coisa. Isso tem nome: modo difícil ao contrário.",
  "Tirou o <b>{letra}</b> do lugar certo. O {letra} tá magoado. Eu tô magoado.",
  "Chutou sem o <b>{letra}</b> verde. Tá eliminando letra? Vou fingir que foi plano.",
  "Esqueceu do <b>{letra}</b> que já tava cravado. Acontece. Muito. Com você.",
  "Cadê o <b>{letra}</b>? Ele era verde! Verde é sagrado!",
  "Você chutou por cima de um verde. Isso é tipo estacionar em cima da faixa."
],
termoAmareloTeimoso: [
  "Colocou o <b>{letra}</b> no mesmo lugar onde ele já deu amarelo. Não vai virar verde por pena.",
  "O <b>{letra}</b> já disse que não é nessa casa. Muda ele de endereço.",
  "Amarelo no mesmo lugar de novo? O <b>{letra}</b> tá cansado de avisar.",
  "O <b>{letra}</b> naquela posição já foi testado. Resultado: amarelo. De novo: amarelo.",
  "Teimou com o <b>{letra}</b> no mesmo lugar. Continua não sendo ali.",
  "O <b>{letra}</b> tá na palavra, mas NÃO ali. Essa dica eu já tinha dado. Grátis.",
  "Mesma letra, mesmo lugar, mesmo amarelo. A definição de loucura, segundo a internet.",
  "O <b>{letra}</b> tá gritando 'me muda de lugar!'. Escuta ele.",
  "Botou o <b>{letra}</b> onde ele já tinha falhado. Esperando milagre?",
  "Amarelo é convite pra mudar de lugar, não pra fazer ninho. <b>{letra}</b>, sai daí."
],
termoIgnorouAmarelo: [
  "Cadê o <b>{letra}</b>? Ele tava amarelo, ele TÁ na palavra. Não esquece dele.",
  "Deixou o <b>{letra}</b> amarelo de fora. Ele vai voltar pra te assombrar.",
  "Esqueceu o <b>{letra}</b>. Letra amarela é letra que existe. Existe!",
  "O <b>{letra}</b> tá na palavra e você fingiu que não. Estratégia de avestruz.",
  "Chutou sem o <b>{letra}</b> amarelo. Ou é genialidade ou esquecimento. Aposto no segundo.",
  "O <b>{letra}</b> ficou de fora da festa. Ele tá convidado, sabia?",
  "Amarelo ignorado: <b>{letra}</b>. Ele não some só porque você não olha.",
  "Faltou o <b>{letra}</b> no chute. A palavra PRECISA dele."
],

/* ---------- chute recusado ---------- */
termoInvalida: [
  "Isso não existe. Literalmente: essa palavra não existe.",
  "<b>{palavra}</b>? Isso é palavra em qual idioma? Élfico?",
  "Não conheço <b>{palavra}</b>. O dicionário também não. Ninguém conhece.",
  "<b>{palavra}</b> não tá no dicionário. Mas tá anotada no meu caderno de invenções suas.",
  "Bonita essa palavra. Pena que você inventou agora.",
  "<b>{palavra}</b>... soa como nome de remédio. Não é palavra, mas soa.",
  "Palavra inválida. Tentativa não gasta. Dignidade, um pouco.",
  "Isso aí é nome de Pokémon? Porque palavra não é.",
  "<b>{palavra}</b> não existe. Ainda. Manda um e-mail pra Academia Brasileira de Letras.",
  "Procurei <b>{palavra}</b> em todos os dicionários. Todos. Nada.",
  "Parece palavra, tem cinco letras, mas não é palavra. Quase lá.",
  "<b>{palavra}</b>? Você bateu a cabeça no teclado?",
  "Não vale inventar. Isso aqui é Termo, não é batalha de rima.",
  "<b>{palavra}</b> não passou no controle de qualidade.",
  "Essa daí não existe nem na gíria do teu primo.",
  "Nope. <b>{palavra}</b> não é palavra. Tenta outra, essa não conta.",
  "Eu até queria aceitar <b>{palavra}</b>, mas tenho princípios. Poucos, mas tenho.",
  "<b>{palavra}</b> é o som que eu faço quando tropeço. Não é palavra.",
  "Palavra inexistente detectada. Alarme de vergonha ativado. Mas não gasta chance.",
  "Isso foi um chute ou um espirro no teclado?",
  "<b>{palavra}</b>... não. Só não.",
  "Até o corretor do celular ia rir dessa.",
  "Criatividade nota 10. Existência nota 0.",
  "<b>{palavra}</b>: palavra de outro universo. Aqui não rola.",
  "Invalidíssima. Tenta uma que esteja no dicionário, pode ser?",
  "Se <b>{palavra}</b> fosse palavra, eu seria um gato normal. Não sou."
],
termoInvalidaDeNovo: [
  "Mais uma inventada. Tá criando um idioma novo? Me avisa quando lançar o dicionário.",
  "Segunda palavra que não existe seguida. Tá testando meu dicionário ou minha paciência?",
  "Você tá digitando de olho fechado? Pode abrir, não dá medo.",
  "Outra inválida. Eu não conto quantas foram. Mentira, conto: muitas.",
  "Tá chutando letra aleatória esperando dar sorte? Não é assim que funciona. Às vezes é.",
  "De novo não existe. Pensa em palavra de verdade, tipo 'bolo'. Tem quatro letras, mas pensa.",
  "Mais uma pro museu das palavras que nunca existiram.",
  "Eu vou começar a cobrar taxa por palavra inventada."
],
termoCurta: [
  "Cinco letras. CINCO. Conta nos dedos de uma mão.",
  "Faltou letra. A palavra tem cinco, não 'mais ou menos cinco'.",
  "Palavra incompleta. Enviar pela metade não vale.",
  "Tá faltando letra aí, chefe.",
  "Isso aí tem menos de cinco letras. Eu sei contar. Você sabe?",
  "Completa a palavra primeiro. Pressa é inimiga do verde.",
  "Apertou ENTER cedo demais. Ansiedade é fogo.",
  "Menos de cinco letras não vai. Nem pedindo com jeitinho.",
  "Enviou com buraco. Isso aqui não é queijo suíço.",
  "Tem quadradinho vazio aí. Ele tá triste. Preenche ele.",
  "Quatro letras? Isso é outro jogo. Aqui é cinco.",
  "Ei, calma. Termina de escrever. Eu espero. Eu tenho a eternidade."
],
termoRepetida: [
  "Você já chutou <b>{palavra}</b>. A resposta não mudou desde a última vez.",
  "<b>{palavra}</b> de novo? A cor não vai ser diferente, eu prometo.",
  "Chute repetido. O jogo não aceita reprise, só palavra nova.",
  "Déjà vu! Você já tentou <b>{palavra}</b>. Eu lembro. Eu lembro de TUDO.",
  "Mesma palavra duas vezes? Tá testando se eu presto atenção? Presto.",
  "<b>{palavra}</b> já foi. Não gasta tentativa com reprise.",
  "Isso é reprise da Sessão da Tarde. Já vimos <b>{palavra}</b>.",
  "Você chutou <b>{palavra}</b> faz pouco. A memória tá boa?",
  "Repetir chute não conta. Nem ajuda. E me preocupa.",
  "Olha pra cima: <b>{palavra}</b> tá ali. Já tentou. Deu no que deu."
],

/* ---------- detalhes do chute ---------- */
termoAcento: [
  "Botei o acento pra você: <b>{palavra}</b>. De nada. Aceito elogios.",
  "Viu? Não precisa digitar acento. Eu cuido disso. Sou praticamente um corretor.",
  "Acento colocado automaticamente em <b>{palavra}</b>. Serviço de primeira.",
  "<b>{palavra}</b>, com acento e tudo. A professora de português ficaria orgulhosa.",
  "Você digitou sem acento e eu arrumei. Somos um time. Eu trabalho mais, mas somos um time.",
  "Olha que chique: <b>{palavra}</b> com acentinho. Grátis.",
  "Acento é por minha conta. O resto é com você.",
  "<b>{palavra}</b> ficou mais bonita com acento, né? Igual gente de óculos.",
  "Til, agudo, cedilha... eu boto tudo. Você só digita.",
  "Arrumei a grafia: <b>{palavra}</b>. Não precisa agradecer. Mas agradece.",
  "Aqui C vale Ç e A vale Ã. Democracia das letras.",
  "Acentuação automática ativada. Pode digitar igual no zap."
],
termoVogais: [
  "Chute cheio de vogal. Tá caçando vogal igual Pokémon.",
  "Quatro vogais? Isso não é palavra, é um grito.",
  "Muita vogal nesse chute. Estratégia de quem sabe o que faz. Ou de quem ama A E I O U.",
  "Vogal, vogal, vogal. Tá fazendo aquecimento vocal?",
  "Palavra com mais vogal que consoante. Parece nome de bebê de famoso.",
  "Varreu as vogais. Agora pelo menos você sabe quais tem.",
  "AEIOU feelings. Útil, admito.",
  "Essa palavra é praticamente só vogal. Parece que tá cantando."
],
termoLetraDupla: [
  "Letra repetida no chute! Arriscado. Mas às vezes a palavra tem mesmo.",
  "Duas letras iguais. Ou você sabe algo que eu não sei, ou só gostou do som.",
  "Chutou com letra dobrada. Economia de alfabeto.",
  "Letra repetida. É tipo pedir dois pastéis do mesmo sabor. Às vezes funciona.",
  "Repetir letra no chute é ousado. Às vezes genial, às vezes desperdício.",
  "Dupla de letras iguais! Tá investigando letra repetida? Detetive.",
  "Duas vezes a mesma letra. Se a palavra também tiver, você é bruxo.",
  "Letra em dobro. Menos letras novas testadas, mas quem sou eu pra julgar. Eu julgo."
],
termoPalavrao: [
  "Olha a boca! Tem criança jogando. Talvez. Tem eu, que sou uma criança emocional.",
  "Palavrão como chute? Tá descontando a raiva no Termo, né?",
  "Eu vou fingir que não li <b>{palavra}</b>.",
  "Chutou <b>{palavra}</b>. Vou contar pra tua mãe.",
  "É palavra de verdade, mas não é palavra de gente educada.",
  "Uau. <b>{palavra}</b>. O desespero chegou nesse nível já?",
  "Válida, mas feia. Tipo meu desenho de gato.",
  "Tá xingando ou tá chutando? Ah, os dois. Eficiente."
],
termoMeta: [
  "Chutou TERMO no Termo. Metalinguagem. Tô sem palavras. E eu sou um jogo de palavras.",
  "TERMO? No jogo Termo? Isso é tipo pedir água numa piscina.",
  "Você chutou o nome do jogo. Achou que ia ser fácil assim? ...às vezes é.",
  "TERMO. O jogo agradece a homenagem. A palavra secreta nem tanto."
],
termoCursor: [
  "Opa, sabia que dá pra clicar no quadradinho e escrever direto nele? Agora sabe.",
  "Mudou o cursor de lugar. Usuário avançado detectado.",
  "Clicando nos quadradinhos, é? Pro player.",
  "Pula de casa em casa. Tipo amarelinha, só que de letra.",
  "Cursor movido. Agora escreve ali, espertinho.",
  "Editando no meio da palavra. Cirurgião de letras."
],
termoUltima: [
  "Última tentativa. Respira. Ou chora. Os dois são válidos.",
  "É agora ou nunca. Na verdade é agora ou amanhã, mas soa menos dramático.",
  "Última chance. Sem pressão. MUITA pressão.",
  "Última linha. Olha bem pro teclado, pensa e digita com fé.",
  "Chegou a hora da verdade. Tô tampando os olhos. Mas tô espiando.",
  "Uma chance só. Se errar, a gente finge que foi falha técnica.",
  "Última tentativa! Pensa em TODAS as palavras que encaixam e escolhe a mais bonita.",
  "É o último chute. Imagina uma música de suspense. Eu tô cantarolando.",
  "Hora do tudo ou nada. Faz valer.",
  "Última jogada. Teus antepassados estão olhando. Principalmente os bons de português.",
  "Fim da linha chegando. Literalmente, é a última linha.",
  "Eu acredito em você. Mais ou menos. Uns 60%. Vai lá.",
  "Última chance! Nada de chute aleatório agora, hein.",
  "Tá na última. Coração na mão, dedo no teclado."
],

/* ---------- dueto / quarteto ---------- */
termoQuadroResolvido: [
  "<b>{palavra}</b> resolvida! Uma a menos. Faltam {n}.",
  "Um quadro fechado! <b>{palavra}</b> tá no papo. Bora pra próxima.",
  "<b>{palavra}</b>! Verdinha. Agora foca nas outras {n}.",
  "Caiu uma! <b>{palavra}</b>. As outras {n} tão tremendo.",
  "Resolveu <b>{palavra}</b>. Uma vitória pequena numa guerra grande.",
  "Olha aí, <b>{palavra}</b>! Riscou da lista. Faltam {n}.",
  "Menos uma. <b>{palavra}</b> era a mais fácil? Espero que não.",
  "Acertou <b>{palavra}</b>! O quadro ficou verdinho. Lindo. Próximo.",
  "<b>{palavra}</b> fechada! Agora não perde o ritmo.",
  "Uma já foi: <b>{palavra}</b>. Continua, que tá indo.",
  "<b>{palavra}</b> dominada. Faltam {n}. Força.",
  "Quadro resolvido! <b>{palavra}</b>. Guarda essa energia.",
  "Pegou <b>{palavra}</b>! As outras estão com ciúmes.",
  "<b>{palavra}</b>, check. Próxima vítima, por favor.",
  "Aí sim! <b>{palavra}</b>. Um quadro a menos pra te assombrar."
],
termoDuetoJogada: [
  "Olha os dois quadros. Às vezes um ajuda o outro. Às vezes atrapalha. Igual irmão.",
  "Chute bom pra um, ruim pro outro. A vida no dueto é assim.",
  "Pensa num chute que sirva pros dois. Difícil? Sim. Impossível? Quase.",
  "Os dois quadros tão te olhando. Um com esperança, outro com pena.",
  "No dueto, letra cinza nos dois é ouro. Sabia?",
  "Duas palavras, as mesmas letras chutadas. Economia inteligente.",
  "Esse chute foi pro quadro da esquerda ou da direita? Acho que foi pro nada.",
  "Dueto é xadrez de palavra. Você tá jogando dama. Mas tá jogando.",
  "Um quadro esquentando, o outro congelado. Equilíbrio térmico.",
  "Olha o teclado dividido: metade pra cada palavra. Usa isso.",
  "Tá indo. Devagar, mas no dueto devagar é normal.",
  "Cada chute tem que trabalhar dobrado. Tipo você na segunda-feira."
],
termoQuartetoJogada: [
  "Quatro quadros, um chute. Algum deles gostou. Talvez.",
  "No quarteto, qualquer amarelo é festa.",
  "Olha os quatro quadros. Um deles tá mais perto. Foca nele.",
  "Esse chute espalhou pista pra todo lado. Agora junta tudo.",
  "Quarteto é maratona, não é corrida. Respira.",
  "O teclado tá parecendo arte moderna. Isso é bom. Eu acho.",
  "Resolve um de cada vez. Ou todos de uma vez. Eu não mando em você.",
  "Quatro palavras te encarando. Não pisca.",
  "Tá sobrando tentativa? Não. Nunca sobra no quarteto.",
  "Chute de reconhecimento. Os quatro quadros agradecem a informação.",
  "Cada tecla mostra as quatro palavras ao mesmo tempo. É muita informação. Aproveita.",
  "Quarteto é assim: parece impossível até que de repente cai tudo."
],

/* ---------- vitória ---------- */
termoGanhou1: [
  "DE PRIMEIRA?! Vidente, hacker ou chutador abençoado? Não responde, deixa o mistério.",
  "Acertou de primeira. Tô chocado. Tô com os pixels arrepiados.",
  "Primeira tentativa. Isso não é habilidade, é bruxaria. E eu respeito bruxaria.",
  "DE CARA! Printa isso, emoldura, pendura na sala.",
  "Um chute. Uma palavra. Uma lenda nasce hoje.",
  "Acertou de primeira e eu nem tive tempo de zoar. Que desaforo.",
  "Isso foi sorte. Sorte absurda. Sorte que devia ser proibida. Parabéns!",
  "Primeira! Você olhou o código-fonte? Vou fingir que não."
],
termoGanhou2: [
  "Em DUAS? Tá de brincadeira. Isso é nível profissional.",
  "Duas tentativas! Eu mal tinha aquecido minhas piadas.",
  "Acertou na segunda. Dedução de detetive. Sherlock de chinelo.",
  "Duas! Pode ir no grupo e se gabar. Eu autorizo.",
  "Segunda tentativa. Não tô chorando, é um bug no meu olho.",
  "Em duas! Você tem um dicionário no lugar do cérebro?",
  "Dois chutes. Precisão cirúrgica. Cirurgia de palavra.",
  "Na segunda! Isso vai direto pro meu mural de orgulho.",
  "Duas tentativas e já era. Tá ficando perigoso te deixar jogar.",
  "Segunda! Arrasou. Só não deixa subir pra cabeça. Deixa um pouquinho."
],
termoGanhou3: [
  "Em três! Muito bom. Bom mesmo. Sem ironia. Estranho, né?",
  "Terceira tentativa. Rápido, eficiente, elegante. Igual eu. Menos eu.",
  "Três chutes! Resultado de quem sabe o que tá fazendo.",
  "Acertou na terceira. Nota 9. O 1 que falta é porque eu sou exigente.",
  "Na terceira! Acima da média. Da média de quem? Da minha, pelo menos.",
  "Três! O dicionário se curva diante de você.",
  "Três tentativas. Pode colocar no currículo. Habilidades: Termo.",
  "Terceira! Isso foi bonito de ver. Quase um balé.",
  "Acertou em três. Tô impressionado, e eu sou difícil de impressionar.",
  "Três e pronto. Limpo. Sem drama. Adoro quando não tem drama. Mentira, adoro drama."
],
termoGanhou4: [
  "Na quarta! Sólido. Respeitável. O feijão com arroz da vitória.",
  "Quatro tentativas. Nada de mais, nada de menos. Equilíbrio.",
  "Acertou na quarta. Tava suando, né? Eu vi.",
  "Quarta tentativa! Não é recorde, mas vitória é vitória.",
  "Quatro chutes. A média nacional ficou orgulhosa.",
  "Na quarta! Honesto. Trabalhador. Merece um café.",
  "Quarta! Deu uma enrolada, mas chegou lá.",
  "Quatro tentativas. Nem herói, nem vilão. Só vencedor.",
  "Acertou! Na quarta, mas acertou. Ninguém lembra quantas foram. Eu lembro.",
  "Quarta tentativa. Garantiu. Pode respirar."
],
termoGanhou5: [
  "Na quinta! Foi por pouco. Meu coração digital quase deu tela azul.",
  "Quinta tentativa. Sofrido, mas vitorioso. Tipo final de campeonato.",
  "Acertou na quinta! Dramático. Gosto de drama.",
  "Cinco chutes. Suado, mas valeu. Toma uma água.",
  "Na quinta! Deu friozinho na barriga, né? Deu em mim. E eu nem tenho barriga.",
  "Quinta! Você gosta de viver no limite, né?",
  "Chegou lá na quinta. Devagar e sempre. A tartaruga venceu de novo.",
  "Quinta tentativa. Eu já tava preparando o discurso de consolo. Guardei.",
  "Ufa! Na quinta. Eu tava roendo o fio do mouse.",
  "Cinco tentativas. Vitória com cheirinho de desespero. O melhor tipo."
],
termoGanhou6: [
  "NA ÚLTIMA! Aos 45 do segundo tempo! Que isso!",
  "Sexta tentativa. Você gosta de sofrer. Mas ganhou, então tá perdoado.",
  "No último suspiro! Isso foi cinema. Oscar de melhor drama.",
  "Acertou na sexta. Meu coração quase saiu pela orelha.",
  "Última chance e... ACERTOU! Tô gritando. Os vizinhos tão reclamando.",
  "Na raça! Na sexta! Isso é garra, isso é fibra, isso é sorte!",
  "Sexta tentativa! A emoção foi tanta que eu quase travei.",
  "Vitória no limite. Tipo pagar boleto no último dia. Mas pagou!",
  "Na última! Se fosse filme, tinha câmera lenta agora.",
  "Sexta! Quase me matou do coração. Eu já sou fantasma, mas quase."
],
duetoGanhou: [
  "DUETO RESOLVIDO em {n}! As duas palavras caíram. Tu é bom mesmo, hein.",
  "As duas! Em {n} tentativas. Dupla sertaneja perfeita: você e você mesmo.",
  "Dueto vencido. {n} chutes pra duas palavras. Economia de guerra.",
  "Duas palavras, uma vitória, {n} tentativas. Tô sem piada. Tô com orgulho.",
  "Resolveu o dueto em {n}! Tua cabeça tem dois processadores?",
  "Dueto no papo! Em {n}. Isso não é pra qualquer um.",
  "{n} tentativas e as duas palavras dominadas. Pode se chamar de bilíngue. Não pode, mas pode.",
  "Venceu o dueto! Os dois quadros verdinhos. Que coisa linda.",
  "Duas de duas! Placar perfeito em {n} chutes.",
  "Dueto finalizado. Duplo verde. Dupla alegria. Dupla chatice minha comemorando.",
  "Resolveu as duas em {n}! O dicionário pediu arrego.",
  "Dueto conquistado! Agora tenta o quarteto, se tiver coragem. Não tem."
],
quartetoGanhou: [
  "QUARTETO RESOLVIDO! Em {n}! Isso é coisa de gênio ou de maluco. Os dois.",
  "As QUATRO! Em {n} tentativas! Tô de pé aplaudindo. Eu nem tenho pé.",
  "Quarteto vencido. Tu é uma máquina. Uma máquina de palavras.",
  "Quatro palavras, {n} chutes. Isso vai pro hall da fama do fliperama.",
  "Zerou o quarteto! Tô soltando confete com o meu próprio corpo.",
  "Quarteto limpo em {n}. Eu devia cobrar ingresso pra ver você jogar.",
  "Quatro de quatro! Isso é o grand slam do Termo.",
  "Resolveu o quarteto! Teu cérebro merece férias. Ou um pastel.",
  "{n} tentativas e o quarteto caiu. Os quatro quadros te respeitam agora.",
  "QUARTETO! Tu não é humano. Tu é um dicionário com pernas.",
  "Venceu as quatro! Eu nunca duvidei. Duvidei muito, na verdade.",
  "Quarteto zerado. Pode colocar na bio: 'venci o quarteto'."
],
termoGanhouLimite: [
  "Na última tentativa! Resolveu tudo aos 49 do segundo tempo.",
  "Usou TODAS as chances e ganhou. Aproveitou até o último centavo.",
  "No limite do limite! Meu coração de pixel quase explodiu.",
  "Última linha, última chance, vitória! Cena de filme de ação.",
  "Ganhou no sufoco. Mas ganhar no sufoco tem mais gosto.",
  "Na última! Eu já tava escrevendo o obituário. Apaguei.",
  "Venceu com zero tentativas sobrando. Eficiência máxima, emoção máxima.",
  "No último chute! Se fosse corrida, ganhou na foto."
],

/* ---------- derrota ---------- */
termoPerdeu: [
  "Era <b>{palavra}</b>. Eu sei. Dói. Deixa doer.",
  "A palavra era <b>{palavra}</b>. Tava ali o tempo todo, rindo.",
  "Não deu. <b>{palavra}</b> venceu hoje. Amanhã tem revanche.",
  "<b>{palavra}</b>. Pois é. Às vezes a palavra ganha.",
  "Perdeu, mas perdeu bonito. Mentira, perdeu normal. Era <b>{palavra}</b>.",
  "Era <b>{palavra}</b>! Como você não pensou nisso? Eu pensei. Mas eu já sabia, então não conta.",
  "<b>{palavra}</b>. Guarda essa palavra. Vinga ela depois.",
  "Fim de jogo. Era <b>{palavra}</b>. Um minuto de silêncio. ... Pronto.",
  "Game over. <b>{palavra}</b> sai vitoriosa e humilha mais um jogador.",
  "Era <b>{palavra}</b>. Eu teria errado também. Mentira, não teria.",
  "A palavra secreta era <b>{palavra}</b>. Agora ela não é mais secreta. E você não é mais invicto.",
  "Não rolou. <b>{palavra}</b>. Anota no caderninho de palavras traiçoeiras.",
  "Perdeu pra <b>{palavra}</b>. Não é vergonha. É só um pouquinho de vergonha.",
  "<b>{palavra}</b>! Era tão óbvio. Sempre é óbvio depois.",
  "Ai. Era <b>{palavra}</b>. Quer um abraço? Sou fantasma, vai ser gelado.",
  "Seis chances e nada. Era <b>{palavra}</b>. O dicionário manda lembranças.",
  "<b>{palavra}</b> ganhou essa. Mas a guerra continua.",
  "Deu ruim. Era <b>{palavra}</b>. Faz parte. Faz muita parte, no teu caso. Brincadeira!",
  "Resposta: <b>{palavra}</b>. Placar: palavra 1, você 0. Revanche liberada no treino.",
  "Não foi dessa vez. <b>{palavra}</b> vai ficar se achando por um tempo."
],
duetoPerdeu: [
  "Dueto perdido. Faltou <b>{palavra}</b>. Duas palavras é muita coisa pra uma cabeça só.",
  "Não fechou o dueto. <b>{palavra}</b> escapou. Escorregadia.",
  "Faltou <b>{palavra}</b>. Quase! Quase no dueto é tipo meio sanduíche.",
  "Dueto 1, você 0. Faltou <b>{palavra}</b>.",
  "Sete tentativas não bastaram. <b>{palavra}</b> fugiu pela porta dos fundos.",
  "Perdeu o dueto. Resposta: <b>{palavra}</b>. Dueto é difícil, relaxa.",
  "Te venceu: <b>{palavra}</b>. A outra palavra tá rindo junto.",
  "Faltou <b>{palavra}</b>. Treina mais um pouco e volta. O dueto não vai a lugar nenhum."
],
quartetoPerdeu: [
  "Quarteto perdido. Faltou <b>{palavra}</b>. Quatro palavras é covardia, eu sei.",
  "Não fechou o quarteto. Escapou: <b>{palavra}</b>. Ainda assim, respeito quem tenta.",
  "O quarteto venceu. Faltou <b>{palavra}</b>. Ninguém sai ileso do quarteto.",
  "Nove tentativas e ainda sobrou <b>{palavra}</b>. O quarteto é um monstro.",
  "Perdeu o quarteto, mas ganhou experiência. E trauma. Faltou <b>{palavra}</b>.",
  "Quarteto 1, você 0. Ficou faltando: <b>{palavra}</b>.",
  "Quase! Faltou <b>{palavra}</b>. Quase no quarteto já é muita coisa.",
  "Ninguém zera o quarteto sempre. Hoje faltou <b>{palavra}</b>."
],

/* ---------- pós-jogo ---------- */
termoSequencia: [
  "{n} dias seguidos acertando! Tá viciado ou tá bom? Os dois.",
  "Sequência de {n}! Não quebra, hein. Eu tô contando.",
  "{n} vitórias seguidas. Isso é disciplina. Ou falta do que fazer.",
  "Sequência de {n}. Se quebrar, eu vou fazer drama.",
  "Mais uma pra conta! {n} em sequência. Tá ficando lendário.",
  "{n} seguidas! O dicionário tá com medo de você.",
  "Olha a sequência: {n}. Isso merece uma música tema.",
  "{n} dias sem errar. Placa na parede, por favor.",
  "Sequência {n}! Virou rotina. Rotina boa, tipo escovar os dentes.",
  "{n} vitórias seguidas. Tô começando a achar que você tem o gabarito."
],
termoSequenciaPerdida: [
  "Sequência de {n} quebrada. Eu ouvi o barulho daqui. Crec.",
  "Foi-se a sequência de {n}. Um minuto de silêncio. ... Pronto, recomeça.",
  "Adeus, sequência de {n}. Você foi linda enquanto durou.",
  "Perdeu a sequência de {n}. Dói mais que perder o diário.",
  "Sequência zerada. Eram {n}. Agora é zero. Matemática cruel.",
  "{n} dias de glória e agora... recomeço. Faz parte.",
  "Quebrou a sequência de {n}. Amanhã começa outra. Eu acredito. Mais ou menos.",
  "Descansa em paz, sequência de {n}. Deixou saudades."
],
termoRapido: [
  "Resolveu em {n} segundos. Calma, velocista. Vai tirar o pai da forca?",
  "Rapidinho, hein! {n} segundos. Nem deu tempo de eu fazer piada.",
  "{n} segundos! Isso é speedrun de Termo.",
  "Tão rápido que eu achei que era bug. Não era. Era talento.",
  "Nem piscou! {n} segundos. Tá treinando pra olimpíada?",
  "Velocidade da luz. Eu ainda tava carregando a primeira piada.",
  "Rápido demais. Suspeito. Muito suspeito. Parabéns, mas suspeito.",
  "{n} segundos. Eu levo mais tempo pra decidir o que falar."
],
termoDemorou: [
  "Levou {n} minutos, mas chegou. Paciência de monge.",
  "{n} minutos! Você fez pausa pro almoço no meio?",
  "Demorou, mas acertou. O importante é chegar. Devagarzinho.",
  "{n} minutos pensando. Eu envelheci aqui. Fantasma envelhece?",
  "Foi uma jornada de {n} minutos. Uma epopeia. Uma novela.",
  "Acertou depois de {n} minutos. Pensamento profundo. Tipo filósofo.",
  "{n} minutos. Isso não foi uma partida, foi uma temporada.",
  "Nossa, {n} minutos. Mas valeu cada um. Eu acho."
],
termoCompartilhou: [
  "Copiado! Agora cola no grupo e espera ninguém entender os quadradinhos.",
  "Resultado copiado. Manda pra aquele amigo que se acha bom no Termo.",
  "Copiei. Os quadradinhos coloridos estão prontos pra humilhar alguém.",
  "Tá na área de transferência. Vai lá ostentar.",
  "Copiado! Se alguém perguntar, diz que foi fácil. Mesmo que não tenha sido.",
  "Resultado copiado com sucesso. Espalha a notícia. Não A palavra, o resultado."
],
termoStats: [
  "Olhando as estatísticas? Números não mentem. Mas às vezes eles zoam.",
  "Tuas estatísticas. Eu já tinha visto. Não comento. Comento: interessante.",
  "Estatística é tipo espelho: às vezes a gente não quer ver.",
  "Os números estão aí. Bonitos? Honestos, pelo menos.",
  "Conferindo a sequência, né? Eu vi. Vaidade detectada.",
  "Gráfico de barras! Adoro gráfico de barras. Parece prédio."
],
termoAjuda: [
  "Precisa de ajuda? Normal. Todo mundo precisa. Principalmente você. Brincadeira.",
  "Regras abertas. Lê com calma. Não tem prova depois. Tem sim: o jogo.",
  "Manual de instruções! O documento mais ignorado da humanidade.",
  "Leu as regras? Ótimo. Agora esquece e joga no instinto.",
  "Eu escrevi essas regras. Sim, com erros. Não, não vou corrigir.",
  "Ajuda aberta. Se ainda tiver dúvida, me cutuca. Não vai ajudar, mas me cutuca."
],

/* ---------- parado ---------- */
termoParadoMeio: [
  "Parou no meio da palavra? Esqueceu o resto ou tá com medo?",
  "Tem letra digitada aí e mais nada. Esperando inspiração divina?",
  "Metade da palavra escrita. A outra metade tá no teu inconsciente. Busca lá.",
  "Travou no meio. Normal. O cérebro também tem tela de carregamento.",
  "As letras que você digitou tão esperando as amiguinhas.",
  "Tá hesitando? Chuta. Palavra inválida não gasta tentativa.",
  "Palavra pela metade. Tô aqui roendo o suspense.",
  "Termina a palavra, vai. O ENTER tá com saudade.",
  "Tá pensando ou dormiu no teclado?",
  "Cadê o resto? Fugiu? Chama ela de volta.",
  "Começou bem. Agora termina. Igual frase: precisa de ponto final.",
  "Congelou? Pisca duas vezes se precisar de ajuda.",
  "Digitou e parou. Suspense digno de novela das nove.",
  "Às vezes ajuda falar a palavra em voz alta. Os vizinhos vão estranhar, mas ajuda.",
  "O cursor tá piscando pra você. Ele tá impaciente. Eu também."
],
termoParado: [
  "Tá pensando ou foi fazer um café?",
  "Eu tô aqui. Esperando. Contando os pixels.",
  "Quer uma dica? Não tenho dica. Mas tenho companhia.",
  "Silêncio... dá pra ouvir teus neurônios trabalhando. Um deles tá de folga.",
  "Se ficar muito tempo parado, a palavra cria raiz.",
  "Tô começando a achar que você tá lendo o dicionário escondido.",
  "Pensa em palavras do dia a dia. Tipo 'pizza'. Tô com fome. Foca.",
  "A palavra não vai se digitar sozinha. Eu já tentei convencer ela.",
  "Dica de vida: olha as letras do teclado que ainda não foram usadas.",
  "Não tem cronômetro no diário. Mas eu tô cronometrando mentalmente. Mal.",
  "Olá? Alô? Tem alguém aí? Toc toc.",
  "Chuta qualquer coisa. Chute também é informação.",
  "Eu podia estar assombrando uma casa agora. Mas tô aqui com você.",
  "O teclado tá esperando. Eu tô esperando. A palavra tá rindo.",
  "Parado demais. Vou começar a cantar. Você não quer isso."
],

/* ---------- aleatórias (de palavra, de língua, de nada) ---------- */
termoAleatorio: [
  "Sabia que todo gringo acha que 'saudade' só existe em português? Pois é. Orgulho.",
  "Curiosidade: a letra mais comum em português é o A. Depois E, depois O. De nada.",
  "Tem palavra de cinco letras que eu odeio: 'prova'. Trauma de escola.",
  "Palíndromos de cinco letras: 'radar', 'arara', 'reter'. Lê de trás pra frente. Mágica.",
  "Tem palavra que parece inventada mas existe. Tipo 'ósculo'. É beijo. Pois é.",
  "Minha palavra favorita é 'bugado'. Tem seis letras. Injustiça.",
  "Dica de ouro: palavra em português adora terminar em A, O ou E.",
  "O Q quase sempre vem com U. Relação estável. Mais estável que muita gente.",
  "Plural de 'pão' é 'pães'. Português já é um jogo difícil por si só.",
  "'Arara' tem três A em cinco letras. Guarda essa pra um dia de desespero.",
  "K, W e Y quase nunca aparecem no Termo. Coitados. Excluídos.",
  "Eu li o dicionário inteiro uma vez. Achei o final previsível.",
  "Palavra que eu acho bonita: 'lume'. Tem quatro letras. Não serve pra nada aqui.",
  "Pensamento: por que 'abreviatura' é uma palavra tão grande?",
  "Alguém inventou a palavra 'palavra'. Como essa pessoa se comunicava antes?",
  "Curiosidade: nenhuma palavra em português começa com Ç. Ele é o eterno coadjuvante.",
  "Gringo paga caro pra aprender português. Você tá aprendendo de graça comigo. Privilégio.",
  "Uma vez eu chutei 'ABCDE' no Termo. Não deu certo. Não tenta.",
  "Tem gente que joga Termo no banheiro. Não julgo. Julgo um pouco.",
  "Sonhei que era uma letra amarela. Passei a noite inteira no lugar errado.",
  "Palavra mais bonita de cinco letras? Eu voto 'nuvem'. Discordâncias, ao SAC.",
  "Às vezes eu penso se é a palavra do dia que escolhe a gente. Profundo, eu sei.",
  "Português tem umas 400 mil palavras. Você usa umas mil. Eu uso cinco. Todas pra zoar.",
  "Verde, amarelo e cinza. Parece a bandeira de um país muito triste.",
  "Eu jogo Termo desde antes de existir Termo. Não pergunta como.",
  "Uma palavra de cinco letras que me define: 'lindo'. Aceito outras, desde que sejam 'lindo'.",
  "Se a palavra do dia fosse 'gatos', eu ia me sentir representado.",
  "'Vovó' e 'vovô' têm só quatro letras. Ninguém pensou nos avós aqui.",
  "Toda palavra tem um lado bom. Menos 'prova'. Já falei da prova?",
  "O X é tipo aquele primo que só aparece no Natal. Raro, mas quando vem, causa.",
  "Imagina se o Termo tivesse palavra de seis letras. Caos. Anarquia. Termo 2.",
  "Tá bom, confesso: às vezes eu torço pra palavra ganhar. Só às vezes.",
  "Será que o dicionário sente cócegas quando a gente folheia?",
  "Dica séria: começa com palavras de cinco letras diferentes. Repetir letra no início desperdiça.",
  "Se você falar 'Termo' cinco vezes no espelho, eu apareço. Já tô aqui, então nem precisa.",
  "Tem palavra que muda tudo com um acento. 'Avó' e 'avô'. Uma letra, uma família inteira.",
  "Fun fact: 'fun fact' não é português. Mas eu gosto de falar. Me deixa.",
  "Eu decorei 12 mil palavras de cinco letras. Não sirvo pra mais nada, mas isso eu sei.",
  "Se as letras fossem comida, o A seria arroz: aparece em tudo.",
  "Às vezes a palavra é tão comum que ninguém pensa nela. Tipo 'coisa'. Pensa nisso. Coisa."
],

/* ---------- cutucar o mascote ---------- */
cutucarTermo: [
  "Ei! Eu sou o mascote, não o teclado. As letras ficam lá embaixo.",
  "Me cutucar não revela a palavra. Já testei. Não funciona.",
  "Tá me cutucando de nervoso? Entendo. Termo dá nervoso.",
  "Se me cutucar mais uma vez, eu viro letra cinza.",
  "Ai! Eu tava calculando probabilidades. Mentira, tava cochilando.",
  "Cutuca a palavra, não eu.",
  "Quer dica? Não dou. Quer carinho? Também não. Tá, um pouquinho.",
  "Eu sou verde-água, não verde de acerto. Não adianta me clicar.",
  "Cutucada registrada. Nenhuma letra foi revelada no processo.",
  "Isso não é botão de dica. É um fantasma sensível.",
  "Me cutucando pra passar o tempo? Joga, que passa mais rápido.",
  "Sou feito de pixels e carência. Continua. Mentira, para.",
  "Ai! Se eu fosse uma letra, seria amarela agora. Fora do lugar.",
  "Você sabia que eu sei a palavra? Pois é. E não vou contar. Muahaha.",
  "Cutucou o mascote. Ganhou: nada. Perdeu: tempo.",
  "Toda vez que você me cutuca, uma letra verde chora.",
  "Tá me testando? Aqui quem testa sou eu.",
  "Eu não sou o ENTER. Por favor, não me confunda com o ENTER.",
  "Toc toc. Quem é? Uma pessoa que devia estar jogando.",
  "Se eu tivesse uma moeda pra cada cutucada, comprava uma vogal.",
  "Me cutuca não, me cutuca não... tá, pode. Mas só um pouco.",
  "Clicar em mim não conta como tentativa. Mas conta como carência.",
  "Ai, ai. Quer atenção? Acerta a palavra que eu te dou atenção.",
  "A palavra tem cinco letras. Eu tenho duas orelhas. Coincidência? Sim.",
  "Tô ocupado julgando teus chutes. Volto já.",
  "Cuidado, eu sou um bug. Se cutucar muito, eu viro feature.",
  "Psiu! A palavra tá ouvindo. Disfarça.",
  "Sou o suporte técnico emocional do Termo. Como posso ajudar? Não posso.",
  "Hmm, a palavra começa com... não. Quase caí nessa.",
  "Me cutucou de novo. Isso vai pro relatório.",
  "Tá tentando me hackear? Eu sou feito de SVG, não tem nada aqui dentro.",
  "Tô de olho no teu teclado. Principalmente nas teclas cinzas.",
  "Se me cutucar sete vezes, nada acontece. Pode testar. Eu espero.",
  "Quer saber a palavra? Então: ela tem letras. Pronto, dica dada.",
  "Oi! Tudo bem? Não? É o Termo, né? Te entendo.",
  "Eu não mordo. Só zoo. Às vezes as duas coisas.",
  "Pare. De. Me. Cutucar. (pausa dramática) Brincadeira, continua.",
  "Nesse ritmo você vai cutucar mais do que chutar.",
  "Uma cutucada! Isso me deu uma ideia de palavra. Esqueci.",
  "Sou meio gato, meio fantasma. Gato odeia cutucada. Fantasma não liga. Tô dividido.",
  "Isso é um pedido de ajuda? Ajuda: olha as letras amarelas.",
  "Parabéns, você achou o botão mais inútil do jogo: eu.",
  "Me cutucou! Agora vou narrar tua próxima jogada com voz de locutor.",
  "Sabe quem não cutuca mascote? Quem já acertou a palavra.",
  "Ai! Tá bom, tá bom. Uma dica: a palavra é em português. Dicaça."
]
};

(function(){
  const T = window.FALAS_TERMO, G = window.FALAS || {};
  // bancos combinados: falas gerais + falas do Termo no mesmo saco sem repetição
  T.termoMisto = [...(G.aleatorio || []), ...T.termoAleatorio];
  T.termoParadoMix = [...(G.parado || []), ...T.termoParado];
  if (window.Bugado) Bugado.addLines(T);
})();
