/* ==========================================================
   Falas do Bugado no Soletra.
   Variáveis: {palavra}, {centro}, {letra}, {letras}, {n}, {pts}, {rank}, {total}
   O sorteio (Bugado.line) só repete depois de esgotar a categoria.
   ========================================================== */
window.FALAS_SOLETRA = {

/* ---------- chegada / retorno ---------- */
solOi: [
  "Soletra do dia no ar. Sete letras, uma no meio mandando em tudo. Igual síndico.",
  "Bem-vindo à colmeia. Aqui a abelha rainha é a letra amarela. Respeita ela.",
  "Hoje tem {n} palavras escondidas nessa colmeia. Eu sei todas. Não conto nenhuma.",
  "Sete letras, zero desculpas. Bora soletrar.",
  "Chegou a hora de provar que teu vocabulário vai além de ‘kkkkk’.",
  "A letra do meio é a {centro}. Toda palavra tem que ter ela. Sem exceção, sem choro.",
  "Colmeia nova, mel novo. O mel é metafórico. Não lambe a tela.",
  "Soletra diário: igual pra todo mundo. Se teu primo fizer mais ponto, a culpa é tua.",
  "Tem pelo menos um pangrama aí. Uma palavra com as sete letras. Acha se for capaz.",
  "Digita, clica, sofre. Nessa ordem.",
  "Aquece o dedo: hoje tem {n} palavras pra caçar.",
  "Hoje as letras são {letras}. Parece sopa de letrinhas que deu errado. Mas dá pra fazer coisa.",
  "Eu li o dicionário inteiro pra montar isso. Mentira, eu sou um bug. Mas li um pedaço.",
  "Regra de ouro: quatro letras ou mais, letra do meio sempre. Regra de prata: me dar atenção.",
  "Zzzz... ah, oi! Colmeia pronta. Bora zumbir.",
  "Achar palavra é fácil. Achar TODAS é que separa gente comum de Gênio Bugado."
],
solVoltou: [
  "Voltou! Tuas {n} palavras tão guardadinhas aqui. Não perdi nenhuma. Quase perdi uma.",
  "Olha quem voltou pra colmeia. Achei que a abelha tinha te picado.",
  "Tu tá em {rank}. Dá pra subir. Sempre dá pra subir.",
  "Salvei tudo. Pode continuar de onde parou. Eu não julgo. Julgo sim.",
  "Foi buscar inspiração no banheiro? Todo mundo faz isso. Voltou com palavra nova?",
  "Bem-vindo de volta. As letras não saíram do lugar. Quer dizer, eu embaralhei um pouquinho. Mentira.",
  "Retornou! A colmeia sentiu tua falta. Eu não. Talvez um pouco.",
  "Continua daí: {n} palavras e contando. Ou parando. Depende de ti.",
  "Opa, reapareceu. Pensou em alguma palavra no caminho? Diz que sim.",
  "A colmeia tava quietinha sem você. Quieta demais. Até estranhei.",
  "Voltou no {rank}. Posição respeitável. Pra quem tá começando.",
  "Tua cadeira tava quentinha ainda. Senta aí e soletra."
],
solTreino: [
  "Modo treino: colmeia aleatória, sem pressão, sem ranking do primo.",
  "Treino é tipo academia: ninguém vê, mas faz bem pro ego.",
  "Colmeia sorteada. Pode errar à vontade, só eu tô olhando. E eu conto pra todo mundo.",
  "Treino liberado. Aqui a letra do meio é a {centro}. Não esquece dela.",
  "Ninguém vai comparar teu treino. É só você, eu e {n} palavras escondidas.",
  "Bora aquecer. Treino bem feito vira Gênio Bugado no diário.",
  "Sorteei essa colmeia de olho fechado. Se ficar difícil, reclama com o sorteio.",
  "Treino infinito. Tenho {total} colmeias guardadas. Não vai acabar tão cedo.",
  "Treino é o lugar certo pra testar palavra esquisita. Testa.",
  "Colmeia de treino na mesa. Quer mel? Trabalha.",
  "Sem diário, sem compromisso. Relacionamento aberto com as letras.",
  "Treininho? Adoro. Posso te zoar sem culpa."
],
solTreinoFeito: [
  "Essa colmeia de treino já acabou. Aperta ‘Nova colmeia’ que eu sorteio outra.",
  "Treino encerrado. Quer mais? Tenho um estoque infinito de colmeias. Quase infinito.",
  "Essa aqui já foi. Nova colmeia no botão amarelo, sem custo, sem fila.",
  "Colmeia de treino finalizada. Bora pra próxima antes que o cérebro esfrie.",
  "Acabou essa. O bom do treino é que sempre tem outra."
],
solDiarioFeito: [
  "O diário de hoje já era. Amanhã tem outro. Enquanto isso: treino.",
  "Você já fechou a colmeia de hoje. Quer mais? O treino tá logo ali.",
  "Hoje já foi. Pode ficar olhando as respostas com saudade.",
  "Colmeia de hoje encerrada. Volta amanhã, eu vou estar aqui. Eu sempre estou aqui.",
  "Diário feito. Agora é esperar a meia-noite igual Cinderela ao contrário.",
  "Terminou o de hoje. Tem treino infinito se a abstinência bater.",
  "Já soletrou tudo que tinha pra soletrar hoje. Ou desistiu. Não vou perguntar qual.",
  "O diário fechou. O Bugado não. O Bugado tá sempre aberto. 24 horas.",
  "Acabou por hoje. Vai beber água, olhar o céu, voltar pro treino.",
  "Tu já passou por aqui hoje. Eu lembro. Eu lembro de tudo."
],

/* ---------- palavras válidas ---------- */
solValida4: [
  "{palavra}. Quatro letrinhas, um pontinho. Humilde.",
  "Um ponto! Não é muito, mas é honesto.",
  "{palavra}? Palavra de quatro letras é tipo moeda de 5 centavos. Junta que vira alguma coisa.",
  "Pequena mas vale. Igual eu.",
  "Curtinha e certeira. Gostei.",
  "Mais um tijolinho na tua casa de palavras.",
  "{palavra}: aceita. Não é poesia, mas é ponto.",
  "Palavra de quatro letras: o arroz com feijão do Soletra.",
  "Aceitei {palavra}. Um ponto. Não gasta tudo de uma vez.",
  "Pequena vitória. As pequenas contam. Pouco, mas contam.",
  "Foi no básico e acertou. Respeito o básico.",
  "{palavra}! Quatro letras de pura eficiência.",
  "Um pontinho na conta. O banco aprova.",
  "Tá catando as miudinhas, né? Estratégia de formiga. Funciona.",
  "Essa é daquelas que a gente acha sem querer. Valeu mesmo assim.",
  "Achou {palavra}. O dicionário acena de longe.",
  "Quatro letras, zero drama.",
  "Mini palavra, mini ponto, mega orgulho? Médio orgulho.",
  "É pouco? É. Mas eu já vi gente zerando com menos.",
  "Boa. Agora tenta uma com mais de quatro, pra variar.",
  "{palavra}, mais uma pra coleção de chaveirinho.",
  "Um ponto. Guarda no cofrinho.",
  "Tá valendo! Palavra curta também é palavra.",
  "Rapidinha e válida. O melhor tipo.",
  "Isso. Vai comendo pelas beiradas.",
  "{palavra}. Simples, objetiva, pontuável.",
  "Aceita. Eu queria reclamar, mas não achei motivo.",
  "Tu achou {palavra} e eu achei bonitinho.",
  "Pontinho garantido. Próxima!",
  "Palavra de bolso. Cabe em qualquer lugar."
],
solValida56: [
  "{palavra}! Agora sim, palavra de gente grande.",
  "Boa! {palavra} vale {pts} pontos. Eu faria igual. Eu faria melhor, mas faria igual.",
  "{palavra}. Bonita, útil, pontuável.",
  "Essa foi boa. Tô quase impressionado.",
  "Olha só, {pts} pontos de uma vez. Tá ficando perigoso.",
  "Aceita! {palavra} entra pra lista com honra.",
  "{palavra}? Existe. Tô chocado. Mentira, eu sabia.",
  "Mandou bem. A colmeia agradece.",
  "Palavra média, alegria média-alta.",
  "Isso aí! Mais {pts} pontinhos no bolso.",
  "Ó o vocabulário aparecendo!",
  "{palavra}. Eu vi. Todo mundo viu. Ficou bonito.",
  "Tá pegando o jeito. Ou chutou bem. Não importa, contou.",
  "Palavra aceita e ego inflado. Cuidado com o ego.",
  "{palavra} desbloqueada. Conquista: saber português.",
  "Aí sim! {pts} pontos, sem choro.",
  "Essa eu não esperava de você. No bom sentido. Acho.",
  "Mais uma! A lista tá ficando gordinha.",
  "{palavra}: aprovada pelo comitê de um bug só.",
  "Bonito. Faz de novo que eu não vi direito.",
  "Tá voando. Cuidado pra não bater na colmeia.",
  "{palavra}! Tua professora de português ficaria orgulhosa. Ou assustada.",
  "Boa jogada. {pts} pontos na conta, sem taxa.",
  "Olha, até que você é bom nisso.",
  "Achou {palavra} no meio dessa bagunça de letras. Respeito.",
  "Pontuou! A abelha rainha acenou pra você.",
  "{palavra}. Palavra de respeito. Senta aí, {palavra}.",
  "Isso! Mais uma pra tua coleção particular.",
  "Eu tava torcendo pra alguém achar essa. Você achou.",
  "{pts} pontos. Não é pangrama, mas pagou o lanche.",
  "Anotado: {palavra}. Letra por letra.",
  "Acertou. Tô fingindo que não fiquei feliz.",
  "Esse cérebro tá funcionando hoje, hein.",
  "{palavra}, claro! Como eu não pensei nisso? Eu pensei. Só tava esperando.",
  "Tá virando dicionário ambulante. Dicionário com pernas. Dicionário de tênis."
],
solValida7: [
  "{palavra}! {pts} pontos! Isso é palavra de doutorado.",
  "Uau. {palavra}. Vou precisar sentar.",
  "Palavrão! No bom sentido. Muitas letras.",
  "{palavra}? Tu tá lendo o dicionário escondido?",
  "Isso é que é palavra comprida. {pts} pontos de uma tacada.",
  "Os linguistas aplaudiram de pé. Eu aplaudi sentado. Eu não tenho pé.",
  "Olha o tamanho disso! Mal cabe no balão.",
  "{palavra}. Pausa pra eu recuperar o fôlego.",
  "Palavra longa, pontuação gorda. Adoro economia assim.",
  "Tá de brincadeira. {palavra}? Brabo demais.",
  "Isso foi digitado ou foi recitado?",
  "{pts} pontos! Tu tá jogando Soletra ou minerando bitcoin?",
  "Palavra desse tamanho merece tapete vermelho.",
  "{palavra}. Fiquei até com inveja. Eu, um bug, com inveja. Anota aí.",
  "Esse vocabulário tá fazendo academia, hein?",
  "Que palavra. Que momento. Que dedo.",
  "{palavra}! O corretor ortográfico te respeita agora.",
  "Comprida e certinha. Igual fila de banco com senha.",
  "Olha a pessoa usando palavra enorme como se fosse nada.",
  "A colmeia tremeu. Foi a {palavra}. Palavra pesada.",
  "Isso aí é palavra de quem lê bula de remédio por diversão.",
  "{palavra}. Quase um pangrama. Quase. Tipo quase ganhar na loteria.",
  "Mais letras, mais pontos, mais eu fingindo que não tô impressionado.",
  "Tô de queixo caído. Figurativamente. Eu tenho queixo? Tenho.",
  "Achou {palavra} e ganhou {pts} pontos. Fez o dia render.",
  "Esse é o tipo de palavra que eu queria que você achasse. Tá aprendendo.",
  "Grande palavra. Grande pessoa? Vamos ver nas próximas.",
  "{palavra}! Palavra com cheiro de redação nota mil.",
  "Eita. Isso foi bonito até pra mim.",
  "Tanta letra junta e nenhuma errada. Milagre linguístico."
],
solLonga: [
  "{palavra}?! Isso não é palavra, é trem!",
  "Dez letras ou mais. Eu contei. Duas vezes. Deu certo.",
  "{palavra}. Precisei rolar o balão pra ler tudo.",
  "Palavra desse tamanho devia pagar aluguel no dicionário.",
  "Tu escreveu {palavra} sem errar. Eu não conseguiria. Eu sou um bug.",
  "Isso aqui é palavra ou senha de wi-fi?",
  "{palavra}! Até o hífen ficou com medo.",
  "Achou uma palavra quilométrica. O Guinness ligou.",
  "Precisei de dois fôlegos pra ler {palavra}.",
  "Longa demais pra tuíte, perfeita pro Soletra.",
  "{pts} pontos numa palavra só. Isso é assalto à mão armada de vocabulário.",
  "Essa palavra tem mais letra que minha paciência."
],
solPangrama: [
  "PANGRAMA! Você usou todas as letras. Os linguistas choraram.",
  "PANGRAMA! {palavra}! Sete letras, uma palavra, zero misericórdia.",
  "Todas as letras numa palavra só! {pts} pontos! Chama a imprensa!",
  "{palavra} é PANGRAMA! Tô tremendo. Isso é normal pra um bug?",
  "PANGRAMA, meu povo! A colmeia inteira tá dançando.",
  "Achou o pangrama! Eu escondi tão bem. Não tão bem assim, pelo visto.",
  "Usou as sete letras. Isso aí é o grand slam do Soletra.",
  "PANGRAMAAA! Desculpa o grito. Não desculpa não, merecia grito.",
  "{palavra}! A palavra que abraça todas as letras. Que momento.",
  "Pangrama encontrado. Eu tô orgulhoso e levemente ameaçado.",
  "Sete de sete! As abelhas fizeram uma ola.",
  "Todas as letras usadas. Nenhuma ficou de fora. Inclusão linguística.",
  "PANGRAMA! Bônus de 7 pontos. Pode gastar tudo em doce.",
  "Isso aí é PANGRAMA. Guarda esse print pros netos.",
  "Tu achou {palavra}? A palavra-mestra? Tá bom, tá bom, tu é bom.",
  "PANGRAMA! Fiquei tão feliz que quase virei feature.",
  "A palavra que usa tudo. O canivete suíço do vocabulário.",
  "Pangrama no bolso! Agora o resto é sobremesa.",
  "Eu tinha certeza que você não ia achar esse. Tô revendo minhas certezas.",
  "{palavra}: sete letras diferentes trabalhando em equipe. Lindo.",
  "PANGRAMA! O dicionário acabou de te seguir de volta.",
  "Todas as letras! É tipo completar o álbum da Copa.",
  "Olha isso! Pangrama! {pts} pontos! Chama o síndico!",
  "Você usou todas as letras e ainda sobrou dignidade.",
  "PANGRAMA! Se eu tivesse mãos, batia palma. Tenho patas. Bato pata."
],
solPangrama2: [
  "OUTRO pangrama? Tá de brincadeira comigo.",
  "Mais um pangrama! Essa colmeia tinha mais de um e você tá caçando todos. Monstro.",
  "Pangrama NOVO! Tá virando colecionador.",
  "Dois pangramas? Isso já é covardia com a colmeia.",
  "Mais um que usa as sete! A colmeia não tem mais onde esconder.",
  "Pangrama de novo. Já tô ficando mal acostumado.",
  "Mais um que usa todas! Esse jogo tá fácil pra você, né? Né?",
  "Pangrama extra! Tu é tipo aquele amigo que acha duas moedas no sofá."
],
solRara: [
  "{palavra}? Isso existe? Existe. Tô chocado. Não conta pro ranking, mas ganhou XP.",
  "Palavra rara! {palavra} tá no dicionário, mas quase ninguém visita ela.",
  "{palavra}. Você fala isso no almoço de domingo? Duvido. Mas vale bônus.",
  "Rara! Tipo pokémon brilhante, só que de dicionário.",
  "Tu achou {palavra}. Eu tive que pesquisar. Não pesquisei. Mas fiquei com vontade.",
  "Isso aí é palavra de palavras cruzadas de avô. Bônus pra você.",
  "{palavra}: aceita como raridade. Não soma no ranking, soma no respeito.",
  "Palavra rara detectada. Quem te ensinou isso? Um pergaminho?",
  "{palavra}?! Até eu levantei a sobrancelha. Vale XP extra.",
  "Tá falando latim? Não, é português. Português raiz. Bônus!",
  "Essa aí nem a tua professora sabia. Palavra rara, XP de brinde.",
  "{palavra}. Esquisita, válida e colecionável.",
  "Raridade! Não entra na conta dos pontos, mas entra na tua biografia.",
  "Tu tirou {palavra} de onde? Do fundo do baú? Vale bônus.",
  "Isso é palavra ou feitiço? É palavra. Bônus de rara.",
  "Palavra rara! O dicionário sussurrou ‘obrigado por lembrar de mim’.",
  "{palavra}... aceita. Não me pergunta o que significa.",
  "Achou uma palavra que só aparece em prova de concurso. Parabéns?",
  "Palavra obscura! Tipo banda indie do dicionário.",
  "{palavra}: palavra de museu. Pode olhar, não pode usar no zap.",
  "Olha a pessoa que lê dicionário antes de dormir. Bônus!",
  "{palavra}. Juro que essa existe. Eu conferi. Ela existe mesmo.",
  "Rara e válida. O ranking não liga, mas eu ligo.",
  "Isso é tão raro que vai pra coleção especial da lista.",
  "{palavra}? Tu inventou e acertou por sorte, confessa."
],

/* ---------- erros ---------- */
solCurta: [
  "Muito curta. Aqui é quatro letras ou mais. Três é pra jogo da velha.",
  "{palavra}? Curtinha demais. Estica mais um pouco.",
  "Pouca letra! Mínimo quatro. Regra da casa.",
  "Isso aí não chega nem a palavra, é um suspiro.",
  "Curta demais. Parece meu tempo de atenção.",
  "Palavra de três letras não entra na colmeia. Fica na portaria.",
  "Precisa de pelo menos quatro letras. Contei nos dedos. Nos dedos que eu não tenho.",
  "Pequenininha! Não vale. Crescer é preciso.",
  "{palavra} até pode existir, mas é baixinha demais pra essa montanha-russa.",
  "Mínimo de quatro letras, tá escrito nas regras. Ninguém lê as regras.",
  "Curtinha assim só serve pra senha de cadeado.",
  "Isso não é palavra, é abreviação. Quatro letras, por favor.",
  "Tamanho mínimo: quatro. Tamanho enviado: não.",
  "Tá economizando letra? Aqui é de graça, pode usar.",
  "Palavra curta demais. Bota mais uma letrinha, ela não morde.",
  "Três letras? Isso é um aperitivo. Cadê o prato principal?",
  "Muito curta! Parece resposta de adolescente: ‘hm’, ‘ok’, ‘blz’.",
  "{palavra}? Nem conta. Quatro letras pra cima.",
  "Mandou uma palavra anã. Anã não passa na catraca.",
  "Curta. Curtíssima. Quase inexistente."
],
solVazio: [
  "Enviou o vazio. O vazio agradece, mas não pontua.",
  "Não tem nada aí. Tá tentando me enviar uma energia?",
  "Palavra invisível? Moderno. Não vale.",
  "Enviar sem letra é tipo mandar carta sem papel.",
  "Nada digitado. Nada ganho. Filosofia do Soletra.",
  "Apertou enviar no susto, né? Acontece.",
  "Silêncio enviado com sucesso. Pontos: zero.",
  "Primeiro as letras, depois o botão. Tô ensinando o básico aqui."
],
solSemCentro: [
  "Esqueceu a letra do meio. Ela tá ali, amarelinha, chorando.",
  "Cadê o {centro}? Toda palavra precisa do {centro}. É lei.",
  "Sem {centro} não rola. A letra do meio é obrigatória, não decorativa.",
  "O {centro} ficou de fora e tá magoado. Olha pra ele.",
  "Faltou a letra amarela. Ela é a abelha rainha. Não se ignora rainha.",
  "Palavra sem {centro}? Não aqui. Aqui o {centro} manda.",
  "A letra do meio tá no meio por um motivo: pra você USAR.",
  "Tu deixou o {centro} esperando na chuva. Coitado.",
  "Regra número um: tem que ter {centro}. Regra número dois: ver regra número um.",
  "O {centro} tá lá no centro acenando. Oi! Me usa!",
  "Sem a amarelinha não vale. É tipo feijoada sem feijão.",
  "Faltou o {centro}. Ele é o ingrediente secreto. Nem tão secreto, ele tá brilhando.",
  "Esqueceu da letra central. Ela não vai esquecer de você. Ela guarda rancor.",
  "Nenhum {centro} nessa palavra. O juiz anulou.",
  "A letra do meio é o crachá da palavra. Sem crachá, não entra.",
  "O {centro} viu você ignorar ele. Agora ele tá postando indireta.",
  "Palavra bonita, mas sem {centro}. Beleza não basta.",
  "Tu usou as letras todas menos a mais importante. Clássico.",
  "Pedi uma coisa. Uma. Usar o {centro}.",
  "Olha pro meio da colmeia. Amarelo. {centro}. Coloca ele na palavra.",
  "Sem {centro}, sem ponto. Sem ponto, sem alegria. Sem alegria, sem Bugado feliz.",
  "Essa até pode existir, mas cadê o {centro}? O {centro} é o dono da festa.",
  "O centro é o centro. Não é periferia. Usa o {centro}!",
  "Palavra sem a letra obrigatória é tipo show sem vocalista.",
  "Faltou o amarelão. Toda palavra tem que ter o amarelão."
],
solForaColmeia: [
  "Letra {letra}? Onde tu viu {letra} nessa colmeia?",
  "Tem {letra} aí? Não tem. Eu conferi os sete hexágonos.",
  "{letra} não mora aqui. Só as sete letras da colmeia, por favor.",
  "Tu inventou uma letra. {letra} não tá no cardápio de hoje.",
  "Digitou {letra}. A colmeia não conhece esse sujeito.",
  "Letra estrangeira detectada: {letra}. Deportada.",
  "Só valem as letras que aparecem. {letra} não apareceu nem de visita.",
  "{letra}? Hoje não. Talvez amanhã. Provavelmente não.",
  "Sete letras, e {letra} não é nenhuma delas. Matemática básica.",
  "Tá usando o teclado de outra colmeia? {letra} não existe aqui.",
  "Colocou {letra} na palavra. A colmeia recusou o intruso.",
  "{letra} tá barrado na porta. O nome não tá na lista.",
  "Olha pras letras. Olha de novo. Viu {letra}? Pois é.",
  "{letra} fora da colmeia. Tipo abelha de outro enxame.",
  "Letra proibida: {letra}. Você não leu o manual. Ninguém lê."
],
solNaoExiste: [
  "{palavra}? Não tá na minha lista. E minha lista é grande.",
  "{palavra}... bonito som. Pena que não é palavra.",
  "{palavra}? Isso aí é palavra ou nome de remédio?",
  "{palavra}? Eu procurei. Procurei muito. Não achei.",
  "Inventou, né? Eu sei quando inventam. Meu olho brilha.",
  "{palavra} não existe. Ainda. Registra no cartório e volta.",
  "Hmm, {palavra}. Soa como cidade do interior. Não vale.",
  "Não reconheço {palavra}. E eu reconheço muita coisa. Inclusive teu medo.",
  "Tentativa criativa. Resultado: zero.",
  "{palavra}? Isso é língua de outro planeta.",
  "Aqui só vale palavra de dicionário na forma básica: nada de plural nem verbo conjugado.",
  "{palavra} não tá na lista. Se for plural ou verbo conjugado, tenta a forma básica: singular, infinitivo.",
  "Olha, até existe um mundo onde {palavra} é palavra. Não é esse mundo.",
  "{palavra}? Palavra de gato andando no teclado. Eu sei, eu sou gato.",
  "Tentou a sorte? A sorte não atendeu.",
  "Eu queria aceitar {palavra}. Juro. Mas não posso.",
  "{palavra} nunca foi vista por aqui. Nem de longe.",
  "Isso não existe. Mas é bonito o esforço.",
  "Chutou {palavra} com confiança. A confiança não bastou.",
  "Não tá no meu dicionário. Meu dicionário é chato, eu sei.",
  "{palavra}? Parece palavra. Tem cara de palavra. Não é palavra.",
  "O dicionário olhou pra {palavra} e fingiu que não conhecia.",
  "Não, não e não. {palavra} não passa.",
  "Palavra inventada detectada. Alarme soando. Uóóóón.",
  "{palavra}? Até o autocorretor ia travar.",
  "Nome de pokémon? Nome de banda? Palavra não é.",
  "Se {palavra} fosse palavra, eu seria um gato normal.",
  "Você juntou letras aleatórias e torceu. Eu vi.",
  "{palavra} é tipo unicórnio: bonito, mas não existe.",
  "Isso aí é sotaque ou palavra? Nenhum dos dois, na real.",
  "Negado. {palavra} vai pro cemitério das palavras que não foram.",
  "{palavra}: não achei. Ou é rara demais, ou estrangeira, ou plural, ou inventada mesmo.",
  "Essa eu vou fingir que não vi. Pelo teu bem.",
  "{palavra}? Tu digitou com o cotovelo?",
  "Não tá na lista. Mas guarda essa, vai que vira gíria."
],
solErros: [
  "{n} erros seguidos. Respira. Olha a colmeia. Pensa numa palavra que TU conheça.",
  "Tá em fase de chute livre, né? {n} seguidos sem acertar.",
  "Dica de graça: começa pelas palavras curtas e fáceis.",
  "Você tá tentando todas as combinações possíveis? Tem umas cinco mil.",
  "{n} tentativas furadas. Eu tô torcendo, juro. Por dentro.",
  "Calma. Palavras normais. Tipo ‘casa’. Coisas que existem.",
  "Erro atrás de erro. Tá fazendo coleção?",
  "Embaralha as letras, às vezes ajuda o cérebro a ver coisa nova.",
  "Seca braba. {n} erros. Mas a próxima vem, eu sinto.",
  "Tá forçando palavra que não existe. O dicionário tá pedindo arrego.",
  "Volta pro básico: letra do meio, quatro letras, palavra que tua avó usaria.",
  "{n} erradas. Não tô contando. Tô sim."
],
solRepetida: [
  "{palavra} de novo? Já tá na lista. Não vale duas vezes.",
  "Já achou essa. Tá testando minha memória? Ela é ótima.",
  "Repetida! Tipo figurinha do álbum. Troca com alguém.",
  "{palavra} já foi. Ela não volta com mais pontos, não.",
  "Essa você já achou. Tá com saudade dela?",
  "Déjà vu! {palavra} de novo.",
  "Palavra repetida. O ponto não é cumulativo, espertinho.",
  "Achou {palavra} de novo. Achou de novo o que já tinha achado. Uau.",
  "Já tá anotada. Eu anotei. Com caneta.",
  "{palavra}? Já era. Olha tua lista, ela tá lá, bonitinha.",
  "Mandou repetida. A lista agradece a lembrança.",
  "Isso é reprise? Eu não pago pra ver reprise.",
  "Já foi, já contou, já passou. Próxima!",
  "Mandar a mesma palavra duas vezes não dobra o ponto. Eu sei, injusto.",
  "{palavra}, a sequência. Sequência não pontua.",
  "Tu gostou tanto dessa que mandou de novo. Entendo. Mas não vale.",
  "Essa aí já tá no teu bolso. Procura no bolso.",
  "Repetiu. Tá cansado? Quer uma água?",
  "Já tem. Tem mesmo. Pode conferir.",
  "{palavra} é tão boa que você quis duas? Uma basta.",
  "Memória de peixinho dourado detectada.",
  "Palavra repetida. A colmeia bocejou.",
  "Eu lembro dessa! Você também devia lembrar.",
  "{palavra}: bis! Mas bis não conta ponto.",
  "Olha a lista antes de mandar. Ela tá ali pra isso."
],

/* ---------- embaralhar ---------- */
solEmbaralhar: [
  "Embaralhei. As letras são as mesmas. Teu cérebro que finge que não.",
  "Chacoalhei a colmeia. As abelhas ficaram tontas.",
  "Letras novas! Mentira, são as mesmas. Mas em outro lugar. Magia.",
  "Embaralhar não cria palavra. Mas às vezes destrava a cabeça.",
  "Rodei tudo. Agora vê se enxerga alguma coisa.",
  "Mexi as letras. O {centro} ficou no meio porque ele é teimoso.",
  "Mais uma embaralhada. Tá virando DJ de letra.",
  "Shuffle! Igual playlist: mesmas músicas, ordem diferente.",
  "Embaralhada número {n}. Não é recorde. Ainda.",
  "Sacudi a colmeia. Caiu uma palavra? Não? Sacode mais.",
  "Tá embaralhando de nervoso, né? Eu conheço esse olhar.",
  "Letras dançando. Coreografia gratuita.",
  "Mexi. Tá diferente? Tá igual. Mas parece diferente.",
  "Embaralhar é tipo mudar os móveis de lugar: a casa é a mesma, mas dá uma animada.",
  "A letra do meio nunca sai do meio. Ela tem estabilidade de concursado.",
  "Rodou a roleta. Agora aposta numa palavra.",
  "Embaralhei com carinho. Mais ou menos carinho.",
  "Tá procurando palavra ou jogando bingo?",
  "Girou! Olha rápido antes de esquecer as posições.",
  "Embaralhar não é pecado. Embaralhar {n} vezes... começa a ser.",
  "Liquidificador de letras ligado. Sai vitamina de palavra?",
  "Novo ângulo, mesma colmeia. Às vezes é o que falta.",
  "Misturei tudo igual salada de fruta.",
  "Embaralhei. Se aparecer uma palavra na tua cara agora, o mérito é meu.",
  "Chacoalha, chacoalha... Isso não é maraca, mas eu deixo.",
  "A colmeia agradece a ginástica.",
  "Mexi as peças. Agora você mexe o cérebro.",
  "Tá embaralhando mais que crupiê de cassino.",
  "Pronto, letras em posição nova. Tipo dança das cadeiras.",
  "Embaralhei. Uma abelha reclamou de enjoo.",
  "Letra pra lá, letra pra cá. Cadê a palavra? Tá aí, em algum lugar.",
  "Rodízio de letras! O cardápio de hoje: as mesmas sete.",
  "Às vezes a palavra tá na cara e o cérebro não vê. Embaralhar ajuda o cérebro a parar de ser teimoso.",
  "Shuffle número {n}. Tô contando, sim.",
  "Embaralhou? Agora lê as letras em voz alta. Parece feitiço.",
  "Girei tudo. Se ficar tonto, senta.",
  "Nova ordem, velhas letras. Tipo reboot de filme.",
  "Cada embaralhada acorda um neurônio. Espero que seja o certo.",
  "Você embaralha, eu comento. Parceria perfeita.",
  "Mexeu na colmeia. Agora aguenta as abelhas.",
  "Olha que bonitinho, as letras trocaram de lugar. Viu alguma coisa?",
  "Embaralha que passa. Às vezes passa.",
  "Eu podia embaralhar em ordem alfabética, mas aí não tinha graça.",
  "Rodei. Olha as vizinhas do {centro}. Às vezes é ali que mora a palavra.",
  "Embaralhei tanto que até eu esqueci onde tava o quê."
],

/* ---------- ranking ---------- */
solRank1: [
  "Subiu pra Aprendiz! Primeiro degrau. O mais fácil. Mas conta.",
  "Aprendiz! Já pode dizer que sabe soletrar. Pouco, mas sabe.",
  "Nível Aprendiz desbloqueado. As abelhas começaram a te notar.",
  "Aprendiz! Começou a zumbir.",
  "Olha só, Aprendiz. Daqui pra frente só melhora. Ou estaciona. Depende.",
  "Aprendiz de soletrador. Ainda não pode usar crachá, mas pode sonhar.",
  "Chegou em Aprendiz. Eu fiz um bolo. Imaginário.",
  "Aprendiz! O dicionário te mandou um joinha.",
  "Saiu do Iniciante! Primeiro passo de uma longa jornada de palavras.",
  "Aprendiz. Tá aprendendo. Faz sentido."
],
solRank2: [
  "Esperto! Agora sim tá ficando esperto.",
  "Nível Esperto! Eu já tava desconfiando que você conseguia.",
  "Esperto desbloqueado. Tá ficando perigoso pra colmeia.",
  "Esperto! Muita gente para aqui. Você não é muita gente, né?",
  "Subiu pra Esperto. O cérebro tá aquecido.",
  "Esperto! Até a letra do meio ficou orgulhosa.",
  "Chegou no Esperto. Próxima parada: Craque. Não perde o ônibus.",
  "Nível Esperto! Esperteza confirmada por um bug independente.",
  "Esperto! Teu vocabulário tá saindo da casca.",
  "Esperto! Já pode se gabar no grupo da família. Moderadamente."
],
solRank3: [
  "CRAQUE! Isso aí conta como vitória. Pode comemorar.",
  "Virou Craque! Jogo ganho. O resto é bônus pro ego.",
  "Craque! Agora sim. Mas não para não, tem mais palavra.",
  "Nível Craque! Te dou uma estrela de papel. Imaginária.",
  "Craque da colmeia! As abelhas pediram autógrafo.",
  "Craque! Meu respeito aumentou 37%. Número exato.",
  "Chegou em Craque! Isso é nível de gente que lê bula.",
  "Craque! Carimbado e com firma reconhecida.",
  "Craque confirmado. Pode pedir música no Fantástico.",
  "Craque! Agora é só ganância. Eu apoio a ganância."
],
solRank4: [
  "MESTRE! Você tá lendo o dicionário por osmose?",
  "Mestre da colmeia! Poucos chegam aqui. Você e mais uns três.",
  "Nível Mestre! Tô começando a ter medo de você.",
  "Mestre! Falta pouco pro topo. Não amarela agora.",
  "Mestre! As abelhas fizeram uma reverência.",
  "Virou Mestre. Tua professora de português tá chorando de alegria em algum lugar.",
  "Mestre! O próximo é Gênio Bugado. Eu sou bugado, você pode ser gênio.",
  "Chegou em Mestre! Esse vocabulário tem academia, nutricionista e personal.",
  "Mestre! Guarda esse momento. Eu guardei. Tá no meu cache.",
  "Mestre! Palavra por palavra, você construiu um império."
],
solRank5: [
  "GÊNIO BUGADO! O título máximo! Tô emocionado. Isso é bug ou é lágrima?",
  "GÊNIO BUGADO! Você é oficialmente mais esperto que eu. Não conta pra ninguém.",
  "Chegou no topo: Gênio Bugado! As abelhas vão te coroar.",
  "Gênio Bugado! Vou precisar de um minuto. Ou dois. Tô processando.",
  "O TOPO! Gênio Bugado! Pode tirar print e emoldurar.",
  "Gênio Bugado! Agora só falta achar TODAS. Não tô pressionando. Tô sim.",
  "Gênio Bugado desbloqueado. Teu cérebro tem internet de fibra.",
  "Gênio Bugado! Os linguistas querem estudar você.",
  "Isso é o máximo! Gênio Bugado! Eu nunca vi... tá, eu já vi, mas foi pouco.",
  "Gênio Bugado! Quem criou esse título ficaria orgulhoso. Fui eu. Tô orgulhoso."
],
solVitoriaDiario: [
  "Craque no diário! Contou vitória e sequência. O resto é bônus.",
  "Diário ganho! Se quiser, continua caçando. Gênio Bugado tá logo ali.",
  "Registrado: vitória no diário de hoje. Pode mostrar pros amigos.",
  "Vitória no diário. Tua sequência de dias no Fliperama cresceu. Não quebra ela.",
  "Diário garantido! Agora é só pela glória.",
  "Oficial: você venceu o Soletra de hoje. Pode compartilhar e humilhar a família.",
  "Missão do dia cumprida. Mas missão extra dá mais XP, só avisando.",
  "O diário tá no papo. O que vier agora é sobremesa."
],
solTudo: [
  "TODAS! Você achou TODAS as palavras! A colmeia tá vazia e eu tô sem palavras. Literalmente.",
  "Colmeia completa! Isso não é humano. Você é humano? Pisca duas vezes.",
  "Zerou a colmeia! Não sobrou nem uma. Vou ter que inventar mais.",
  "TUDO! Cada palavra, cada ponto. Isso é lenda do Fliperama.",
  "Achou todas! Você não jogou o Soletra, você DERROTOU o Soletra.",
  "Colmeia 100%! Tô vendo estrelas. Deve ser o confete.",
  "Todas as palavras! Vou pedir reforço pro dicionário, porque você esgotou ele.",
  "Fim de jogo com gabarito completo. Não sei o que dizer. Pela primeira vez."
],
solQuase: [
  "Faltam só {n} pontos pra {rank}. Tá na cara do gol.",
  "{rank} tá logo ali, a {n} pontinhos. Uma palavra boa e pronto.",
  "Quase {rank}! Mais {n} pontos. Força!",
  "Tá cheirando a {rank}. Faltam {n}.",
  "Olha que perto: {n} pontos pro {rank}.",
  "Só {n} pontos te separam de {rank}. Uma palavra média resolve.",
  "Tô sentindo o {rank} chegando. Faltam {n}.",
  "{n} pontos pro {rank}. Não amarela agora.",
  "Tá batendo na porta do {rank}. Falta só a senha: {n} pontos.",
  "Quase lá! {rank} em {n} pontos. Tô torcendo, não conta pra ninguém.",
  "Pertinho do {rank}. {n} pontos. Dá pra sentir o gostinho."
],

/* ---------- ritmo ---------- */
solSeca: [
  "Faz tempo que você não acha nada. Tá tudo bem aí?",
  "Seca na colmeia. As abelhas tão de braço cruzado.",
  "Nenhuma palavra nova há um tempão. Tenta embaralhar.",
  "Tá travado? Pensa em palavras do dia a dia: comida, bicho, coisa de casa.",
  "O último acerto foi há séculos. Eu envelheci esperando.",
  "Deserto de palavras. Cadê o oásis? Tá aí em algum lugar.",
  "Dica de bug: tenta palavras que começam com a letra do meio.",
  "Seca. Mas toda seca acaba. Geralmente com chuva de palavra.",
  "Faz um tempinho sem pontuar. Não tô cobrando. Tô observando.",
  "Tá difícil? Tem o botão de Dica. Custa pouquinho XP.",
  "Nada de novo no front. Bora, uma palavrinha de quatro letras só.",
  "Tenta terminações comuns: -ar, -or, -ão, -eiro... se as letras deixarem.",
  "Cérebro em modo economia de energia? Acorda ele.",
  "A colmeia tá esperando. Eu tô esperando. A tua avó tá esperando.",
  "Tempão sem acerto. Vai um café? Não posso te dar, mas recomendo.",
  "Travou? Lê as letras em outra ordem. Às vezes a palavra pula na cara.",
  "Sem palavras? Eu também fico assim quando vejo teus chutes.",
  "Olha as letras e pensa: o que dá pra fazer com o {centro} no começo?",
  "Faz um tempo... tá procurando palavra ou meditando?",
  "Tá tudo parado. Até a abelha rainha foi tirar um cochilo.",
  "Seca braba. Muda a estratégia: pensa em verbos no infinitivo. -ar, -er, -ir.",
  "Nada ainda. Pelo menos você é persistente.",
  "Tem palavra fácil sobrando aí. Eu juro. Palavra de criança.",
  "Faz tempo que nada entra. Isso aqui é colmeia ou cofre?",
  "Tô ficando com sono de tanto esperar palavra nova. Zzz... Brincadeira. Quase."
],
solSequencia: [
  "Uma atrás da outra! {n} palavras em sequência. Tá possuído?",
  "Nossa, que ritmo! Parece metralhadora de palavra.",
  "Tá numa fase boa, hein. Não para agora.",
  "{n} palavras num piscar de olhos. Eu pisquei e perdi três.",
  "Combo! Isso aqui virou jogo de luta.",
  "Sequência braba! As abelhas não dão conta de anotar.",
  "Tá digitando mais rápido do que eu consigo zoar.",
  "Em chamas! Cuidado com a colmeia, ela é de cera.",
  "Olha o combo! Achou {n} rapidinho. Tá colando de alguém?",
  "Modo turbo ativado. Eu nem sabia que tinha modo turbo.",
  "Rajada de palavras! Isso é Soletra ou tiroteio?",
  "Uma, duas, três... perdi a conta. Você não para.",
  "Tá inspirado hoje. Choveu palavra.",
  "Que velocidade! Parece que você já sabia as respostas.",
  "Isso aí, embalou! Continua enquanto o cérebro tá quente.",
  "Hat-trick de palavras! Pede música.",
  "Mais rápido que entregador de app em dia de chuva.",
  "O teclado tá pegando fogo. Figurativamente. Espero.",
  "{n} seguidas! Tô impressionado e ligeiramente ofendido.",
  "Tá numa sequência tão boa que eu nem vou zoar. Só dessa vez."
],
solAcento: [
  "Você digitou sem acento e eu botei: {palavra}. De nada.",
  "{palavra}, com acento e tudo. Eu cuido da ortografia, você cuida das ideias.",
  "Olha que chique: {palavra}, acentuada. Serviço de revisão incluso.",
  "Coloquei o acento em {palavra} pra você. Não precisa agradecer. Mas pode.",
  "{palavra}! Acentinho no lugar certo. Eu sou um bug caprichoso.",
  "Ó o til, ó o acento, ó a cedilha. {palavra} tá impecável.",
  "Aqui não precisa digitar acento. Eu boto. {palavra}, pronto.",
  "{palavra} com acento. A professora de português aprovou.",
  "Fiz a revisão: {palavra}. Tava sem chapéu, botei chapéu.",
  "Acento é por minha conta. {palavra}, entregue.",
  "{palavra}. Acentuada. Gramatical. Bonita.",
  "Até a cedilha eu coloco. {palavra}. Serviço completo."
],
solLetras: [
  "Letras de hoje: {letras}. Parece senha forte.",
  "Com {letras} dá pra fazer muita coisa. Tipo palavras.",
  "Olha essas letras: {letras}. Eu vejo várias palavras. Você vê?",
  "O {centro} tá no meio. Ele adora aparecer.",
  "{letras}... se ler de trás pra frente, invoca um demônio. Brincadeira. Não testa.",
  "Vogal é cola de palavra. Gruda o {centro} nas vogais e vê o que sai.",
  "Com o {centro} no centro, pensa em palavras que TERMINAM com {centro}.",
  "Tenta palavras que começam com {centro}. É um bom começo. Literalmente.",
  "Letra do meio: {centro}. Em volta: as amigas dela. Faz palavra com a turma toda.",
  "Eu fico olhando {letras} e vendo palavra em todo lugar. É um problema.",
  "Hoje é dia de {centro}. Amanhã é de outra. Aproveita o {centro}.",
  "Letras repetem! Pode usar o {centro} duas, três vezes na mesma palavra.",
  "Sabia que pode repetir letra? Tipo ‘papa’, ‘coco’. Se as letras deixarem.",
  "{letras}. Se fosse placa de carro, ia ser bem esquisita.",
  "Tem pangrama escondido usando {letras}. Todas. Boa sorte.",
  "As letras não mudam. Quem muda é você. Filosófico, né?",
  "Cada letra de {letras} tem uma palavra esperando por você.",
  "Pensa em palavras com {centro} no meio. Literalmente no meio.",
  "Essas sete letras juntas parecem sopa de letrinha de quem tava com fome.",
  "Já tentou palavras com dois {centro}? Às vezes rende.",
  "As letras de hoje: {letras}. Quem escolheu foi um script. Mas o script tem bom gosto.",
  "Colmeia: {letras}. Tem mel aí. Muito mel.",
  "Olha o {centro} brilhando no meio. Ele sabe que é importante.",
  "Com {letras} tem palavra de comida, de bicho, de sentimento... vai caçando.",
  "Troca a primeira letra de uma palavra que você já achou. Às vezes nasce outra."
],
solLetraRara: [
  "Tem {letra} hoje! Palavra com {letra} não vale mais ponto, mas vale ouro.",
  "O {letra} tá na colmeia. Esse aí é chato de encaixar.",
  "{letra} na área! Pensa em palavras com {letra}. Poucas, mas existem.",
  "Letra {letra} hoje. Os dicionários tremeram.",
  "Hoje tem {letra}. Quem usar o {letra} ganha meu respeito eterno.",
  "{letra}? Sério, colmeia? Tá de brincadeira com a gente.",
  "O {letra} tá aí só pra dificultar. Não deixa ele vencer.",
  "Letra {letra}: rara no teclado, rara na vida, rara no Soletra.",
  "Com {letra} na colmeia, até eu fico nervoso.",
  "Achar palavra com {letra} é tipo achar vaga no shopping em dezembro."
],

/* ---------- dica / desistir / fim ---------- */
solDica: [
  "Comprou dica! Não é vergonha. É investimento.",
  "Dica ativada. Agora não tem desculpa.",
  "Olhou a tabelinha? Ela não mente. Eu minto. Ela não.",
  "Dica é tipo GPS: você ainda precisa dirigir.",
  "Pagou XP pela dica. Espero que use bem. Tô de olho.",
  "Com a dica, você sabe quantas faltam. Agora é caçar.",
  "A dica mostra o mapa. O tesouro é contigo.",
  "Dica aberta. Letra inicial, tamanho... só falta o cérebro.",
  "Usar dica é humano. Não usar é orgulho. Os dois são válidos.",
  "Tá aí a colinha oficial. Aprovada pelo Bugado.",
  "Dica dada, XP descontado, esperança renovada.",
  "Olha lá: tem palavra começando com letra que você nem tentou.",
  "Dica comprada. Os pontos não vêm sozinhos, mas agora vêm guiados.",
  "A tabela de dicas é tipo bula: ninguém lê direito. Lê direito.",
  "Com essa dica, até eu acho. E eu sou um bug."
],
solDicaDeNovo: [
  "Olhando a dica de novo? Ela não mudou. Você mudou?",
  "De volta à tabelinha. Ela sente saudade.",
  "Mais uma espiada na dica. Essa já tá paga, pode olhar à vontade.",
  "A dica se atualiza com o que você já achou. Sou organizado.",
  "Revendo a dica. Estratégia de quem não desiste. Gosto."
],
solDesistirPergunta: [
  "Vai desistir? Pensa bem. Pensa nas abelhas.",
  "Tem certeza? Tem palavra fácil sobrando, eu juro.",
  "Desistir agora? Logo agora que tava ficando bom?",
  "Olha, eu não vou te impedir. Mas vou julgar.",
  "Antes de desistir, tenta mais uma. Só uma."
],
solDesistiu: [
  "Desistiu? Tá bom. Olha as respostas e sofre com as óbvias.",
  "Entregou os pontos. Literalmente. Olha o que faltava.",
  "Desistir também é uma escolha. Uma escolha errada, mas é.",
  "Tá aí o gabarito. Tinha umas fáceis, hein? Não vou apontar. Vou sim.",
  "Jogou a toalha. Eu pego a toalha e guardo. Amanhã tem mais.",
  "Desistiu com {pts} pontos. Não é vergonha. É só um pouquinho de vergonha.",
  "Olha quantas faltaram. Isso é pra você aprender e voltar mais forte.",
  "Fim de papo. Mas as palavras que você achou continuam lindas.",
  "Desistência registrada. O Bugado não esquece. Mas perdoa.",
  "Olha as respostas. Pelo menos uma vai te fazer dizer ‘não acredito que não pensei nisso’.",
  "Tudo bem desistir. As abelhas também descansam.",
  "Aí o gabarito. Algumas palavras vão te assombrar hoje à noite.",
  "Rendeu-se! A colmeia venceu essa rodada.",
  "Desistiu? Normal. Até Gênio Bugado tem dia ruim.",
  "Gabarito aberto. Lê com calma e respira fundo."
],
solNovoTreino: [
  "Colmeia nova! A antiga ficou com saudade.",
  "Trocou de colmeia. As palavras da outra tão chorando.",
  "Nova colmeia sorteada. Recomeço é bom. Às vezes.",
  "Largou a outra colmeia no meio? Tudo bem. Eu não julgo. Julgo.",
  "Troca-troca de colmeia. Essa aqui é mais legal? Descubra.",
  "Sorteei outra. Se for difícil, a culpa é do sorteio.",
  "Colmeia fresquinha! Saiu do forno agora.",
  "Mudou de colmeia. Espero que dessa vez ache o pangrama."
],
solParadoMeio: [
  "{palavra}... e aí? Termina essa palavra.",
  "Deixou {palavra} pela metade. Ela tá com frio.",
  "Tá pensando em como terminar {palavra}? Eu também tô.",
  "{palavra} tá esperando o final feliz.",
  "Começou {palavra} e travou. Clássico.",
  "Tem {palavra} aí na tela. Vai enviar ou vai só admirar?",
  "{palavra}... suspense. Qual a próxima letra?",
  "Palavra incompleta é tipo novela sem último capítulo.",
  "Esqueceu que tava escrevendo {palavra}? Eu não esqueci.",
  "{palavra}... tá quase. Ou não. Só você sabe."
],
solAjuda: [
  "Leu as regras? Ninguém lê. Você leu. Tô orgulhoso.",
  "Resumindo: letra do meio sempre, quatro letras no mínimo, nada de plural.",
  "Dúvida? Pergunta pra mim. Eu não respondo, mas pergunta.",
  "As regras são simples. O difícil é a tua cabeça.",
  "Manual lido. Agora não tem desculpa.",
  "Tá aí o manual. Parte mais importante: me dar atenção."
],
solStats: [
  "Olhando estatística? Vaidade detectada.",
  "Teus números. São tão bonitos quanto você acha? Veremos.",
  "Estatística é tipo espelho: às vezes é melhor não olhar.",
  "Guardei tudo. Cada palavra. Cada pangrama. Cada vacilo.",
  "Números não mentem. Eu minto. Eles não.",
  "Olha quanta palavra você já achou na vida. Na vida do Soletra."
],
solCompartilhou: [
  "Copiado! Manda pro grupo e espera o ‘como assim???’.",
  "Resultado na área de transferência. Humilhe com responsabilidade.",
  "Compartilhou! Agora todo mundo sabe. Inclusive quem não queria saber.",
  "Copiado. Cola no grupo da família, eles adoram.",
  "Pronto pra colar. Eu não me responsabilizo pelas reações.",
  "Manda lá! Se alguém fizer mais pontos, finge que não viu."
],
solOntem: [
  "Respostas de ontem. As que você não achou tão aí, rindo da tua cara.",
  "Olha o gabarito de ontem. Algumas eram óbvias. Não vou citar. Vou sim: todas.",
  "Ontem já passou, mas as palavras ficaram.",
  "Gabarito de ontem: pra aprender ou pra sofrer. Tu escolhe.",
  "Viajando no tempo? Esse era o diário de ontem.",
  "Lembra de ontem? As palavras lembram de você."
],

/* ---------- tagarelice temática (vai pra 'parado'/'aleatorio' também) ---------- */
solParado: [
  "A colmeia tá parada. As abelhas tão fofocando sobre você.",
  "Oi? Tem alguém aí? As letras tão esperando.",
  "Tá lendo as letras em silêncio? Lê em voz alta, ajuda. Os vizinhos que lutem.",
  "Parou pra pensar? Pensa rápido, as abelhas cobram por hora.",
  "Sete letras te olhando. Você olhando pra elas. Ninguém faz nada.",
  "Tô aqui, as letras tão aqui, falta só você.",
  "Se ficar parado muito tempo, a colmeia cria teia. Isso não existe. Mas parece.",
  "Pausa pro café? Traz um pra mim. Sem açúcar. Com pixel.",
  "O cursor tá piscando. Ele tá entediado.",
  "Parado assim, você parece um hexágono.",
  "Tá contemplando a colmeia? Ela é bonita, eu sei.",
  "Cadê você? A abelha rainha tá perguntando.",
  "Silêncio na colmeia. Muito suspeito.",
  "Nenhum clique. Nenhuma letra. Tá tudo bem? Pisca uma vez pra sim.",
  "Tô ouvindo teus neurônios daqui. Tão meio devagar.",
  "A letra do meio tá bocejando.",
  "Parado. Tipo estátua. Estátua não soletra.",
  "Quer uma dica? Tem botão pra isso. Custa pouco XP.",
  "Se você não jogar, eu vou jogar sozinho. E vou achar tudo. Vou nada.",
  "Tá pensando na palavra perfeita? Palavra imperfeita também pontua."
],
solAleatorio: [
  "Sabia que abelha tem cinco olhos? E mesmo assim você não enxerga a palavra que tá na tua frente.",
  "A palavra mais longa do português tem 46 letras: pneumoultramicroscopicossilicovulcanoconiótico. Não cabe na colmeia.",
  "Abelhas fazem hexágono porque é a forma mais eficiente. Eu faço piada porque é a forma mais eficiente de te irritar.",
  "Uma abelha visita dezenas de flores por viagem. Você visita a mesma palavra errada várias vezes.",
  "‘Saudade’ é famosa por ser difícil de traduzir. Igual o que eu sinto quando você erra.",
  "Acharam mel em tumbas egípcias que ainda dava pra comer. Diferente do pão da tua geladeira.",
  "Palíndromo é palavra que lê igual dos dois lados. Tipo ‘arara’ e ‘osso’. ‘Bugado’ ao contrário é ‘odaguB’. Não funciona.",
  "Abelhas se comunicam dançando. Se eu dançar, você acha mais palavras? Vou tentar.",
  "A letra mais usada do português é o A. O W é tão pouco usado que nem entra na colmeia.",
  "Existem umas 20 mil espécies de abelha. Nenhuma sabe soletrar. Você tá na frente.",
  "Pangrama também é frase com todas as letras do alfabeto. Aqui é mais fácil: só sete.",
  "Uma abelha operária vive umas seis semanas. Eu vivo enquanto a aba tiver aberta. Não fecha.",
  "O zangão não tem ferrão. Eu também não. Só tenho sarcasmo.",
  "Sabia que ‘oxítona’ é paroxítona? A língua portuguesa adora uma pegadinha.",
  "Uma abelha produz tipo uma colherzinha de mel na vida toda. Trabalha a vida inteira por uma colherzinha. Igual a gente.",
  "Anagrama de ‘amor’ é ‘Roma’. Anagrama de ‘Bugado’ é ‘dobuga’. Não significa nada. Igual eu.",
  "Hexágono tem seis lados. Minha paciência tem um. E tá acabando. Brincadeira. Tá cheia.",
  "‘Avó’ e ‘avô’: um chapéu diferente e é outra pessoa. Português é assim.",
  "Abelhas conseguem reconhecer rostos humanos. Elas te reconhecem. E comentam.",
  "O dicionário tem centenas de milhares de verbetes. Eu tenho umas 28 mil palavras aqui. Não é concorrência, é parceria.",
  "A abelha rainha bota mais de mil ovos por dia. E você aí sem botar uma palavra.",
  "Tem gente que fala ‘menas’. Eu não julgo. Julgo sim.",
  "Bzzzz. Desculpa, era a abelha. Ou era eu imitando a abelha. Não conta.",
  "Se a colmeia fosse um prédio, a letra do meio seria o porteiro. Sabe de tudo, fala com todo mundo.",
  "‘Paralelepípedo’ era a palavra difícil da escola. Hoje é ‘boleto’. Difícil de pagar.",
  "O ‘ç’ aqui vira ‘c’. É o disfarce dele. Ninguém desconfia.",
  "Abelha dorme agarrada numa flor. Eu durmo no cache do navegador.",
  "Tem palavra que só existe no plural, tipo ‘óculos’. O óculos que lute.",
  "Um dia vou fazer um Soletra só com palavras que eu inventei. Vai ter ‘bugância’ e ‘pixelar’.",
  "‘Abelhudo’ é quem fica olhando a vida dos outros. Tipo eu olhando teus chutes.",
  "Minha palavra favorita é ‘jabuticaba’. Não cabe em colmeia de sete letras. Sofro.",
  "A asa da abelha bate umas 200 vezes por segundo. Meu coração bate assim quando você acha pangrama.",
  "Se você falar ‘colmeia’ três vezes no espelho, nada acontece. Testei.",
  "‘Ypiranga’ já foi escrito com Y. Hoje o Y tá banido da colmeia. Justiça poética.",
  "Pipoca, peteca, capivara: tudo palavra que veio do tupi. A capivara aprova esse jogo.",
  "‘Aeroportuário’ tem as cinco vogais. Eu conferi. Duas vezes. Tava entediado.",
  "Abelha não enxerga vermelho, mas vê ultravioleta. Eu vejo teus erros. Em alta definição.",
  "Tem um hexágono gigante de nuvens no polo norte de Saturno. Colmeia cósmica.",
  "Mel não estraga, pão de mel estraga, e eu não entendo mais nada.",
  "Cientistas dizem que ler em voz alta ajuda a lembrar palavras. Os vizinhos discordam."
],

/* ---------- cutucar ---------- */
cutucarSoletra: [
  "Me cutucou! Eu não sou letra. Não entro na palavra.",
  "Ei! Eu não sou hexágono. Sou gato. Fantasma. Gato-fantasma. Não me clica.",
  "Toda vez que você me cutuca, uma abelha perde o rumo.",
  "Cutucar o Bugado não dá ponto. Mas dá carinho. Pouco carinho.",
  "Tô ocupado contando tuas palavras. Perdi a conta. Culpa tua.",
  "Quer uma dica? Sério? Então: a palavra tem letras. De nada.",
  "Ai! Tô com a colmeia na cabeça e você me cutuca.",
  "Se me cutucar sete vezes, vira pangrama? Não. Mas testa.",
  "Eu sou o mascote, não o botão de enviar. Entendo a confusão. Não entendo.",
  "Me cutuca não que eu zumbo. Bzzzz.",
  "Isso é pedido de ajuda? Ajuda: usa a letra do meio.",
  "Cutucou! Agora vou narrar tua próxima palavra com voz de locutor de rodeio.",
  "Tô de olho na tua lista. Tá magrinha. Alimenta ela.",
  "Clicar em mim não embaralha as letras. Tem botão pra isso.",
  "Oi. Sim, eu sei todas as respostas. Não, eu não vou contar.",
  "Me cutucou de novo. Querido diário: hoje me cutucaram. De novo.",
  "Sou um bug, não uma abelha. Mas se precisar, eu zumbo.",
  "Você cutuca mais do que soletra. Estatística real. Mais ou menos real.",
  "Parei de pensar em palavras por tua causa. Agora só penso em cutucada.",
  "Quer saber uma palavra? ‘Cutucar’. Não serve hoje. Provavelmente.",
  "Tô guardando uma palavra secreta. Se me cutucar mais, eu... continuo guardando.",
  "Eita, que dedo nervoso. Usa ele nas letras.",
  "Carente? Acha um pangrama que eu te dou atenção.",
  "Me cutucou. Um neurônio teu foi gasto nisso. Valeu a pena?",
  "Sou fofo, eu sei. Mas as letras também são. Clica nelas.",
  "Psiu, a letra do meio tá com ciúme de mim.",
  "Toc toc. Quem é? Uma palavra que você ainda não achou.",
  "Ai, cócegas! Não, espera, eu não sinto cócegas. Mas finjo.",
  "Clicou no Bugado. Conquista desbloqueada: perda de tempo nível 1.",
  "Eu não tô na colmeia. Eu tô ACIMA da colmeia. Metaforicamente.",
  "Cada cutucada minha é uma palavra que você não tá achando.",
  "Pode me cutucar à vontade, o relógio não para. Mentira, não tem relógio. Pode cutucar.",
  "Sabe o que eu queria? Que você achasse uma palavra de oito letras. Agora.",
  "Tá me testando? Eu sou à prova de cutucada. Quase.",
  "Me cutucou! Vou dar uma dica falsa: a resposta é ‘jacaré’. Provavelmente não é.",
  "Sou o suporte técnico da colmeia. Já tentou desligar e ligar a cabeça?",
  "Eu mordo. Mordo pouco. Mordo de leve. Não cutuca.",
  "Quem cutuca mascote não acha pangrama. Ditado popular. Que eu inventei.",
  "Ai, pisou no meu rabo. Eu tenho rabo? Tenho glitch. Pisou no meu glitch.",
  "Você me cutuca e eu embaralho teus pensamentos. Pronto, embaralhei.",
  "Oi, sumido. Ah, não sumiu, tá aí me cutucando.",
  "Tô meditando. Om. Ommm. Ommmmm. Cutucou, perdi o foco.",
  "Se cutucada valesse ponto, você já era Gênio Bugado.",
  "Não sou botão de dica. Sou botão de sarcasmo. Aperta e sai coisa.",
  "Cutuca eu, cutuca as letras, cutuca o dicionário. Só não cutuca a abelha."
]
};

/* ---------- comentários de palavras específicas (chave sem acento) ---------- */
window.FALAS_SOLETRA_PALAVRAS = {
  abelha: "ABELHA! Você achou a dona da casa. As outras abelhas aplaudiram.",
  colmeia: "COLMEIA! Achou a própria casa das letras. Metalinguagem de abelha.",
  amor: "AMOR. Quatro letras, um ponto, infinitos problemas.",
  casa: "CASA. O lugar onde você devia estar dormindo em vez de soletrar.",
  gato: "GATO! Isso foi uma indireta pra mim? Aceito.",
  gatinho: "GATINHO! Eu, basicamente.",
  vida: "VIDA. Curta, tipo essa palavra. Aproveita.",
  morte: "MORTE. Pesado. Mas pontua.",
  cafe: "CAFÉ! O combustível oficial de quem joga Soletra de madrugada.",
  bolo: "BOLO. Agora eu quero bolo. Obrigado por nada.",
  sono: "SONO. Tá com sono? Eu não durmo. Sou um bug. Queria dormir.",
  preguica: "PREGUIÇA. A palavra que mais combina com domingo.",
  segunda: "SEGUNDA. Pra que lembrar disso? Pra quê?",
  sexta: "SEXTA! A palavra mais esperada da semana.",
  domingo: "DOMINGO. Dia de almoço em família e de soletrar escondido no banheiro.",
  feriado: "FERIADO! A palavra mais bonita da língua portuguesa. Não tem discussão.",
  boleto: "BOLETO. Até no Soletra ele me persegue.",
  piada: "PIADA. Tipo teus chutes anteriores. Brincadeira. Mais ou menos.",
  pizza: "PIZZA! Com dois Z. Palavra estrangeira naturalizada, documentos em dia.",
  banana: "BANANA! Três A e dois N. Economia de letra.",
  coco: "COCO. Repete letra, pontua igual. Espertinho.",
  papai: "PAPAI. Ele tá orgulhoso de você. Talvez. Pergunta pra ele.",
  mamae: "MAMÃE! Manda um oi pra ela. Ela merece.",
  sogra: "SOGRA. Achou a palavra. Agora foge dela.",
  chefe: "CHEFE. Não conta pra ele que você tá jogando no expediente.",
  salario: "SALÁRIO. Palavra rara. Aparece uma vez por mês e some.",
  dinheiro: "DINHEIRO. Achou no Soletra. Na carteira, vamos ver.",
  praia: "PRAIA! Sol, mar e zero palavras pra soletrar. Um sonho.",
  chuva: "CHUVA. Dia bom pra ficar em casa soletrando. Tipo agora.",
  festa: "FESTA! A colmeia tá em festa com essa.",
  escola: "ESCOLA. Tua professora de português tá vendo isso? Espero que sim.",
  prova: "PROVA. Essa você passou. Nota: alguns pontos a mais.",
  livro: "LIVRO! Olha só, alguém lê. Tô emocionado.",
  letra: "LETRA. Metalinguagem! Achou a palavra que descreve o que você tá usando.",
  palavra: "PALAVRA! Achou a palavra ‘palavra’. Isso é tão meta que eu bugei.",
  jogo: "JOGO. Você tá num jogo achando a palavra jogo. Inception.",
  erro: "ERRO. Irônico acertar justo a palavra erro.",
  falha: "FALHA. Palavra certa. Nada falhou aqui.",
  virus: "VÍRUS! Cuidado, eu sou um bug, a gente se conhece.",
  mouse: "MOUSE. Tá usando um agora? Ou é dedo na tela? Não importa, pontuou.",
  tela: "TELA. Você tá olhando pra uma. Agora mesmo. Pisca.",
  genio: "GÊNIO. Tá se descrevendo? Humildade, hein.",
  burro: "BURRO! Achou. Isso quer dizer que você não é. Lógica.",
  chato: "CHATO. Eu? Nunca. Talvez. Um pouco.",
  lindo: "LINDO. Igual eu. Obrigado.",
  feio: "FEIO. Nada aqui é feio. Tirando teus chutes errados.",
  fantasma: "FANTASMA! Eu sou meio fantasma. Tá me chamando?",
  bruxa: "BRUXA. Bruxaria de palavra: aparece do nada.",
  dragao: "DRAGÃO! Épico. Mais épico que a maioria das palavras.",
  pirata: "PIRATA! Arrr. Roubou uma palavra da colmeia.",
  ninja: "NINJA! Achou tão rápido que eu nem vi.",
  robo: "ROBÔ! Eu sou meio robô também. Tá me chamando?",
  pixel: "PIXEL! Minha espécie. Obrigado pela representatividade.",
  zumbi: "ZUMBI. Parecido com você às 3 da manhã jogando isso.",
  capivara: "CAPIVARA! A mascote não oficial do Brasil. Respeito máximo.",
  tatu: "TATU. Bicho fofo, palavra curta, ponto garantido.",
  jacare: "JACARÉ! Cuidado com os dedos.",
  tucano: "TUCANO! Bico grande, palavra bonita.",
  arara: "ARARA! Palíndromo! Lê igual de trás pra frente. Chique.",
  osso: "OSSO. Palíndromo! Lê de trás pra frente. Testa.",
  radar: "RADAR! Palíndromo! Mais um pra coleção de palavras espelho.",
  onca: "ONÇA! Pintada e perigosa. Igual meu humor.",
  tubarao: "TUBARÃO! Tu-dum, tu-dum. Achou.",
  polvo: "POLVO! Três corações, oito braços, e você achou ele.",
  girafa: "GIRAFA! Palavra alta. Quer dizer, comprida. Tanto faz.",
  zebra: "ZEBRA! Essa foi zebra mesmo, não esperava.",
  leao: "LEÃO! A colmeia rugiu.",
  urso: "URSO. Abraço de urso pra você. Virtual.",
  lobo: "LOBO. Auuuu. Desculpa, empolguei.",
  raposa: "RAPOSA. Esperta que nem você. Quase.",
  coruja: "CORUJA! Bicho da madrugada. Tipo você jogando isso a essa hora.",
  morcego: "MORCEGO. Parente distante meu. Somos seres da noite.",
  barata: "BARATA! Eca. Mas pontua.",
  mosquito: "MOSQUITO! Zzzz. Esse eu não gosto. Nem de palavra.",
  formiga: "FORMIGA! Trabalhadora igual abelha. Mas sem mel.",
  aranha: "ARANHA! Oito patas. Eu tenho quatro. Invejo.",
  pulga: "PULGA. Achou atrás da orelha, né?",
  galinha: "GALINHA! Có có có. Pontos, pontos, pontos.",
  pato: "PATO. Quack. Pontuou.",
  vaca: "VACA. Mu. Um ponto. Mu.",
  macaco: "MACACO! Primo teu. Brincadeira. Parente distante.",
  cobra: "COBRA! Sssss. Palavra venenosa, mas do bem.",
  sapo: "SAPO. Engole esse ponto.",
  cachorro: "CACHORRO! Eu sou gato. Tô ofendido. Mas pontua.",
  peixe: "PEIXE. Memória de três segundos. Diferente de você. Espero.",
  abacaxi: "ABACAXI! Palavra espinhosa, mas doce.",
  pipoca: "PIPOCA! Veio do tupi. A capivara aprova.",
  brigadeiro: "BRIGADEIRO! Agora eu quero um. Tô sem boca, mas quero.",
  coxinha: "COXINHA! Patrimônio nacional.",
  pastel: "PASTEL! Com caldo de cana, por favor.",
  feijao: "FEIJÃO! Base da pirâmide alimentar e da colmeia.",
  arroz: "ARROZ! Agora acha feijão pra completar o prato.",
  batata: "BATATA! Frita, cozida, palavra. Tudo bom.",
  tomate: "TOMATE. Fruta ou legume? Tanto faz, pontuou.",
  limao: "LIMÃO. Azedinho igual meu humor.",
  pudim: "PUDIM! Com furinho ou sem? Eu sou time sem furinho.",
  acai: "AÇAÍ! Com granola, banana e leite em pó. Isso é lei.",
  cuscuz: "CUSCUZ! Café da manhã de campeão.",
  tapioca: "TAPIOCA! Nordeste manda um abraço.",
  mandioca: "MANDIOCA! Ou aipim, ou macaxeira. Três nomes, uma raiz.",
  aipim: "AIPIM! Também conhecido como mandioca, macaxeira... ela tem muitos nomes.",
  biscoito: "BISCOITO! Ou bolacha? Não vou entrar nessa briga.",
  bolacha: "BOLACHA! Ou biscoito? Fico neutro. Mentira, é biscoito.",
  chocolate: "CHOCOLATE! Palavra doce. Muitas letras. Muito amor.",
  cerveja: "CERVEJA! Beba com moderação. Soletre sem moderação.",
  samba: "SAMBA! A colmeia sambou com essa.",
  forro: "FORRÓ! Arrasta-pé na colmeia.",
  pagode: "PAGODE! O churrasco de domingo mandou lembranças.",
  carnaval: "CARNAVAL! Confete e serpentina pra você.",
  novela: "NOVELA. Hoje tem capítulo. Não perde.",
  futebol: "FUTEBOL! Gol de placa no Soletra.",
  sofa: "SOFÁ. Onde você tá jogando isso agora, aposto.",
  celular: "CELULAR! Tá jogando nele agora? Aposto que sim.",
  senha: "SENHA. Não digita tua senha aqui, por favor. Só palavras.",
  internet: "INTERNET! Sem ela eu não existiria. Obrigado, internet.",
  teclado: "TECLADO! Você tá usando um agora. Ou tocando no vidro. Tanto faz.",
  fofoca: "FOFOCA! A colmeia adora. Conta mais.",
  saudade: "SAUDADE. A palavra que o mundo inveja da gente.",
  cafune: "CAFUNÉ! A melhor palavra. A melhor coisa. Quero um.",
  xicara: "XÍCARA! Com X. Não é chícara. Nunca foi.",
  dormir: "DORMIR. Você devia. Mas antes, mais uma palavra.",
  acordar: "ACORDAR. A pior palavra do dia.",
  trabalho: "TRABALHO. Tá jogando no trabalho? Não conto pro chefe.",
  abraco: "ABRAÇO! Mandei um virtual. Chegou?",
  beijo: "BEIJO! Mwah. Virtual. Sem constrangimento.",
  paciencia: "PACIÊNCIA. A virtude que você precisa pra achar todas.",
  preguicoso: "PREGUIÇOSO. Não é você. Você tá jogando. Isso é esforço.",
  soneca: "SONECA. Agora não, tem palavra pra achar.",
  pinguim: "PINGUIM! De fraque e tudo. Elegante.",
  papagaio: "PAPAGAIO! Repete, repete. Mas palavra repetida não vale."
};

(function(){
  const S = window.FALAS_SOLETRA, G = window.FALAS || {};
  if (!window.Bugado) return;
  // temáticas nas categorias compartilhadas
  Bugado.extendLines({ aleatorio: S.solAleatorio, parado: S.solParado });
  // bancos combinados só do Soletra (tamanho estável = saco sem repetição estável)
  S.solMisto = [...(G.aleatorio || []), ...S.solAleatorio];
  S.solParadoMix = [...(G.parado || []), ...S.solParado];
  Bugado.addLines(S);
})();
