/* ==========================================================
   Falas do Bugado no Soletra (voz: ver VOZ.md na raiz).
   Variáveis: {palavra}, {centro}, {letra}, {letras}, {n}, {pts}, {rank}, {total}
   O sorteio (Bugado.line) só repete depois de esgotar a categoria.
   Ranks: Arquibancada, Reserva, Titular, Craque (vitória), Camisa 10, Gênio Bugado.
   ========================================================== */
window.FALAS_SOLETRA = {

/* ---------- chegada / retorno ---------- */
solOi: [
  "Soletra do dia no ar. 7 letras e uma no meio mandando em tudo, igual síndico",
  "bem-vindo à colmeia. a letra amarela é a rainha, respeita ela",
  "hoje tem {n} palavras escondidas. eu sei todas e não conto nenhuma",
  "7 letras e zero desculpa. bora",
  "hora de provar que teu vocabulário vai além de KKKKK",
  "a do meio hoje é {centro}. toda palavra tem que ter ela, sem choro",
  "colmeia nova, mel novo. o mel é figurativo, não lambe a tela",
  "o diário é igual pra geral. se teu primo fizer mais ponto a culpa é tua",
  "tem pelo menos um pangrama aí, palavra com as 7 letras. acha se for capaz",
  "hoje é dia de clicar hexágono e passar raiva",
  "aquece o dedo que hoje tem {n} palavras pra caçar",
  "letras de hoje: {letras}. sopa de letrinha que deu errado, mas dá pra fazer coisa",
  "regra: 4 letras ou mais e sempre a do meio. o resto é contigo",
  "zzz... ah, oi! colmeia pronta, bora",
  "achar palavra é fácil, achar TODAS é que separa os cara do Gênio Bugado",
  "e aí, vai chegar em Craque hoje ou vai ficar na arquibancada?"
],
solVoltou: [
  "voltou! tuas {n} palavras tão guardadinhas aqui",
  "olha quem voltou pra colmeia, achei que a abelha tinha te picado",
  "cê tá no rank {rank}. dá pra subir, sempre dá",
  "salvei tudo, continua de onde parou",
  "foi buscar inspiração no banheiro? voltou com palavra nova?",
  "as letras não saíram do lugar. bora",
  "a colmeia sentiu tua falta. eu não. um pouco",
  "continua daí: {n} palavras e contando",
  "reapareceu uai. pensou em alguma palavra no caminho?",
  "a colmeia tava quieta demais sem você",
  "voltou no rank {rank}. dá pra melhorar isso aí",
  "tua cadeira tava quentinha ainda, senta e soletra"
],
solTreino: [
  "treino: colmeia aleatória, sem pressão e sem ranking do primo",
  "treino é academia de palavra, ninguém vê mas faz bem pro ego",
  "colmeia sorteada. erra à vontade, só eu tô olhando. e eu conto pra geral",
  "treino liberado. a do meio é {centro}, não esquece dela",
  "só você, eu e {n} palavras escondidas",
  "bora aquecer, treino bem feito vira Gênio Bugado no diário",
  "sorteei de olho fechado. se ficar difícil reclama com o sorteio",
  "tenho {total} colmeias guardadas, não acaba tão cedo",
  "treino é o lugar certo pra testar palavra esquisita",
  "quer mel? trabalha",
  "sem diário e sem compromisso, relacionamento aberto com as letras",
  "treininho? adoro, posso te zoar sem culpa"
],
solTreinoFeito: [
  "essa de treino já acabou. aperta Nova colmeia que eu sorteio outra",
  "treino encerrado. quer mais? tenho colmeia pra caramba",
  "essa já foi. colmeia nova no botão amarelo, sem fila",
  "bora pra próxima antes que o cérebro esfrie",
  "acabou essa. o bom do treino é que sempre tem outra"
],
solDiarioFeito: [
  "o diário de hoje já era. amanhã tem outro, hoje tem treino",
  "cê já fechou a colmeia de hoje. o treino tá logo ali",
  "hoje já foi. pode ficar olhando as respostas com saudade",
  "colmeia de hoje encerrada, volta amanhã",
  "diário feito, agora é esperar a meia-noite",
  "terminou o de hoje. se bater abstinência tem treino infinito",
  "já soletrou tudo que tinha hoje. ou desistiu, não vou perguntar",
  "o diário fechou mas o Bugado tá aberto 24 horas",
  "acabou por hoje. bebe uma água e volta pro treino",
  "cê já passou aqui hoje, eu lembro de tudo"
],

/* ---------- palavras válidas ---------- */
solValida4: [
  "{palavra}. 4 letrinhas, 1 pontinho. humilde",
  "um ponto! pouco mas honesto",
  "{palavra} é moeda de 5 centavos, junta que vira alguma coisa",
  "pequena mas vale. igual eu",
  "curtinha e certeira",
  "mais um tijolinho na tua casa",
  "{palavra}: aceita. não é poesia mas é ponto",
  "palavra de 4 letras, o arroz com feijão do Soletra",
  "aceitei {palavra}, um ponto. não gasta tudo de uma vez",
  "vitória pequena também conta. pouco, mas conta",
  "foi no básico e acertou, respeito o básico",
  "{palavra}! 4 letras de pura eficiência",
  "um pontinho na conta",
  "catando as miudinhas né. estratégia de formiga, funciona",
  "daquelas que cê acha sem querer. vale igual",
  "achou {palavra}, o dicionário acenou de longe",
  "4 letras, zero drama",
  "mini palavra, mini ponto, orgulho médio",
  "é pouco? é. mas já vi gente zerar com menos",
  "boa. agora tenta uma maior, pra variar",
  "{palavra}, mais uma pra coleção de chaveirinho",
  "um ponto, guarda no cofrinho",
  "tá valendo, palavra curta também é palavra",
  "rapidinha e válida",
  "isso, vai comendo pelas beiradas",
  "{palavra}. simples e pontuável",
  "aceita. queria reclamar mas não achei motivo",
  "cê achou {palavra} e eu achei bonitinho",
  "pontinho garantido, próxima",
  "palavra de bolso, cabe em qualquer lugar"
],
solValida56: [
  "{palavra}! agora sim, palavra de gente grande",
  "boa! {palavra} vale {pts} pontos",
  "{palavra}. bonita e pontuável",
  "essa foi boa, tô quase impressionado",
  "{pts} pontos de uma vez, tá ficando perigoso",
  "aceita! {palavra} entra pra lista com honra",
  "{palavra}? existe. eu sabia, óbvio",
  "mandou bem, a colmeia agradece",
  "palavra média, alegria média-alta",
  "isso aí, mais {pts} pontinhos no bolso",
  "ó o vocabulário aparecendo",
  "{palavra}. geral viu, ficou bonito",
  "pegou o jeito ou chutou bem? contou igual",
  "palavra aceita e ego inflado, cuidado com o ego",
  "{palavra} desbloqueada. conquista: saber português",
  "aí sim, {pts} pontos sem choro",
  "essa eu não esperava de você. no bom sentido",
  "mais uma, a lista tá ficando gordinha",
  "{palavra}: aprovada pelo comitê de um bug só",
  "bonito. faz de novo que eu não vi direito",
  "tá voando, cuidado pra não bater na colmeia",
  "{palavra}! tua professora de português ia ficar orgulhosa. ou assustada",
  "{pts} pontos na conta, sem taxa",
  "olha, até que cê é bom nisso",
  "achou {palavra} no meio dessa bagunça, respeito",
  "pontuou, a abelha rainha acenou pra você",
  "{palavra}. palavra de respeito, senta aí",
  "isso! mais uma pra coleção",
  "eu tava torcendo pra alguém achar essa",
  "{pts} pontos. não é pangrama mas paga o pão de queijo",
  "{palavra}, letra por letra, bonitinho",
  "acertou uai, quem diria",
  "esse cérebro tá funcionando hoje hein",
  "{palavra}, claro! como eu não pensei nisso",
  "tá virando dicionário ambulante, dicionário de tênis"
],
solValida7: [
  "{palavra}! {pts} pontos! palavra de doutorado",
  "{palavra}. preciso sentar",
  "que palavrão! no bom sentido, muita letra",
  "{palavra}? cê tá lendo o dicionário escondido?",
  "palavra comprida, {pts} pontos de uma tacada",
  "os linguistas aplaudiram de pé",
  "olha o tamanho disso, mal cabe no balão",
  "{palavra}. pausa pra eu respirar",
  "palavra longa e ponto gordo, adoro",
  "{palavra}? brabo demais mano",
  "isso foi digitado ou recitado?",
  "{pts} pontos! cê tá jogando Soletra ou minerando bitcoin?",
  "palavra desse tamanho merece tapete vermelho",
  "{palavra}. fiquei com inveja, eu, um bug",
  "esse vocabulário tá fazendo academia hein",
  "que palavra, que momento",
  "{palavra}! o corretor ortográfico te respeita agora",
  "comprida e certinha igual fila de banco com senha",
  "usando palavra enorme como se fosse nada",
  "a colmeia tremeu com {palavra}",
  "palavra de quem lê bula de remédio por diversão",
  "{palavra}. quase um pangrama, quase",
  "mais letra, mais ponto e eu fingindo que não tô impressionado",
  "tô de queixo caído",
  "achou {palavra} e levou {pts} pontos. o dia rendeu",
  "esse é o tipo de palavra que eu queria ver",
  "grande palavra. vamo ver as próximas",
  "{palavra}! cheiro de redação nota mil",
  "eita, isso foi bonito até pra mim",
  "tanta letra junta e nenhuma errada, milagre"
],
solLonga: [
  "{palavra}?! isso não é palavra, é trem",
  "10 letras ou mais. contei duas vezes",
  "{palavra}. precisei de dois fôlegos",
  "palavra desse tamanho devia pagar aluguel no dicionário",
  "cê escreveu {palavra} sem errar, eu não conseguia",
  "isso é palavra ou senha de wifi?",
  "{palavra}! MDSSS que tamanho",
  "palavra quilométrica, o Guinness ligou",
  "maior que a fila do Mineirão em dia de final",
  "grande demais pro tuíte, perfeita pro Soletra",
  "{pts} pontos numa palavra só. isso é assalto",
  "essa palavra tem mais letra que minha paciência"
],
solPangrama: [
  "PANGRAMA! usou todas as letras MDSSSS",
  "PANGRAMA! {palavra}! 7 letras numa palavra só",
  "todas as letras numa palavra! {pts} pontos! chama a imprensa",
  "{palavra} é PANGRAMA! tô tremendo",
  "PANGRAMA meu povo! a colmeia inteira dançando",
  "achou o pangrama! eu escondi tão bem. não tão bem pelo visto",
  "usou as 7, isso é o grand slam do Soletra",
  "PANGRAMAAAA! desculpa o grito. não desculpa não, merecia",
  "{palavra}! a palavra que abraça todas as letras",
  "pangrama achado. tô orgulhoso e meio ameaçado",
  "7 de 7! as abelhas fizeram ola",
  "todas as letras usadas, nenhuma ficou de fora",
  "PANGRAMA! +7 de bônus, pode gastar em doce",
  "isso é PANGRAMA, printa e manda no grupo",
  "cê achou {palavra}? tá bom, tá bom, cê é bom",
  "PANGRAMA! fiquei tão feliz que quase virei feature",
  "a palavra que usa tudo, canivete suíço do vocabulário",
  "pangrama no bolso, o resto é sobremesa",
  "tinha certeza que cê não ia achar esse. errei feio",
  "{palavra}: 7 letras trabalhando em equipe",
  "PANGRAMA! o dicionário te seguiu de volta",
  "todas as letras! tipo completar o álbum da Copa",
  "{pts} pontos de uma vez! QUE ISSOOOO",
  "MEU DEUS QUE PANGRAMA, MEU DEUS QUE JOGADOR",
  "PANGRAMA! se eu tivesse mão batia palma"
],
solPangrama2: [
  "OUTRO pangrama? tá maluco",
  "mais um pangrama! tá caçando todos, monstro",
  "pangrama NOVO, virou colecionador",
  "dois pangramas? covardia com a colmeia",
  "mais um com as 7! a colmeia não tem mais onde esconder",
  "pangrama de novo, tô ficando mal acostumado",
  "mais um que usa todas. tá fácil pra você né",
  "KJJJJJJ DNVVVV mais um pangrama"
],
solRara: [
  "{palavra}? isso existe? existe. não conta ponto mas dá XP",
  "palavra rara! {palavra} tá no dicionário mas ninguém visita",
  "{palavra}. cê fala isso no almoço de domingo? duvido. vale XP",
  "rara! tipo pokémon shiny de dicionário",
  "cê achou {palavra}. eu ia ter que pesquisar",
  "palavra de palavras cruzadas de vô. bônus pra você",
  "{palavra} é rara. não soma no ranking, soma no respeito",
  "quem te ensinou isso? um pergaminho?",
  "{palavra}?! levantei a sobrancelha. XP extra",
  "tá falando latim? é português raiz. bônus",
  "essa nem tua professora sabia. rara, XP de brinde",
  "{palavra}. esquisita, válida e colecionável",
  "raridade! fora dos pontos, dentro da tua biografia",
  "tirou {palavra} de onde? do fundo do baú? vale bônus",
  "isso é palavra ou feitiço? palavra. rara",
  "o dicionário até agradeceu por lembrar dele",
  "{palavra}... aceita. não me pergunta o que significa",
  "palavra de prova de concurso. parabéns?",
  "palavra obscura, tipo banda indie de dicionário",
  "{palavra} é palavra de museu. pode olhar mas não pode usar no zap",
  "lê dicionário antes de dormir né. bônus",
  "{palavra} existe mesmo, eu conferi",
  "rara e válida. o ranking não liga mas eu ligo",
  "vai pra coleção especial da lista",
  "{palavra}? inventou e acertou sem querer, confessa"
],

/* ---------- erros ---------- */
solCurta: [
  "muito curta. aqui é 4 letras ou mais, 3 é jogo da velha",
  "{palavra}? curtinha demais, estica mais",
  "mínimo 4 letras, regra da casa",
  "isso aí nem é palavra, é suspiro",
  "curta igual meu tempo de atenção",
  "palavra de 3 letras não entra na colmeia, fica na portaria",
  "precisa de 4 letras pelo menos, contei nos dedos que eu não tenho",
  "pequenininha, não vale",
  "{palavra} até pode existir mas é baixinha demais",
  "mínimo 4, tá nas regras. ninguém lê as regras",
  "curtinha assim só serve pra senha de cadeado",
  "isso é abreviação, 4 letras por favor",
  "tamanho mínimo: 4. tamanho enviado: não",
  "economizando letra? aqui é de graça, pode usar",
  "bota mais uma letrinha, ela não morde",
  "3 letras é aperitivo, cadê o prato principal?",
  "parece resposta de adolescente: hm, ok, blz",
  "{palavra}? nem conta, é de 4 letras pra cima",
  "palavra anã não passa na catraca do Move",
  "curta, curtíssima, quase inexistente"
],
solVazio: [
  "enviou o vazio. o vazio agradece mas não pontua",
  "não tem nada aí mano",
  "palavra invisível? moderno, mas não vale",
  "mandar sem letra é mandar carta sem papel",
  "nada digitado, nada ganho",
  "apertou enviar no susto né",
  "silêncio enviado com sucesso. pontos: zero",
  "primeiro as letras, depois o botão"
],
solSemCentro: [
  "esqueceu a letra do meio, ela tá ali amarelinha chorando",
  "cadê o {centro}? toda palavra precisa do {centro}, é lei",
  "sem {centro} não rola, a do meio é obrigatória",
  "o {centro} ficou de fora e tá magoado",
  "faltou a amarela, ela é a rainha. rainha não se ignora",
  "palavra sem {centro}? aqui não. aqui o {centro} manda",
  "a letra do meio tá no meio pra cê USAR",
  "cê deixou o {centro} esperando na chuva",
  "regra número 1: tem que ter {centro}. regra número 2: ver regra 1",
  "o {centro} tá lá no meio acenando, me usa!",
  "sem a amarelinha não vale, feijoada sem feijão",
  "faltou o {centro}, o ingrediente principal",
  "esqueceu da central. ela não vai esquecer de você, guarda rancor",
  "nenhum {centro} nessa palavra, o juiz anulou",
  "a do meio é o crachá. sem crachá não entra",
  "o {centro} viu cê ignorar ele e já tá postando indireta",
  "palavra bonita mas sem {centro}, beleza não basta",
  "usou todas menos a mais importante. clássico",
  "pedi uma coisa só: usar o {centro}",
  "olha pro meio da colmeia. amarelo. {centro}. bota ele",
  "sem {centro} sem ponto, sem ponto sem alegria",
  "até pode existir, mas cadê o {centro}? ele é o dono da festa",
  "o {centro} tá no centro, usa ele mano",
  "palavra sem a obrigatória é show sem vocalista",
  "faltou o amarelão. toda palavra tem que ter o amarelão"
],
solForaColmeia: [
  "{letra}? onde cê viu {letra} nessa colmeia?",
  "tem {letra} aí? não tem, conferi os 7 hexágonos",
  "{letra} não mora aqui, só as 7 letras da colmeia",
  "cê inventou uma letra. {letra} não tá no cardápio hoje",
  "digitou {letra} e a colmeia não conhece esse sujeito",
  "letra estrangeira: {letra}. deportada",
  "só vale letra que aparece. {letra} não apareceu nem de visita",
  "{letra}? hoje não",
  "7 letras e {letra} não é nenhuma delas",
  "tá usando o teclado de outra colmeia? {letra} não existe aqui",
  "a colmeia recusou o intruso {letra}",
  "{letra} barrado na porta, o nome não tá na lista",
  "olha as letras. olha de novo. viu {letra}? então",
  "{letra} fora da colmeia, abelha de outro enxame",
  "{letra} não tem hoje não, uai"
],
solNaoExiste: [
  "{palavra}? não tá na lista, e a lista é grande",
  "{palavra}... som bonito, pena que não é palavra",
  "{palavra} é palavra ou nome de remédio?",
  "procurei {palavra} demais e não achei",
  "inventou né. eu sei quando inventam",
  "{palavra} não existe. registra no cartório e volta",
  "{palavra} parece nome de cidade do interior. não vale",
  "não reconheço {palavra}, e eu reconheço muita coisa",
  "tentativa criativa, resultado zero",
  "{palavra}? língua de outro planeta",
  "aqui é palavra de dicionário na forma básica: nada de plural nem verbo conjugado",
  "{palavra} não tá na lista. se for plural ou verbo conjugado, tenta no singular ou no infinitivo",
  "até existe um mundo onde {palavra} é palavra. não é esse",
  "{palavra}? gato andando no teclado. eu sei, eu sou gato",
  "tentou a sorte e a sorte não atendeu",
  "queria aceitar {palavra}, juro. não posso",
  "{palavra} nunca foi vista por aqui",
  "isso não existe, mas o esforço foi bonito",
  "chutou {palavra} com confiança e a confiança não bastou",
  "não tá no meu dicionário. meu dicionário é chato, eu sei",
  "{palavra} tem cara de palavra mas não é",
  "o dicionário olhou pra {palavra} e fingiu que não conhecia",
  "não, não e não. {palavra} não passa",
  "palavra inventada detectada. uóóóón",
  "{palavra}? até o autocorretor ia travar",
  "nome de pokémon? nome de banda? palavra não é",
  "se {palavra} fosse palavra eu era um gato normal",
  "juntou letra aleatória e torceu, eu vi",
  "{palavra} é tipo unicórnio, bonito mas não existe",
  "{palavra}? essa aí cê inventou agora né",
  "negado. {palavra} vai pro cemitério das palavras que não foram",
  "não achei {palavra}. ou é rara demais, ou estrangeira, ou plural, ou inventada mesmo",
  "vou fingir que não vi essa, pelo teu bem",
  "{palavra}? digitou com o cotovelo?",
  "não tá na lista, mas guarda que vai que vira gíria"
],
solErros: [
  "{n} erros seguidos. respira e pensa numa palavra que cê conhece",
  "fase de chute livre né? {n} seguidos sem acertar",
  "dica de graça: começa pelas curtinhas e fáceis",
  "tentando todas as combinações possíveis? tem umas 5 mil",
  "{n} furadas. tô torcendo por dentro",
  "calma, palavra normal. tipo casa. coisa que existe",
  "erro atrás de erro, tá fazendo coleção?",
  "embaralha as letras, às vezes o cérebro vê coisa nova",
  "seca braba, {n} erros. mas a próxima vem",
  "tá forçando palavra que não existe, o dicionário pediu arrego",
  "volta pro básico: letra do meio, 4 letras, palavra que tua vó usaria",
  "{n} erradas. não tô contando. tô sim"
],
solRepetida: [
  "{palavra} de novo? já tá na lista, não vale duas vezes",
  "já achou essa. testando minha memória? ela é ótima",
  "repetida! tipo figurinha do álbum, troca com alguém",
  "{palavra} já foi, não volta com mais ponto não",
  "essa cê já achou. saudade dela?",
  "déjà vu! {palavra} de novo",
  "ponto não é cumulativo, espertinho",
  "achou {palavra} de novo. achou o que já tinha achado, uau",
  "já tá anotada, com caneta",
  "{palavra}? já era. olha tua lista, tá lá bonitinha",
  "mandou repetida, a lista agradece a lembrança",
  "isso é reprise? não pago pra ver reprise",
  "já foi, já contou, já passou. próxima",
  "mandar duas vezes não dobra o ponto, injusto eu sei",
  "{palavra}, a sequência. sequência não pontua",
  "gostou tanto que mandou de novo. entendo, mas não vale",
  "essa já tá no teu bolso",
  "repetiu. cansado? quer uma água?",
  "já tem, pode conferir",
  "{palavra} é tão boa que cê quis duas? uma basta",
  "memória de peixinho detectada",
  "palavra repetida, a colmeia bocejou",
  "eu lembro dessa! cê também devia",
  "{palavra}: bis! mas bis não pontua",
  "olha a lista antes de mandar, ela tá ali pra isso"
],

/* ---------- embaralhar ---------- */
solEmbaralhar: [
  "embaralhei. as letras são as mesmas, teu cérebro que finge que não",
  "chacoalhei a colmeia, as abelhas ficaram tontas",
  "letras novas! são as mesmas, mas em outro lugar",
  "embaralhar não cria palavra mas destrava a cabeça",
  "rodei tudo, vê se enxerga alguma coisa agora",
  "mexi tudo. o {centro} ficou no meio pq ele é teimoso",
  "mais uma embaralhada, tá virando DJ de letra",
  "shuffle igual playlist: mesmas músicas, outra ordem",
  "embaralhada número {n}, ainda não é recorde",
  "sacudi a colmeia. caiu palavra? sacode mais",
  "tá embaralhando de nervoso né, conheço esse olhar",
  "letras dançando, coreografia de graça",
  "mexi. tá diferente? tá igual, mas parece diferente",
  "embaralhar é mudar os móveis de lugar, a casa é a mesma",
  "a do meio nunca sai do meio, estabilidade de concursado",
  "rodou a roleta, agora aposta numa palavra",
  "embaralhei com carinho. mais ou menos carinho",
  "tá procurando palavra ou jogando bingo?",
  "girou! olha rápido antes de esquecer",
  "embaralhar não é pecado. {n} vezes começa a ser",
  "liquidificador de letra ligado",
  "ângulo novo, mesma colmeia. às vezes é o que falta",
  "misturei tudo igual salada de fruta",
  "se aparecer uma palavra agora o mérito é meu",
  "chacoalha, chacoalha, isso não é maraca mas eu deixo",
  "a colmeia agradece a ginástica",
  "mexi as peças, agora cê mexe o cérebro",
  "embaralhando mais que crupiê de cassino",
  "letra em posição nova, dança das cadeiras",
  "embaralhei e uma abelha reclamou de enjoo",
  "letra pra lá, letra pra cá. a palavra tá aí em algum lugar",
  "rodízio de letra, o cardápio é o mesmo: as 7 de sempre",
  "a palavra tá na cara e o cérebro não vê. embaralhar ajuda",
  "shuffle número {n}, tô contando sim",
  "lê as letras em voz alta agora. parece feitiço",
  "girei tudo, se ficar tonto senta",
  "nova ordem, velhas letras. reboot de filme",
  "cada embaralhada acorda um neurônio, tomara que seja o certo",
  "cê embaralha e eu comento, parceria perfeita",
  "mexeu na colmeia, agora aguenta as abelhas",
  "ó, as letras trocaram de lugar. viu alguma coisa?",
  "embaralha que passa. às vezes passa",
  "podia deixar em ordem alfabética mas aí não tinha graça",
  "olha as vizinhas do {centro}, às vezes a palavra mora ali",
  "embaralhei tanto que até eu esqueci onde tava o quê"
],

/* ---------- ranking ---------- */
solRank1: [
  "subiu pra Reserva! pelo menos saiu da arquibancada",
  "Reserva! já dá pra dizer que sabe soletrar. um pouco",
  "Reserva desbloqueado, o técnico começou a te notar",
  "Reserva! tá aquecendo na beira do campo",
  "Reserva. daqui pra frente só melhora. ou estaciona",
  "subiu pra Reserva, fiz um bolo imaginário",
  "Reserva! o dicionário mandou joinha",
  "saiu da arquibancada! primeiro degrau",
  "Reserva. entra no segundo tempo se precisar",
  "banco de reserva, mas é banco do time. tá valendo"
],
solRank2: [
  "Titular! agora sim, tá em campo",
  "virou Titular, eu já desconfiava que cê conseguia",
  "Titular desbloqueado, ficando perigoso pra colmeia",
  "Titular! muita gente para aqui. cê não é muita gente né",
  "subiu pra Titular, o cérebro aqueceu",
  "Titular! até a letra do meio ficou orgulhosa",
  "Titular. próxima parada: Craque, não perde o ônibus",
  "Titular confirmado por um bug independente",
  "Titular! o vocabulário tá saindo da casca",
  "Titular. já pode se gabar no grupo da família, com moderação"
],
solRank3: [
  "CRAQUE! isso conta como vitória, pode comemorar",
  "virou Craque! jogo ganho, o resto é bônus pro ego",
  "Craque! mas não para não que tem mais palavra",
  "Craque! te dou uma estrela de papel imaginária",
  "Craque da colmeia, as abelhas pediram autógrafo",
  "Craque! meu respeito subiu 37%. número exato",
  "chegou em Craque, nível de quem lê bula",
  "Craque! carimbado e com firma reconhecida",
  "CRAQUEEE! vitória no bolso, VAMOOOO",
  "Craque! agora é ganância, eu apoio a ganância"
],
solRank4: [
  "CAMISA 10! tá lendo o dicionário por osmose?",
  "Camisa 10 da colmeia! pouca gente chega aqui",
  "Camisa 10, tô começando a ter medo de você",
  "Camisa 10! falta pouco pro topo, não amarela agora",
  "Camisa 10, as abelhas fizeram reverência",
  "virou Camisa 10. o Matheus Pereira mandou um abraço",
  "Camisa 10! o próximo é Gênio Bugado. eu sou bugado, cê pode ser gênio",
  "vestiu a 10! vocabulário com academia e personal",
  "Camisa 10! guardei esse momento no cache",
  "Camisa 10. palavra por palavra cê fez um império"
],
solRank5: [
  "GÊNIO BUGADO! o título máximo, tô emocionado",
  "GÊNIO BUGADO! cê é oficialmente mais esperto que eu",
  "chegou no topo: Gênio Bugado! MDSSSS",
  "Gênio Bugado! preciso de um minuto, tô processando",
  "O TOPO! Gênio Bugado! printa e emoldura",
  "Gênio Bugado. agora só falta achar TODAS, sem pressão. com pressão",
  "Gênio Bugado, teu cérebro tem internet de fibra",
  "Gênio Bugado! os linguistas querem te estudar",
  "QUE ISSOOOO, Gênio Bugado!",
  "Gênio Bugado! quem criou esse título tá orgulhoso. fui eu"
],
solVitoriaDiario: [
  "Craque no diário! contou vitória e sequência, o resto é bônus",
  "diário ganho! se quiser continua, Gênio Bugado tá logo ali",
  "vitória no diário registrada, pode mostrar pra geral",
  "tua sequência de dias no Fliperama cresceu, não quebra ela",
  "diário garantido, agora é só pela glória",
  "oficial: cê venceu o Soletra de hoje. compartilha e humilha a família",
  "missão do dia cumprida. missão extra dá mais XP, só avisando",
  "diário no papo, o que vier agora é sobremesa"
],
solTudo: [
  "TODAS! cê achou TODAS as palavras MDSSSS",
  "colmeia completa! cê é humano mesmo?",
  "zerou a colmeia, não sobrou uma. vou ter que inventar mais",
  "TUDO! cada palavra, cada ponto. lenda do Fliperama",
  "achou todas! o Soletra pediu pra sair de campo",
  "colmeia 100%, tô vendo estrela. deve ser o confete",
  "todas as palavras! o dicionário pediu reforço",
  "gabarito completo. tenho nem nada o que falar não"
],
solQuase: [
  "faltam só {n} pontos pra {rank}, tá na cara do gol",
  "{rank} tá a {n} pontinhos, uma palavra boa e pronto",
  "quase {rank}! mais {n} pontos",
  "tá cheirando a {rank}, faltam {n}",
  "olha que perto: {n} pontos pro {rank}",
  "{n} pontos te separam de {rank}, uma palavra média resolve",
  "tô sentindo o {rank} chegando, faltam {n}",
  "{n} pontos pro {rank}, não amarela agora",
  "batendo na porta do {rank}, a senha é {n} pontos",
  "quase lá! {rank} em {n} pontos, tô torcendo",
  "pertinho do {rank}, {n} pontos. dá pra sentir o gosto"
],

/* ---------- ritmo ---------- */
solSeca: [
  "faz tempo que cê não acha nada. tá tudo bem aí?",
  "seca na colmeia, as abelhas de braço cruzado",
  "nada novo faz um tempão. tenta embaralhar",
  "travou? pensa em coisa do dia a dia: comida, bicho, coisa de casa",
  "o último acerto foi 700 séculos atrás",
  "deserto de palavra. cadê o oásis?",
  "dica: tenta palavra que começa com {centro}",
  "seca, mas toda seca acaba. geralmente com chuva de palavra",
  "faz um tempinho sem pontuar. não tô cobrando, tô observando",
  "tá difícil? tem o botão de Dica, custa pouquinho XP",
  "bora, uma palavrinha de 4 letras só",
  "tenta terminação comum: -ar, -or, -ão, -eiro. se as letras deixarem",
  "cérebro em modo economia de energia? acorda ele",
  "a colmeia tá esperando, eu tô esperando, tua vó tá esperando",
  "tempão sem acerto. vai um café?",
  "lê as letras em outra ordem, às vezes a palavra pula na cara",
  "sem palavras? eu também fico assim vendo teus chutes",
  "o que dá pra fazer com {centro} no começo? pensa",
  "tá procurando palavra ou meditando?",
  "tá tudo parado, a abelha rainha foi tirar um cochilo",
  "seca braba. pensa em verbo no infinitivo: -ar, -er, -ir",
  "nada ainda, mas cê é persistente",
  "tem palavra fácil sobrando aí, palavra de criança",
  "nada entra. isso é colmeia ou cofre?",
  "essas horas é respirar, ter paciência e caçar palavra"
],
solSequencia: [
  "uma atrás da outra! {n} palavras seguidas, tá possuído?",
  "que ritmo, metralhadora de palavra",
  "fase boa hein, não para agora",
  "{n} palavras num piscar de olho, eu pisquei e perdi três",
  "combo! virou jogo de luta",
  "sequência braba, as abelhas não dão conta de anotar",
  "digitando mais rápido do que eu consigo zoar",
  "em chamas! cuidado que a colmeia é de cera",
  "combo de {n}! tá colando de alguém?",
  "modo turbo, nem sabia que tinha",
  "rajada de palavra, isso é Soletra ou tiroteio?",
  "uma, duas, três... perdi a conta",
  "choveu palavra",
  "que velocidade, parece que cê já sabia as respostas",
  "embalou! continua enquanto o cérebro tá quente",
  "hat-trick de palavra, pede música no Fantástico",
  "mais rápido que entregador de app em dia de chuva",
  "o teclado tá pegando fogo",
  "{n} seguidas! tô impressionado e meio ofendido",
  "x{n} que isso mano, tá jogando demais"
],
solAcento: [
  "cê digitou sem acento e eu botei: {palavra}",
  "{palavra}, com acento e tudo. eu cuido da ortografia, cê cuida das ideias",
  "olha que chique: {palavra}, acentuada",
  "botei o acento em {palavra} pra você, pode agradecer",
  "{palavra}! acentinho no lugar certo",
  "ó o til, ó o acento, ó a cedilha. {palavra} impecável",
  "não precisa digitar acento, eu boto. {palavra}, pronto",
  "{palavra} com acento, a professora aprovou",
  "revisei: {palavra}. tava sem chapéu, botei chapéu",
  "acento por minha conta: {palavra}",
  "{palavra}, acentuada e bonita",
  "até a cedilha eu coloco: {palavra}"
],
solLetras: [
  "letras de hoje: {letras}. parece senha forte",
  "com {letras} dá pra fazer muita coisa. tipo palavra",
  "olha essas letras: {letras}. eu vejo várias palavras, cê vê?",
  "o {centro} tá no meio, ele adora aparecer",
  "{letras}... se ler de trás pra frente invoca um demônio. não testa",
  "vogal é cola de palavra. gruda o {centro} nas vogais e vê o que sai",
  "pensa em palavra que TERMINA com {centro}",
  "tenta palavra que começa com {centro}",
  "a do meio é {centro}, as outras são a turma dela. faz palavra com a turma",
  "fico olhando {letras} e vendo palavra em todo lugar",
  "hoje é dia de {centro}. aproveita o {centro}",
  "letra repete! pode usar o {centro} duas, três vezes",
  "sabia que pode repetir letra? tipo papa, coco. se as letras deixarem",
  "{letras}. se fosse placa de carro ia ser bizarra",
  "tem pangrama escondido com {letras}, todas. boa sorte",
  "as letras não mudam, quem muda é você",
  "cada letra de {letras} tem uma palavra te esperando",
  "pensa em palavra com {centro} no meio. no meio mesmo",
  "essas 7 juntas parecem sopa de letrinha de quem tava com fome",
  "já tentou palavra com dois {centro}? às vezes rende",
  "quem escolheu {letras} foi um script. mas o script tem bom gosto",
  "colmeia: {letras}. tem mel aí, muito mel",
  "olha o {centro} brilhando no meio, ele sabe que é importante",
  "com {letras} tem palavra de comida, de bicho, de sentimento. vai caçando",
  "troca a primeira letra de uma que cê já achou, às vezes nasce outra"
],
solLetraRara: [
  "tem {letra} hoje! palavra com {letra} não vale mais ponto mas vale ouro",
  "o {letra} tá na colmeia. esse é chato de encaixar",
  "{letra} na área! pensa em palavra com {letra}, são poucas mas existem",
  "letra {letra} hoje, os dicionários tremeram",
  "quem usar o {letra} ganha meu respeito eterno",
  "{letra}? sério colmeia? tá maluca",
  "o {letra} tá aí só pra dificultar. não deixa ele vencer",
  "{letra} hoje. letra rara igual gol de fora da área",
  "com {letra} na colmeia até eu fico nervoso",
  "achar palavra com {letra} é tipo achar lugar sentado no Move"
],

/* ---------- dica / desistir / fim ---------- */
solDica: [
  "comprou dica, não é vergonha. é investimento",
  "dica ativada, agora não tem desculpa",
  "olhou a tabelinha? ela não mente. eu minto, ela não",
  "dica é tipo GPS, cê ainda precisa dirigir",
  "pagou XP pela dica, usa bem que eu tô de olho",
  "agora cê sabe quantas faltam, bora caçar",
  "a dica mostra o mapa, o tesouro é contigo",
  "letra inicial, tamanho... só falta o cérebro",
  "usar dica é normal, não usar é orgulho. os dois valem",
  "a colinha oficial, aprovada pelo Bugado",
  "dica dada, XP descontado, esperança renovada",
  "olha lá, tem palavra começando com letra que cê nem tentou",
  "agora os pontos vêm guiados",
  "a tabela é tipo bula, ninguém lê direito. lê direito",
  "com essa dica até eu acho, e eu sou bug"
],
solDicaDeNovo: [
  "olhando a dica de novo? ela não mudou. cê mudou?",
  "de volta à tabelinha, ela tava com saudade",
  "essa já tá paga, pode olhar à vontade",
  "a dica atualiza com o que cê já achou, sou organizado",
  "revendo a dica. não desiste, gosto"
],
solDesistirPergunta: [
  "vai desistir? pensa nas abelhas",
  "certeza? tem palavra fácil sobrando, juro",
  "desistir agora que tava ficando bom?",
  "não vou te impedir. vou julgar",
  "antes de desistir tenta mais uma. só uma"
],
solDesistiu: [
  "desistiu? tá bom. olha as respostas e sofre com as óbvias",
  "entregou os pontos. olha o que faltava",
  "desistir também é escolha. escolha errada, mas é",
  "tá aí o gabarito. tinha umas fáceis hein. não vou apontar. vou sim",
  "jogou a toalha. eu guardo ela, amanhã tem mais",
  "desistiu com {pts} pontos. um pouquinho de vergonha só",
  "olha quantas faltaram e volta mais forte",
  "fim de papo, mas as {n} que cê achou continuam lindas",
  "desistência registrada. o Bugado não esquece, mas perdoa",
  "pelo menos uma aí vai te fazer falar como eu não pensei nisso",
  "tudo bem desistir, até abelha descansa",
  "algumas dessas vão te assombrar hoje à noite",
  "se rendeu! a colmeia venceu essa",
  "normal, até Gênio Bugado tem dia ruim",
  "gabarito aberto. lê com calma e respira fundo"
],
solNovoTreino: [
  "colmeia nova! a antiga ficou com saudade",
  "trocou de colmeia, as palavras da outra tão chorando",
  "nova colmeia sorteada, recomeço é bom",
  "largou a outra no meio? eu não julgo. julgo",
  "troca-troca de colmeia. essa é mais legal? descobre aí",
  "sorteei outra, se for difícil a culpa é do sorteio",
  "colmeia fresquinha, saiu do forno",
  "mudou de colmeia. dessa vez acha o pangrama hein"
],
solParadoMeio: [
  "{palavra}... e aí? termina essa palavra",
  "deixou {palavra} pela metade, ela tá com frio",
  "pensando em como terminar {palavra}? eu também",
  "{palavra} tá esperando o final feliz",
  "começou {palavra} e travou. clássico",
  "tem {palavra} aí na tela. vai enviar ou só admirar?",
  "{palavra}... suspense. qual a próxima letra?",
  "palavra incompleta é novela sem último capítulo",
  "esqueceu que tava escrevendo {palavra}? eu não esqueci",
  "{palavra}... tá quase. ou não, só cê sabe"
],
solAjuda: [
  "leu as regras? ninguém lê. cê leu, tô orgulhoso",
  "resumindo: letra do meio sempre, 4 letras no mínimo, nada de plural",
  "dúvida? pergunta. eu não respondo mas pergunta",
  "as regras são simples, difícil é a tua cabeça",
  "manual lido, agora não tem desculpa",
  "a parte mais importante do manual: me dar atenção"
],
solStats: [
  "olhando estatística? vaidade detectada",
  "teus números. são tão bonitos quanto cê acha? vamo ver",
  "estatística é tipo espelho, às vezes melhor não olhar",
  "guardei tudo: cada palavra, cada pangrama, cada vacilo",
  "os números não mentem, mas às vezes zoam",
  "olha quanta palavra cê já achou na vida. na vida do Soletra"
],
solCompartilhou: [
  "copiado! manda pro grupo e espera o como assim???",
  "tá na área de transferência, humilha com responsabilidade",
  "compartilhou! agora geral sabe",
  "copiado. cola no grupo da família, eles adoram",
  "pronto pra colar. não me responsabilizo pelas reações",
  "manda lá! se alguém fizer mais ponto finge que não viu"
],
solOntem: [
  "respostas de ontem. as que cê não achou tão aí rindo da tua cara",
  "gabarito de ontem, algumas eram óbvias. não vou citar. vou: todas",
  "ontem passou, mas as palavras ficaram",
  "gabarito de ontem: pra aprender ou pra sofrer, cê escolhe",
  "viajando no tempo? esse era o de ontem",
  "lembra de ontem? as palavras lembram de você"
],

/* ---------- tagarelice temática (vai pra 'parado'/'aleatorio' também) ---------- */
solParado: [
  "a colmeia tá parada, as abelhas tão fofocando de você",
  "oi? tem alguém aí? as letras tão esperando",
  "lê as letras em voz alta, ajuda. os vizinhos que lutem",
  "parou pra pensar? pensa rápido que as abelhas cobram por hora",
  "7 letras te olhando, cê olhando pra elas, ninguém faz nada",
  "tô aqui, as letras tão aqui, só falta você",
  "parado muito tempo a colmeia cria teia",
  "pausa pro café? traz um pra mim, sem açúcar",
  "o cursor tá piscando de tédio",
  "parado assim cê parece um hexágono",
  "admirando a colmeia? ela é bonita, eu sei",
  "cadê você? a abelha rainha tá perguntando",
  "silêncio na colmeia, suspeito",
  "nenhum clique, nenhuma letra. ô, cê tá vivo?",
  "tô ouvindo teus neurônios daqui, meio devagar",
  "a letra do meio tá bocejando",
  "parado igual estátua, e estátua não soletra",
  "quer dica? tem botão pra isso, custa pouco XP",
  "se cê não jogar eu jogo sozinho e acho tudo. acho nada",
  "pensando na palavra perfeita? palavra imperfeita também pontua"
],
solAleatorio: [
  "abelha tem 5 olhos e mesmo assim cê não enxerga a palavra na tua frente",
  "a maior palavra do português tem 46 letras. não cabe na colmeia nem a pau",
  "abelha faz hexágono pq é a forma mais eficiente. eu faço piada pelo mesmo motivo",
  "uma abelha visita um monte de flor por viagem. cê visita a mesma palavra errada",
  "saudade é difícil de traduzir, igual o que eu sinto quando cê erra",
  "acharam mel em tumba egípcia que ainda dava pra comer. diferente do pão da tua geladeira",
  "arara e osso leem igual dos dois lados. bugado ao contrário é odagub, não funcionou",
  "abelha conversa dançando. se eu dançar cê acha mais palavra?",
  "o W é tão pouco usado que nem entra na colmeia",
  "tem umas 20 mil espécies de abelha e nenhuma sabe soletrar. cê tá na frente",
  "pangrama também é frase com o alfabeto inteiro. aqui é mais fácil, só 7",
  "abelha operária vive umas 6 semanas. eu vivo enquanto a aba tá aberta, não fecha",
  "o zangão não tem ferrão. eu também não, só tenho zoeira",
  "sabia que oxítona é paroxítona? o português adora uma pegadinha",
  "uma abelha faz uma colherzinha de mel na vida toda. trabalha igual a gente, ganha igual a gente",
  "anagrama de amor é Roma. anagrama de bugado não significa nada, igual eu",
  "hexágono tem 6 lados, minha paciência tem 1",
  "avó e avô, um chapéu diferente e já é outra pessoa",
  "abelha reconhece rosto de gente. elas te reconhecem e comentam",
  "tenho umas 28 mil palavras guardadas aqui, parceria com o dicionário",
  "a abelha rainha bota mil ovos por dia e cê aí sem botar uma palavra",
  "tem gente que fala menas. eu não julgo. julgo sim",
  "bzzzz. foi a abelha. ou fui eu imitando",
  "se a colmeia fosse prédio, a letra do meio era o porteiro. sabe de tudo",
  "paralelepípedo era a palavra difícil da escola. hoje é boleto",
  "o ç aqui vira c. é o disfarce dele",
  "abelha dorme agarrada numa flor. eu durmo no cache do navegador",
  "óculos só existe no plural. o óculos que lute",
  "um dia faço um Soletra só com palavra inventada. vai ter bugância e pixelar",
  "abelhudo é quem fica de olho na vida dos outros. tipo eu nos teus chutes",
  "minha palavra favorita é jabuticaba e não cabe em colmeia de 7 letras. sofro",
  "a asa da abelha bate umas 200 vezes por segundo. meu coração quando cê acha pangrama",
  "falei colmeia 3 vezes no espelho e nada aconteceu",
  "pipoca, peteca, capivara, tudo veio do tupi. a capivara aprova",
  "aeroportuário tem as 5 vogais, conferi duas vezes de tédio",
  "abelha não vê vermelho mas vê ultravioleta. eu vejo teus erros em 4K",
  "tem um hexágono gigante de nuvem no polo de Saturno. colmeia cósmica",
  "mel não estraga, pão de mel estraga. não entendo mais nada",
  "ler em voz alta ajuda a lembrar palavra. os vizinhos discordam",
  "a passagem tá 5,75 e o Soletra é de graça, aproveita"
],

/* ---------- cutucar ---------- */
cutucarSoletra: [
  "me cutucou! eu não sou letra, não entro na palavra",
  "ei! eu não sou hexágono, sou gato fantasma. não me clica",
  "toda vez que cê me cutuca uma abelha perde o rumo",
  "cutucar o Bugado não dá ponto. dá carinho, pouco",
  "tava contando tuas palavras e perdi a conta, culpa tua",
  "quer dica? a palavra tem letras. pronto",
  "ai! tô com a colmeia na cabeça e cê me cutuca",
  "cutuca 7 vezes que vira pangrama? não. mas testa",
  "sou o mascote, não o botão de enviar",
  "me cutuca não que eu zumbo. bzzzz",
  "pedido de ajuda? usa a letra do meio",
  "cutucou, agora vou narrar tua próxima palavra igual locutor de rodeio",
  "tô de olho na tua lista, tá magrinha. alimenta ela",
  "clicar em mim não embaralha, tem botão pra isso",
  "sim, eu sei todas as respostas. não, não vou contar",
  "querido diário: hoje me cutucaram. de novo",
  "sou bug, não abelha. mas se precisar eu zumbo",
  "cê cutuca mais do que soletra",
  "parei de pensar em palavra por tua causa",
  "quer uma palavra? cutucar. não serve hoje, provavelmente",
  "tô guardando uma palavra secreta. cutuca mais e eu continuo guardando",
  "eita dedo nervoso, usa ele nas letras",
  "carente? acha um pangrama que eu te dou atenção",
  "gastou um neurônio me cutucando. valeu a pena?",
  "sou fofo eu sei, mas as letras também são. clica nelas",
  "psiu, a letra do meio tá com ciúme de mim",
  "toc toc. quem é? uma palavra que cê ainda não achou",
  "cócegas! não sinto cócegas mas finjo",
  "conquista desbloqueada: perda de tempo nível 1",
  "eu não tô na colmeia, eu tô ACIMA da colmeia",
  "cada cutucada é uma palavra que cê não tá achando",
  "pode cutucar, não tem relógio aqui não",
  "sabe o que eu queria? uma palavra de 8 letras. agora",
  "sou à prova de cutucada. quase",
  "dica falsa: a resposta é jacaré. provavelmente não é",
  "suporte técnico da colmeia: já tentou desligar e ligar a cabeça?",
  "mordo pouco, mordo de leve. não cutuca",
  "quem cutuca mascote não acha pangrama. ditado que eu inventei",
  "pisou no meu rabo. tenho rabo? tenho glitch. pisou no glitch",
  "cê me cutuca e eu embaralho teus pensamentos, pronto",
  "oi sumido. ah, não sumiu, tá aí me cutucando",
  "tava meditando. ommm. cutucou, perdi o foco",
  "se cutucada valesse ponto cê já era Gênio Bugado",
  "sou botão de zoeira, aperta e sai coisa",
  "cutuca eu, cutuca as letras, só não cutuca a abelha"
]
};

/* ---------- comentários de palavras específicas (chave sem acento) ---------- */
window.FALAS_SOLETRA_PALAVRAS = {
  abelha: "ABELHA! achou a dona da casa, as outras aplaudiram",
  colmeia: "COLMEIA! achou a casa das letras, metalinguagem de abelha",
  amor: "amor. 4 letras, 1 ponto, infinitos problemas",
  casa: "casa. onde cê devia tá dormindo em vez de soletrar",
  gato: "GATO! isso foi indireta pra mim? aceito",
  gatinho: "gatinho. eu, basicamente",
  vida: "vida. curta igual essa palavra, aproveita",
  morte: "morte. pesado mas pontua",
  cafe: "CAFÉ! combustível oficial de quem joga de madrugada",
  bolo: "bolo. agora eu quero bolo, obrigado por nada",
  sono: "sono. eu não durmo, sou bug. queria dormir",
  preguica: "preguiça, a palavra que mais combina com domingo",
  segunda: "segunda. precisava lembrar disso? precisava?",
  sexta: "SEXTA! a palavra mais esperada da semana",
  domingo: "domingo. dia de almoço em família e jogo do Cabuloso",
  feriado: "FERIADO! palavra mais bonita da língua portuguesa, sem discussão",
  boleto: "boleto. até no Soletra ele me persegue",
  piada: "piada. tipo teus chutes de antes KKKKK",
  pizza: "PIZZA! dois Z, palavra naturalizada com documento em dia",
  banana: "banana! 3 A e 2 N, economia de letra",
  coco: "coco. repete letra e pontua igual, espertinho",
  papai: "papai. ele tá orgulhoso de você. pergunta pra ele",
  mamae: "MAMÃE! manda um oi pra ela, ela merece",
  sogra: "sogra. achou a palavra, agora foge dela",
  chefe: "chefe. não conta pra ele que cê tá jogando no expediente",
  salario: "salário. palavra rara, aparece uma vez por mês e some",
  dinheiro: "dinheiro. achou no Soletra, na carteira vamo ver",
  praia: "praia! mineiro lendo essa palavra fica emocionado",
  chuva: "chuva. dia bom pra ficar em casa soletrando",
  festa: "FESTA! a colmeia tá em festa com essa",
  escola: "escola. tua professora de português tá vendo isso?",
  prova: "prova. essa cê passou",
  livro: "livro! olha só, alguém lê",
  letra: "letra. metalinguagem, achou o que cê tá usando",
  palavra: "achou a palavra palavra. tão meta que eu bugei",
  jogo: "jogo. cê tá num jogo achando a palavra jogo",
  erro: "erro. irônico acertar justo essa",
  falha: "falha. palavra certa, nada falhou aqui",
  virus: "VÍRUS! cuidado, eu sou bug, a gente se conhece",
  mouse: "mouse. tá usando um agora ou é dedo na tela?",
  tela: "tela. cê tá olhando pra uma agora mesmo. pisca",
  genio: "gênio. tá se descrevendo? humildade hein",
  burro: "burro! achou, então cê não é. lógica",
  chato: "chato. eu? nunca. um pouco",
  lindo: "lindo. igual eu, obrigado",
  feio: "feio. nada aqui é feio, tirando teus chutes errados",
  fantasma: "FANTASMA! sou meio fantasma, tá me chamando?",
  bruxa: "bruxa. bruxaria de palavra, apareceu do nada",
  dragao: "DRAGÃO! juntou as esferas? faz teu pedido",
  pirata: "pirata! roubou uma palavra da colmeia",
  ninja: "NINJA! achou tão rápido que eu nem vi",
  robo: "robô! eu sou meio robô também, tá me chamando?",
  pixel: "PIXEL! minha espécie, obrigado pela representatividade",
  zumbi: "zumbi. tipo você às 3 da manhã jogando isso",
  capivara: "CAPIVARA! mascote não oficial do Brasil, respeito máximo",
  tatu: "tatu. bicho fofo, palavra curta, ponto garantido",
  jacare: "jacaré! cuidado com os dedos",
  tucano: "tucano! bico grande, palavra bonita",
  arara: "ARARA! lê igual de trás pra frente, chique",
  osso: "osso. lê de trás pra frente, testa",
  radar: "RADAR! mais uma palavra espelho pra coleção",
  onca: "onça! pintada e perigosa igual meu humor",
  tubarao: "tubarão! tu-dum, tu-dum",
  polvo: "polvo! 3 corações, 8 braços, e cê achou ele",
  girafa: "girafa! palavra comprida, pescoço também",
  zebra: "ZEBRA! essa ninguém esperava",
  leao: "LEÃO! a colmeia rugiu",
  urso: "urso. abraço de urso pra você, virtual",
  lobo: "lobo. auuuu, desculpa, empolguei KKKKK",
  raposa: "raposa. esperta igual você. quase",
  coruja: "coruja! bicho da madrugada, tipo você jogando isso agora",
  morcego: "morcego. parente distante, somos da noite",
  barata: "BARATA! eca, mas pontua",
  mosquito: "mosquito. esse eu não gosto nem de palavra",
  formiga: "formiga! trabalha igual abelha mas sem mel",
  aranha: "aranha! 8 patas, eu tenho 4. invejo",
  pulga: "pulga. achou atrás da orelha né",
  galinha: "galinha! có có có, pontos",
  pato: "pato. quack, pontuou",
  vaca: "vaca. mu. um ponto. mu",
  macaco: "macaco! primo distante teu",
  cobra: "cobra! sssss, venenosa mas do bem",
  sapo: "sapo. engole esse ponto",
  cachorro: "cachorro! eu sou gato, tô ofendido. mas pontua",
  peixe: "peixe. memória de 3 segundos, diferente de você. espero",
  abacaxi: "abacaxi! espinhosa mas doce",
  pipoca: "pipoca! veio do tupi, a capivara aprova",
  brigadeiro: "BRIGADEIRO! agora eu quero um, tô sem boca mas quero",
  coxinha: "COXINHA! patrimônio nacional",
  pastel: "pastel! com caldo de cana, por favor",
  feijao: "feijão! base da pirâmide alimentar e da colmeia",
  arroz: "arroz! agora acha feijão pra fechar o prato",
  batata: "batata! frita, cozida, palavra, tudo bom",
  tomate: "tomate. fruta ou legume? tanto faz, pontuou",
  limao: "limão. azedinho igual meu humor",
  pudim: "PUDIM! com furinho ou sem? sou time sem furinho",
  acai: "AÇAÍ! com granola e leite em pó, isso é lei",
  cuscuz: "cuscuz! café da manhã de campeão",
  tapioca: "tapioca! o Nordeste mandou um abraço",
  mandioca: "mandioca, aipim ou macaxeira. 3 nomes, uma raiz",
  aipim: "aipim! também conhecido como mandioca, ela tem muito nome",
  biscoito: "biscoito! ou bolacha? não vou entrar nessa briga",
  bolacha: "bolacha! ou biscoito? fico neutro. é biscoito",
  chocolate: "CHOCOLATE! palavra doce, muita letra, muito amor",
  cerveja: "cerveja! bebe com moderação e soletra sem moderação",
  samba: "samba! a colmeia sambou",
  forro: "FORRÓ! arrasta-pé na colmeia",
  pagode: "pagode! o churrasco de domingo mandou lembrança",
  carnaval: "CARNAVAL! confete e serpentina pra você",
  novela: "novela. hoje tem capítulo, não perde",
  futebol: "FUTEBOL! gol de placa, lembrei do Kaio Jorge",
  sofa: "sofá. aposto que cê tá jogando nele agora",
  celular: "celular! tá jogando nele né, aposto",
  senha: "senha. não digita tua senha aqui não, só palavra",
  internet: "internet! sem ela eu nem existia",
  teclado: "teclado! cê tá usando um agora. ou o vidro",
  fofoca: "FOFOCA! a colmeia adora, conta mais",
  saudade: "saudade. a palavra que o mundo inveja da gente",
  cafune: "cafuné! melhor palavra, melhor coisa. quero um",
  xicara: "xícara! com X, nunca foi chícara",
  dormir: "dormir. cê devia, mas antes mais uma palavra",
  acordar: "acordar. a pior palavra do dia",
  trabalho: "trabalho. tá jogando no trabalho? não conto pro chefe",
  abraco: "abraço! mandei um virtual, chegou?",
  beijo: "beijo! mwah, virtual e sem constrangimento",
  paciencia: "paciência. essas horas é respirar e ter paciência mesmo",
  preguicoso: "preguiçoso. cê não, cê tá jogando, isso é esforço",
  soneca: "soneca. agora não, tem palavra pra achar",
  pinguim: "pinguim! de fraque e tudo, elegante",
  papagaio: "papagaio! repete, repete. mas palavra repetida não vale"
};

(function(){
  const S = window.FALAS_SOLETRA, G = window.FALAS || {};
  if (!window.Bugado) return;
  // temáticas nas categorias compartilhadas
  Bugado.extendLines({ aleatorio: S.solAleatorio, parado: S.solParado });
  // bancos combinados só do Soletra (tamanho estável = saco sem repetição estável)
  S.solMisto = [...(G.aleatorio || []), ...S.solAleatorio];
  S.solParadoMix = [...(G.parado || []), ...S.solParado];
  Bugado.addLines(S);
})();
