/* Falas do Bugado no Sudoku. Variáveis: {d} número, {n} quantidade, {tipo} linha/coluna/quadrado, {s} segundos, {tempo} mm:ss */
Bugado.addLines({

sdStart: [
  'grade nova, bora',
  'bora que bora, grade fresquinha',
  'sudoku não tem conta não, é só não repetir número',
  'toca numa casa e depois num número, só isso',
  'vamo ver se hoje sai ou se vai ser igual ontem',
  'grade saindo do forno agora',
  'lá vamos nós dnv',
  'estala os dedo e vai',
  'mais uma? cê tá viciado mano',
  'bora, sem pressa e sem chute',
  'essa grade tá com cara de que vai dar trabalho',
  'grade bonitinha, parece inofensiva né',
  'um número de cada vez, sem inventar moda',
  'linha, coluna e quadrado sem repetir. acabou a regra',
  'partiu, vou ficar aqui só olhando',
  'se travar olha o quadrado mais cheio',
  'papo reto, essa aqui cê fecha',
  'vambora que o relógio já tá rodando',
  'cê joga e eu comento, fechou?',
  'começa pelo número que mais aparece na grade',
  'cada sudoku desse só tem uma solução, nada de jeitinho',
  'mais um sudoku pro currículo',
  'esquenta o cérebro aí que a grade tá gelada',
  'que comece a resenha',
  'bora fazer bonito, ou pelo menos terminar',
  'olha o numerinho no canto do botão, ele fala quantos faltam',
  'tô com fé em você hoje, pouca mas tô',
  'grade nova, zero desculpa',
  'abre o olho e vai',
  'outra rodada? tá maluco, cê não cansa'
],
sdDaily: [
  'Sudoku do Dia #{n}, geral jogando o mesmo tabuleiro hoje',
  'dia #{n}. mesma grade pra todo mundo, agora dá pra ver quem é lento',
  'é o oficial do dia, capricha que vale +40 de XP',
  'sudoku #{n} valendo, termina e joga o tempo no grupo',
  'grade do dia na mesa. se o amigo fizer mais rápido a culpa é tua',
  'desafio do dia, nível Normal, sem choro',
  'mesmo sudoku pra todo mundo, mas a vergonha é individual KKKKK',
  'dia #{n}, bora ver se o cérebro acordou junto com cê',
  'SUDOKU DO DIAAAA vambora',
  'oficial do dia. se der ruim amanhã tem outro',
  'essa grade é igual pra geral, não tem desculpa de grade difícil',
  'o do dia é o que vale pra resenha no grupo, papo reto'
],
sdDiff_bebe: [
  'Bebê. tá quase tudo preenchido, não tem como errar',
  'modo Bebê, a grade praticamente se resolve sozinha',
  'Bebê é pra aquecer. ou pra se sentir gênio, vale também',
  'se errar no Bebê eu vou zoar por uma semana',
  'Bebê. é tipo pintar por número',
  'nível Bebê, rodinha e capacete no lugar',
  'no Bebê pedir dica é crime hein',
  'Bebê. tá muito fácil, bora'
],
sdDiff_normal: [
  'Normal. sudoku de verdade agora, sem rodinha',
  'Normal, aqui o bicho pega um pouquinho',
  'tirou a rodinha né, cuidado com o meio-fio',
  'Normal. menos número dado, mais cabeça',
  'no Normal os dois truques da ajuda resolvem tudo',
  'Normal é onde separa os curioso dos viciado',
  'modo Normal, vai suar um pouquinho',
  'Normal. nem fácil nem difícil, tipo segunda-feira'
],
sdDiff_achando: [
  'Tô Me Achando. o nome já fala tudo né',
  'ganhou duas e já tá no Tô Me Achando, que isso',
  'aqui o lápis vira teu melhor amigo',
  'pouca pista e muita coragem, gostei',
  'Tô Me Achando. esse pede paciência, cê tem?',
  'confiança lá em cima e grade vazia, vamo ver no que dá',
  'esse nível é pra quem sabe o que tá fazendo. cê sabe?',
  'ousado demais mano, respeito'
],
sdDiff_sofrencia: [
  'Sofrência. tá no nome, cê escolheu',
  'Sofrência. traz lápis, água e paciência',
  'aqui nem minha dica explica tudo, às vezes ela só entrega a resposta',
  'cê escolheu sofrer, eu adoro',
  'coragem ou falta de noção? vamo descobrir',
  'aqui os truque básico não bastam, vai ter que pensar mo',
  'Sofrência. coloca uma música triste que combina',
  'poucos números e muita dor, tá maluco'
],
sdBack: [
  'voltou! teu jogo tava salvo, continua de onde parou',
  'olha quem apareceu, a grade tava com saudade',
  'teu jogo tava aqui te esperando igual cachorro na porta',
  'os número tão onde cê deixou, não mexi em nada',
  'lembra onde tava? nem eu KKKKK',
  'a grade não fugiu não, ela não tem perna',
  'voltou pra terminar, gosto assim',
  'dá uma olhada geral antes de sair clicando',
  'o cronômetro também tava te esperando, ele não esquece',
  'bem-vindo de volta ao sofrimento pausado',
  'ô sumido, bora terminar isso aqui',
  'jogo recuperado. agora recupera o raciocínio'
],
sdNoCell: [
  'escolhe uma casa primeiro uai',
  'número em qual casa? toca numa casa antes',
  'cê apertou número pro nada',
  'primeiro a casa, depois o número. tipo meia e tênis',
  'seleciona uma casa aí, tô vendo o dedo ansioso'
],
sdGiven: [
  'esse veio de fábrica, não mexe',
  'número impresso, nem com borracha sai',
  'esse aí já tava certo antes de cê nascer',
  'pode tocar o quanto quiser, esse é fixo igual boleto',
  'número dado é patrimônio tombado mano',
  'quer trocar número que veio pronto? tá maluco',
  'esse é da casa, deixa ele',
  'número dado não sai nem com reza',
  'esse tá aí desde o começo da grade',
  'esse é de pedra',
  'isso é pista, não é sugestão',
  'cutucar número fixo não vai mudar ele não'
],
sdLocked: [
  'esse cê já acertou, deixa quieto',
  'tá certo mano, confia em você',
  'já tá certo, quer estragar pq?',
  'não mexe em time que tá ganhando',
  'esse número tá certinho, eu conferi',
  'esse é teu já, tá pago',
  'certo é certo uai',
  'acertou e agora quer trocar? a insegurança bateu',
  'essa casa já tá resolvida, vai pra outra',
  'se eu tivesse polegar fazia joinha pra esse aí'
],
sdNotesMany: [
  '{n} anotações já, tá escrevendo livro?',
  '{n} rabisco de lápis, a grade virou caderno de faculdade',
  '{n} anotações, o lápis tá pedindo férias',
  'mo rascunho hein, {n} já. tá ajudando pelo menos?',
  '{n} anotações, planejamento de gente séria'
],
sdCorrect: [
  'acertou uai, quem diria',
  'certo, não se acostuma',
  'isso aí',
  'viu? nem doeu',
  'pensou antes de clicar, evolução',
  'o {d} ficou lindo aí',
  'acertou o {d}, o {d} tá orgulhoso',
  'mais um, a grade tá sentindo',
  'certinho, parece até que sabe o que tá fazendo',
  'foi sorte? fala a verdade',
  'eu tava torcendo contra mas beleza',
  'esse {d} foi bonito demais',
  'olha a pessoa jogando sudoku igual profissional',
  'o {d} achou a casa dele, chorei',
  'tá indo, devagar mas tá indo',
  'nenhum {d} repetido, lindo',
  'um de cada vez, assim que é',
  'mandou bem mano',
  'tá esquentando',
  'o {d} tá confortável aí, deixa ele',
  'foi lógica ou chute? nem responde',
  'mais uma casa conquistada',
  'se sudoku desse dinheiro cê tava rico',
  'ISSOOOO',
  'esse {d} tava escondido e cê achou',
  'a grade tá começando a te respeitar',
  'certo. papo reto, tô sem piada',
  'o {d} entrou suave',
  'tá virando máquina',
  'boa, continua assim',
  'pode fazer uma dancinha discreta',
  'vou ter que inventar zoeira nova',
  'tá com o cérebro ligado na tomada hoje',
  'a lógica venceu dessa vez',
  'raciocínio puro. ou não, tá certo igual',
  'boa, a grade tá ficando bonita',
  'o {d} tava pedindo pra ir aí',
  'acertou, tô achando que cê leu a ajuda',
  'certo e sem enrolar, gostei',
  'que isso, tá jogando demais',
  'esse aí eu também ia colocar. depois de uns 3 minutos',
  'número certo na casa certa, simples assim',
  'boa, menos uma',
  'tá fácil pra você hein',
  'esse {d} foi mais certeiro que falta do Matheus Pereira',
  'tá jogando bonito mano',
  'olha esse {d} aí, tá maluco',
  'certo. sem comentários, só respeito',
  'uma casa a menos pra me estressar',
  'boa, bora pra próxima',
  'foi no capricho',
  'o {d} agradece a moradia',
  'certinho, vambora',
  'tá afiado hoje',
  'nem pensou muito, gostei',
  'cada {d} que cê coloca a grade chora um pouco',
  'certo! tá pegando o jeito',
  'bonito isso, namoral',
  'mais um pra conta',
  'eu ia zoar se errasse, não deu'
],
sdFast: [
  'rapidinho hein, pensou ou só foi?',
  'que isso, tá com pressa pra quê',
  'clicando rápido assim cuidado pra não atropelar a lógica',
  'nem deu tempo de eu pensar numa zoeira',
  'rápido demais, tô desconfiado',
  'modo turbo, tem pão de queijo no forno?',
  'rápido e certo, perigoso isso',
  'tá jogando no 2x?',
  'nem piscou mano',
  'tá no embalo, não para agora',
  'speedrun detectado',
  'tá voando, cuidado com o radar',
  'isso foi instinto puro',
  'rápido assim até eu fico com medo',
  'mais rápido que o Move vazio às 5 da manhã',
  'relâmpago. respira também',
  'VRUUUUM',
  'tá com medo do cronômetro?',
  'mais rápido que contra-ataque do Cabuloso',
  'clicou antes de eu terminar de ler, tá maluco'
],
sdSlow: [
  'demorou 700 séculos mas foi',
  '{s} segundos pensando, eu contei',
  'achei que cê tinha ido passar um café',
  'demorou igual obra da prefeitura mas saiu',
  'pensou pensou pensou e acertou, valeu o suspense',
  'esse saiu no fórceps',
  '{s} segundos. mais demorado que o 330 no horário de pico',
  'que parto hein, mas nasceu bonito',
  'deu tempo de eu envelhecer, mas acertou',
  'tava travado e destravou, é isso',
  'demorou tanto que o cronômetro quase dormiu',
  '{s} segundos pra um número, 6 séculos mds',
  'lento mas certeiro, estilo tartaruga ninja',
  'eu já ia mandar mensagem perguntando se cê tava vivo',
  'foi devagar mas foi, é o que importa'
],
sdCombo: [
  '<b>x{n}</b> que isso mano, tá jogando demais',
  '<b>x{n}!</b> cabeça ou sorte? tanto faz, continua',
  '<b>COMBO x{n}</b>, se errar agora eu vou rir mo',
  '<b>x{n}</b> seguidos, tá possuído',
  '<b>{n} seguidos</b>, a grade tá pedindo arrego',
  '<b>x{n}</b>. não olha pra mim, olha pra grade',
  '<b>x{n}</b> sem errar, tô até nervoso',
  '<b>x{n}!</b> chamem os narrador',
  '<b>{n} de uma vez</b>, tá ligado no 220',
  '<b>x{n}</b>, onde tava esse talento o jogo todo?',
  '<b>COMBO x{n}</b> tô sem fala',
  '<b>x{n}</b>, mais combo que jogo de luta',
  '<b>{n} seguidos</b>, hadouken de sudoku',
  '<b>x{n}</b> não para não para não para',
  '<b>x{n}!</b> faz de novo que eu não vi',
  '<b>{n}</b> seguidos, nem calculadora é tão precisa',
  '<b>x{n}</b>, não vou falar nada pra não dar azar. ops',
  '<b>{n} acertos seguidos</b>, o cronômetro tá com inveja',
  '<b>x{n}!</b> acordou inspirado hoje',
  '<b>COMBO x{n}</b> já tô ouvindo a musiquinha de vitória',
  '<b>x{n}</b>, preparei zoeira pra quando cê errasse e não tô conseguindo usar',
  '<b>x{n}</b>, a grade tá levando um sacode',
  '<b>{n} de lavada</b>, modo deus',
  '<b>x{n}</b> KKKKKK que isso',
  '<b>COMBO x{n}</b> MDSSSS',
  '<b>x{n}</b>, mais embalado que torcida no Mineirão',
  '<b>x{n}</b>. papo reto, cê tá jogando muito',
  '<b>{n} sem errar</b>, isso tem nome: flow',
  '<b>x{n}</b>, se fosse Duolingo era ofensiva de 1 ano',
  '<b>x{n}!</b> tá igual o Heat no quarto período',
  '<b>COMBO x{n}</b>, ninguém segura',
  '<b>x{n}</b>, bizarro isso',
  '<b>x{n}</b> e subindo, vambora'
],
sdComboBreak: [
  'ih, quebrou o combo de {n}',
  'combo de {n} foi pro saco, mas foi lindo enquanto durou',
  'adeus combo x{n}',
  'tava tão bem mano, {n} seguidos e aí isso',
  'o combo de {n} morreu, minuto de silêncio',
  'quebrou o x{n}, eu falei que ia rir KKKKKK',
  'era x{n}, agora é x0. matemática triste',
  'jogou fora um x{n} com um número só',
  'o combo caiu, levanta e bora dnv',
  '{n} SEGUIDOS E CÊ FAZ ISSO',
  'x{n} destruído, coisa ridícula',
  'tava no x{n} e pisou na casca de banana',
  'pipocou no x{n}, patético',
  'o combo de {n} tava lindo, que dó',
  'x{n} pro espaço. respira e começa outro'
],
sdWrongRow: [
  'já tem {d} nessa linha, tá ali ó',
  'olha pro lado, esquerda e direita. viu o {d}?',
  'essa linha já tem {d}, ela só aceita um',
  'dois {d} na mesma linha? é a regra número 1 mano',
  'tá repetindo o {d} na linha',
  'olha a linha inteira antes, o {d} tá ali rindo',
  '{d} repetido na linha não pode, tá na primeira frase da ajuda',
  'o {d} dessa linha já tem dono',
  'na horizontal já tem {d}',
  'o {d} que cê quer já mora nessa linha',
  'deu ruim, {d} duplicado na linha',
  'essa linha falou não pro teu {d}',
  'tem um {d} piscando vermelho aí na linha, não tem como não ver',
  'repetiu o {d} na linha, erro clássico',
  'passa o olho na linha, o {d} tá lá',
  'linha com dois {d}? nunca nem vi',
  'o {d} dessa linha tá te olhando torto',
  'mano, olha a linha. já tem {d}'
],
sdWrongCol: [
  'já tem {d} nessa coluna, olha pra cima e pra baixo',
  'a coluna já tem o {d} dela, tá piscando',
  'coluna com {d} repetido, nem pensar',
  'o {d} já tá nessa coluna, vertical lembra?',
  'essa coluna já ocupou a vaga do {d}',
  'olha a coluna tipo prédio, o {d} tá num andar aí',
  'repetiu {d} na coluna, a coluna ficou de braço cruzado',
  'sobe e desce com o olho, o {d} tá lá',
  'coluna não aceita {d} duplicado',
  'opa, esse {d} já tem na coluna',
  'a coluna gritou ocupado quando cê colocou o {d}',
  'tem {d} na vertical, aquela que fica em pé',
  'coluna, {d}, já tem. resumo do erro',
  'não rola {d} duas vezes na coluna',
  'o {d} lá de cima ficou com ciúme',
  'coluna lotada de {d}. quer dizer, com um, e um já lota',
  'olhou a coluna? o {d} tá bem ali uai',
  'dois {d} empilhado na coluna, tá maluco'
],
sdWrongBox: [
  'já tem {d} nesse quadrado, olha dentro do 3×3',
  'o quadrado já tem o {d} dele',
  'um {d} por quadrado, regra de condomínio',
  'tem {d} nesse quadradinho, tá piscando pra você',
  'quadrado com dois {d}? nunca',
  'são só nove casas no quadrado e cê não viu o {d}',
  'quadrado é igual kitnet, não cabe dois {d}',
  'repetiu o {d} no quadrado, esse era o mais fácil de ver',
  'tem {d} no mesmo bloco, ó ali',
  'o quadrado falou: já tenho {d}, valeu',
  'confere o bloco antes, já tem {d}',
  'esquece esse {d} aqui, o quadrado já tem',
  '{d} duplicado no quadrado, o mais óbvio mano',
  'o {d} do quadrado tá lá feliz e sozinho, deixa ele',
  'nesse bloco o {d} já apareceu, figurinha repetida',
  'olha o quadradinho inteiro, o {d} tá lá',
  'mais apertado que o 330 às 18h, não cabe outro {d} nesse quadrado',
  'o quadrado tá rindo do teu {d}'
],
sdWrongHidden: [
  'não bate com nada que dá pra ver, mas não é {d}. confia',
  '{d} aí não mano, confia',
  'o {d} até parece caber, mas não é ele',
  'parece certo né? o {d} é armadilha aqui',
  'não repete nada e tá errado igual, sudoku é cruel',
  'o {d} não briga com ninguém mas também não é a resposta',
  'quase convenceu. o {d} mora em outro lugar',
  'sem conflito mas errado. usa o lápis pra ver as opções',
  'o {d} não é daí, anota as possibilidade antes de chutar',
  'chute detectado, não é {d}',
  'errou bonito, não repete nada mas não é',
  'nada contra o {d}, mas ele não é daí',
  'o {d} passou na linha, na coluna e no quadrado e reprovou na resposta',
  'erro traiçoeiro. vê qual número falta em volta',
  'não é {d}. essa casa tem pouca opção, vê qual sobra',
  'o {d} parecia bom partido, não era',
  'eu também chutaria {d}, e também erraria KKKKK',
  'chute no escuro né, o escuro errou',
  'sem conflito e sem acerto, sudoku é seco assim',
  'tá chutando? o lápis tá ali pra isso',
  'o {d} vai dar problema lá na frente, confia',
  'caiu na pegadinha do {d}'
],
sdLastLife: [
  'último coração, agora é na raça',
  'só sobrou um coraçãozinho, cuida dele',
  'uma vida só, pressão total',
  'último coração, se errar dnv eu chamo o padre',
  'tá no último, respira antes de cada número',
  'uma vida, usa o lápis pelo amor',
  'agora cada número é decisão de final de campeonato',
  'sem chute agora hein, último coração',
  'tá no fio da navalha',
  'último coração, a grade já tá sentindo cheiro de vitória. dela',
  'uma vida. é tipo pênalti no último minuto',
  'mds, um coração só. calma'
],
sdThirdMistake: [
  'terceiro erro. ih',
  'e lá se vai o último coração',
  'três erros, acabou',
  'eita, esse foi o terceiro',
  'três strikes, fora',
  'último coração partido',
  'pronto, era o último',
  'ah não mano'
],
sdUnit: [
  'fechou {tipo}, chora não grade',
  '{tipo} a menos, a grade tá com medo',
  'faxina de sudoku, tá limpando tudo',
  'ISSO, fechou {tipo}',
  'fechou {tipo}, pode fazer a dancinha',
  'mais um fechamento, tá ficando bonito',
  'fechou! sensação de gaveta arrumada',
  'fechou {tipo}, a grade perdeu um pedaço da alma',
  'olha isso, fechou {tipo} de uma vez',
  'tá desmontando a grade peça por peça',
  'fechar {tipo} é o melhor barulho do sudoku',
  'aí sim, essa já era',
  'que satisfação, parece estourar plástico bolha',
  'fechou {tipo}, ganhou XP e um pouquinho de respeito',
  'nada faltando, tá fechado',
  'mais uma pro museu das coisas resolvidas',
  'a grade tá cada vez com menos problema',
  'fechou {tipo}, sente o poder subindo',
  'isso merece um brinde, com água',
  'clicou e brilhou tudo, que coisa linda',
  'riscou {tipo} da lista',
  'tô vendo a vitória no horizonte, longe mas tô',
  'fechou {tipo}, jogando igual gente grande',
  'FECHOUUUU',
  'fechou {tipo}, isso é bom demais namoral'
],
sdUnitMulti: [
  'COMBO DUPLO! fechou duas de uma vez',
  'duas de uma vez, strike no boliche',
  'um número, dois coelho',
  'a grade tomou dois soco de uma vez',
  'dois fechamento com um número só, eficiência',
  'dupla fechada, tô orgulhoso',
  'fechou duas coisa junto, multitarefa',
  'combo duplo, isso vale um grito',
  'um número e dois fechamento, isso é arte',
  'dobradinha! se fosse jogo do Cruzeiro era gol de bicicleta'
],
sdNumDone: [
  'todos os {d} no lugar',
  'zerou o {d}, menos um problema na vida',
  'acabaram os {d}, o botão pode descansar',
  'os nove {d} em casa, família reunida',
  'completou os {d}, agora esquece que o {d} existe',
  '{d} finalizado, próximo',
  'não sobrou nenhum {d}, risca da lista',
  'o {d} terminou, foi tomar um café',
  'todos os {d}! menos opção, menos confusão',
  '{d} aposentado',
  'acabou o estoque de {d}, olha o botão apagado',
  'nove de nove {d}, nota nove',
  'mais um número fechado, tá afunilando',
  'o {d} tá em todas as linhas agora, missão cumprida',
  'tchau {d}, foi bom te conhecer'
],
sdQuarter: [
  'um quarto da grade feito, bom começo',
  '25% feito, falta só o resto KKKK',
  'já foi um pedaço, continua nesse ritmo',
  '25%, tá indo',
  'um quarto do caminho, bebe uma água',
  'já tem uma boa parte preenchida, tá esquentando',
  '25%. se fosse bateria de celular eu já tava desesperado',
  'um quarto já, o começo é a parte mais chata'
],
sdHalf: [
  'metade, agora é ladeira abaixo',
  'metade da grade resolvida, tá virando gente',
  '50%, meio caminho andado',
  'metade feita, daqui pra frente fica mais fácil pq tem menos opção',
  'meio tabuleiro, a grade começou a suar',
  'metade feita e a outra metade tá com medo',
  '50%, se fosse pizza cê já comeu metade',
  'tá na metade, segue que tá bonito'
],
sdThreeQ: [
  'três quartos, tá quase',
  '75%, agora não pode vacilar',
  'já dá pra ver o fim, não tropeça nele',
  'os número tão acabando e as opção também',
  'reta final chegando, foco',
  '75%, agora os número quase se colocam sozinhos',
  'falta pouco, olha os botões apagados que eles te guiam',
  'três quartos, o cronômetro tá torcendo por você'
],
sdAlmost: [
  'só mais {n}, não estraga agora',
  '{n} pra acabar, tô nervoso',
  'falta pouco, {n} e acabou. respira',
  'reta final, {n} pra fechar',
  'só {n}, se errar agora eu conto pra todo mundo',
  '{n} pra glória',
  'tá quase, {n} e é tua',
  'contagem regressiva: {n}',
  '{n}! vai que é tua',
  'faltando {n}, não para',
  'MDS faltando {n}',
  '{n} pra terminar, não inventa moda agora'
],
sdErase: [
  'apagou as anotação, recomeçando',
  'borracha nela',
  'limpou, às vezes é bom começar do zero',
  'arrependimento é válido',
  'casa limpinha dnv',
  'adeus rascunho',
  'apagou, estratégia nova? gostei',
  'rascunho errado não merece viver'
],
sdEraseEmpty: [
  'apagar o quê? a casa tá vazia',
  'cê tá apagando o nada',
  'não tem nada aí pra apagar',
  'borracha no vazio, filosófico',
  'casa vazia precisa de número, não de borracha'
],
sdUndoNone: [
  'não tem nada pra desfazer, cê ainda não fez besteira',
  'desfazer o quê? tá igual começou',
  'histórico vazio, folha em branco',
  'não dá pra voltar mais, aqui é o começo dos tempos',
  'nem eu desfaço o que não foi feito',
  'apertou desfazer no vazio, ok'
],
sdUndo: [
  'desfeito, viajou no tempo',
  'ctrl+z na vida real seria bom né',
  'voltou atrás, sabedoria ou medo?',
  'pronto, como se nada tivesse acontecido',
  'já é o {n}º desfazer, tá indeciso hoje',
  'voltou, o passado agradece a visita',
  'a máquina do tempo tá esquentando',
  'o botão favorito dos arrependido',
  '{n} vezes desfazendo, cê é o Doutor Estranho do sudoku',
  'rebobinou igual fita',
  'desfez, mas o que tava certo continua certo',
  '{n} desfazer, decide mano'
],
sdNotesOn: [
  'lápis ligado, anota os palpite que é de graça',
  'lápis ON, rascunho não conta como erro',
  'lápis na mão, agora pensa com calma',
  'modo anotação, aqui pode chutar sem medo',
  'lápis ligado, os número saem pequenininho',
  'rascunho liberado, coisa de gente séria',
  'anota as possibilidade de cada casa',
  'lápis ON. igual prova de escola, rascunho na margem',
  'quem joga bem usa muito isso, só falando',
  'aqui errar é de graça, aproveita',
  'lápis ligado. toca no número de novo pra apagar a anotação',
  'modo planejamento, tô gostando dessa maturidade'
],
sdNotesOff: [
  'lápis desligado, agora é caneta',
  'lápis OFF, agora vale de verdade',
  'chega de rascunho, hora de decidir',
  'voltou pra caneta, coragem',
  'lápis guardado, agora erro custa coração',
  'modo caneta, certeza absoluta hein',
  'desligou o lápis, já sabe a resposta?',
  'agora é pra valer'
],
sdHint1: [
  'tá, toma.',
  'primeira dica, de boa.',
  'lá vai uma ajudinha.',
  'dica liberada, aprende o truque hein.',
  'uma dica não mata ninguém, só o orgulho.',
  'beleza, vou te ajudar essa vez.',
  'chamou? cheguei.',
  'lê a explicação que é isso que importa.',
  'tô de bom humor, toma.',
  'te ajudo mas cê me deve um pão de queijo.'
],
sdHint2: [
  'de novo? ok.',
  'segunda dica, tô contando.',
  'mais uma, mas presta atenção no truque.',
  'dica dois, vou começar a cobrar.',
  'segunda vez, tá virando hábito?',
  'olha bem como eu achei.',
  'eu dnv, sou praticamente teu copiloto.',
  'dica número dois. cê consegue sozinho também hein.',
  'eu aqui dnv, com carinho e julgamento.',
  'segunda dica, guardei pra zoar depois.'
],
sdHintMany: [
  'dica {n}, tô contando.',
  'já é a {n}ª dica, eu jogo ou cê joga?',
  'dica {n}, daqui a pouco eu peço o controle.',
  '{n} dicas, cê tá assistindo eu jogar.',
  'mais uma? {n}! vou abrir curso de sudoku.',
  '{n}ª dica, tá dependente mano.',
  'dica {n}, quero crédito no final.',
  'dica {n}, vou cobrar mensalidade.',
  'lá vai a {n}ª, mas lê a explicação hein.',
  '{n} dicas. papo reto, quem tá jogando sou eu.',
  'essa é a {n}ª. se chegar em 81 eu fiz o sudoku inteiro.',
  'dica {n}, tá maluco.',
  '{n} dicas, mds.',
  'dica {n}. nem o Duolingo é tão insistente.',
  'dica {n}, depois fala que ganhou sozinho KKKKK.'
],
sdHintFallback: [
  'nem eu achei atalho aqui, toma a resposta e finge que foi você',
  'essa casa não tem truque fácil, tô te entregando de mão beijada',
  'aqui só lógica avançada resolvia, toma logo',
  'nem candidato único nem único lugar, só a resposta mesmo',
  'grade das difíceis, eu trapaceei. fica entre nós',
  'não achei explicação bonita, mas a resposta tá aí',
  'esse precisava de técnica avançada, dei um jeitinho',
  'pulei a aula e fui direto na resposta'
],
sdWin: [
  'ZEROU em {tempo}, printa e manda no grupo',
  'ganhou em {tempo}, vou ter que mudar minha opinião sobre você',
  'terminou! {tempo}. tô orgulhoso',
  'grade resolvida, a grade tá chorando no canto',
  'vitória em {tempo}, pode fazer a dancinha',
  'ACABOUUU e cê ganhou',
  'resolveu tudo, que maneiro mano',
  '{tempo} e grade fechada, o cronômetro aplaude',
  'ganhou, tá virando lenda do meu sudoku',
  'campeão em {tempo}, na lógica e em uns chute'
],
sdWinClean: [
  'ZERO ERRO mano, quem é você',
  'nenhum coração perdido, tô chocado',
  'perfeito, sem erro, tô sem piada',
  'zero erro em {tempo}, tá maluco',
  'nenhum erro, vai pro hall da fama',
  'sem errar nada, jogou de olho aberto hoje',
  'partida limpa igual lençol lavado',
  'MDSSSS QUE ISSO, zero erro',
  'zero vergonha, olha a conquista',
  'nem um errinho, me deixou sem emprego'
],
sdWinNoHint: [
  'ganhou sem pedir dica, orgulho próprio',
  'sem dica, cê nem precisou de mim. doeu',
  'tudo sozinho, tô feliz e meio ofendido',
  'zero dica, independente',
  'sem ajuda, {tempo} de puro cérebro',
  'ganhou sem mim, vou ficar ali no canto',
  'nenhuma dica, viu que cê consegue',
  'independência ou morte, e foi independência'
],
sdWinFast: [
  'rapidão! {tempo}, tava com pressa pra quê',
  'speedrun, {tempo}',
  '{tempo}! tá jogando com turbo',
  'voou, {tempo}. nem deu tempo de zoar',
  '{tempo}, isso é recorde? olha as estatísticas',
  'rápido demais, eu mal comecei a comentar',
  'terminou em {tempo}, cê é iniciante mesmo?',
  'relâmpago, a grade nem viu de onde veio'
],
sdWinSlow: [
  'demorou {tempo} mas ganhou',
  '{tempo}, maratona. mas maratona tem medalha',
  '{tempo} de batalha, a vitória é tua',
  'ganhou! demorou um pouquinho, mas quem tá contando? o cronômetro',
  'vitória paciente em {tempo}',
  '{tempo}. demorou 700 séculos mas foi',
  'foi devagar e chegou',
  'ufa, {tempo}. até eu cansei e eu só assisti'
],
sdOver: [
  '3 erros. perdeu pra uma grade de número, patético KKKKK',
  'game over, a grade tá comemorando. bora estragar a festa dela?',
  'acabou os coração, mas dá pra continuar',
  'perdeu. eu ia fingir surpresa mas não deu',
  'morreu, mas sudoku tem continue. a vida não',
  'três strikes, mas a partida não precisa acabar aqui',
  'a grade te derrotou, que vergonha. pra grade, pq cê vai voltar',
  'fim de jogo, tô de luto por uns 3 segundos',
  'X nos olhos, morri de vergonha alheia',
  'perdeu os 3 coração, os número certo continuam lá'
],
sdCont: [
  'continuou, respeito. sem vergonha nenhuma',
  'renasceu das cinzas, fênix meio chamuscada',
  'continue igual fliperama antigo, sem ficha e sem culpa',
  'voltou do além, coração cheio dnv',
  'mais uma chance, aproveita que tô bonzinho',
  'continuou, a taxa da vergonha tá guardada, mas bora',
  'ressuscitou, o importante é terminar',
  'três coração novinho, não gasta tudo de uma vez',
  'segunda chance, a grade não sabe o que vem aí',
  'continuar é pra quem não desiste. ou pra teimoso'
],
sdPaused: [
  'cê sumiu, pausei o tempo',
  'pausei o cronômetro, vai que cê foi no banheiro',
  'tempo pausado, fui tirar um cochilo também',
  'parado? pausei tudo, toca na grade pra voltar',
  'zzz pausei o relógio pra cê não perder recorde',
  'congelei o tempo, sou praticamente um mago',
  'pausa automática, não precisa agradecer',
  'ô, cê tá vivo? pausei aqui'
],
sdUnpause: [
  'voltou, tempo correndo dnv',
  'despausado, bora',
  'acordei, onde a gente tava?',
  'de volta à ação',
  'tempo destravado, e você também espero',
  'dá uma olhada geral antes de clicar'
],

cutucarSudoku: [
  'me cutucar não revela número nenhum',
  'eu não sou casa vazia, a casa vazia tá ali',
  'quer dica? tem botão pra isso, eu sou só o comentarista',
  'cutucou! qual número falta no quadrado do meio?',
  'existem 6.670.903.752.021.072.936.960 grades de sudoku válidas e cê aqui me cutucando',
  'dica grátis: o número que mais aparece na grade costuma ser o mais fácil de terminar',
  'dica grátis: pega um quadrado e pergunta qual número falta e onde ele PODE ir',
  'nasci de um erro de código, igual teus chutes',
  'me cutuca dnv e eu troco todos os números. não consigo, mas imagina',
  'ei, tô resolvendo de cabeça também, me desconcentrou',
  'não tem número escondido aqui, pode parar',
  'isso não é casa do sudoku, é minha cara',
  'sudoku quer dizer mais ou menos número único em japonês',
  'o sudoku moderno foi inventado por um americano em 1979 e ficou famoso no Japão',
  'cutuca menos e fecha mais linha',
  'já te vi fazendo combo, faz de novo aí',
  'cutucar mascote dá 0 de XP, número certo dá XP. faz a conta',
  'procurando o número 10? não existe',
  'olha a linha com mais número, pronto. agora para de me apertar',
  'mano para',
  'se me cutucar 81 vezes eu resolvo a grade. resolvo nada',
  'sabe o que é melhor que me cutucar? fechar quadrado',
  'cê me cutuca e eu glitcho, a grade tá vendo tudo',
  'já tentou o lápis? é melhor que me cutucar',
  'tô aqui, sempre aqui, julgando cada número',
  'para que eu perco a conta dos teus erros',
  'eu tava quase vendo onde vai o 7 e cê me cutucou',
  'truque bônus: se um número só pode ir numa linha dentro de um quadrado, ele bloqueia essa linha nos outros quadrados',
  'começa pelos quadrados mais cheios, menos opção menos erro',
  'quem joga muito anota TUDO no lápis',
  'me usa de bolinha antiestresse e volta pra grade',
  'cutucar não quebra combo, mas também não aumenta',
  'travou? a dica tá ali do lado, sem vergonha',
  'eu tava contando os 5 da grade e perdi a conta, culpa tua',
  'toca na casa e depois no número. não em mim',
  'mais uma cutucada e eu começo a narrar tuas jogadas igual narrador de rádio',
  'KAKAKAKA para mano, cócegas',
  'achei que era sudoku uai, tá parecendo que eu assinei o canal combate',
  'me cutuca mais não que eu conto pro teu Duolingo que cê sumiu',
  'tô de olho no teu cronômetro, ele tá rodando'
]

});
