/* Falas do Bugado no Sudoku. Variáveis: {d} número, {n} quantidade, {tipo} linha/coluna/quadrado, {s} segundos, {tempo} mm:ss */
Bugado.addLines({

sdStart: [
  'Grade nova, vergonha nova. Bora.',
  'Relaxa: sudoku não tem conta. É só não repetir número. Simples. Pra alguns.',
  'Toca numa casa, depois num número. Até eu faria. E eu sou um desenho.',
  'Prometo não rir. Muito.',
  'Nove números. Zero desculpas.',
  'Tabuleiro fresquinho, saído do forno do gerador.',
  'Essa grade foi feita especialmente pra você. Por um algoritmo sem sentimentos. Mas com carinho.',
  'Bora! Eu trouxe pipoca. Imaginária.',
  'Começou. Respira, alonga os dedos e tenta não passar vergonha.',
  'Outra partida! Você tá virando cliente fiel.',
  'Nova grade. Essa aqui tem cara de quem vai te dar trabalho.',
  'Olha que bonitinha essa grade. Parece inofensiva. Não é.',
  'Vamos lá. Um número de cada vez. Igual a vida.',
  'Grade gerada com sucesso. Agora é com você. Boa sorte, vai precisar.',
  'Sudoku novo, esperança nova. Vamos ver quanto dura.',
  'Lembra: linha, coluna e quadrado. Sem repetir. É só isso. Eu acredito em você. Mais ou menos.',
  'Esse tabuleiro me contou que tá com medo de você. Mentira, ele riu.',
  'Aperta o cinto que lá vem número.',
  'Já sabe o esquema: você joga, eu comento, ninguém sai ileso.',
  'Pra começar bem: procura o número que mais aparece na grade.',
  'Sabia que cada sudoku desses tem uma solução só? Pois é. Nada de “jeito alternativo”.',
  'Partida nova. O cronômetro tá olhando. Eu também.',
  'Esquenta o cérebro que a grade tá gelada.',
  'Mais uma grade pra sua coleção de conquistas. Ou de traumas.',
  'Bora fazer bonito. Ou fazer. Já tá bom.',
  'Eu apostei com o Jorge que você termina essa. O Jorge é o pixel. Não me decepciona.',
  'Hora do show. O show é você errando. Brincadeira. Às vezes.',
  'Grade limpinha. Tá esperando seus dedinhos.',
  'Vamos nessa. Se travar, olha pro quadrado mais cheio.',
  'Começou! Não esquece: o numerinho no canto do botão diz quantos faltam.'
],
sdDaily: [
  'Sudoku do Dia #{n}! Todo mundo tá jogando esse mesmo tabuleiro hoje. Não passa vergonha em público.',
  'Desafio do dia! Mesmo tabuleiro pra todo mundo. Agora dá pra comparar quem é mais lento.',
  'Sudoku #{n}. Oficial. Registrado. Eu tô com a prancheta na mão.',
  'O tabuleiro de hoje foi escolhido pelo destino. E por uma semente de número aleatório. Mesma coisa.',
  'Diário valendo! Termina e compartilha o tempo pra humilhar os amigos.',
  'Esse aqui é o do dia. Se errar, amanhã tem outro. Mas hoje você vai lembrar.',
  'Sudoku do Dia: nível Normal, zero desculpa, plateia imaginária lotada.',
  'Chegou o tabuleiro do dia. Ele é igual pra todo mundo, mas o fracasso é pessoal.',
  'Dia #{n}. Bora ver se hoje o cérebro acordou junto com você.',
  'Desafio oficial! Se ganhar, vale XP extra e meu respeito temporário.',
  'Mesmo sudoku pra todo mundo. Se alguém do grupo fizer mais rápido, a culpa é sua.',
  'Hoje é dia de sudoku oficial. Capricha que eu tô gravando. Não tô. Mas imagina.'
],
sdDiff_bebe: [
  'Modo Bebê. Até eu jogaria de olho fechado. Não tenho pálpebra, mas jogaria.',
  'Bebê: a grade praticamente se resolve sozinha. Não estraga.',
  'Nível Bebê. Sem julgamento. Com um pouquinho de julgamento.',
  'Bebê é ótimo pra aquecer. Ou pra se sentir gênio. As duas coisas valem.',
  'Modo fácil ativado. Se errar aqui, eu vou falar sobre isso por semanas.',
  'Bebê. Tá quase tudo preenchido. É tipo pintar por número.',
  'Nível Bebê: a rodinha tá colocada, o capacete também, e eu tô segurando o banco.',
  'Grade Bebê. Se precisar de dica aqui, eu tiro uma foto e guardo.'
],
sdDiff_normal: [
  'Normal. O sudoku de verdade. Sem rodinha.',
  'Nível Normal. Agora o bicho pega. Pega de leve, mas pega.',
  'Normal: nem fácil, nem difícil. Igual segunda-feira.',
  'Tirou a rodinha, hein? Cuidado com o meio-fio.',
  'Modo Normal ativado. Seu cérebro vai suar um pouquinho.',
  'Normal é onde a gente separa os curiosos dos viciados.',
  'Normal. Tem menos número dado. Mais espaço pra criatividade. Criatividade = errar.',
  'Normal! Os dois truques resolvem tudo aqui. Candidato único e único lugar. Decora.'
],
sdDiff_achando: [
  'Tô Me Achando. O nome já diz tudo, né.',
  'Nível Tô Me Achando. Ganhou duas e já quer ser campeão mundial.',
  'Confiança alta, grade vazia. Vamos ver no que dá.',
  'Tô Me Achando: aqui o lápis vira seu melhor amigo.',
  'Esse nível pede paciência. Você tem? Eu não tenho. Mas eu só assisto.',
  'Ousado. Gosto. Vou ficar de olho.',
  'Tô Me Achando! Tem pouca pista. Muita coragem. Um pouco de loucura.',
  'Nível pra quem já sabe o que tá fazendo. Você sabe? Veremos.'
],
sdDiff_sofrencia: [
  'Sofrência. Eu avisei. Tá no nome.',
  'Nível Sofrência. Traz lenço. E lápis. E um psicólogo.',
  'Sofrência ativada. Aqui nem eu consigo te ajudar direito. Minha dica às vezes só entrega a resposta.',
  'Você escolheu sofrer. Eu respeito. Eu adoro, na verdade.',
  'Sofrência: poucos números, muita dor, zero garantia.',
  'Coragem ou falta de noção? Descobriremos juntos.',
  'Aqui os truques básicos não bastam. Você vai ter que pensar de verdade. Assustador, eu sei.',
  'Sofrência! Coloca uma música triste pra combinar.'
],
sdBack: [
  'Voltou! Salvei teu jogo. De nada. Continua de onde parou.',
  'Olha quem apareceu. A grade tava com saudade. Eu não. Talvez.',
  'Seu jogo tava aqui esperando. Igual cachorro na porta.',
  'Bem-vindo de volta. Os números continuam onde você deixou. Não mexi em nada. Juro.',
  'Retomando a partida. Lembra onde tava? Nem eu.',
  'Continua aí. A grade não fugiu. Ela não tem perna.',
  'Voltou pro sudoku inacabado. Isso é coragem ou teimosia?',
  'Opa! Jogo salvo recuperado com sucesso. Agora é recuperar o raciocínio.',
  'Ah, você voltou pra terminar. Gosto de gente que termina as coisas. Diferente de mim.',
  'O jogo tá onde você deixou. O cronômetro também. Ele não esquece.',
  'Continuando! Dá uma olhada geral antes de sair clicando.',
  'Seja bem-vindo de volta ao seu sofrimento pausado.'
],
sdNoCell: [
  'Escolhe uma casa primeiro. Eu não leio mentes. Ainda.',
  'Número em qual casa? Toca numa casa antes, campeão.',
  'Você apertou um número pro nada. O nada agradece.',
  'Primeiro a casa, depois o número. É tipo sapato e meia. Meia primeiro.',
  'Seleciona uma casa! Tô vendo seu dedo ansioso.'
],
sdGiven: [
  'Esse veio de fábrica. Não mexe.',
  'Número impresso. Nem com lápis você apaga isso.',
  'Esse aí já tava certo antes de você nascer.',
  'Pode tocar quanto quiser, ele não sai. É fixo. Igual boleto.',
  'Esse número é patrimônio tombado. Não pode mexer.',
  'Quer trocar um número que já veio pronto? Ousado. Proibido. Mas ousado.',
  'Esse é da casa. Literalmente. Da casa.',
  'Número dado é número sagrado. Respeita.',
  'Tá tentando mudar o que o universo decidiu? Não rola.',
  'Esse número tá aí desde o Big Bang da grade. Deixa ele.',
  'Não adianta, esse é de pedra.',
  'Isso é uma pista, não uma sugestão.'
],
sdLocked: [
  'Tá certo, não precisa apagar. Confia em você pelo menos uma vez.',
  'Esse você acertou. Deixa quieto, campeão.',
  'Já tá certo! Quer estragar por quê?',
  'Mexer no que tá certo é o primeiro passo pro caos.',
  'Esse número tá certinho. Eu conferi. Duas vezes.',
  'Não mexe em time que tá ganhando.',
  'Esse aí já é seu. Tá pago. Tá registrado.',
  'Certo é certo. Não tem “mais certo”.',
  'Você acertou e agora quer trocar? A insegurança bateu forte.',
  'Tá certo! Se eu tivesse polegar, faria joinha.'
],
sdNotesMany: [
  'Já são {n} anotações. Tá escrevendo um livro?',
  '{n} rabiscos de lápis. Você é do tipo que planeja. Respeito.',
  'Anotou {n} vezes. A grade tá parecendo caderno de faculdade.',
  '{n} anotações! O lápis tá pedindo férias.',
  'Muito rascunho, hein? {n} já. Tá funcionando pelo menos?'
],
sdCorrect: [
  'Olha só! Acertou e tudo.',
  'Certo. Não se acostuma.',
  'Isso aí, gênio incompreendido.',
  'Tá vendo? Nem doeu.',
  'Pensou antes de clicar? Evolução.',
  'Correto. Vou fingir que não tô surpreso.',
  'Boa. Anotei no teu currículo.',
  'O {d} ficou lindo aí.',
  'Acertou o {d}. O {d} tá orgulhoso.',
  'Mais um! A grade tá sentindo a pressão.',
  'Isso! Ó o raciocínio funcionando.',
  'Certinho. Parece até que sabe o que tá fazendo.',
  'Boa jogada. Foi sorte? Fala a verdade.',
  'Acertou. Eu tava torcendo contra, mas tudo bem.',
  'Esse {d} foi bonito. Elegante até.',
  'Olha a pessoa jogando sudoku igual profissional.',
  'Certo! Mais um passo rumo à glória. Glória pequena. Mas glória.',
  'É isso. O {d} achou sua casa. Chorei.',
  'Bela casa, belo número, bela pessoa. Tô bonzinho hoje.',
  'Acertou. Tô começando a ficar preocupado com meu emprego de zoar você.',
  'Correto! A grade fez “ai”.',
  'Tá indo. Devagar e sempre. Mais devagar que sempre, mas indo.',
  'Isso aí! Nenhum {d} repetido. Lindo.',
  'Casa preenchida com sucesso. Fecha a conta, garçom.',
  'Um de cada vez. Assim que se faz.',
  'Opa! Mais um. Sua mãe ficaria orgulhosa.',
  'Mandou bem. Não conta pra ninguém que eu elogiei.',
  'Tá esquentando! A grade tá suando.',
  'Correto. Eu tinha certeza. Não tinha. Mas agora tenho.',
  'Boa! O {d} tá confortável aí. Não mexe mais.',
  'Tá jogando bonito. Tô até sem piada. Mentira. Tenho várias.',
  'Acertou! Foi lógica ou chute certeiro? Não responde, eu prefiro imaginar.',
  'Mais uma casa conquistada. Coloca uma bandeirinha.',
  'Olha a eficiência. Parece planilha do Excel. Minha mãe.',
  'Correto! Se sudoku desse dinheiro, você tava rico.',
  'Isso, isso, isso! Ok, me empolguei.',
  'Esse {d} tava escondido e você achou. Detetive.',
  'Acertou. A grade tá começando a te respeitar.',
  'Beleza. Continua assim que eu fico quieto. Mentira, não fico.',
  'Casa certa, número certo, pessoa… quase certa. Brincadeira.',
  'Certo! Eu sabia. Eu sempre sei. Depois.',
  'O {d} entrou suave. Tipo pé na meia.',
  'Tá virando máquina, hein? Máquina de acertar.',
  'Boa! Mais uma dessas e eu te chamo de mestre. Não chamo.',
  'Isso! Ó a confiança.',
  'Acertou mais uma. Tô anotando tudo. Pro relatório final.',
  'Correto. Pode fazer uma dancinha discreta.',
  'Muito bem. Vou ter que inventar críticas novas.',
  'Tá jogando melhor que ontem. Eu lembro de ontem? Não. Mas parece.',
  'Mais um pro placar! Placar imaginário. Mas conta.',
  'Certinho. Tá com o cérebro ligado na tomada hoje.',
  'A lógica venceu. Pelo menos dessa vez.',
  'Perfeito. A casa agradece. A casa é educada.',
  'Esse aí foi raciocínio puro. Ou não. Tanto faz, tá certo.',
  'Olha, tô impressionado. 3 de 10 impressionado. Mas tô.',
  'Acertou! Até o Jorge aplaudiu. O pixel.',
  'Boa! A grade tá ficando bonita.',
  'Mais uma casa resolvida. Faltam menos. Matemática básica.',
  'O {d} tava pedindo pra ir aí. Você ouviu. Bonito.',
  'Correto! Tô começando a achar que você leu a ajuda.'
],
sdFast: [
  'Opa, rapidinho! Pensou ou só foi?',
  'Velocidade da luz! Quem é você, o Flash?',
  'Tá clicando rápido, hein. Cuidado pra não atropelar a lógica.',
  'Rapidez de quem já sabia. Ou de quem tem sorte. Respeito os dois.',
  'Uou! Nem deu tempo de eu preparar uma piada.',
  'Isso foi rápido demais. Tô desconfiado.',
  'Modo turbo ativado. Tá com pressa pra quê? Tem pastel no forno?',
  'Rápido e certo. Combinação perigosa.',
  'Tá jogando em 2x de velocidade?',
  'Nem piscou! Eu nem tenho pálpebra e pisquei mais.',
  'Tá no embalo! Não para agora.',
  'Speedrun detectado. Chamem a comunidade.',
  'Tá voando. Cuidado com o radar.',
  'Isso foi instinto. Instinto de sudoku. Existe? Agora existe.',
  'Rápido assim até eu fico com medo.',
  'Clique certeiro. Parece jogador de competição.',
  'Tá rápido que nem entregador de aplicativo com fome.',
  'Relâmpago! Mas não esquece de respirar.',
  'Quem te viu, quem te vê. Rápido e rasteiro.',
  'Olha a pressa. Tá com medo do cronômetro?'
],
sdSlow: [
  'Demorou {s} segundos, mas saiu. Valeu a espera.',
  '{s} segundos pensando. Eu contei. Foi lindo.',
  'Paciência de monge. Acertou depois de um tempão.',
  'Enfim! Achei que você tinha ido fazer café.',
  'Demorou mas foi. Igual obra da prefeitura.',
  'Pensou, pensou, pensou… e acertou! O suspense valeu.',
  'Levou um tempinho, hein. Mas o que importa é o resultado. Não importa. Mas foi.',
  'Esse aí saiu com fórceps.',
  'Finalmente! O {s} segundos mais longos da minha vida.',
  'Nossa, que parto. Mas nasceu bonito.',
  'Deu tempo de eu envelhecer um frame. Mas acertou.',
  'Uma jogada lenta mas certeira. Estilo tartaruga ninja.',
  'Tava travado e destravou. Isso é superação.',
  'Pensamento profundo resolvido. A filosofia agradece.',
  'Demorou tanto que o cronômetro quase dormiu.'
],
sdCombo: [
  '<b>COMBO x{n}</b>. Quem é você e o que fez com o jogador?',
  '<b>x{n}!</b> Mente ou sorte? Tanto faz, continua.',
  '<b>x{n} seguidos.</b> Tô levemente impressionado. Levemente.',
  '<b>x{n}!</b> Isso é modo anime ativado?',
  '<b>COMBO x{n}!</b> Se errar agora eu vou rir muito.',
  '<b>x{n}!</b> Tá possuído pelo espírito do sudoku.',
  '<b>{n} seguidos!</b> A grade tá pedindo arrego.',
  '<b>x{n}.</b> Não olha pra mim, olha pra grade. Mantém o foco.',
  'COMBO <b>x{n}</b>! Tá jogando com fone de ouvido e música épica, né?',
  '<b>x{n}!</b> Sequência limpa. Tô até nervoso.',
  '<b>{n} sem errar!</b> Isso tem nome: flow.',
  '<b>x{n}!</b> O Jorge desmaiou de emoção. O pixel.',
  '<b>COMBO x{n}</b>! Chamem os narradores!',
  '<b>x{n}.</b> Se continuar assim eu vou ter que te dar um apelido. “Máquina”. Pronto, dei.',
  '<b>{n} de uma vez!</b> Tá ligado no 220V.',
  '<b>x{n}!</b> Onde tava esse talento o jogo todo?',
  '<b>COMBO x{n}</b>. Tô sem fala. Mentira, olha eu falando.',
  '<b>x{n}!</b> Isso é mais combo que jogo de luta.',
  '<b>{n} seguidos!</b> Hadouken de sudoku.',
  '<b>x{n}.</b> Tá imparável. Não para, não para, não para.',
  '<b>x{n}!</b> Eu não acredito. Faz de novo.',
  '<b>{n}!</b> Nem a calculadora é tão precisa.',
  '<b>COMBO x{n}</b>! Essa sequência vai pros livros de história. Do fliperama.',
  '<b>x{n}!</b> Fica tranquilo, não vou falar nada pra não dar azar. Ops. Falei.',
  '<b>{n} acertos seguidos</b>. O cronômetro tá com inveja.',
  '<b>x{n}!</b> Você acordou inspirado hoje.',
  '<b>COMBO x{n}</b>! Tô ouvindo a música de vitória já.',
  '<b>x{n}!</b> Isso é que é ritmo. Parece bateria de escola de samba.',
  '<b>{n} seguidos!</b> Se for chute, é o chute mais sortudo do mundo.',
  '<b>x{n}</b>. Olha, eu preparei uma piada pra quando você errasse. Tá difícil usar.',
  '<b>COMBO x{n}</b>! Isso não existe. Mas tá existindo.',
  '<b>x{n}!</b> A grade tá levando uma surra. Chamem o juiz.',
  '<b>{n} de lavada!</b> Tá jogando no modo deus?'
],
sdComboBreak: [
  'Ih, quebrou o combo de {n}. Tava tão bonito…',
  'Combo de {n} foi pro saco. Pelo menos foi lindo enquanto durou.',
  'Adeus, combo x{n}. Você será lembrado.',
  'Tava indo tão bem! {n} seguidos e aí… isso.',
  'O combo de {n} morreu. Minuto de silêncio.',
  'Quebrou a sequência de {n}. Eu falei que ia rir. Tô rindo.',
  'Era x{n}. Agora é x0. Matemática triste.',
  'Nem o combo de {n} te segurou. Respira e recomeça.',
  'x{n} jogado fora com um número só. Que desperdício.',
  'O combo caiu. Levanta ele e bora de novo.',
  'Ahhh! {n} seguidos! Por quê? Por quêêê?',
  'Combo x{n} destruído. Foi o Jorge que empurrou? Não foi. Foi você.',
  'A sequência acabou, mas a dignidade… também. Brincadeira. Segue o jogo.',
  'x{n}… Eu gostava tanto dele.',
  'Tava no x{n} e pisou na casca de banana.'
],
sdWrongRow: [
  'Já tem um {d} nessa linha. Tá ali, ó. Piscando.',
  'Um {d} nessa linha já existe. Dois? Isso não existe.',
  'Óculos resolvem: já tem {d} nessa linha.',
  'Olha pro lado. Isso, pra esquerda e pra direita. Viu o {d}?',
  'Linha já tem {d}. A linha é ciumenta, só aceita um.',
  'Dois {d} na mesma linha? A regra número 1, campeão.',
  'Essa linha já tem o {d} dela. Ela é monogâmica.',
  'Tá repetindo o {d} na linha. O sudoku ficou ofendido.',
  'Olha a linha inteira antes. O {d} tá ali rindo de você.',
  'Não pode {d} repetido na linha. Tá no manual. Página 1. Linha 1.',
  'O {d} tá vendo o outro {d} e ficou constrangido.',
  'Linha lotada de {d}. Quer dizer, com um. Um já é lotado.',
  'Já tem {d} na horizontal. Horizontal é deitado. Deitado igual seu raciocínio agora.',
  'O {d} que você quer já tá morando nessa linha. Vizinhança cheia.',
  'Deu ruim: {d} duplicado na linha. Tenta outro.',
  'Essa linha disse “não, obrigada” pro seu {d}.',
  'Tem um {d} bem ali. Tá piscando vermelho. Não dá pra não ver. Você não viu.',
  'Repetiu o {d} na linha. Clássico de iniciante. Charmoso até.'
],
sdWrongCol: [
  'Já tem {d} nessa coluna. Olha pra cima e pra baixo.',
  'A coluna já tem o {d} dela. Tá piscando, olha.',
  'Coluna com {d} repetido? Nem pensar.',
  'O {d} já tá nessa coluna, campeão. Vertical, lembra?',
  'Dois {d} em pé na mesma coluna. Não pode, não pode.',
  'Essa coluna já ocupou a vaga do {d}.',
  'Olha verticalmente. É tipo olhar prédio. Viu o {d} no andar de cima?',
  'Coluna já tem {d}. Ela não quer outro. Ela tá bem sozinha.',
  'Repetiu {d} na coluna. A coluna tá de braços cruzados.',
  'Sobe e desce com o olho. O {d} tá lá rindo.',
  'Coluna não aceita {d} duplicado. É política da casa.',
  'Opa, esse {d} já tem na coluna. Mira pra cima, mira pra baixo.',
  'A coluna gritou “ocupado!” quando você colocou o {d}.',
  'O {d} da coluna ficou com ciúmes do seu {d}.',
  'Tem {d} na vertical. Vertical! Aquela que fica em pé!',
  'Coluna, {d}, já tem. Três palavras que resumem seu erro.',
  'Esse {d} é repetido na coluna. Tá ali, bem visível. Tá piscando até.',
  'Não rola {d} duas vezes na coluna. Tenta outro número.'
],
sdWrongBox: [
  'Já tem {d} nesse quadrado. Olha dentro do 3×3.',
  'O quadrado já tem seu {d}. Ele não precisa de outro.',
  'Um {d} por quadrado. Regra de condomínio.',
  'Tem {d} nesse quadradinho já. Tá piscando pra você.',
  'Quadrado 3×3 com dois {d}? Isso não existe.',
  'Esse quadrado já tem {d}. Olha com calma, são só nove casas.',
  'Dentro do quadrado já tem {d}. Quadrado é igual apartamento: não cabe dois.',
  'O quadrado ficou bravo. Já tem {d} lá dentro.',
  'Repetiu o {d} no quadrado. O mais fácil de ver, inclusive.',
  'Tem {d} no mesmo bloco. Ó ali, piscando.',
  'Quadrado lotado de {d}. Um só já lota.',
  'Nove casas no quadrado e você não viu o {d}? Tá tudo bem. Não tá. Mas tá.',
  'O quadrado disse: “já tenho um {d}, obrigado”.',
  'Esse bloco 3×3 já tem {d}. Confere o bloco antes.',
  'Esquece esse {d} aqui. O quadrado já tem o dele.',
  'Opa, {d} duplicado no quadrado. Esse era o mais óbvio.',
  'O {d} do quadrado tá lá, pleno, feliz, sozinho. Deixa ele.',
  'Nesse bloco o {d} já apareceu. É tipo figurinha repetida.'
],
sdWrongHidden: [
  'Não bate com nada que dá pra ver… mas a resposta não é {d}. Confia no Bugado.',
  'Isso não existe. Literalmente: o {d} não pode existir aí.',
  'Não. Só… não. O {d} vai causar problema lá na frente.',
  'O {d} até parece caber, mas não é ele. Pensa em outro.',
  'Parece certo, né? Não é. O {d} é uma armadilha aqui.',
  'Tecnicamente não repete nada. Mas é errado mesmo assim. O sudoku é cruel.',
  'O {d} não tá em conflito com ninguém, mas não é a resposta. Chute bem-intencionado.',
  'Quase convincente. O {d} tem outro lugar pra morar.',
  'Sem repetição visível, mas errado. Tenta usar o lápis pra ver as opções.',
  'Hmm, o {d} não é daí. Anota as possibilidades antes de chutar.',
  'Chute detectado. O {d} não é a resposta dessa casa.',
  'Errado de um jeito elegante. Não repete nada, mas também não é.',
  'Nada contra o {d}. Mas ele não é daí.',
  'O {d} passou no teste da linha, da coluna e do quadrado… e reprovou no da resposta.',
  'Esse erro é dos traiçoeiros. Tenta ver qual número falta em volta.',
  'Não é {d}. Dica: essa casa tem pouca opção, vê qual sobra.',
  'O {d} parecia bom partido. Não era.',
  'Olha, não vou mentir: eu também chutaria {d}. E também erraria.',
  'Esse chute foi no escuro, né? O escuro errou.',
  'Nenhum conflito, mas também nenhum acerto. Sudoku é assim, seco.',
  'Tá chutando? Chute é arriscado. O lápis é teu amigo.',
  'Errou, mas errou com lógica. Mais ou menos. Tenta de novo.'
],
sdLastLife: [
  'Último coração! Agora é na raça.',
  'Só sobrou um coraçãozinho. Cuida bem dele.',
  'Uma vida. Uma chance. Muita pressão. Adoro.',
  'Último coração. Se errar de novo, eu chamo o padre.',
  'Tá no último! Respira fundo antes de cada número.',
  'Só um coração restante. Esse jogo virou filme de ação.',
  'Uma vida só. Agora usa o lápis, pelo amor.',
  'Último suspiro. Cada número agora é decisão de vida ou morte.',
  'Um coração! O Jorge tá roendo as unhas. Ele não tem unha. Tá nervoso mesmo assim.',
  'Pressão total: último coração. Sem chute, hein.',
  'Tá no fio da navalha. Segura esse último coração.',
  'Último coração. A grade tá sentindo o cheiro de vitória. Dela.'
],
sdThirdMistake: [
  'Terceiro erro. Ih.',
  'E lá se vai o último coração.',
  'Três erros. Acabou. Por enquanto.',
  'Eita. Esse foi o terceiro.',
  'Terceiro erro. Pode ir preparando o discurso de derrota.',
  'Três. Contei. Acabou a vida.',
  'Último coração partido. Literalmente.',
  'Três strikes. Fora!'
],
sdUnit: [
  'Fechou a {tipo}! Chora não, grade.',
  'Uma {tipo} a menos. A grade tá com medo.',
  'Faxina de sudoku. Tá limpando tudo.',
  'Isso! Sente o poder.',
  '{tipo} completa! Pode fazer a dancinha.',
  'Mais uma {tipo} fechada. Tá ficando bonito.',
  'Fechou! Aquela sensação de gaveta arrumada.',
  'Completou a {tipo}! A grade perdeu um pedaço da alma.',
  '{tipo} fechada com chave de ouro. Chave de pixel. Tanto faz.',
  'Olha isso! {tipo} completinha.',
  'Mais uma! Tá desmontando a grade peça por peça.',
  'Fechar {tipo} é o melhor barulho do sudoku.',
  'Aí sim! Essa {tipo} tá resolvida pra sempre.',
  'Completou. O {tipo} manda lembranças.',
  'Que satisfação! Parece estourar plástico bolha.',
  'Fechou uma {tipo}! Ganhou XP e meu respeito. Um pouquinho de respeito.',
  'Fechadinha! Nada de número faltando.',
  'Mais uma {tipo} pro museu das coisas resolvidas.',
  'É isso! A grade tá cada vez mais vazia de problema.',
  'Fechou a {tipo}. Tá sentindo o poder subindo?',
  'Completou! Isso merece um brinde. Brinde com água, que eu sou saudável.',
  'Clique, fecha, brilha. Que coisa linda.',
  'Mais uma {tipo} riscada da lista.',
  'Tô vendo a vitória no horizonte. Bem longe ainda. Mas tô vendo.',
  'Mais uma {tipo}! Tá jogando igual gente grande.'
],
sdUnitMulti: [
  'COMBO DUPLO! Fechou duas de uma vez. Que isso!',
  'Duas de uma vez! Isso é tipo strike no boliche.',
  'Fechou duas! Um número, dois coelhos.',
  'Duplo! A grade tomou dois socos de uma vez.',
  'Dois fechamentos com um número só. Eficiência nível planilha.',
  'Olha isso! Dupla completa. Tô orgulhoso. Um pouco.',
  'Fechou linha E coluna (ou quadrado). Multitarefa!',
  'Combo duplo! Isso vale pelo menos um grito.',
  'Um número, dois fechamentos. Isso é arte.',
  'Dobradinha! Se fosse futebol, era gol de bicicleta.'
],
sdNumDone: [
  'Todos os {d} no lugar. O {d} agradece.',
  '{d} zerado. Menos um problema na tua vida.',
  'Acabaram os {d}! Esse botão pode ir descansar.',
  'Os nove {d} estão em casa. Família reunida.',
  'Completou todos os {d}. Agora esquece que o {d} existe.',
  '{d}: missão cumprida. Próximo!',
  'Nove {d} no tabuleiro. Isso é colecionar direitinho.',
  'Não sobrou nenhum {d}. Pode riscar da lista.',
  'O {d} terminou. Ele tá tomando um café agora. Merecido.',
  'Todos os {d}! Menos opções, menos confusão.',
  'Fim da linha pro {d}. Literalmente, ele tá em todas as linhas.',
  '{d} completo! Esse número tá aposentado.',
  'Acabou o estoque de {d}. Viu? Botão apagadinho.',
  'Nove de nove {d}. Nota dez. Quer dizer, nove.',
  'Mais um número finalizado. Tá afunilando!'
],
sdQuarter: [
  'Um quarto da grade resolvido. Bom começo!',
  '25% feito. Falta só… o resto.',
  'Já foi um pedaço! Continua nesse ritmo.',
  'Um quarto! O começo é sempre o mais difícil. Mentira, o final é pior.',
  'Progresso detectado: 25%. Tá indo.',
  'Um quarto do caminho. Bebe água.',
  'Opa, já tem uma boa parte preenchida. Tá esquentando.',
  '25%! Se fosse bateria de celular, eu já tava desesperado.'
],
sdHalf: [
  'Metade! Agora é ladeira abaixo. Ou acima. Depende do seu otimismo.',
  'Metade da grade resolvida. Tá virando gente.',
  '50%! Meio caminho andado. Meio caminho pensado.',
  'Chegou na metade. Daqui pra frente fica mais fácil, porque tem menos opção.',
  'Meio tabuleiro! A grade tá começando a suar.',
  'Metade feita. A outra metade tá com medo.',
  '50%. Se isso fosse uma pizza, você já comeu metade.',
  'Tá na metade! Continua que tá bonito.'
],
sdThreeQ: [
  'Três quartos! Tá quase, tá quase!',
  '75% feito. Agora não pode vacilar.',
  'Já dá pra ver o fim. Cuidado pra não tropeçar nele.',
  'Três quartos da grade! Os números tão acabando, as opções também.',
  'Reta final chegando. Foco.',
  '75%! Agora os números praticamente se colocam sozinhos. Praticamente.',
  'Falta pouco! Olha os botões apagados, eles te guiam.',
  'Três quartos. O cronômetro tá torcendo por você. Eu não. Talvez.'
],
sdAlmost: [
  'Só faltam {n} casas! Não estraga agora.',
  '{n} casas! Tô nervoso. Você tá nervoso? Eu tô.',
  'Faltam {n}. Respira. Isso. Agora termina.',
  'Reta final: {n} casas. Tô roendo as orelhas.',
  'Só {n}! Se errar agora eu vou contar pra todo mundo.',
  '{n} casas pra glória. Glória de fliperama. Mas glória.',
  'Tá quase! {n} casinhas e acabou.',
  'Faltam {n}. O Jorge tá de olhos fechados, não aguenta ver.',
  'Última etapa! {n} casas. Eu confio. Confio sim.',
  '{n} casas restantes. Vai que é tua!',
  'Tá acabando! {n} casas. Não para agora.',
  'Contagem regressiva: {n}. Que emoção.'
],
sdErase: [
  'Apagou as anotações. Recomeçando o raciocínio.',
  'Borracha nela! Anotação errada não merece viver.',
  'Limpou. Às vezes é bom começar do zero.',
  'Apagou tudo. Arrependimento é um sentimento válido.',
  'Borrachada! A casa tá limpinha de novo.',
  'Adeus, rascunho. Você não fará falta.',
  'Apagou. Estratégia nova? Gosto.',
  'Limpeza de anotação feita com sucesso.'
],
sdEraseEmpty: [
  'Apagar o quê? Essa casa tá vazia.',
  'Você tá apagando o nada. O nada agradece o carinho.',
  'Não tem nada aí pra apagar, campeão.',
  'Borracha no vazio. Filosófico.',
  'Casa vazia não precisa de borracha. Precisa de número.'
],
sdUndoNone: [
  'Não tem nada pra desfazer. Você ainda não fez besteira. Por enquanto.',
  'Desfazer o quê? Tá tudo como começou.',
  'Nada no histórico. Você é uma folha em branco.',
  'Não dá pra voltar mais. Isso aqui é o começo dos tempos.',
  'Histórico vazio. Nem eu consigo desfazer o que não foi feito.',
  'Você apertou desfazer no vazio. O vazio agradece.'
],
sdUndo: [
  'Desfeito. Viajou no tempo.',
  'Ctrl+Z na vida real seria bom, né?',
  'Voltou atrás. Sabedoria ou medo? Não sei.',
  'Desfazendo… pronto. Como se nada tivesse acontecido.',
  'Já é o {n}º desfazer. Tá indeciso hoje, hein.',
  'Desfazer é aceitar que errou. Crescimento pessoal.',
  'Voltou. O passado agradece a visita.',
  'Mais um desfazer. A máquina do tempo tá esquentando.',
  'Undo! O botão favorito dos arrependidos.',
  '{n} vezes desfazendo. Você é o Doutor Estranho do sudoku.',
  'Rebobinou. Igual fita cassete.',
  'Desfez. Mas lembra: o que foi certo continua certo.'
],
sdNotesOn: [
  'Modo lápis ligado. Anota os palpites, é de graça.',
  'Lápis ON. Rascunho não conta como erro. Anota à vontade.',
  'Lápis na mão! Agora é hora de pensar com calma.',
  'Modo anotação. Aqui pode chutar sem medo.',
  'Lápis ligado. Os números agora saem pequenininhos. Fofos.',
  'Rascunho liberado. Estratégia de gente séria.',
  'Lápis ativado! Anota as possibilidades de cada casa.',
  'Modo lápis. Igual prova de escola, rascunho na margem.',
  'Lápis ON. Jogadores bons usam muito isso. Você vai usar? Espero que sim.',
  'Anotando! Aqui errar é de graça. Aproveita.',
  'Lápis ligado. Toca de novo no número pra apagar a anotação.',
  'Modo planejamento ativado. Tô gostando dessa maturidade.'
],
sdNotesOff: [
  'Lápis desligado. Agora é caneta. Sem medo.',
  'Lápis OFF. Agora vale de verdade.',
  'Chega de rascunho. Hora de decidir.',
  'Voltou pra caneta. Coragem.',
  'Lápis guardado. Agora os erros custam coração.',
  'Modo caneta! Certeza absoluta, hein?',
  'Desligou o lápis. Já sabe a resposta ou tá sendo corajoso?',
  'Lápis off. Número agora é pra valer.'
],
sdHint1: [
  'Tá, toma.',
  'Primeira dica. Eu te ajudo, mas não conto pra ninguém. Conto sim.',
  'Ok, lá vai uma ajudinha.',
  'Dica liberada. Aprende o truque, hein.',
  'Uma dica não mata ninguém. Mata um pouco o orgulho.',
  'Tá bom, vou te ajudar essa vez.',
  'Chamou o Bugado? O Bugado veio.',
  'Aqui vai. Lê a explicação que é o que importa.',
  'Primeira dica da partida. Tô de bom humor.',
  'Olha, eu te ajudo, mas depois você me paga um pastel.'
],
sdHint2: [
  'De novo? Ok.',
  'Segunda dica. Tô anotando.',
  'Mais uma? Tá bom. Mas presta atenção no truque.',
  'Dica dois. Vou começar a cobrar.',
  'Segunda vez. Tá virando hábito?',
  'Ok, mais uma. Olha bem como eu achei.',
  'De novo eu. Sou praticamente seu copiloto.',
  'Tá, dica número dois. Respira que você consegue sozinho também.',
  'Olha eu aqui de novo. Com carinho e julgamento.',
  'Segunda dica. Guardei na pastinha “pra zoar depois”.'
],
sdHintMany: [
  'Dica nº {n}, anotado.',
  'Dica {n}. Tô anotando num caderninho.',
  'Já é a {n}ª dica. Eu jogo ou você joga?',
  'Dica {n}. Daqui a pouco eu peço pra você me dar o controle.',
  '{n} dicas. Você não tá jogando sudoku, tá assistindo eu jogar.',
  'Mais uma? {n}! Vou abrir um curso de sudoku.',
  'Dica {n}. O Jorge falou que você tá dependente. O pixel tem razão.',
  '{n}ª dica. Tá tudo bem. Não tá. Mas tá.',
  'Dica {n}! Isso já é parceria. Quero crédito no final.',
  'Dica {n}. Tô pensando em cobrar mensalidade.',
  'Lá vai a {n}ª. Mas olha a explicação, hein!',
  'Dica {n}. Minha paciência tá acabando. Mentira, é infinita. Meu sarcasmo também.',
  '{n} dicas. Parece que eu tô jogando sozinho e você tá assistindo.',
  'Essa é a {n}ª. Se chegar em 81, eu fiz o sudoku inteiro.',
  'Dica {n}. Olha, eu gosto de ajudar. Mas também gosto de zoar. Os dois.'
],
sdHintFallback: [
  'Nem eu achei atalho aqui. Toma a resposta e finge que foi você.',
  'Essa casa não tem truque fácil. Tô te entregando de mão beijada.',
  'Aqui só lógica avançada resolvia. Toma logo.',
  'Nem candidato único, nem único lugar. Só a resposta mesmo. De nada.',
  'Essa grade é das difíceis. Eu trapaceei. Não conta.',
  'Não achei explicação bonita. Mas a resposta tá aí.',
  'Esse aqui precisava de técnica avançada. Eu dei um jeitinho.',
  'Pulei a aula e fui direto pra resposta. Shhh.'
],
sdWin: [
  'Ganhou em {tempo}. Vou ter que atualizar minha opinião sobre você.',
  'ZEROU! {tempo} no relógio. Printa e manda no grupo.',
  'Terminou! {tempo}. Eu tô orgulhoso. Não conta pra ninguém.',
  'Grade resolvida. A grade tá chorando no canto.',
  'Vitória! {tempo}. Pode fazer a dancinha.',
  'Acabou! E você ganhou! Isso não existe! Existe sim.',
  'Resolveu tudo. Sério, que maneiro.',
  'Venceu em {tempo}. O cronômetro aplaude.',
  'Ganhou! Tá virando lenda do sudoku. Pelo menos do meu sudoku.',
  'É campeão! {tempo} de pura lógica. E uns chutes.'
],
sdWinClean: [
  'ZERO ERROS! Quem é você? Eu não te reconheço.',
  'Nenhum coração perdido! Tô chocado. Genuinamente.',
  'Perfeito. Sem erro. Eu não tenho nem piada pra isso.',
  'Zero erros em {tempo}. Isso não existe. Mas você fez existir.',
  'Nenhum erro! Isso vai pro hall da fama do Bugado.',
  'Sem errar nada! Tá jogando de olho aberto hoje, hein.',
  'Partida limpa. Tipo lençol recém-lavado.',
  'Perfeição! Eu vou chorar. De pixel.',
  'Zero vergonha! Literalmente, olha a conquista.',
  'Nem um errinho. Você me deixou sem emprego.'
],
sdWinNoHint: [
  'Ganhou sem pedir dica! Orgulho próprio desbloqueado.',
  'Sem dica! Você não precisou de mim. Isso dói um pouco.',
  'Tudo sozinho! Tô feliz e levemente ofendido.',
  'Zero dicas. Você é independente. Eu respeito.',
  'Sem ajuda! {tempo} de puro cérebro.',
  'Ganhou sem minha ajuda. Vou ficar ali no canto, pensando na vida.',
  'Nenhuma dica! Tá vendo? Você consegue.',
  'Independência ou morte! E foi independência.'
],
sdWinFast: [
  'Rapidão! {tempo}! Tava com pressa pra quê?',
  'Speedrun! {tempo}. Os russos do speedrun tão com medo.',
  'Que velocidade! {tempo}. Tá jogando com turbo.',
  'Voou! {tempo}. Nem deu tempo de eu fazer piada.',
  '{tempo}! Isso é recorde? Olha lá nas estatísticas.',
  'Rápido demais! Eu mal comecei a comentar.',
  'Terminou em {tempo}! Tem certeza que é iniciante?',
  'Relâmpago! A grade nem viu de onde veio.'
],
sdWinSlow: [
  'Demorou {tempo}, mas ganhou! O importante é terminar.',
  'Levou {tempo}. Maratona! Mas maratona também tem medalha.',
  '{tempo} de batalha. Mas a vitória é sua!',
  'Ganhou! Demorou um pouquinho, mas quem tá contando? O cronômetro. Só ele.',
  'Vitória paciente em {tempo}. Tartaruga venceu a lebre.',
  'Longa jornada, final feliz. {tempo} bem investidos.',
  'Foi devagar e chegou. Isso que importa.',
  'Ufa! {tempo}. Até eu cansei. E eu só assisti.'
],
sdOver: [
  'Três erros. A grade venceu. Mas ela é uma grade e você é uma pessoa. Sei lá, tenta de novo.',
  'Game over! A grade tá comemorando. Vamos estragar a festa dela?',
  'Acabaram os corações. Mas não acabou a esperança. Acabou um pouco.',
  'Perdeu! Eu fingiria surpresa, mas…',
  'Morreu. Mas sudoku tem continue. Diferente da vida.',
  'Três strikes. Mas a partida não precisa acabar aqui.',
  'A grade te derrotou. Que humilhação. Pra grade, porque você vai voltar.',
  'Fim de jogo. Tô de luto. Por uns três segundos.',
  'X nos meus olhos. Tô morto de vergonha alheia.',
  'Perdeu os três corações. Os números certos continuam lá, tá?'
],
sdCont: [
  'Continuou? Respeito. Sem vergonha nenhuma. Nenhuma mesmo.',
  'Renasceu das cinzas! Tipo fênix. Uma fênix meio chamuscada.',
  'Continue! Igual fliperama dos anos 90. Sem ficha, sem culpa.',
  'Voltou do além! Corações cheios de novo.',
  'Mais uma chance! Aproveita que eu tô bonzinho.',
  'Continuou! A taxa da vergonha tá anotada, mas bora.',
  'Ressuscitou! O importante é terminar.',
  'Três corações novinhos. Não gasta tudo de uma vez.',
  'Segunda chance! A grade não sabe o que tá por vir.',
  'Continuar é pra quem não desiste. Ou pra quem é teimoso. Os dois servem.'
],
sdPaused: [
  'Você sumiu, eu pausei o tempo. Sou gente boa.',
  'Pausei o cronômetro. Vai que você foi no banheiro.',
  'Tempo pausado. Eu também fui tirar um cochilo.',
  'Parado? Pausei tudo. Toca na grade pra voltar.',
  'Zzz… pausei o relógio pra você não perder recorde.',
  'Congelei o tempo. Sou praticamente um mago.',
  'Pausa automática ativada. Não precisa agradecer. Mas pode.',
  'Te esperando com o tempo parado. Romântico, até.'
],
sdUnpause: [
  'Voltou! Tempo correndo de novo.',
  'Despausado. Bora que o cronômetro tá ansioso.',
  'Acordei! Onde a gente tava? Ah, é. Você tava travado.',
  'De volta à ação!',
  'Tempo destravado. Você também, espero.',
  'Retomando! Dá uma olhada geral antes de clicar.'
],

cutucarSudoku: [
  'Me cutucar não vai revelar número nenhum.',
  'Eu não sou a casa vazia. A casa vazia tá ali.',
  'Quer uma dica? Tem botão pra isso. Eu sou só o comentarista.',
  'Cutucou! Agora me diz: qual número falta no quadrado do meio?',
  'Sabia que existem 6.670.903.752.021.072.936.960 grades de sudoku válidas? E você me cutucando.',
  'Dica grátis: o número que mais aparece na grade costuma ser o mais fácil de terminar.',
  'Dica grátis: pega um quadrado 3×3 e pergunta: qual número falta aqui? Onde ele PODE ir?',
  'Sou o Bugado porque nasci de um erro de código. Igual teus chutes.',
  'Me cutuca de novo e eu troco todos os números. Mentira. Não consigo.',
  'Ei! Tô tentando resolver essa grade de cabeça também. Me desconcentrou.',
  'Aqui não tem número escondido, pode parar.',
  'Isso não é uma casa do sudoku, é minha cara.',
  'Sabia que “sudoku” quer dizer mais ou menos “número único” em japonês? Agora sabe.',
  'O sudoku moderno foi criado por um americano em 1979, mas ficou famoso no Japão. Curiosidade de mascote.',
  'Me cutuca e resolve uma casa. Faz um combo comigo.',
  'Eu já vi você fazer combo. Me impressiona de novo.',
  'Cutucar mascote dá 0 XP. Colocar número certo dá XP. Faz a conta.',
  'Tá procurando o número 10? Não existe. Nem eu.',
  'Minha dica secreta: olha a linha com mais números. Pronto. Agora para de me apertar.',
  'Cutucou. Anotado no seu histórico de comportamento suspeito.',
  'Se me cutucar 81 vezes eu resolvo a grade. Mentira. Mas imagina.',
  'Sabe o que dá mais satisfação que me cutucar? Fechar um quadrado.',
  'Você me cutuca e eu glitcho. A grade tá assistindo a gente.',
  'Já tentou o lápis? É ótimo. Muito melhor que me cutucar.',
  'Oi, tô aqui. Sempre aqui. Julgando cada número seu.',
  'Não me cutuca que eu erro a conta dos seus erros.',
  'Me cutucou no meio da minha análise da grade. Eu tava quase vendo o 7.',
  'Truque bônus: se um número só pode ir numa linha dentro de um quadrado, ele “bloqueia” essa linha nos outros quadrados.',
  'Dica de mestre: começa pelos quadrados mais cheios. Menos opção, menos erro.',
  'Sabia que os grandes jogadores anotam TUDO no lápis? Você devia tentar.',
  'Quer saber um segredo? A dica do nível Bebê sempre tem explicação bonita.',
  'Isso! Me usa de bola antiestresse. Depois volta pra grade.',
  'Cutucar não quebra combo. Mas também não aumenta.',
  'Se você me cutucou porque travou, a dica tá ali do lado. Sem vergonha.',
  'Eu sou o único número desse jogo que não vai de 1 a 9.',
  'Eu tava contando os 5 da grade. Perdi a conta. Culpa sua.',
  'Toca na casa, depois no número. Não em mim. Ok, em mim também, mas depois.',
  'Me cutuca menos e fecha mais linha.',
  'Tá bom, tá bom, dá um oi pro Jorge. Ele tá bem ali. Pixelzinho rosa.',
  'Mais uma cutucada e eu começo a narrar suas jogadas em voz de novela.'
]

});
