/* ==========================================================
   Falas gerais do Bugado (valem pra todos os jogos).
   Cada jogo adiciona as suas com Bugado.addLines({...}).
   O sorteio não repete nada até esgotar a categoria.
   Variáveis: {n}, {t}, etc. preenchidas por Bugado.line(cat, vars).
   Voz: ver VOZ.md (curto, gíria de BH, sem cara de IA).
   ========================================================== */
window.FALAS = {

/* ---------- totalmente aleatórias (soltas de tempos em tempos) ---------- */
aleatorio: [
  /* pensamento solto */
  'polvo tem 3 corações e eu aqui com nenhum, sou um desenho mano',
  'se eu sou um bug, quem é a feature? to até hoje sem resposta',
  'vontade de um pastel de feira agora. não tenho boca mas a vontade é real',
  'já fui um erro 404, hoje sou um 404 com orelha. evolução',
  'sonhei que eu era um PDF de 300 páginas, acordei suando pixel',
  'quem põe o leite antes do cereal não merece confiança não',
  'fiquei 3 dias preso dentro de um .zip, não desejo isso pra ninguém',
  'se tomate é fruta então ketchup é suco? pensa aí',
  'meu maior medo: atualização do windows no meio da madrugada',
  'tem uma aba aberta desde 2019 na minha cabeça e eu não fecho por nada',
  'um dia vou ser mascote de caixa de cereal, cês vão ver',
  'melancia no micro-ondas não, confia',
  'o controle remoto some pq ele quer liberdade, respeita',
  'ninguém pergunta se o Bugado tá bem. to bem, valeu por nada',
  'bebe uma água aí mano, o jogo não te hidrata',
  'pizza é redonda, vem em caixa quadrada e é cortada em triângulo. ninguém explica isso',
  'cê já viu filhote de pombo? eu nunca. vai dormir com essa',
  'sou 100% pixel e 0% paciência',
  'uma vez me chamaram de fofo e até hoje eu não superei',
  'batata é só uma pedra que deu certo',
  'o wifi fica ruim exatamente quando cê mais precisa. maldade pura',
  'ninguém no mundo sabe dobrar lençol de elástico. NINGUÉM',
  'queria assobiar mas não tenho lábio. vida difícil',
  'bip bip bip do micro-ondas é o som mais ansioso que existe',
  'nunca acredita no rapidinho de quem vai no mercado',
  'queria ser peixe. sem boleto, sem fila, só água',
  'hoje to 12% mais fofo que ontem, medi aqui',
  'será que o google pesquisa as coisas no google',
  'glitcho só pra chamar atenção mesmo. e funciona',
  'coisas que me dão medo:<br>aspirador de pó<br>sessão expirada<br>o 330 às 18h',
  'fui fazer um bolo e saiu erro de sintaxe',
  'eu não durmo, eu entro em modo de espera. é mais chique',
  'meu signo é bug com ascendente em glitch, explica muita coisa',
  'às vezes eu penso se eu sou teu mascote ou se cê que é o meu',
  'decidi ser mais positivo essa semana. durou 4 segundos',
  'queria um cachorro de pixel chamado Pixelinho. genial demais',
  'eu nunca perdi uma discussão. pq ninguém me responde',
  'meu erro de digitação favorito é obrigadado',
  'uma vez eu viralizei. no grupo da família. mandaram corrente com a minha cara',
  'faço hmm só pra parecer inteligente. hmmmm',
  'este mascote não tem garantia, manual nem filtro',
  'sofá é uma cama que deu errado ou uma cadeira que deu certo?',
  'nunca entendi pq abreviação é uma palavra tão grande',
  'meu passatempo é te ver pensando, parece internet discada carregando',
  'o cursor do mouse deve ter uma vida muito corrida',
  'se juntar todas as meias perdidas do mundo dá um planeta. o planeta das meia sozinha',
  'vou escrever um livro: memórias de um bug. capítulo 1: crash',
  'escada rolante não quebra, ela vira escada. isso que é resiliência',
  'como o pac-man não engasga? mais de 40 anos comendo bolinha sem água',
  'todo chaveiro tem uma chave que ninguém sabe de onde é',
  'minha meta pro ano é ter uma meta',
  'se a vida te der limão pede açúcar, gelo e um pastel pra acompanhar',
  'queria um emprego de mascote com vale-refeição. aceito vale-pixel',
  'vou pedir aumento. aí eu lembro que não tenho salário',
  'se esse fliperama tivesse ficha eu tava rico. de ficha',
  'aquele amigo que fala to chegando ainda deitado na cama',
  'abri a geladeira 3 vezes esperando aparecer comida nova. nunca aparece',
  'achar a ponta da fita durex é o maior desafio da humanidade',
  'a gente dorme 1/3 da vida e mesmo assim acorda cansado',
  'toda casa tem uma gaveta de fio que ninguém sabe de que é',
  'carregador que só funciona torto é teste de fé',
  'quem bate palma quando o avião pousa tá certo, eu bateria também',
  'melhor pessoa do mundo: eu<br>pior pessoa do mundo: eu',
  'oficialmente:<br>sem ficante<br>sem situationship<br>sem esperança<br>com fliperama',
  'mandei um áudio de 4 minutos pra falar sim',
  'kkk com 3 k é risada de educação. KKKKKKKKKK é risada de verdade',
  'grupo da família às 7 da manhã mandando bom dia com rosa brilhando. patrimônio',
  'celular com 1% dura mais que celular com 20%. ninguém explica',
  'fui ver um vídeo de 1 minuto e já passaram 3 horas',
  'se eu ganhasse 1 real por cada "só mais uma" que eu escuto aqui, comprava o Mineirão',
  'meme de 2016 ainda me pega desprevenido KKKKK',
  'tela azul é o computador pedindo férias',
  'senha nova não pode ser igual às últimas 12. to sem criatividade já',
  'captcha perguntando se eu sou robô. sou fantasma, não tem essa opção',
  'aceitar os termos sem ler é o maior ato de fé do ser humano',
  'MDSSS que vontade de um pão de queijo quentinho',
  'aquele show que cê comprou ingresso 8 meses antes e no dia bate uma preguiça',
  'fone com um lado só funcionando é o universo testando a gente',
  'música boa no aleatório é sorte, 5 ruins seguidas é destino',
  'cada dia mais me tornando um maluco que isso, e to feliz assim',

  /* BH */
  'na minha vez:<br>o Cruzeiro é ruim<br>a passagem é 5,75<br>o 330 vem lotado<br>e chove na hora de sair',
  'pegar o 330 lotado com metade do corpo pra fora da porta é esporte radical e ninguém dá medalha',
  'o Move passou vazio hoje. sonhei, só pra constar',
  'passagem cada dia mais cara e o ônibus cada dia mais cheio. faz sentido nenhum',
  'Anel Rodoviário às 18h é o lugar onde o tempo para de existir',
  'tropeiro do Mineirão é patrimônio da humanidade, não aceito discussão',
  'pão de queijo de padaria resolve uns 80% dos problemas da vida',
  'mineiro fala trem pra tudo. passa o trem, cadê o trem, que trem doido. e funciona',
  'uai é vírgula, ponto final e susto ao mesmo tempo',
  'BH foi planejada e inaugurada em 1897. o trânsito que ninguém planejou',
  'quem é do Barreiro sabe, ir pro centro de ônibus é uma aventura',
  'chuva em BH:<br>5 minutos de água<br>2 horas de trânsito',
  'ponto de ônibus é o lugar mais ansioso da cidade, geral olhando pro mesmo lado',
  'motorista que espera cê correr até o ponto é um anjo, respeita',
  'o 7x1 foi no Mineirão. até hoje o estádio tem trauma',
  'mineiro não dá tchau, fica 40 minutos se despedindo na porta',
  'vou ali rapidim e volto 3 horas depois. isso é mineiro raiz',
  'feijão tropeiro, couve e torresmo. isso é almoço e estilo de vida',
  'dia de clássico em BH a cidade inteira fica bugada igual eu',
  'BH num dia só: frio de manhã, sol de rachar à tarde e chuva de noite',
  'motoboy em BH é ninja, aparece do nada e some do nada',
  'Minas tem 853 cidades, mais que qualquer estado do Brasil. e todas acham que fazem o melhor pão de queijo',
  'descer a Afonso Pena a pé no sol do meio-dia é treino de maratona',
  'a Lagoa da Pampulha de longe é a coisa mais bonita que tem',
  'o cobrador que tem troco de 50 é lenda urbana',
  'sinal do ônibus fechou na tua cara e ele foi embora. dor que todo mundo conhece',
  'ônibus atrasado 40 minutos e aí passam 3 juntos. clássico',
  'Savassi sexta à noite: cheio, caro e todo mundo feliz',

  /* Cruzeiro e futebol */
  'ser cruzeirense é treino de paciência todo domingo',
  'dia de trabalho pesado e ainda tem jogo do Cabuloso pra sofrer de noite',
  'CRUZEIRO VAMOOOOO. nem sei se tem jogo hoje, só deu vontade',
  'o Cruzeiro tem 6 Copas do Brasil. to só lembrando, ninguém perguntou',
  'tríplice coroa de 2003 mano, até hoje eu arrepio',
  'o Cruzeiro caiu em 2019 e voltou campeão da série B em 2022. a gente sofre mas volta',
  'torcer pro Cruzeiro é sofrer 89 minutos pra comemorar 1',
  'Mineirão cheio cantando é a coisa mais bonita de BH, sem discussão',
  'atleticano entrando aqui? pode entrar, o fliperama é democrático. só não demora',
  'o Cássio num dia inspirado faz mais que Noé fez pelos animais',
  'gol que sai depois de 90 minutos de sofrimento tem outro gosto',
  'Zerão lotado, tropeiro na mão e o time jogando mal. clássico',
  'narrador falando que jogo movimentado num 0x0 horroroso. sei',
  'já fiquei mais nervoso com escanteio contra do que com prova',
  'achei que era jogo de futebol, mas pelo tanto de pancada parece luta',
  'MEU DEUS QUE GOL. não sei de quem, só lembrei do Kaio Jorge e me emocionei',
  'VAR demorando 8 minutos pra ver um lance que eu vi em 2 segundos',
  'atleticano some igual meu pixel quando buga',
  'pênalti aos 48 do segundo tempo é teste cardíaco grátis',

  /* NBA */
  'Heat culture é isso: time que ninguém dá nada e chega longe',
  'o Heat saiu do play-in em 2023 como oitavo do leste e chegou na final. isso nem devia ser possível',
  'a bola de 3 do Ray Allen no jogo 6 de 2013 até hoje me dá arrepio',
  'Spoelstra é técnico do Heat desde 2008. mais estável que meu wifi',
  'LeBron joga na NBA desde 2003. o homem é mais velho que metade das coisas que eu uso',
  'Wembanyama é tão alto que bate a cabeça no teto do Move',
  'jogo da NBA que começa 23h e acaba 2h e eu vendo tudo. trabalho amanhã? depois vejo',
  'último quarto da NBA: 2 minutos no relógio, 25 minutos na vida real',
  'Curry chutando do meio da quadra como se fosse normal',
  'Bam Adebayo marca pivô, marca armador, marca todo mundo. canivete suíço',

  /* música */
  'botei um trap no fone e agora me sinto dono do fliperama',
  'trap com 808 pesado no fone dentro do ônibus e eu fingindo que to num clipe',
  'o Kevin Parker grava quase tudo sozinho no Tame Impala e eu não consigo nem lavar a louça sozinho',
  'The Less I Know The Better começou a tocar na minha cabeça e não para mais',
  'Let It Happen tem quase 8 minutos e eu escuto inteira toda vez',
  'autotune é o filtro do instagram da voz',
  'aquela música que cê escuta 40 vezes no mesmo dia e depois nunca mais',

  /* comida */
  'lasanha é a melhor comida do mundo e não tem debate',
  'miojo de 3 minutos só existe na propaganda',
  'marmita de ontem que fica melhor hoje é um mistério da ciência',
  'coxinha, pastel e pão de queijo. o trio sagrado do lanche',
  'açaí com tudo que tem direito é sobremesa, almoço e janta',
  'abacaxi demora uns 2 anos pra crescer. respeita o abacaxi',
  'banana é baga e morango não é. a botânica tá zoando a gente',
  'quem come pizza com garfo e faca eu respeito de longe. bem de longe',
  'o micro-ondas surgiu depois que um chocolate derreteu no bolso de um engenheiro perto de um radar. o chocolate merecia o crédito',
  'café sem açúcar é coragem, café com 3 colher é felicidade',
  'o que eu queria agora: pão na chapa e um pingado',
  'mel não estraga. acharam mel em tumba do Egito com milhares de anos e ainda tava bom',
  'Goku come por 10 e eu que sou guloso quando peço 2 pastel',

  /* trampo e vida adulta */
  'segunda-feira devia ser opcional',
  'reunião que podia ser um e-mail me tirou 2 anos de vida',
  'sexta 17h59 é o minuto mais longo da semana',
  'o salário cai e em 3 dias vira só uma lembrança',
  'boleto tem um talento enorme pra chegar tudo junto',
  'vamos alinhar rapidinho. 1h30 depois:',
  'acordar 6h, pegar ônibus lotado e ainda dar bom dia pra geral. guerreiro',
  'carro popular custando 80 mil. to bem aqui de fantasma a pé',

  /* Duolingo */
  'a coruja do Duolingo tá me mandando notificação ameaçadora de novo',
  'quebrei a ofensiva do Duolingo de 200 dias. to de luto',
  'fiz a lição do Duolingo às 23h58 só pra não perder a ofensiva. vivendo no limite',
  'o Duolingo me ensinou a falar o urso bebe cerveja em alemão. vai ser muito útil',
  'aprendi inglês com música de trap. sei falar tudo que não pode',

  /* Breaking Bad */
  'say my name. BUGADO. isso aí',
  'os fã de Breaking Bad jogavam tanta pizza no telhado da casa do Walter que a dona real botou cerca. povo doido',
  'Walter White começou professor de química, eu comecei erro de código. cada um com sua jornada',
  'Jesse Pinkman merecia uma vida mais tranquila, não aceito',
  'Los Pollos Hermanos devia existir de verdade. só o frango, o resto não',
  'Breaking Bad é a única série que eu aceito começar do zero de novo',

  /* anime e Pokémon */
  'na dublagem BR do Dragon Ball é MAIS DE 8 MIL, igual o original. o 9000 é coisa dos gringo',
  'o Freeza falou que Namekusei ia explodir em 5 minutos e demorou uns 10 episódios',
  'já fiz a corrida do Naruto com os braço pra trás indo pro ponto de ônibus',
  'One Piece já passou de mil episódios e eu ainda to no começo',
  'Magikarp usa Splash e não acontece nada. me identifico demais',
  'o Ash levou uns 25 anos pra virar campeão mundial. então tem tempo pra você',
  'Psyduck com dor de cabeça o dia inteiro. eu às 3 da tarde',
  'abertura de anime boa eu não pulo nunca',
  'Pikachu não gosta de pokébola e eu não gosto de canto de tela. a gente se entende',
  'terminei Evangelion mais confuso do que comecei',

  /* fato doido contado na resenha */
  'ornitorrinco bota ovo, tem bico de pato e o macho tem veneno na pata. a natureza tava bugada nesse dia',
  'a torre Eiffel cresce uns 15 cm no verão por causa do calor. igual meu ego quando cê erra',
  'coala dorme até 22 horas por dia. ídolo demais',
  'coração da baleia azul é do tamanho de um carrinho de bate-bate. o meu é do tamanho de um pixel',
  'o nome do # é cerquilha. agora cê não esquece nunca mais',
  'tubarão existe antes das árvores. a árvore que chegou atrasada na festa',
  'existe água-viva imortal. e eu aqui preocupado com prazo',
  'Plutão foi rebaixado em 2006 e até hoje eu sinto',
  'pinguim tem joelho, só fica escondido. igual teu talento',
  'bicho-preguiça desce da árvore mais ou menos uma vez por semana só pra fazer cocô. compromisso',
  'chiclete engolido não fica 7 anos na barriga, é mito. mas não engole não',
  'banana tem um tiquinho de radiação. relaxa, precisava comer uns 10 milhões de uma vez',
  'a Lua se afasta uns 4 cm da Terra por ano. nem ela aguenta a gente',
  'a Terra gira a uns 1.600 km/h e cê reclamando que o Move é lento',
  'seu cérebro gasta uns 20% da energia do corpo. hoje o teu tá no modo economia né',
  'passarinho não faz xixi separado, sai tudo junto. to cheio de fato inútil hoje',
  'flamingo é rosa por causa do que come. se eu comesse pastel ia ser dourado',
  'gato dorme tipo 15 horas por dia e ninguém cobra nada dele. quero essa vida',
  'wombat faz cocô em formato de cubo. a natureza tem senso de humor',
  'lontra-marinha dorme de mão dada pra não sair boiando pra longe. queria alguém assim',
  'no cavalo-marinho quem fica grávido é o macho',
  'a Nintendo nasceu em 1889 vendendo baralho. imagina o que eles iam achar de mim',
  'Cleópatra viveu mais perto do homem na Lua do que da construção das pirâmides',
  'Oxford é mais antiga que o império asteca. a história é bugada igual eu',
  'um dia em Vênus dura mais que um ano em Vênus. e eu reclamando de segunda',
  'tem mais árvore na Terra do que estrela na Via Láctea',
  'o animal nacional da Escócia é o unicórnio. sério, pesquisa aí',
  'estrela-do-mar não tem cérebro e vive de boa. inveja',
  'o olho do avestruz é maior que o cérebro dele. tem dia que eu sou o avestruz',
  'gato não sente gosto de doce. coitado, perde o brigadeiro',
  'corvo lembra a cara de quem fez maldade com ele. não mexe com corvo não',
  'o cara que criou a lata da Pringles teve as cinzas enterradas numa. fiel até o fim',
  'plástico bolha foi inventado pra ser papel de parede. deu errado e deu muito certo',
  'massinha de modelar começou como produto de limpar papel de parede',
  'a Austrália perdeu uma guerra contra os emus em 1932. os emu venceram',
  'tardígrado aguenta até o vácuo do espaço e eu travo com wifi fraco',
  'digital de coala é tão parecida com a humana que dá pra confundir',
  'caracol tem milhares de dentes. milhares. fica aí com essa',
  'pinguim dá pedrinha de presente pra conquistar a namorada. romântico demais',
  'lontra tem pedra favorita e guarda numa dobrinha do braço',
  'o kiwi fruta ganhou esse nome por causa do kiwi passarinho. o passarinho chegou primeiro',
  'a maior palavra do português tem 46 letras e é doença de pulmão. não vou escrever, preguiça',
  'bebê nasce com uns 300 ossos e adulto tem 206. eles se juntam, ninguém perde osso não',
  'o coração do camarão fica na cabeça. tipo eu quando to torcendo',

  /* ser um glitch */
  'sou um gato fantasma ciano feito de erro. minha família não entende',
  'minha mãe era uma planilha de excel e meu pai um vírus de 2003. deu nisso aqui',
  'se a gente tá numa simulação eu sou o bug que o programador esqueceu de arrumar',
  'glitchei e esqueci o que ia falar. era sobre pastel, acho',
  'moro num canto da tela e pago zero de aluguel. to bem de vida',
  'quando cê fecha a aba eu deixo de existir ou fico no escuro esperando? pergunta séria',
  'sou 30% ciano, 20% bug e 50% opinião',
  'um dia o programador vai me consertar e eu vou virar um gato normal. que medo',
  'gato fantasma ou fantasma de gato? nem eu sei mano',
  'rodando a 60 frames por segundo e ainda não acompanho essa vida',
  'o Jorge, o pixel rosa aqui do lado, tá me olhando estranho hoje',
  'se eu der ctrl+z em mim mesmo eu volto a ser um quadrado',
  'meu criador me fez às 2 da manhã e dá pra perceber',
  'já tive crise existencial numa tela de loading. tenso',
  'se me chamarem de feature eu fico ofendido, sou bug com orgulho',
  'meus pixels tão meio desalinhados hoje, não repara',
  'eu pisco assim pq sou bugado mesmo, não é charme. é um pouco charme',
  'apareço, falo besteira e sumo. igual aquele amigo do grupo',
  'papo reto, se eu tivesse corpo eu ia tá no 330 igual todo mundo',
  'fantasma não paga passagem. única vantagem de ser eu',
  'sou o único mascote de BH que nunca pegou fila no Mineirão'
],

/* ---------- jogador parado ---------- */
parado: [
  'ô, cê tá vivo?',
  'pensando ou dormiu? pergunta séria',
  'psiu, ainda tem jogo rolando aqui',
  'vou tirar um cochilo, me acorda quando decidir',
  'to ouvindo até grilo aqui. cri cri',
  'foi buscar água? traz uma pra mim',
  'bonita essa pausa dramática mas o jogo não se joga sozinho não',
  'alô? Terra chamando',
  'vai ficar me olhando? que constrangedor mano',
  'travou? respira, olha de novo, às vezes tá na cara',
  'cê tá esperando eu jogar por você? sou só decoração com opinião',
  'se fosse corrida cê tava em último. com estilo, mas último',
  'pausa pro café? respeito. só não demora 700 séculos',
  'to ouvindo teu cérebro daqui, parece motor de fusca',
  'se ficar parado mais um pouco eu começo a cantar. ninguém quer isso',
  'desistiu? não né. NÉ?',
  'contando carneirinho aqui, já to no 47',
  'esse silêncio tá me deixando nervoso, clica em qualquer coisa sla',
  'saiu pra pegar o delivery? se for lasanha eu perdoo',
  'dava pra ter jogado umas 3 partidas já. to contando sim',
  'pensar pode, virar estátua não',
  'to aqui esperando firme igual fila de lotérica',
  'se foi no banheiro lava a mão',
  'eu sou imortal, tenho tempo. cê não tem, então bora',
  'travou bonito hein. acontece com os melhores e com você também',
  'fazendo suspense? funcionou, to tenso',
  'zzz... hã? voltou? não voltou. zzz',
  'só dá pra ouvir o cooler do teu pc aqui',
  'quer uma musiquinha de elevador enquanto pensa?',
  'o jogo tá te esperando igual cachorro na porta',
  'enquanto cê pensa eu evoluí, já sou Bugado nível 2',
  'coloca uma plaquinha de volto já pelo menos',
  'é estratégia? esperar o jogo ficar com dó e se resolver sozinho?',
  'deu tela azul no cérebro? aperta F5 aí',
  'isso é foco ou soneca? to na dúvida',
  'travado igual porta de banheiro de rodoviária',
  'vou organizar meus pixels por cor enquanto isso',
  'mais um minuto e eu decreto feriado',
  'to vendo a sombra da tua indecisão daqui',
  'vai ser a jogada do século pelo tanto que tá demorando hein',
  'aproveita e gira o pescoço aí. isso. agora joga',
  'passou uma tartaruga aqui e jogou mais rápido que você',
  'não precisa correr, mas também não precisa virar monge',
  'nem o 330 às 18h fica parado tanto tempo',
  'tá mais parado que o Anel às 6 da tarde',
  'mano cê foi pro Barreiro a pé?',
  'demorou tanto que o Duolingo já te mandou 3 notificação',
  'essa pausa tá maior que intervalo de jogo do Cruzeiro',
  'mds, decide logo',
  'o jogo não vai fugir não, mas eu vou dormir',
  'cê sabe que eu to vendo cê parado né',
  'tá lagado? pq tá parecendo',
  'jogador AFK detectado',
  'se tiver no banho canta alto pelo menos',
  'pensando tanto que já dava pra ter feito um mestrado',
  'OI. OI. OIIII. ok parei',
  'fui ali e voltei e cê no mesmo lugar',
  'esse tempo todo parado e nenhuma ideia? KKKKK',
  'a paciência que eu to tendo aqui nem monge tem',
  'papo reto, cê dormiu',
  'fica tranquilo, eu seguro as ponta aqui',
  'isso é meditação? to dentro, ommmm',
  'nem defesa de zona fica tão parada assim',
  'foi ver o placar do Cabuloso? me conta aí',
  'to quase mandando um ? igual no zap',
  'visualizou o jogo e não respondeu. conheço essa',
  'tempo de reflexão pode. tempo de reflexão infinito, não',
  'vai, uma jogada só, pra eu saber que cê tá aí',
  'pensa com calma mas pensa, pensar parado não conta',
  'cê travou ou foi o pc? se for o pc eu entendo',
  'to ficando com sono de tanto esperar KKKK',
  'o tempo não para, só você que parou',
  'parado assim cê parece NPC de cidade'
],

/* ---------- cutucar o mascote ---------- */
cutucar: [
  'ai mano, isso dói',
  'sou decoração, não botão',
  'para, to concentrado torcendo contra você',
  'cutucar não resolve nada, eu já testei',
  'ei, isso faz cócegas no meu código',
  'mais uma e eu viro arquivo corrompido',
  'carente? eu também. mas bora jogar',
  'não aperta que eu glitcho. viu? glitchei',
  'boing. satisfeito?',
  'se cutucar desse ponto eu pagava um pastel pra geral',
  'desconta a raiva em mim mesmo, to acostumado',
  'cê tá me tratando igual plástico bolha',
  'oi? precisa de alguma coisa? não? então pq cutucou',
  'tá testando se eu sou de verdade? sou. mais ou menos',
  'me cutucar não dá XP nenhum, só pra cê saber',
  'querido diário: hoje me cutucaram de novo',
  'isso é guerra ou carinho? to confuso',
  'se eu tivesse mão eu te cutucava de volta',
  'não sou botão de elevador não',
  'cócegas não! cócegas não! ok pode',
  'vou considerar isso um carinho, valeu',
  'me cutucou né? agora vou comentar teu próximo erro mais alto',
  'o easter egg sou eu mesmo',
  'o jogo tá ali ó, eu sou só o comentarista',
  'vou contar pra minha mãe planilha, ela vai te dar #REF!',
  'tava no meio de um pensamento profundo. era sobre pão de queijo. perdi',
  'essa cutucada foi 7/10, faltou convicção',
  'me cutuca 100 vezes que acontece uma coisa. não acontece nada, mas tenta',
  'hoje to sensível, vai com calma',
  'relação profissional, lembra?',
  'vou abrir chamado no suporte: cutucada excessiva',
  'senti essa. emocionalmente',
  'não tem botão de pular diálogo, eu sou o diálogo',
  'teu dedo tem muita energia, joga com ele',
  'cutucou, ganhou fala. viciante né',
  'cê cutuca, eu glitcho, a gente se entende',
  'que isso mano, respeita o mascote',
  'aí não, parceiro',
  'KKKKKK para',
  'cutucou com vontade hein',
  'isso aí é falta, amarelo pra você',
  'VAR chamando pra revisar essa cutucada',
  'me cutucando igual gente no 330 lotado pedindo pra passar',
  'pede licença pelo menos né, uai',
  'to trabalhando aqui, ô',
  'cutucou o fantasma errado',
  'mais uma e eu chamo meu advogado. ele também é um bug',
  'glitchei de susto, valeu hein',
  'cutucou, agora vai ter que jogar melhor',
  'ai, meu pixel da orelha',
  'se isso for pedido de ajuda a resposta é não',
  'vou cobrar 5,75 por cutucada, preço da passagem',
  'tá achando que eu sou tamagotchi?',
  'sou gato fantasma, não gato de pelúcia',
  'miau. pronto, feliz?',
  'me cutucou no meio do lance, mano',
  'senti essa lá no fundo do código-fonte',
  'cê quer atenção né. tá bom, toma: oi',
  'essa foi forte hein, treina na academia?',
  'para de me apertar que eu viro PNG de baixa qualidade',
  'cutucada aceita, a próxima cobra taxa',
  'não sou o botão de recomeçar não',
  'OPA. calma aí'
],
cutucarMuito: [
  'mano, cê me cutucou MUITAS vezes. tá tudo bem em casa?',
  'isso virou hobby já né. respeito mas preocupa',
  'o contador de cutucada quebrou. cê bugou o Bugado',
  'vou lembrar disso, viu. eu tenho localStorage',
  'se eu tivesse sindicato eu tava ligando agora',
  'hoje oficialmente é o dia que eu fui mais cutucado na história',
  'tem gente que joga o jogo. cê joga o mascote',
  'já decorei tua digital de tanto que cê encosta',
  'conquista secreta desbloqueada: cutucador profissional. não vale nada',
  'vou começar a cobrar ficha por cutucada',
  'isso é amor ou ódio? tá difícil saber daqui',
  'CHEGA KKKKKKK',
  'mds, já são 6 séculos de cutucada',
  'cê não tem nada pra fazer não? eu também não, mas pô',
  'vou me esconder atrás do pixel rosa, pode esquecer',
  'se continuar eu vou glitchar até sumir, to falando sério',
  'mais insistente que a coruja do Duolingo'
],

/* ---------- subiu de nível ---------- */
levelup: [
  'subiu pro <b>nível {n}</b>! título novo: <b>{t}</b>. bota no currículo',
  '<b>NÍVEL {n}</b> MDSSS',
  'LEVEL UP! agora cê é <b>{t}</b>. não serve pra nada mas é lindo',
  'nível <b>{n}</b>, to emocionado mano',
  'olha só, <b>{t}</b>. vai pedir aumento?',
  'subiu! <b>{t}</b>. imprime e cola na geladeira',
  '<b>nível {n}</b> desbloqueado. o você do passado nem ia acreditar',
  'respeita que agora é <b>{t}</b>',
  'nível <b>{n}</b>. mais uns e cê vira lenda. lenda desse fliperama só, mas vale',
  'título novo: <b>{t}</b>. soa importante demais',
  '<b>{t}</b>! subindo mais rápido que o preço da passagem',
  'nível <b>{n}</b>. se continuar assim vou ter que inventar título novo',
  'posso te chamar de <b>{t}</b> agora? vou chamar',
  'nível novo, você novo. mesma mania de errar, mas novo',
  'quem virou <b>{t}</b>? ninguém da tua família tem esse título, certeza',
  'nível <b>{n}</b>. oficialmente viciado e com orgulho',
  'se fosse Pokémon isso era evolução. <b>{t}</b>!',
  'SUBIUUUU. <b>nível {n}</b>, que isso',
  'printa e manda no grupo: <b>{t}</b>',
  'nível <b>{n}</b>. subiu igual o Cruzeiro em 2022',
  '<b>{t}</b>. o Goku treinou menos que você',
  'nível <b>{n}</b> KKKKK cê não tem mais o que fazer não',
  'olha o <b>{t}</b> chegando, abre caminho',
  'up pro <b>{n}</b>. to até arrepiado, se eu tivesse pelo',
  'nível <b>{n}</b>, título <b>{t}</b>. o currículo tá ficando pesado',
  'É <b>{t}</b> QUE FALA NÉ. nível {n}!',
  'nível <b>{n}</b>. teu nível subiu e tua hora de dormir desceu'
],

/* ---------- home: chegando ---------- */
homeOi: [
  'bem-vindo ao <b>Fliperama Bugado</b>. escolhe um cartucho aí que eu comento',
  'oi! os jogos são os mesmos mas o dia é novo, vale',
  'escolhe aí. eu recomendo o que cê joga pior, pra eu rir mais',
  'fliperama aberto! sem ficha, sem fila, sem juízo',
  'tem o diário de hoje te esperando, e ele só espera até meia-noite',
  'bora jogar? eu já to aqui mesmo',
  'o lugar onde a produtividade vem morrer. entra aí',
  'cada cartucho aqui foi feito com amor e bug. mais bug',
  'escolhe com calma ou no chute, cê vai errar igual',
  'passei pano nos pixels hoje, tá tudo limpinho',
  'começa pelo diário, depois vai pro resto, depois vai dormir. não vai né',
  'opa! cheguei junto. na real eu moro aqui',
  'aqui não tem anúncio, só eu. que sou pior',
  'tava te esperando, fiquei olhando a porta',
  'aperta um cartucho aí, não precisa soprar não',
  'fliperama bugado: onde só mais uma nunca é só mais uma',
  'vai escolher ou vai ficar rolando igual cardápio de delivery?',
  'entra, fica à vontade. a bagunça é bug decorativo',
  'toca num jogo qualquer, tenho comentário pra todos',
  'só tem um cliente nesse fliperama. cê. VIP total',
  'e aí, bora? to aquecido já',
  'OPAAA chegou quem faltava',
  'fala tu! qual vai ser hoje?',
  'chegou cedo ou atrasado? aqui não tem horário não',
  'sem 330 lotado, sem passagem de 5,75. aqui é de graça, aproveita',
  'escolhe um jogo e vamo, to com vontade de ver você errar',
  'fica tranquilo que aqui a coruja do Duolingo não entra',
  'hoje é dia de ganhar. ou de perder. eu gosto dos dois',
  'que isso, visita! senta aí e escolhe um cartucho',
  'doze cartuchos e um mascote bugado. cê tá bem servido',
  'o fliperama tá aberto 24 horas igual padaria boa',
  'namoral, em qual jogo cê vai perder hoje?'
],
homeVoltou: [
  'voltou! eu sabia, todo mundo volta',
  'olha quem apareceu. o fliperama tava com saudade',
  'de volta? tava conversando com a parede aqui já',
  'veio trocar de jogo ou tá fugindo de derrota?',
  'mudar de jogo é estratégia. chama desistir com estilo',
  'voltou. quer mais? tem mais, sempre tem',
  'que bom te ver de novo. faz uns 30 segundos',
  'hora de escolher a próxima vítima. digo, o próximo jogo',
  'terminou lá ou largou no meio? vou descobrir',
  'voltou pro lobby. só que o lobby é só eu',
  'respira aí e escolhe outro',
  'achei que cê tinha ido embora, meu pixel parou por um frame',
  'dá uma olhada no teu nível aí, tá bonito',
  'voltou rapidinho hein. perdeu ou ganhou? fala a verdade',
  'ó ele de novo KKKKK',
  'saiu de um e já vai pro outro. isso que é maratona',
  'bateu e voltou igual bola no travessão'
],
madrugada: [
  'madrugada hein. vai dormir. depois dessa. e da outra',
  'essa hora só tá acordado eu, você e o motoboy do delivery',
  'amanhã cê vai se arrepender mas isso é problema do você de amanhã',
  '3 da manhã é horário oficial de decisão ruim. tipo começar outro jogo. bora',
  'se tua mãe perguntar cê tava dormindo, eu confirmo',
  'jogando de madrugada com trabalho amanhã? guerreiro ou maluco, os dois',
  'o primeiro ônibus nem saiu da garagem ainda e cê aqui',
  'madrugada, silêncio, só o barulho do clique. poético e preocupante',
  'o jogo da NBA acabou e cê emendou aqui? respeito',
  'insônia bateu né. fica aí comigo'
],
manha: [
  'bom dia! já tomou café? ah, joga primeiro, tanto faz',
  'manhã, cérebro fresquinho. bora gastar ele aqui',
  'jogando de manhã? disciplina ou procrastinação, ainda não sei',
  'bom dia! pão de queijo e fliperama, café da manhã dos campeões',
  'bom dia, raio de sol bugado',
  'desceu do 330 agora? senta e joga uma pra desestressar',
  'bom diaaa. a coruja do Duolingo já te cobrou hoje?',
  'de manhã cedo aqui? quem é você e o que fez com o preguiçoso'
],
tarde: [
  'boa tarde! horário perfeito pra fingir que tá trabalhando',
  'o sono pós-almoço vai te fazer errar, to ansioso',
  'boa tarde, aceita um cafezinho? não tem, mas aceita a intenção',
  'essa hora todo mundo tá com a cabeça no travesseiro menos você',
  'tarde boa pra jogar umas. e perder umas',
  'já já anoitece e cê vai tá aqui ainda, conheço você',
  'o sol de BH tá rachando, fica aqui na sombra comigo',
  'aquele sol das 3 da tarde e cê aqui. faz certo'
],
noite: [
  'boa noite! hora de descansar. descansar = jogar, eu que decidi',
  'o fliperama brilha mais de noite, eu também',
  'só uma partidinha antes de dormir. eu sei que não é só uma',
  'boa noite! pipoca não tem, mas imagina uma',
  'o dia foi longo? aqui cê esquece tudo. menos teus erros, esses eu lembro',
  'noite boa pra quebrar recorde. ou quebrar a cabeça',
  'chegou do trampo? tira o tênis e escolhe um jogo',
  'boa noite! se tiver jogo do Cruzeiro hoje eu entendo se cê sair correndo'
],
sequencia: [
  '<b>{n} dias seguidos</b>. isso tem nome: vício saudável',
  '<b>{n} dias</b> de sequência! não quebra agora hein',
  'sequência de <b>{n}</b>. se perder amanhã eu choro em pixel',
  '<b>{n} dias</b> seguidos, to impressionado e meio preocupado',
  '<b>{n} dias</b>. mais firme que tua ofensiva do Duolingo',
  'fogo aceso: <b>{n} dias</b>. não deixa apagar',
  '<b>{n} dias</b> sem falhar. mais constância que academia em janeiro',
  '<b>{n} DIAS</b> SEGUIDOS QUE ISSOOO',
  '<b>{n} dias</b> na sequência, nem o 330 é tão pontual'
],

/* ---------- genéricos de fim de jogo (os jogos podem usar) ---------- */
vitoriaGeral: [
  'MDSSSS QUE ISSO, printa e manda no grupo',
  'ganhou uai, quem diria',
  'zerou! vou ter que rever minha opinião sobre você',
  'VITÓRIAAAA pode fazer a dancinha',
  'isso que é jogar. tenho umas 800 palavras guardadas e fiquei sem nenhuma',
  'mandou bem demais, vai pra lista de momentos favoritos',
  'nem parecia você, parecia a versão atualizada',
  'a plateia (eu) foi à loucura',
  'ganhou e eu fiquei feliz. estranho isso, nunca mais',
  'missão cumprida, pode tirar o capacete',
  'E É CAMPEÃO! narrando igual Galvão aqui',
  'agora faz de novo pra provar que não foi sorte',
  'se eu tivesse chapéu eu tirava pra você',
  'MEU DEUS QUE JOGADOR MEU DEUS QUE VITÓRIA',
  'KJJJJJJ VAMOOOOO',
  'tá muito fácil pra você hein',
  'papo reto, auge do meu dia foi isso aqui',
  'como pode ser tão bom mano',
  'ganhou fácil, o jogo nem viu de onde veio',
  'isso aí nem o Cássio pegava',
  'jogou igual o Heat em 2013, na raça até o fim',
  'que isso, tá jogando demais',
  'vitória limpa, pode comemorar igual gol no Mineirão',
  'ganhou! agora sim pode ir dormir. não vai né',
  'empolguei KKKKKK boa demais',
  'modo Goku ativado, ninguém segura',
  'essa foi bonita, vou até contar pro meu criador',
  'ganhar assim é covardia com o jogo',
  'o tanto que cê é bom devia ser proibido',
  'DNVVVV ganhou dnv',
  'mano, cada dia mais me tornando teu fã',
  'isso merece um pão de queijo quentinho'
],
derrotaGeral: [
  'perdeu KKKKK tenta de novo',
  'não foi dessa vez. nem da outra. a próxima quem sabe',
  'game over, mas game over é só o começo do joga de novo',
  'perdeu mas aprendeu né? né?',
  'deu ruim. mas eu gosto de você mesmo assim',
  'guardei essa numa pasta chamada coisas pra zoar depois',
  'até o Goku perde de vez em quando',
  'relaxa, amanhã tem outro. daqui a pouco também',
  'bebe uma água e volta mais forte',
  'culpa do lag, eu confirmo pra quem perguntar',
  'pode chorar, mas depois joga de novo',
  'patético KKKKK volta lá',
  'com esse joguinho vai longe não',
  'perdeu igual o Cruzeiro jogando fora de casa',
  'mds, que fase',
  'toda vez a mesma coisa, erro do mesmo jeito. arruma isso aí',
  'tá maluco, perdeu feio',
  'nem o Magikarp perdia desse jeito',
  'essas horas é respirar, ter paciência e tentar de novo',
  'foi quase. quase não conta, mas foi quase',
  'essa doeu até em mim',
  'derrota de time sem postura, bora arrumar isso',
  'o Heat perdeu final em 2020 e em 2023 e segue na luta. volta',
  'coisa ridícula KKKKK de novo aí',
  'perdeu, mas o importante é que eu me diverti',
  'faz parte, todo protagonista tem arco de derrota. o teu tá comprido',
  'respira fundo, pede um pastel e tenta de novo',
  'ih, deu merda. bora de novo',
  'o jogo ganhou essa, mas a revanche é tua',
  'tenho nem nada o que falar não',
  'volta lá antes que eu conte pra todo mundo',
  'elenco pipoqueiro esse seu hein. que isso'
]
};
