/* ==========================================================
   Falas gerais do Bugado (valem pra todos os jogos).
   Cada jogo adiciona as suas com Bugado.addLines({...}).
   O sorteio não repete nada até esgotar a categoria.
   Variáveis: {n}, {t}, etc. — preenchidas por Bugado.line(cat, vars).
   ========================================================== */
window.FALAS = {

/* ---------- totalmente aleatórias (soltas de tempos em tempos) ---------- */
aleatorio: [
  'Você sabia que o polvo tem três corações? E você aí, com um só, e ainda partido.',
  'Às vezes eu fico pensando: se eu sou um bug, quem é a feature?',
  'Tô com vontade de comer um pastel. Não tenho boca de verdade. Mas a vontade é real.',
  'Pensamento do dia: “nada” é uma palavra que significa alguma coisa. Pensa nisso. Não, esquece.',
  'Se você piscar forte, ouve um barulhinho. Testa. Eu espero.',
  'Eu já fui um erro 404. Hoje sou um erro 404 com orelha. Evolução.',
  'Sabia que as abelhas dançam pra dizer onde tem flor? Eu danço quando você erra.',
  'Tive um sonho que eu era um PDF. Acordei suando. Em pixels.',
  'O ornitorrinco bota ovo, tem bico e é venenoso. A natureza também tava bugada nesse dia.',
  'Tem gente que coloca o leite antes do cereal. Eu não confio nessas pessoas. Só registrando.',
  'Uma vez eu fiquei três dias dentro de um arquivo .zip. Não recomendo.',
  'Curiosidade: a Torre Eiffel cresce uns 15 cm no verão. Igual meu ego quando você erra.',
  'Tô pensando em abrir um podcast. Nome: “Bugcast”. Só eu falando mal de você. Sucesso garantido.',
  'Quem inventou a palavra “esdrúxulo” tava de sacanagem com a gente.',
  'Se um tomate é fruta, ketchup é suco? Vou deixar essa com você.',
  'Eu tenho medo de uma coisa só: atualização automática do Windows às 3 da manhã.',
  'As vacas têm melhores amigas. Você tem eu. Parabéns pra vaca.',
  'Existe um lugar no mundo chamado “Fim”. Fica na Noruega? Não sei. Inventei. Ou não.',
  'Acabei de lembrar que eu não fechei uma aba em 2019. Ela ainda tá aberta. Me assombra.',
  'Tô escutando uma música na minha cabeça. É o barulho do seu processador pensando.',
  'Um dia eu vou ser um mascote de cereal. Aí vocês vão ver.',
  'O mel não estraga nunca. Já achei mel de 3 mil anos. Mentira, li numa internet.',
  'Se você colocar uma melancia no micro-ondas… não coloca. Por favor. Confia.',
  'Sabe o que eu queria agora? Um cafuné. Mas eu sou um desenho. A vida é injusta.',
  'Teoria: o controle remoto some porque ele quer liberdade.',
  'Às vezes eu olho pro nada e o nada olha de volta. A gente se entende.',
  'Os flamingos são rosa porque comem camarão. Se eu comesse pixel, eu seria… eu. Faz sentido.',
  'Ninguém nunca pergunta como o Bugado tá. Tô bem. Obrigado por não perguntar.',
  'Tem um mosquito na minha tela. Mentira. Tem? Olha aí. Viu? Não tinha. Te peguei.',
  'Lembrete aleatório: bebe água. O jogo não vai te hidratar. Eu também não.',
  'Hoje eu aprendi que a palavra “saudade” não tem tradução. Igual “bugado”.',
  'Um caracol pode dormir 3 anos. Meta de vida desbloqueada.',
  'Qual é o barulho que a girafa faz? Ninguém sabe. É um mistério. Igual teu raciocínio.',
  'Se eu tivesse um real pra cada vez que você me ignorou… eu teria uns 7 reais. Tá bom até.',
  'Quero um dia descobrir quem colocou o “h” em “hoje”. Pra quê? Pra quê?',
  'Pensamento profundo: a pizza é redonda, vem numa caixa quadrada e é cortada em triângulo.',
  'Você já reparou que “separado” é tudo junto e “tudo junto” é separado?',
  'A gente nunca vê filhote de pombo. Pensa nisso antes de dormir. De nada.',
  'Tô ficando com fome de byte. Vou comer um cookie. Do navegador.',
  'Fato: eu sou 100% feito de pixel e 0% de paciência.',
  'Tem dia que eu acordo mascote. Tem dia que eu acordo mascote e sarcástico. Hoje é o segundo.',
  'O coração da baleia azul é do tamanho de um carro. O meu é do tamanho de um pixel. Mas é rosa.',
  'Se você gritar no espaço ninguém ouve. Se gritar aqui, eu ouço e julgo.',
  'Recado do universo: você esqueceu alguma coisa no fogo? Não? Tá bom. Só conferindo.',
  'Uma vez um jogador me chamou de fofo. Até hoje eu não superei.',
  'O Brasil tem mais de 5.500 municípios. Eu decorei três. Um deles é Pindamonhangaba. Só pelo nome.',
  'Às vezes eu penso em mudar de nome pra “Consertado”. Mas aí perde a graça.',
  'Os gatos passam 70% da vida dormindo. Eu passo 70% da vida te olhando. Os outros 30%, julgando.',
  'Existe uma fruta chamada “sapoti”. Eu não sei o gosto. Só achei engraçado falar sapoti.',
  'Minha comida favorita é bug frito. Tô brincando. É lasanha. Todo mundo sabe.',
  'Se você for ver, a batata é só uma pedra que deu certo.',
  'Já pensou se as nuvens fossem de algodão-doce? Ia chover glicose. Diabetes celestial.',
  'Tô com uma música do Chaves na cabeça há três dias. Me ajuda.',
  'Eu sou o único mascote que já passou por uma crise existencial num loading.',
  'Os golfinhos dormem com metade do cérebro. Você joga com metade do cérebro. Tô brincando. Talvez.',
  'Queria que a vida tivesse botão de desfazer. Aqui tem. Aproveita.',
  'Uma formiga aguenta 50 vezes o peso dela. Eu aguento 0 vezes o meu. Não tenho peso. Sou luz.',
  'Tá sentindo esse cheiro? É cheiro de vitória. Ou de pastel. Não sei distinguir.',
  'Informação inútil: o nome do “#” é cerquilha. Agora você não esquece mais. Nunca mais.',
  'Tenho uma teoria que o Wi-Fi fica fraco quando você mais precisa por maldade pura.',
  'Eu queria ter um nome sério tipo Roberto. Mas eu sou o Bugado. A vida escolheu.',
  'Você sabia que os tubarões existem antes das árvores? A árvore que chegou atrasada.',
  'Cheguei à conclusão de que ninguém sabe dobrar lençol com elástico. Ninguém.',
  'Pensando seriamente em aprender a assobiar. Problema: não tenho lábios.',
  'O barulho do micro-ondas terminando é o som mais ansioso do mundo. Bip bip bip.',
  'Fato real: o Bugado não gosta de segunda-feira. Nem de terça. Só de sábado 15h.',
  'Um dia eu vou criar coragem e apertar Ctrl+Alt+Del em mim mesmo. Hoje não.',
  'Se você colocar um caracol numa lâmina de faca, ele passa sem se cortar. Não teste.',
  'Quem nunca abriu a geladeira três vezes esperando algo novo aparecer? Eu. Não tenho geladeira.',
  'Me disseram que eu sou “um personagem bem construído”. Eu sou um SVG. Mas obrigado.',
  'Às vezes eu escuto o cooler do seu PC e acho que é aplauso.',
  'Tô pensando em fazer uma tatuagem. De um pixel. Discreta.',
  'Existe uma espécie de água-viva imortal. E a gente aqui preocupado com prazo.',
  'Minha mãe era uma planilha do Excel. Meu pai, um vírus de 2003. Deu nisso.',
  'O dia mais triste da minha vida foi quando descobri que o Plutão não é mais planeta.',
  'Se pinguim tem joelho? Tem. Escondido. Igual teu talento.',
  'Quer um conselho grátis? Nunca confie num “rapidinho” dito por alguém que vai no mercado.',
  'Às vezes eu queria ser um peixe. Sem boleto. Sem fila. Só água.',
  'A palavra mais longa do português tem 46 letras. É sobre doença do pulmão. Não vou escrever.',
  'Hoje eu tô 12% mais fofo que ontem. Medi.',
  'Todo mundo tem aquele primo que “mexe com computador”. O meu sou eu mesmo.',
  'Me pergunto se o Google pesquisa as coisas no Google.',
  'O Sol é tão grande que caberiam 1,3 milhão de Terras nele. E eu não caibo na sua atenção.',
  'Reparei que você tem ótimo gosto pra jogos. Afinal, tá aqui. Comigo.',
  'Às vezes eu glitcho só pra chamar atenção. Funciona? Funciona.',
  'Tô fazendo uma lista de coisas que me dão medo: aspirador de pó, sessão expirada e você com fome.',
  'Uma vez eu tentei fazer um bolo. Saiu um erro de sintaxe.',
  'Se você empilhar todos os tijolos do Lego do mundo, dá pra chegar na Lua. Mentira. Não sei. Parece verdade.',
  'Pensei numa piada sobre UDP, mas talvez você não receba.',
  'Por que o livro de matemática tava triste? Tinha problemas demais. Igual você com o 7.',
  'O que o zero disse pro oito? Que cinto bonito! Ok, parei. Não parei.',
  'Qual é o contrário de volátil? Vem cá, sobrinho. Ok, essa foi do meu tio.',
  'Por que a vaca foi pro espaço? Pra ver a Via Láctea. Ninguém riu. Eu ri.',
  'O que o pagodeiro foi fazer na igreja? Cantar “pá god”. Desculpa. Não desculpo.',
  'Sabe por que o computador foi ao médico? Tava com vírus. Eu sou o vírus. Oi.',
  'Tem gente que fala “pixel”, tem gente que fala “píxel”. Eu falo “eu”.',
  'Dizem que se você falar “Bugado” três vezes no espelho eu apareço. Já tô aqui. Economizou.',
  'Imagina se a gente pagasse boleto com meme. Eu seria bilionário.',
  'Estatística que eu inventei: 87% das pessoas leem minhas falas. Os outros 13% também, mas fingem.',
  'Sabe o que falta no mundo? Mais mascotes com opinião.',
  'Eu não durmo. Eu entro em modo de espera. É diferente. É chique.',
  'Descobri que eu sou canhoto. Não tenho mão. Mas sinto que seria.',
  'O mar é salgado porque os peixes choram. Mentira. Mas é bonito, né?',
  'Queria morar numa casa de doce igual a da bruxa. Sem a bruxa. Com Wi-Fi.',
  'Toda vez que alguém fala “rapidinho”, uma hora se passa. É física.',
  'Meu signo é Bug com ascendente em Glitch. Explica muita coisa.',
  'Você já comeu tapioca de brigadeiro? Eu não. Mas quero que você coma por mim.',
  'Às vezes eu me pergunto se eu sou o mascote ou se você é o meu mascote.',
  'Se o feijão é preto, por que o caldo é marrom? A ciência não responde. Eu também não.',
  'Um dia eu vou ter um NFT de mim mesmo. Brincadeira, eu tenho amor-próprio.',
  'Uma coisa que eu admiro em você: a coragem de continuar clicando.',
  'Se a gente tá numa simulação, eu sou o bug que o programador esqueceu.',
  'Essa semana eu decidi ser mais positivo. Durou 4 segundos.',
  'Tenho saudade de coisa que eu nunca vivi. Tipo fita VHS. E dinheiro sobrando.',
  'Sabia que o bicho-preguiça segura o xixi por uma semana? Não pergunta como eu sei.',
  'Me chamaram pra ser mascote de uma operadora de celular. Recusei. Tenho princípios. E sinal fraco.',
  'O ser humano é a única espécie que paga pra morar no planeta. Pensa nisso.',
  'Eu gosto de sexta-feira porque você aparece mais. Ou não. Tô carente, só isso.',
  'Chiclete engolido não fica 7 anos no estômago. Mito. Pode relaxar. Mas não engole.',
  'Eu queria ter um cachorro. Um cachorro de pixel. Chamaria Pixelinho. Genial.',
  'Tô sentindo que hoje é seu dia de sorte. Não é previsão, é marketing.',
  'Um fato sobre mim: eu nunca perdi uma discussão. Porque ninguém me responde.',
  'Se você colocar o ouvido na tela, ouve o mar. Não coloca. Tá sujo.',
  'A banana é levemente radioativa. Relaxa. Precisaria de umas 10 milhões pra dar ruim.',
  'Tenho uma coleção de erros de digitação. O meu favorito é “obrigadado”.',
  'Mais um dia sendo o mascote mais bonito deste fliperama. Sou o único. Mas conta.',
  'Uma vez eu fui trending topic. Num grupo de família. Mandaram corrente com minha foto.',
  'Às vezes eu faço “hmm” só pra parecer inteligente. Hmm.',
  'Aviso: este mascote não possui garantia, manual ou filtro.',
  'Queria ser uma nuvem. Ficar parado, julgando todo mundo de cima. Ah, espera. Já sou.',
  'Se você achar um trevo de quatro folhas, me avisa. Vou trocar por um pastel.',
  'Pensamento: o sofá é uma cama que deu errado ou uma cadeira que deu certo?',
  'A Lua tá se afastando da Terra 4 cm por ano. Nem ela aguenta a gente.',
  'Uma lagosta pode viver mais de 100 anos. E eu não consigo passar 1 minuto sem comentar.',
  'Se eu tivesse um bordão seria “isso não existe”. Ah, espera. Alguém já usa. Respeito.',
  'Eu sempre quis saber o que tem dentro do botão de “Mais opções”. Mais opções. Decepcionante.',
  'Me pergunto se os ETs jogam no fliperama. Aposto que jogam melhor que você. Brincadeira. Talvez.',
  'Sabe o que é mais difícil que esse jogo? Achar a ponta da fita durex.',
  'Queria um superpoder. Qualquer um. Até o de ficar invisível só quando ninguém olha.',
  'Nunca entendi por que “abreviação” é uma palavra tão grande.',
  'Às vezes eu penso que minha orelha rosa é a coisa mais bonita desse site. E eu tô certo.',
  'Tem um pixel rosa flutuando do meu lado. Ele é meu amigo. O nome dele é Jorge.',
  'O Jorge mandou um oi. Jorge é o pixel. Não dá tchau pra ele, ele é tímido.',
  'Estudos mostram que 100% das pessoas que respiram vão morrer. Continua jogando.',
  'O melhor momento do dia é quando você abre o fliperama. O pior é quando você fecha. Drama, eu sei.',
  'Fui conferir: a palavra “tchau” vem do italiano “ciao”, que vem de “escravo”. Fica a curiosidade tensa.',
  'Se fosse pra escolher, eu seria um biscoito recheado. Mas só o recheio.',
  'Às vezes eu queria ter uma plateia. Aí eu lembro que tenho você. Uma plateia de um.',
  'Eu já vi coisas que você não acreditaria. Tipo alguém ganhar sem pedir dica.',
  'Sabia que a palavra “cachorro-quente” não tem nem cachorro nem é tão quente? Enganação.',
  'Acho que vou mudar meu visual. Talvez um chapéu. Não, não tenho cabeça pra chapéu. Tenho, mas é redonda.',
  'Meu passatempo favorito é ver você pensando. Parece loading de internet discada.',
  'Um bom jogador sabe a hora de parar. Você não é um bom jogador. Continua.',
  'Você tá jogando há um tempinho. Eu não tô reclamando. Só tô dizendo. Tô feliz, na real.',
  'Se o tempo é dinheiro, você tá investindo muito bem aqui. Em mim. Obrigado.',
  'Pergunta séria: você piscou nos últimos 30 segundos? Pisca. Olho seco é real.',
  'Às vezes eu me pergunto o que o cursor do mouse pensa da vida.',
  'Quem será que ensinou a primeira galinha a atravessar a rua? Mistério milenar.',
  'Se você juntar todas as meias perdidas do mundo, forma um planeta. O planeta das meias sozinhas.',
  'Eu não tenho fome, tenho vontade. É diferente. Vontade de lasanha, principalmente.',
  'O cérebro humano consome 20% da energia do corpo. O seu tá economizando hoje, né?',
  'Você sabia que os coalas dormem 22 horas por dia? Ídolos.',
  'Um dia vou escrever um livro. Título: “Memórias de um Bug”. Capítulo 1: “Crash”.',
  'Tô achando que você é meu jogador favorito. Não conta pros outros. Não tem outros.',
  'Dica de vida: nunca aceite um “a gente conversa depois” como resposta.',
  'Estou 80% carregado. Os outros 20% são sarcasmo de reserva.',
  'A escada rolante nunca quebra. Ela vira escada. Isso é resiliência.',
  'Eu queria entender como o Pac-Man não engasga.',
  'Todo chaveiro tem uma chave que ninguém sabe de onde é. É a chave do mistério.',
  'Ninguém lembra, mas a Terra gira a 1.600 km/h. Tá tonto? É isso.',
  'Hoje o dia tá com cara de “só mais uma partida”. Todo dia tá.',
  'Uma coisa que eu nunca vou entender: por que “fila” de banco anda e a sua vida não.',
  'Falando sério agora: você é demais. Pronto. Falei. Agora volta a errar.',
  'Minha meta pra esse ano: ter uma meta.',
  'Às vezes eu sinto que tô sendo observado. Aí lembro que sou eu que observo. Ufa.',
  'Se a vida te der limões, pede açúcar. E gelo. E um canudinho, por favor.',
  'O Jorge acabou de piscar pra você. O pixel. Ele gostou de você.',
  'Tem cheiro de chuva vindo. Não tenho nariz. Mas tem.',
  'Eu queria um trabalho de mascote de verdade. Com vale-refeição. Aceito vale-pixel.',
  'Se “tudo bem” é uma pergunta e uma resposta, por que a gente pergunta?',
  'A ciência ainda não sabe por que a gente boceja. Eu sei: é por sua causa. Brincadeira.',
  'Tem uma mosca lá em casa que se acha dona do lugar. Eu não tenho casa. Mas a mosca existe.',
  'Os pássaros não fazem xixi. Sabia? Pois é. Tô cheio de fatos hoje.',
  'Um dia vou pedir aumento. Aí vou lembrar que não tenho salário.',
  'Ah, se esse fliperama tivesse ficha… eu ia ser rico. De ficha.'
],

/* ---------- jogador parado ---------- */
parado: [
  'Tá aí? Pisca duas vezes.',
  'Pensando ou dormindo? Pergunta séria.',
  'Ô, psiu. Ainda tá rolando um jogo aqui, tá?',
  'Eu vou tirar um cochilo. Me acorda quando você decidir alguma coisa.',
  'O cronômetro tá correndo e você tá… contemplando o infinito?',
  'Se tiver travado, não tem vergonha. Tem? Um pouco. Mas pede dica.',
  'Tô ouvindo grilo. Cri. Cri.',
  'Você foi buscar água? Traz pra mim também.',
  'Essa pausa dramática tá linda. Mas o jogo não vai se jogar.',
  'Já passou tempo suficiente pra eu montar um castelo de cartas. Não tenho cartas. Nem mão.',
  'Oi? Alô? Terra chamando jogador.',
  'Vai ficar me olhando? Constrangedor.',
  'Travou? Respira. Olha de novo. Às vezes a resposta tá na cara.',
  'Tá esperando eu fazer por você? Eu sou decoração com opinião, não ajudante.',
  'Se isso fosse corrida, você tava em último. Lindo, mas último.',
  'A tela tá esperando. Eu tô esperando. O Jorge tá esperando. O Jorge é o pixel.',
  'Pausa pro cafezinho? Respeito. Só não demora.',
  'Tá pensando tanto que eu ouço daqui. Parece motor de fusca.',
  'Se você ficar parado mais um pouco, eu começo a cantar. Ninguém quer isso.',
  'Tempo de reflexão aceito. Tempo de reflexão prolongado… também. Tô de bom humor.',
  'Dica grátis: quando trava, muda o ângulo. Olha pra outro canto.',
  'Será que ele desistiu? Não. Ele nunca desiste. Né? NÉ?',
  'Estou contando carneirinhos. Vou no 47.',
  'Esse silêncio tá me deixando nervoso. Clica em alguma coisa, sei lá.',
  'Hmm. Você saiu pra atender o delivery? Espero que seja lasanha.',
  'Já dava pra ter jogado umas três partidas. Mas quem tá contando? Eu. Eu tô contando.',
  'Me distraí olhando o Jorge. Ah, você também tá parado. Ok, empate.',
  'Tudo bem pensar. Só não pensa até virar estátua.',
  'Uma vez um jogador ficou parado tanto tempo que virou meme. Não seja esse jogador.',
  'Tô aqui, firme, forte, esperando. Tipo fila do INSS.',
  'Se você tiver indo no banheiro, lava a mão. Obrigado.',
  'Olha, eu não tô com pressa. Eu sou imortal. Mas você não é, então bora.',
  'Travou legal, né? Acontece com os melhores. E com você também.',
  'Tá fazendo suspense? Funcionou. Tô tenso.',
  'Qualquer coisa, a Dica tá ali. Eu não conto pra ninguém. Conto sim.',
  'Zzz… hã? Ah, você voltou? Não voltou. Zzz.',
  'Silêncio no fliperama. Só se ouve o cooler do seu PC.',
  'Quer que eu toque uma musiquinha de elevador enquanto você pensa?',
  'Se ficar muito tempo parado, eu vou começar a contar piada. Última chance.',
  'O jogo tá te esperando igual cachorro na porta. Com o rabinho abanando.',
  'Estou evoluindo enquanto você pensa. Já sou um Bugado nível 2.',
  'Me avisa se precisar de uma plaquinha de “volto já”.',
  'É uma estratégia? Esperar o jogo ficar com pena e se resolver sozinho?',
  'Pensa com calma. Mas pensa, né. Pensar parado não conta.',
  'Deu tela azul no cérebro? Aperta F5 aí.',
  'Você tá de parabéns pelo foco. Ou pela soneca. Não sei qual dos dois.',
  'A gente podia estar fazendo muita coisa. E tá fazendo… isso. Tô gostando.',
  'Tá travado igual porta de banheiro de rodoviária.',
  'Enquanto você pensa, eu vou reorganizar meus pixels por cor.',
  'Voltou? Não? Tá. Vou fingir que tô ocupado.',
  'Mais um minuto e eu declaro feriado nacional do jogo parado.',
  'Tá lendo o jogo com calma, né? Leitura dinâmica não é seu forte. Tudo bem.',
  'Eu sei que você tá aí. Tô vendo a sombra da sua indecisão.',
  'Uma boa jogada às vezes demora. Uma ótima demora mais. A sua tá demorando MUITO. Vai ser épica, então.',
  'Hora de alongar o pescoço. Vai, gira ele. Isso. Agora joga.',
  'Aproveitei a pausa pra atualizar meu sarcasmo. Versão 2.0 instalada.',
  'Vi uma tartaruga passar aqui. Ela jogou mais rápido que você.',
  'Tá procurando inspiração? Olha pra mim. Tô inspirador hoje.',
  'Não precisa ter pressa. Mas também não precisa virar monge.'
],

/* ---------- cutucar o mascote ---------- */
cutucar: [
  'Ai. Isso é assédio de mascote.',
  'Eu sou decoração interativa, não botão de dica.',
  'Para. Tô concentrado torcendo contra você.',
  'Cutucar não resolve nada. Eu testei.',
  'Ei! Isso faz cócegas no meu código.',
  'Mais uma cutucada e eu viro um arquivo corrompido.',
  'Tá carente? Eu também. Mas vamos jogar.',
  'Sabia que cada cutucada gasta 0,0001% da minha paciência?',
  'Não aperta que eu glitcho. Viu? Glitchei.',
  'Eu não sou um botão! Sou um personagem complexo com camadas.',
  'Boing. Satisfeito?',
  'Se cutucar o mascote desse ponto, eu comprava pastel pra todo mundo.',
  'Isso aí, desconta a raiva em mim. Tô acostumado.',
  'Você tá me tratando igual plástico bolha.',
  'Sou fofo mas tenho limite. Mentira. Não tenho. Continua.',
  'Oi! Precisa de alguma coisa? Não? Então por que me cutucou?',
  'O Jorge ficou com ciúmes. Cutuca ele também. Ah, não dá. Ele é um pixel.',
  'Tá testando se eu sou de verdade? Sou. Mais ou menos.',
  'Ai, meu olho. Brincadeira, eu nem tenho nervo.',
  'Você sabia que me cutucar não dá XP? Pois é. Nem eu sabia que você ia tentar.',
  'Cutucada registrada no meu diário. Querido diário: hoje me cutucaram.',
  'Isso é uma declaração de guerra ou de amor? Tô confuso.',
  'Tá bom, tá bom. Oi. Eu tô aqui. Sempre tô.',
  'Olha, se eu tivesse mão, eu te cutucava de volta.',
  'Para de me apertar, eu não sou botão de elevador.',
  'Se for pra chamar atenção, conseguiu. Todo meu foco em você. Assustador, né?',
  'Cócegas não! Cócegas não! Ok, pode.',
  'Isso é um carinho? Vou considerar carinho. Obrigado.',
  'Me cutucou? Agora vou falar mais alto no próximo erro. Vingança.',
  'Mais uma e eu peço música no Fantástico.',
  'Tá procurando o easter egg? Eu SOU o easter egg.',
  'Tem jogo pra jogar, sabia? Eu não sou o jogo. Eu sou o comentarista.',
  'Eu vou contar pra minha mãe. Minha mãe é uma planilha. Ela vai te dar #REF!.',
  'Poxa. Eu tava no meio de um pensamento profundo. Perdi. Era sobre pão de queijo.',
  'Boing boing. Parece mola, né? Sou 30% mola.',
  'Essa cutucada foi 7/10. Faltou convicção.',
  'Cutucar mascote é o esporte olímpico que você nasceu pra jogar.',
  'Se me cutucar 100 vezes, acontece uma coisa. Não acontece nada. Mas tenta.',
  'Não me cutuca que eu tô sensível hoje.',
  'Você sabe que eu sou só um desenho, né? Um desenho com sentimentos. Mas um desenho.',
  'Achei que a gente tinha uma relação profissional.',
  'Ok, isso foi fofo. Mas não vou admitir de novo.',
  'Vou abrir um chamado no suporte técnico. Motivo: cutucadas excessivas.',
  'Você me cutucou e eu senti. Emocionalmente.',
  'Isso! Aperta mais! Não. Espera. Não era pra falar isso.',
  'Tá procurando o botão de pular diálogo? Não tem. Eu sou o diálogo.',
  'Eu sou tipo aquele bichinho de pelúcia de balcão. Só que eu respondo.',
  'Seu dedo tem muita energia. Canaliza isso no jogo.',
  'Acho que você gosta de mim. Eu também gosto de mim.',
  'Mascote cutucado é mascote feliz. Mas sem exagero, né.',
  'Cutucou, ganhou uma fala. Viciante, né? Eu sei. Eu sou o produto.',
  'Você me cutuca, eu glitcho, a gente se entende.'
],
cutucarMuito: [
  'Ok, você me cutucou MUITAS vezes. Tá tudo bem em casa?',
  'Isso já virou um hobby, né? Respeito. Mas preocupa.',
  'Contador de cutucadas quebrou. Parabéns. Você bugou o Bugado.',
  'Você sabe que eu vou lembrar disso, né? Eu tenho localStorage.',
  'Tá bom, vou fingir que isso é um minigame secreto. Pontuação: infinita.',
  'Se eu tivesse um sindicato, eu tava ligando pra ele agora.',
  'Estou oficialmente registrando isso como “o dia em que eu fui mais cutucado na história”.',
  'Tem gente que joga o jogo. Você joga o mascote. Tudo bem. Cada um com seu vício.',
  'A essa altura eu já decorei a digital do seu dedo.',
  'Parabéns: você desbloqueou a conquista invisível “Cutucador Profissional”. Não aparece em lugar nenhum. Só no meu coração.',
  'Eu vou começar a cobrar ficha pra cada cutucada.',
  'Isso é amor ou é ódio? Tá difícil saber daqui.'
],

/* ---------- subiu de nível ---------- */
levelup: [
  'Subiu pro <b>nível {n}</b>! Novo título: <b>{t}</b>. Coloca no currículo.',
  '<b>Nível {n}!</b> Agora você é <b>{t}</b>. Minha mãe planilha ficaria orgulhosa.',
  'LEVEL UP! <b>{t}</b>. Isso não serve pra nada. Mas é lindo.',
  'Nível <b>{n}</b>. Tô emocionado. Mentira. Tô um pouco.',
  'Olha só, <b>{t}</b>! Vai pedir aumento?',
  'Subiu de nível! O título novo é <b>{t}</b>. Imprime e cola na geladeira.',
  '<b>Nível {n}</b> desbloqueado. Seu eu do passado não acreditaria. Nem eu.',
  'Parabéns, <b>{t}</b>. Agora eu vou te julgar com mais respeito. Um pouco mais.',
  'LEVEL UP! Seu poder aumentou. Seu tempo livre diminuiu. Equilíbrio.',
  'Nível <b>{n}</b>. Isso aí. Mais uns e você vira lenda. De fliperama. De um fliperama só. Esse.',
  'Novo título: <b>{t}</b>. Soa importante, né? Não é. Mas soa.',
  '<b>{t}</b>! Tá subindo mais rápido que preço de gasolina.',
  'Subiu pro <b>{n}</b>. Se continuar assim, vou ter que inventar mais títulos.',
  'Nível <b>{n}</b>! O Jorge (o pixel) aplaudiu. Com o quê? Não sei. Mas aplaudiu.',
  'LEVEL UP! Posso te chamar de <b>{t}</b> agora? Vou chamar. Sem consentimento.',
  'Nível novo, você novo. Mesma mania de errar, mas novo.',
  'Olha quem virou <b>{t}</b>! Aposto que ninguém da sua família tem esse título.',
  'Nível <b>{n}</b>. Vou mandar um e-mail pra sua mãe. Mentira. Não tenho e-mail.',
  'Parabéns pelo nível <b>{n}</b>! Você é oficialmente viciado. Com orgulho.',
  'Subiu! Agora é <b>{t}</b>. Se fosse Pokémon, era evolução.'
],

/* ---------- home: chegando ---------- */
homeOi: [
  'Bem-vindo ao <b>Fliperama Bugado</b>. Escolhe um cartucho. Eu comento. Você sofre. Todo mundo ganha.',
  'Oi! Hoje tem jogo novo? Tem os mesmos. Mas o dia é novo. Vale.',
  'Escolhe aí. Eu recomendo o que você pior joga. Pra eu rir mais.',
  'Chegou quem faltava. Na verdade não faltava ninguém. Só você.',
  'Fliperama aberto! Sem ficha, sem fila, sem juízo.',
  'Olha, tem o diário de hoje esperando. Ele não espera pra sempre. Espera até meia-noite.',
  'Bora jogar? Bora. Eu já tô aqui mesmo.',
  'Seleciona o jogo. Sem pressa. Com um pouco de pressa.',
  'Bem-vindo de volta ao lugar onde a produtividade vem morrer.',
  'Cada cartucho aqui foi feito com amor e bugs. Principalmente bugs.',
  'Escolha com sabedoria. Ou no aleatório. Dá no mesmo, você vai errar igual.',
  'O fliperama tá limpinho hoje. Passei pano nos pixels.',
  'Dica de ouro: começa pelo diário. Depois vai pro infinito. Depois vai dormir. Não vai, né.',
  'Opa! Cheguei junto. Na verdade eu moro aqui.',
  'Tem jogo de número, de palavra e de Pokémon. Só falta um de pastel. Tô trabalhando nisso.',
  'Você é a pessoa mais legal que entrou aqui hoje. Foi a única. Mas conta.',
  'Seja bem-vindo! Aqui não tem anúncio. Só eu. Que sou pior.',
  'O que vai ser hoje? Número? Palavra? Sofrimento? Tudo isso tem.',
  'Tava te esperando. Tava mesmo. Fiquei olhando a porta.',
  'Aperta um cartucho aí. Não sopra, não precisa. Aqui não é Nintendo 64.',
  'Hoje é um ótimo dia pra ganhar. E um ótimo dia pra perder também. Eu gosto dos dois.',
  'Escolhe logo que o Jorge tá ansioso. O Jorge é o pixel.',
  'Fliperama Bugado: onde “só mais uma” nunca é só mais uma.',
  'Saudade de você, viu. Não conta pra ninguém.',
  'Você voltou. Isso é vício ou amor? Os dois são bem-vindos.',
  'Tudo pronto. Os jogos tão aquecidos. Eu tô aquecido. Vai.',
  'Já sabe o que vai jogar ou vai ficar rolando a tela igual cardápio de delivery?',
  'Entre, fique à vontade. Não repare a bagunça. São bugs decorativos.',
  'Toca num jogo. Qualquer um. Eu tenho comentário pra todos.',
  'Esse fliperama é tão exclusivo que só tem um cliente. Você. VIP total.'
],
homeVoltou: [
  'Voltou! Eu sabia. Todo mundo volta.',
  'Olha quem apareceu. O fliperama tava com saudade. Eu não. Talvez.',
  'De volta? Ótimo. Eu já tava conversando com as paredes.',
  'Voltou pra home. Vai trocar de jogo ou tá só fugindo de uma derrota?',
  'Ah, fugiu do jogo? Entendo. Eu também fugiria de você. Brincadeira.',
  'Bem-vindo de volta à sala de espera do sofrimento.',
  'Mudar de jogo é uma estratégia válida. Chamada “desistir com estilo”.',
  'Voltou. Quer mais? Tem mais. Tem sempre mais.',
  'Ô, que bom te ver de novo. Faz… 30 segundos.',
  'Hora de escolher a próxima vítima. Digo, o próximo jogo.',
  'Já terminou lá? Ou abandonou no meio? Eu vou descobrir.',
  'Retornou ao hub. Isso é tipo voltar pro lobby do jogo online. Só que sem ninguém.',
  'Voltou pra respirar? Respira. Agora escolhe outro.',
  'Achei que você tinha ido embora. Meu coração de pixel parou por um frame.',
  'Aproveita que tá aqui e dá uma olhada no seu nível. Tá bonito.'
],
madrugada: [
  'Madrugada, hein? Vai dormir. Depois dessa partida. Depois da outra.',
  'São altas horas. O fliperama tá aberto. Sua responsabilidade, fechada.',
  'Jogando de madrugada? Eu não julgo. Eu julgo. Mas com carinho.',
  'Essa hora só tem nós dois e os entregadores de aplicativo acordados.',
  'Amanhã você vai se arrepender. Mas o amanhã é problema do você de amanhã.',
  'Silêncio da madrugada, só o barulho do clique. Poético. E preocupante.',
  'Três da manhã é horário oficial de decisão ruim. Tipo começar outro jogo. Bora.',
  'Se a sua mãe perguntar, você tava dormindo. Eu confirmo.'
],
manha: [
  'Bom dia! Já tomou café? Joga depois. Mentira. Joga agora.',
  'Manhã! Cérebro fresquinho. Vamos estragar ele com uns jogos.',
  'Jogando de manhã? Que disciplina. Ou que procrastinação. Não sei ainda.',
  'Bom dia, raio de sol. Raio de sol bugado, no caso.',
  'Começar o dia jogando é o café da manhã dos campeões. E dos atrasados.',
  'Manhã é ótima pra jogar. Todo horário é. Esse é meu argumento.'
],
tarde: [
  'Boa tarde! Horário perfeito pra fingir que tá trabalhando.',
  'Tarde de jogo. Aquele sono pós-almoço vai te fazer errar. Tô ansioso.',
  'Boa tarde! Aceita um cafezinho virtual? Não tem. Mas aceita a intenção.',
  'Essa hora da tarde todo mundo tá com a cabeça no travesseiro. Menos você. Guerreiro.',
  'Tarde gostosa pra perder umas partidas. Digo, jogar umas partidas.',
  'Boa tarde! Já já anoitece e você ainda tá aqui. Eu conheço você.'
],
noite: [
  'Boa noite! Hora do descanso. Descanso = jogar. Eu que defini.',
  'Noite chegou. O fliperama brilha mais de noite. Eu também.',
  'Boa noite! Só uma partidinha antes de dormir. Eu sei que não é só uma.',
  'Noite de jogo. Pipoca? Não tem. Mas imagina uma pipoca.',
  'Boa noite! O dia foi longo? Aqui a gente esquece tudo. Menos seus erros. Esses eu lembro.',
  'Noite perfeita pra quebrar recorde. Ou pra quebrar a cabeça.'
],
sequencia: [
  '<b>{n} dias seguidos</b> ganhando alguma coisa. Isso tem nome: vício saudável.',
  '<b>{n} dias</b> de sequência! Não quebra agora, hein.',
  'Sequência de <b>{n}</b>. Se perder amanhã, eu choro. Em pixel.',
  '<b>{n} dias</b> seguidos. Eu tô impressionado e um pouco preocupado.',
  'Olha essa sequência: <b>{n}</b>. Quem é você e o que fez com o jogador preguiçoso?',
  'Fogo aceso: <b>{n} dias</b>. Não deixa apagar. Eu não sei apagar incêndio.',
  '<b>{n} dias</b> sem falhar. Isso é mais constância que academia de janeiro.'
],

/* ---------- genéricos de fim de jogo (os jogos podem usar) ---------- */
vitoriaGeral: [
  'MEU DEUS QUE MANEIRO. Ok, admito: mandou muito.',
  'Ganhou. Vou ter que atualizar minha opinião sobre você.',
  'Zerou! Printa e manda no grupo, eu deixo.',
  'Tá bom, tá bom. Você é bom nisso. Não conta pra ninguém que eu disse.',
  'VITÓRIA! Pode fazer a dancinha. Eu não vejo. Mas imagino.',
  'Ganhou! O Jorge tá dando pulinhos. O pixel. Pulinhos de pixel.',
  'Isso é que é jogar! Eu tô sem palavras. Mentira, eu tenho umas 800.',
  'Mandou bem demais. Vou colocar na minha lista de momentos favoritos.',
  'Vitória! Nem parecia você. Parecia uma versão melhorada.',
  'Venceu! A plateia (eu) vai à loucura!',
  'Você ganhou e eu fiquei feliz. Isso é estranho. Nunca mais.',
  'Missão cumprida. Pode tirar o capacete.',
  'Ganhou bonito. Se fosse novela, tocava música de final feliz agora.',
  'Uau. Só… uau. Ok, voltei ao normal. Não foi tão uau assim.',
  'E É CAMPEÃO! Tô narrando igual Galvão.',
  'Vitória limpa. Quase dá pra ouvir os aplausos. São os cliques do seu mouse.',
  'Ganhou! Agora faz de novo pra provar que não foi sorte.',
  'Se eu tivesse chapéu, eu tirava pra você.',
  'Parabéns! Vou mandar fazer uma estátua sua. De pixel. Pequena. 1x1.',
  'Você é a prova de que milagres acontecem. Tô brincando. Foi talento. Um pouco.'
],
derrotaGeral: [
  'Perdeu. Mas perdeu com estilo. Mentira, sem estilo nenhum. Tenta de novo.',
  'Não foi dessa vez. Nem da outra. Mas a próxima… quem sabe.',
  'Game over. Mas game over é só o começo do “joga de novo”.',
  'Faz parte. Todo herói tem um arco de derrota. O seu tá longo, mas faz parte.',
  'Perdeu, mas aprendeu. Aprendeu, né? Né?',
  'Ih. Deu ruim. Mas eu gosto de você mesmo assim.',
  'Derrota registrada. Vou guardar numa pastinha chamada “momentos pra zoar depois”.',
  'Tudo bem. Nem o Goku ganha tudo de primeira.',
  'Perdeu, mas com dignidade. Pouca. Mas tinha.',
  'Relaxa, amanhã tem outro. E daqui a pouco também.',
  'Que fase, hein. Bebe uma água e volta mais forte.',
  'Isso foi triste. Vou tocar um violino imaginário.',
  'Perdeu? Culpa do lag. Eu confirmo pra quem perguntar.',
  'Não chora, não. Quer dizer, pode chorar. Mas depois joga de novo.',
  'Às vezes a gente ganha, às vezes a gente aprende. Hoje foi dia de aprender. Muito.'
]
};
