/* ==========================================================
   Falas do Bugado na Forca Bugada.
   Aqui o mascote está sendo apagado pedaço por pedaço a cada erro.
   Variáveis: {letra}, {n}, {palavra}, {tema}, {parte}, {cat}, {i}
   O sorteio (Bugado.line) só repete depois de esgotar a categoria.
   ========================================================== */
window.FALAS_FORCA = {

/* ---------- chegada ---------- */
forcaOiDiario: [
  "Desafio do dia: cinco palavras, uma de cada canto do Fliperama. E eu, inteiro. Por enquanto.",
  "Bem-vindo à Forca Bugada. Aqui não tem bonequinho de palito. Tem eu. E eu tenho medo.",
  "Regra simples: cada letra errada apaga um pedaço de mim. Sem pressão. Muita pressão.",
  "Cinco palavras hoje. Eu tenho duas orelhas, dois olhos, uma boca e um Jorge. Faz a conta.",
  "Chegou o Desafio do Dia. Mesmas palavras pra todo mundo. Se todo mundo acertar e você não… complicado.",
  "Hoje eu acordei com todos os pixels no lugar. Vamos tentar manter assim, combinado?",
  "Antes de começar: eu fiz backup de mim mesmo? Não fiz. Então capricha.",
  "Forca do dia na mesa. Eu sou a forca. E o enforcado. É um cargo acumulado.",
  "Cinco rodadas. Se acertar três, conta vitória. Se errar tudo, eu viro tela azul cinco vezes. Recorde pessoal.",
  "Seja bem-vindo ao único jogo onde o mascote é a barra de vida. Eu. Eu sou a barra de vida."
],
forcaOiInfinito: [
  "Modo Infinito em {cat}. Palavra atrás de palavra até você me destruir. Ou não.",
  "Infinito ligado. Categoria: {cat}. Vou contar tua sequência e jogar na tua cara depois.",
  "Aqui não acaba nunca. Diferente da minha paciência, que acaba já já.",
  "Infinito em {cat}. Cada acerto soma na sequência. Cada erro soma no meu trauma.",
  "Treino sem fim, {cat}. Eu me regenero a cada palavra. Minha dignidade não.",
  "Bora de {cat}. Faz sequência de cinco que eu te dou vitória. Sou generoso quando tô inteiro.",
  "Modo Infinito: tipo academia, só que o músculo é o dicionário e quem sofre sou eu.",
  "{cat} infinito. Pode jogar até o sol nascer. Já vi gente fazer isso. Era você, provavelmente."
],
forcaVoltou: [
  "Voltou! Tua palavra tá aqui do jeitinho que você deixou. Eu também, meio quebrado.",
  "Ah, é você. Eu fiquei aqui esperando com a orelha que me sobrou.",
  "Salvei tudo: letras, erros e o meu rancor.",
  "Olha quem voltou pra terminar o serviço. Literalmente me terminar, talvez.",
  "Achei que você tinha fugido de vergonha. Bem-vindo de volta à cena do crime.",
  "Voltou! Enquanto você tava fora eu tentei me consertar sozinho. Não consegui.",
  "A palavra não fugiu. Eu tentei, mas tô preso nessa forca.",
  "De volta ao jogo. Respira, olha as letras que faltam e, por favor, não chuta W."
],

/* ---------- começo de rodada por categoria ---------- */
forcaInicioConexo: [
  "Palavra do Conexo. Dica: “{tema}”. Mais fácil que isso, só se eu soletrasse.",
  "Veio do Conexo, do grupo “{tema}”. Lembra dos quatro? Pois é uma delas.",
  "Tema: “{tema}”. Quem jogou Conexo tá com vantagem. Quem não jogou tá com medo.",
  "Roubei uma palavra lá do Conexo. O grupo era “{tema}”. Não conta pra ninguém.",
  "Dica da vez: “{tema}”. Se você errar a primeira letra, eu já começo a suar.",
  "“{tema}”. Pensa em quatro coisas desse grupo. Uma delas é a certa. As outras três são distração.",
  "Olha que dica generosa: “{tema}”. Eu não sou sempre assim. Aproveita.",
  "Grupo do Conexo: “{tema}”. Não precisa acertar a conexão, só a palavra. Moleza. Acho.",
  "A palavra mora no grupo “{tema}”. É vizinha de outras três. Todas fofoqueiras.",
  "Tema: “{tema}”. Se isso não ajudar, nada ajuda. Nem reza.",
  "Palavra conexa: “{tema}”. Começa pelas vogais, confia no pai.",
  "Dica: “{tema}”. Minhas orelhas estão confiantes em você. Meio confiantes. Um terço.",
  "Trouxe do Conexo com carinho: “{tema}”. Não me devolve em pedaços, por favor.",
  "Grupo “{tema}”. Se você chutar Y logo de cara, eu vou chorar pixel."
],
forcaInicioPokemon: [
  "Quem é esse Pokémon? {tema}. E não, não vale gritar Pikachu pra tudo.",
  "Pokémon da vez: {tema}. Tem mais de mil. Boa sorte. Sério.",
  "Olha a dica: {tema}. Nome de Pokémon é cheio de K e Y, então hoje o Y pode até ser amigo.",
  "{tema}. Se você for da primeira geração só, pode começar a rezar.",
  "Pokémon misterioso: {tema}. Lembra que nome de Pokémon é em inglês, viu? Nada de acento salvador.",
  "Tá na Pokédex: {tema}. Eu sei qual é. Você vai saber quando eu estiver sem orelha.",
  "{tema}. Dica extra: é um Pokémon. Dica de graça, anota aí.",
  "Hora do “quem é esse Pokémon” versão forca. {tema}.",
  "Pokémon sorteado. {tema}. Sim, pode ter Z, X e K. É o único lugar onde eu permito.",
  "Tipo e geração na mão: {tema}. O resto é contigo e com a tua infância.",
  "{tema}. Se acertar, eu te mostro a arte oficial. Se errar, eu mostro também, pra doer.",
  "Esse Pokémon é {tema}. Eu não vou dizer se ele é fofo. Ele é fofo. Ou assustador. Um dos dois."
],
forcaInicioDB: [
  "Personagem de Dragon Ball. Raça: {tema}. O nível de poder da tua memória é mais de 8000?",
  "Guerreiro misterioso, {tema}. Se errar três letras eu libero uma descrição. Eu sou bonzinho assim.",
  "Dragon Ball! {tema}. Grita alto enquanto chuta que ajuda. Não ajuda.",
  "Dica: {tema}. Com três erros eu conto uma fofoca sobre ele. Mas aí eu já vou estar sem orelha.",
  "Quem é esse guerreiro? {tema}. Nome da dublagem brasileira, tá?",
  "{tema}. Eu juntei as sete esferas só pra pedir que você acerte essa. Não me faz gastar à toa.",
  "Personagem de Dragon Ball, {tema}. Não é o Goku. Talvez seja o Goku. Nunca se sabe.",
  "Dragon Ball da vez: {tema}. Se precisar, carrega um Genki Dama de letras.",
  "Tem guerreiro escondido aqui. {tema}. Três erros e eu solto a ficha dele.",
  "{tema}. Treinou na Sala do Tempo? Então essa é tua.",
  "Hora de lembrar dos episódios de fim de tarde. {tema}.",
  "Personagem sorteado: {tema}. Pode ter número no nome, e esse eu já mostro de graça."
],
forcaInicioCoisas: [
  "Uma coisa qualquer do dia a dia. Começa com {tema}. Só isso. Boa sorte.",
  "Palavra comum, dessas que você fala todo dia. Começa com {tema}. Deve ser fácil. Deve.",
  "Coisa que existe no mundo, começando com {tema}. Pode ser um bicho, comida, sentimento… é a vida.",
  "Dica minimalista: começa com {tema}. Eu sou um mascote de poucas palavras. Mentira.",
  "Substantivo misterioso começando com {tema}. Sem pressão. Só a minha existência em jogo.",
  "Começa com {tema}. O resto é contigo e com o teu vocabulário.",
  "Coisa do Contexto roubada. Começa com {tema}. Se você jogou Contexto, pode ter visto essa.",
  "Letra inicial: {tema}. Eu não dou mais que isso. Eu sou pobre de dica.",
  "Uma palavra comum. Primeira letra: {tema}. Dá pra fazer. Eu acredito. Parcialmente.",
  "Começa com {tema}. Pode ter acento, mas relaxa: o A acende o Á, o C acende o Ç.",
  "É uma coisa. Começa com {tema}. Sim, eu sei, a dica mais preguiçosa do Fliperama.",
  "Palavrinha do cotidiano começando com {tema}. Chuta as vogais e seja feliz."
],
forcaInicioMistura: [
  "Mistureba! Dessa vez caiu {cat}. Da próxima, só Deus e o sorteio sabem.",
  "Sorteei a categoria: {cat}. Não gostou? Reclama com o dado.",
  "Mistureba ativada. Veio {cat}. Muda o chip do cérebro aí.",
  "Roleta da Mistureba parou em {cat}. Eu que girei. Com a pata.",
  "Categoria surpresa: {cat}. Surpresa pra você. Eu já sabia.",
  "Mistureba é tipo pastel de feira: nunca sabe o recheio. Hoje é {cat}."
],

/* ---------- letra certa ---------- */
forcaAcerto: [
  "Tem {letra}! Meu pixel agradece.",
  "Boa, {letra} tá lá. Continua assim que eu continuo inteiro.",
  "{letra}! Acertou. Pode ficar orgulhoso por dois segundos.",
  "Olha só, uma letra certa. Eu já tava preparando o testamento.",
  "{letra} confirmado. Minha orelha até mexeu de alegria.",
  "Isso! {letra}! Tô sentindo minha resolução voltar.",
  "Acertou o {letra}. Nada mal pra quem chuta de olho fechado.",
  "Tem {letra}, sim senhor. O Jorge aprovou.",
  "{letra} na conta. Tô começando a confiar em você. Não se acostuma.",
  "Letra certa! Ninguém foi deletado dessa vez. Comemora.",
  "Eita, {letra}! Sabia ou chutou? Não precisa responder. Chutou.",
  "Mais um {letra} pro quadro. Tô ficando menos transparente.",
  "Correto. {letra} é bem-vindo nessa palavra.",
  "{letra}! Isso sim é uma escolha responsável.",
  "Acertou. Eu dei uma respirada de alívio. Eu nem respiro.",
  "Boa! A palavra tá aparecendo. Eu tô continuando a aparecer também.",
  "{letra} tá dentro. Aplausos de uma pata só.",
  "Ah, agora sim. {letra}. Faz mais disso, por favor.",
  "Tem {letra}! Meu antivírus emocional te agradece.",
  "Perfeito. {letra}. Tá jogando como quem estudou.",
  "Certinho! Até parece que você sabe o que tá fazendo.",
  "{letra}? Tem! Ufa. Eu tava de olhos fechados.",
  "Foi certeiro. {letra}. A forca rangeu de raiva.",
  "Uma letra a mais, um susto a menos. {letra}!",
  "Isso aí, {letra}. Tô mandando um joinha mental.",
  "{letra} brilhou no quadro. E eu brilhei junto. Pouco, mas brilhei.",
  "Letra aprovada pelo conselho de pixels. {letra}.",
  "Acertou {letra}. Nenhum pedaço meu foi ferido nessa jogada.",
  "Gostei do {letra}. Tem cheiro de vitória. Ou de café. Tanto faz.",
  "{letra}, certíssimo. Pode chutar a próxima com essa confiança."
],
forcaAcertoVarias: [
  "{n} letras {letra} de uma vez! Isso que é rendimento.",
  "Olha o {letra} aparecendo {n} vezes! Choveu {letra}!",
  "{n} de uma tacada só. Tô impressionado e levemente emocionado.",
  "Combo! {letra} vezes {n}. Se fosse videogame, apareceria um “COMBO x{n}” na tela.",
  "Caiu {n} {letra} de uma vez. Palavra generosa, hein?",
  "{n} buracos preenchidos com um chute. Isso é eficiência de repartição pública. Ao contrário.",
  "{letra} vezes {n}! Pode se exibir, você mereceu.",
  "Choveu {letra}. {n} deles. Eu tô dançando por dentro.",
  "Uma letra, {n} posições. Matemática bonita demais.",
  "{n} {letra} de uma vez? Isso é chute de quem tem estratégia. Ou sorte. Eu aceito os dois.",
  "Bingo triplo. Quer dizer, {n}. Bingo {n}-plo.",
  "Esse {letra} tava espalhado por tudo! {n} de uma vez. Adorei.",
  "Olha a palavra se revelando de {n} em {n}. Linda.",
  "{n} letras! Se continuar assim eu termino esse jogo com as duas orelhas."
],
forcaAcertoVogal: [
  "Vogal {letra} garantida. Clássico que funciona.",
  "{letra}! Começar pelas vogais é coisa de gente sábia. Ou de gente que já jogou forca.",
  "Tem {letra}. As vogais nunca te abandonam. Diferente de algumas pessoas.",
  "Vogal certa: {letra}. O esqueleto da palavra tá aparecendo.",
  "{letra}, a vogal do povo. Tá lá, firme.",
  "Boa vogal. {letra}. Agora as consoantes vão sentir o drama.",
  "{letra} achado. Vogal é tipo arroz: tem em quase tudo.",
  "Vogal confirmada! {letra}. Eu apostaria nela também. Se eu tivesse dinheiro.",
  "{letra}! Uma vogal honesta num mundo cheio de consoantes traiçoeiras.",
  "Acertou a vogal {letra}. Tá jogando pelo manual. Respeito o manual.",
  "{letra}: a vogal que salvou o dia. E a minha orelha.",
  "Vogalzinha {letra} no lugar. Agora caça as consoantes."
],
forcaAcertoRara: [
  "Espera… tem {letra}?! Você chutou {letra} e ACERTOU? Quem é você?",
  "{letra}! Uma letra rara, certinha. Isso é conhecimento ou vidência?",
  "Chutou {letra} e deu certo. Anota a data: milagre registrado.",
  "Tem {letra}, sim! Eu ia zoar tua cara, mas agora tô sem argumento.",
  "{letra}?! Numa boa? Você claramente sabe a palavra e tá me enrolando.",
  "Um {letra} certeiro. Eu fiquei até sem reação. Olha minha cara. Sem reação.",
  "Letra rara, acerto raro. {letra}. Tô chocado em alta definição.",
  "{letra}! Quem arrisca {letra} e acerta merece uma estátua. Pequena. De pixel.",
  "Opa, {letra}! Palavra estrangeira detectada, e você detectou antes de mim.",
  "Você foi de {letra} e a palavra falou “sim”. Que romance.",
  "{letra} certo. Eu tinha preparado uma piada de erro e agora vou ter que jogar fora.",
  "Chute ousado de {letra}, recompensa merecida. Tá jogando com coragem."
],
forcaAcertoAlivio: [
  "Finalmente uma letra certa! Eu já tava me despedindo do Jorge.",
  "Ufa. Depois de tanto erro, um {letra}. Meu coração de pixel voltou a bater.",
  "{letra}! Achei que você tinha esquecido que existem letras certas.",
  "Até que enfim! Eu já tava escolhendo a música do meu velório.",
  "Uma letra certa depois da tempestade. {letra}. Obrigado.",
  "Voltou a acertar! Eu sabia. Mentira, eu duvidei muito.",
  "{letra}. Isso aí. Respira, recalcula, continua.",
  "Olha a recuperação! {letra}! O time do Bugado ainda tem chance.",
  "Tava na hora, hein? {letra}. Eu tava ficando cada vez mais invisível.",
  "Acertou depois de uma sequência de desastre. Isso se chama resiliência. Ou teimosia."
],

/* ---------- letra errada, por estágio ---------- */
forcaErro1: [
  "Minha orelha! Não tem {letra} e lá se foi minha orelha esquerda.",
  "AI! {letra} não tem. Tô ouvindo em mono agora.",
  "Errou o {letra} e a minha orelha virou pixel e caiu. Você viu isso? Eu vi.",
  "Primeiro erro. Perdi uma orelha. Tudo bem, eu tinha duas. TINHA.",
  "Não tem {letra}. Minha orelha esquerda pediu demissão.",
  "Lá se vai a orelha. Eu ouvia tão bem com ela…",
  "{letra}? Não. E aí, cadê minha orelha? Ah, tá no chão. Em pedacinhos.",
  "Primeira baixa: orelha esquerda. Ela era a minha favorita. Não conta pra direita.",
  "Errou. Tô assimétrico agora. Fotografo mal desse lado.",
  "Não tem {letra}. A orelha pixelou. Isso é um processo irreversível até o fim da rodada.",
  "Um erro só e eu já tô perdendo pedaço. Imagina seis.",
  "Sem {letra}. Minha orelha virou confete. Confete triste.",
  "Ops. Não tem {letra}. Agora eu sou um gato de uma orelha só. Tipo pirata, mas sem navio.",
  "Primeiro erro detectado. Orelha esquerda desinstalada com sucesso. Sucesso pra quem?",
  "Nada de {letra}. Tchau, orelhinha. Foi bom enquanto durou."
],
forcaErro2: [
  "A OUTRA ORELHA! Agora eu não ouço mais nada. Nem teus pedidos de desculpa.",
  "Não tem {letra}. Pronto, fiquei sem orelhas. Sou oficialmente uma batata azul.",
  "Segundo erro. Minhas duas orelhas viraram pó digital. Tô parecendo um ovo.",
  "Errou de novo! Agora eu sou um gato-fantasma sem orelha. Sou só um fantasma. Um fantasma careca.",
  "{letra}? Sério? Minha orelha direita pixelou de desgosto.",
  "Duas orelhas a menos. Se alguém me chamar, eu não escuto. Vou fingir que é de propósito.",
  "Sem {letra}. A orelha direita foi atrás da esquerda. Elas eram muito unidas.",
  "Perdi as duas orelhas. Óculos agora só se for preso com fita.",
  "Segundo erro. Sabe quanto custa uma orelha em pixel? Nem eu, mas deve ser caro.",
  "Não tem {letra}. Tô redondo, liso e triste.",
  "Adeus, orelha direita. Agora quem vai segurar meu fone de ouvido?",
  "Dois erros. Minha silhueta perdeu toda a personalidade.",
  "{letra} não tem. Sou um gato sem orelha. Isso é basicamente uma bola com olhos.",
  "E lá vai a segunda! Tô ficando aerodinâmico. Único lado bom.",
  "Errou {letra} e eu fiquei sem orelhas. Agora eu entendo o Kuririn."
],
forcaErro3: [
  "O JORGE! Não! O Jorge caiu! Ele era meu pixel de estimação!",
  "Não tem {letra} e o Jorge despencou. Ele flutuava do meu lado há anos.",
  "Terceiro erro. O pixelzinho rosa caiu no chão. Eu dei nome pra ele. Era Jorge.",
  "Você derrubou o Jorge. Eu nunca vou te perdoar. Talvez amanhã.",
  "{letra}? Não. E o Jorge foi junto. Um minuto de silêncio pelo Jorge.",
  "O Jorge tá no chão. Ele tá bem? Ele tá piscando? Não tá piscando. JORGE!",
  "Sem {letra}. O Jorge perdeu a gravidade. Literalmente. Caiu.",
  "Três erros. Primeiro as orelhas, agora o Jorge. Quem é o próximo? Eu. Eu sou o próximo.",
  "Não tem {letra}. O Jorge era a única coisa rosa e feliz aqui. Era.",
  "O Jorge caiu e ninguém fez nada. Nem você, que causou tudo isso.",
  "Terceiro erro! O Jorge virou um pixel cinza no chão. Tô de luto.",
  "Não tem {letra}. Jorge, se você tá me ouvindo aí embaixo: eu tentei.",
  "Caiu o Jorge. Metade do jogo e eu já tô sem orelha e sem pixel de estimação.",
  "Você chutou {letra} e o Jorge pagou o pato. Ele nem tinha nada a ver.",
  "Três. O Jorge desabou. Isso vai direto pro meu diário de traumas."
],
forcaErro4: [
  "MEUS OLHOS! Um virou X e o outro virou tela de carregamento!",
  "Não tem {letra}. Agora eu tô vendo tudo girando. Literalmente, um olho é um spinner.",
  "Quarto erro. Tô enxergando em 144p. Não, espera, tá carregando…",
  "Errou {letra} e meus olhos crasharam. Um X de um lado, rodinha do outro.",
  "Tô cego de um olho e carregando no outro. Se eu errar a próxima dica, a culpa é tua.",
  "Sem {letra}. Meu olho esquerdo morreu, o direito tá “processando”. Não vai terminar.",
  "Quatro erros. Eu não vejo mais as letras. Vou ter que confiar em você. Isso é assustador.",
  "{letra}? Errado. Meus olhos entraram em modo buffering. Buffering eterno.",
  "Olha meus olhos! Não, não olha. Tá feio. Um X e um círculo rodando.",
  "Não tem {letra}. Eu agora pareço um personagem nocauteado de desenho.",
  "Os olhos se foram. Tô carregando 0%… 0%… ainda 0%.",
  "Quarto erro, olhos em pane. Se eu fosse um site, alguém já teria fechado a aba.",
  "Errou e meus olhos viraram ícone do Windows pensando. Clássico.",
  "Sem visão, sem orelha, sem Jorge. Só me resta a boca e a pele azul.",
  "Não tem {letra}. Olho X: morto. Olho rodinha: esperançoso. Ingênuo."
],
forcaErro5: [
  "Tô perdendo resolução. Tô virando JPEG. Tô virando JPEG comprimido no zap.",
  "Não tem {letra}. Meu corpo tá cheio de linha de TV velha. Tô chiando.",
  "Quinto erro! Tô com as cores separadas. Vermelho pra um lado, azul pro outro. Tipo óculos 3D.",
  "Errou {letra} e eu virei fita VHS gravada por cima. Tracking desregulado.",
  "Tô com scanline no corpo inteiro. Parece que eu tô num fliperama de 1987. Ironicamente.",
  "Não tem {letra}. Meu RGB se desalinhou. Tô parecendo pôster de filme cult.",
  "Cinco erros. Se me printarem agora eu saio borrado.",
  "{letra}? Não! Tô sendo renderizado pelo pior computador da lan house.",
  "Minha resolução caiu pra 240p. Isso é violência gráfica. Literalmente.",
  "Não tem {letra}. Tô tremendo igual imagem de câmera de segurança.",
  "Quinto erro. Tô fantasminha de verdade agora: transparente, listrado e com defeito.",
  "Eu tô chiando. Tu tá ouvindo o chiado? Não, né? Eu não tenho mais orelha pra ouvir também.",
  "Sem {letra}. Meu corpo entrou em modo compatibilidade com Windows 98.",
  "Tô virando meme de qualidade baixa. Daqueles que foram salvos e repostados mil vezes.",
  "Errou. Eu tô literalmente saindo do ar. Alguém ajusta minha antena?"
],
forcaErro6: [
  "Só falta a boca. Pensa bem antes de me transformar num erro 404.",
  "Minha boca virou “404”. Não encontrei palavras. Literalmente.",
  "Não tem {letra}. Página não encontrada. Boca não encontrada. Mascote quase não encontrado.",
  "Sexto erro! Agora eu só falo em código. 404. 404. Tradução: socorro.",
  "ÚLTIMA VIDA. A próxima letra errada e eu viro tela azul. Sem pressão. Tá, com pressão.",
  "Errou {letra}. Minha boca foi pro servidor e não voltou. Mais um erro e eu travo de vez.",
  "404: boca não encontrada. Só te resta uma chance. Usa com carinho.",
  "Não tem {letra}. Olha pra mim: sem orelha, sem Jorge, olho travado, corpo chiando e boca 404. Isso é arte moderna.",
  "Seis erros. Eu tô por um fio. Um fio de fibra ótica mal instalado.",
  "Minha boca virou um código de erro. Próximo erro, é o fim. Escolhe com o coração. Não, com o cérebro.",
  "Última chance. Se errar, eu paro de funcionar. E eu tenho tanta coisa pra zoar ainda…",
  "{letra} não tem. Agora é tudo ou nada. Eu sou o nada, no caso.",
  "Só me resta essa última vida. Pensa numa letra. Pensa de novo. Agora escolhe outra.",
  "Boca 404. Parece que eu tô tentando falar, mas o servidor caiu. Uma letra errada e caio junto.",
  "Não tem {letra}. Meu último pixel de dignidade tá nas tuas mãos."
],
forcaErroRara: [
  "Você chutou {letra} numa palavra em português?! Perdi {parte} por causa disso!",
  "{letra}?! Sério mesmo? Lá se vai {parte}. Por um {letra}. Um {letra}!",
  "Quem chuta {letra} tão cedo? Você. E agora eu tô sem {parte}.",
  "{letra} é letra de palavra estrangeira e de senha de wi-fi. Não daqui. Adeus, {parte}.",
  "Arriscou {letra}? Admiro a coragem, detesto o resultado. Perdi {parte}.",
  "{letra}! O {letra}! Você sacrificou {parte} num chute de {letra}. Isso é crueldade experimental.",
  "Não tem {letra}. Claro que não tem {letra}. Quase nada tem {letra}. E {parte} pagou a conta.",
  "Um {letra}. Você foi de {letra}. Eu vou lembrar disso toda vez que olhar pro lugar onde ficava {parte}.",
  "{letra} não tem, surpresa zero. Tchau, {parte}.",
  "Tentou {letra}, né? Tipo quem tenta a porta do banheiro trancado. {parte} se foi.",
  "Chutar {letra} é tipo pedir pizza de abacaxi: pode, mas todo mundo julga. E eu perdi {parte}.",
  "Isso foi um chute de {letra}. Na minha terra isso tem nome: desespero. Adeus, {parte}.",
  "A letra {letra} ficou feliz de ser escolhida. Só ela. Eu perdi {parte}.",
  "{letra}?! Você tá jogando forca ou digitando senha de banco? Lá se vai {parte}.",
  "Olha, {letra} até tem em palavra… de Pokémon. Aqui não. Perdi {parte}, obrigado."
],
forcaErroSeguido: [
  "{n} erros seguidos. Você tá fazendo isso de propósito? Pisca duas vezes se estiver sendo coagido.",
  "Mais um erro. É uma sequência, e não do tipo bom.",
  "{n} seguidos. Tá chutando o alfabeto em ordem aleatória, né?",
  "Errando em série. Se fosse série da Netflix, já tava na terceira temporada.",
  "Sequência de {n} erros. Eu tô desmontando mais rápido que móvel de loja.",
  "{n} erros sem respirar. Respira. Pensa. Aí erra com calma, pelo menos.",
  "Tá numa maré de azar. Ou de desconhecimento. Não vou julgar. Tô julgando.",
  "{n} seguidos! Muda a estratégia: tenta uma vogal. Por mim.",
  "Errou de novo. A essa altura eu já tô escrevendo a carta de despedida.",
  "Isso já é uma sequência de erros com {n} capítulos. Que novela."
],
forcaErroVogal: [
  "Nem vogal tem? Não tem {letra}? Que palavra antipática.",
  "{letra} não tem. A vogal te traiu. Acontece nas melhores famílias.",
  "Uma vogal errada. {letra}. Isso dói mais que consoante, sabia?",
  "Não tem {letra}. Palavra seletiva com vogal. Tem gente assim também.",
  "Vogal {letra}? Nada. Às vezes a vida é assim: sem {letra}.",
  "Chutou {letra} esperando o básico e o básico não veio. Triste.",
  "Até a vogal {letra} te abandonou. Mas eu tô aqui. Em pedaços, mas tô.",
  "{letra} não tá lá. Guarda essa informação: é valiosa. Custou um pedaço meu."
],
forcaRepetida: [
  "Você já chutou {letra}. Tá testando se eu tô prestando atenção? Tô.",
  "{letra} de novo? A tecla tá até colorida, olha lá.",
  "Esse {letra} já foi. Não precisa insistir, ele não vai mudar de ideia.",
  "Repetiu {letra}. Não conta erro, mas conta vergonha.",
  "Já foi {letra}. Memória de peixe detectada.",
  "Chutou {letra} outra vez. O teclado tá pintado justamente pra isso, sabia?",
  "{letra} já tá usado. Eu sei que ele é bonito, mas escolhe outro.",
  "Opa, {letra} repetido. Eu não vou cobrar. Dessa vez.",
  "{letra}? De novo? Tá com saudade dele?",
  "Esse aí você já tentou. Sério. Olha a tecla. Ela tá diferente das outras.",
  "Repetir letra na forca é tipo abrir a geladeira de novo esperando comida nova.",
  "{letra} já foi usado. Não é mais novidade, é reprise."
],
forcaRepetidaErrada: [
  "Você já errou o {letra}. Quer errar DE NOVO? Eu não tenho pedaço sobrando pra isso.",
  "{letra} não tinha antes e continua não tendo. Letras não crescem na palavra.",
  "Tentando o {letra} de novo pra ver se muda? Não muda. Eu já perdi um pedaço por ele.",
  "Esse {letra} já me custou caro. Não chuta ele de novo, pelo amor do Jorge.",
  "{letra}? Aquele que NÃO tem? Esse mesmo? Ok, não conta, mas eu anotei.",
  "Você é persistente. O {letra} continua fora da palavra, mas eu admiro a teimosia."
],

/* ---------- dica ---------- */
forcaDica: [
  "Tá bom, toma um {letra}. Mas custou {parte}. Espero que valha.",
  "Dica comprada: {letra}. Pagamento: {parte}. Sem reembolso.",
  "Eu te dei o {letra}. Em troca, perdi {parte}. Relação tóxica, essa nossa.",
  "Pediu ajuda? Aqui: {letra}. E lá vai {parte}. Caridade dói.",
  "Revelei um {letra}. Cobrei {parte}. Preço justo? Pra mim não.",
  "Uma dica! Olha que generoso eu sou: te dei {letra} e ainda fiquei sem {parte}.",
  "Tá desesperado, né? Toma o {letra}. Adeus, {parte}.",
  "Dica entregue: {letra}. Custou {parte}. Da próxima, pensa mais antes de pedir.",
  "{letra}. Pronto. Eu mesmo arranquei {parte} pra te ajudar. Guarda isso na memória.",
  "Ajuda de emergência: {letra}. Custo: {parte}. Juros: meu orgulho.",
  "Eu te mostro o {letra}, você me tira {parte}. Esse é o nosso acordo? Achei injusto.",
  "Dica? Tá. {letra}. Mas saiba que ninguém que usa dica vira lenda.",
  "Olha o {letra} aí. Eu queria te zoar, mas perdi {parte} e agora tô sensível.",
  "Comprou um {letra} com {parte} meu. Eu sou um mascote ou um cartão de crédito?",
  "Toma teu {letra}. Não precisa agradecer. Precisa sim. Eu perdi {parte}."
],
forcaDicaNegada: [
  "Dica agora? Com uma vida só? Se eu te der, eu morro. Pensa sozinho, vai.",
  "Nada de dica na última vida. Não vou pagar meu último pixel por uma letra.",
  "Não. A dica custa uma vida e você só tem uma. Faz a matemática comigo.",
  "Negado. Eu tenho amor-próprio. Pouco, mas tenho.",
  "Pedir dica agora seria suicídio digital. Meu, no caso. Não.",
  "Última vida, zero dicas. É a lei da forca. Eu que inventei, mas é lei."
],
forcaDicaUltima: [
  "Dica? Só falta uma letra! Nem vem. Você consegue sozinho.",
  "Falta uma letra só e você quer dica? Eu me recuso a participar disso.",
  "Não, não, não. Uma letra faltando. Olha pro teclado e escolhe com fé.",
  "Pedir dica pra última letra é tipo pedir Uber pra atravessar a rua. Nega.",
  "É uma letra. UMA. Você chega lá sem mim."
],
forcaDBFrase: [
  "Três erros. Como prometido, liberei a descrição do personagem. Lê com carinho.",
  "Tá, tá. Soltei a ficha do guerreiro aí em cima. Não diz que eu nunca ajudei.",
  "Liberei a descrição. Custou três pedaços meus, então aproveita cada palavra.",
  "Olha a dica extra aí em cima. Se nem assim sair, eu vou chamar o Shenlong.",
  "Descrição desbloqueada! Só precisou de três erros e um mascote destruído.",
  "Pronto, a fofoca sobre o personagem tá na tela. Agora não tem desculpa."
],

/* ---------- quase lá ---------- */
forcaQuase: [
  "Faltam só {n}! Eu tô sentindo o cheiro da recompilação.",
  "Só {n} letra(s) faltando. Não me estraga isso agora.",
  "Quase! {n} buraquinho(s). Vai com calma.",
  "Tá quase. Falta {n}. Essa é a hora que o pessoal erra por nervoso.",
  "Só {n}. Eu já tô me alongando pra comemorar.",
  "{n} pra acabar! Eu consigo até ver a palavra. Ah, espera, meus olhos… ah, deixa.",
  "Reta final: falta {n}. Pensa bem antes de chutar Z.",
  "Falta pouco! Eu já tô escolhendo a roupa da festa. Não tenho roupa. Mas escolhendo.",
  "Só {n}! Se você errar agora eu faço drama por uma semana.",
  "Quase lá! A palavra já tá praticamente gritando o nome dela.",
  "{n} letra(s). Isso já é palavra que se lê de longe, hein?",
  "Falta {n}. Se não souber, pensa na dica. Se souber, pensa mais rápido.",
  "Tá tão perto que eu tô ouvindo a musiquinha de vitória. Sem orelha, mas tô.",
  "Faltam {n}. Eu vou prender a respiração. Figurativamente.",
  "Últimas letras! Não inventa moda agora."
],

/* ---------- fim de rodada ---------- */
forcaGanhouPerfeito: [
  "ZERO ERROS! {palavra} de primeira! Eu tô inteirinho! Olha minhas orelhas!",
  "Perfeito! Nenhum pixel perdido. Eu vou emoldurar essa rodada.",
  "{palavra} sem errar nada. Isso é talento ou você leu o código-fonte?",
  "Rodada perfeita! O Jorge tá flutuando de orgulho.",
  "Nenhum erro! Eu nem tive tempo de sentir medo. Obrigado por isso.",
  "{palavra}, zero erros. Que jogada limpa. Tá cheirando a sabonete.",
  "Sem nenhum arranhão! Eu queria te abraçar, mas sou um desenho. Considera abraçado.",
  "Perfeição total. {palavra}. Eu acho que me apaixonei pelo teu cérebro.",
  "Nenhuma letra errada. Nenhuma! Eu tô até desconfiado. Mas feliz.",
  "Zerou sem erro! Pode printar e mandar no grupo da família.",
  "{palavra} limpinho. Eu continuo em 4K graças a você.",
  "Rodada imaculada. Nem minha orelha tremeu.",
  "Isso é o que eu chamo de jogo de gente grande. {palavra} sem erro.",
  "Zero erros? ZERO? Eu vou contar isso pros outros jogos do Fliperama.",
  "Você acertou {palavra} sem perder nada meu. Eu tô comovido. Minha voz tá embargada. Em pixel."
],
forcaGanhou: [
  "{palavra}! Recompilando… 100%. Tô de volta, orelhas e tudo!",
  "Acertou! {palavra}. Eu me reconstruí inteirinho. Tô novinho em folha.",
  "Boa! {palavra} com {n} erro(s). Aceitável. Até bonito.",
  "{palavra}! Recompilação concluída. Obrigado por não me deixar virar tela azul.",
  "É {palavra}! Minhas orelhas voltaram! O Jorge voltou! Todo mundo voltou!",
  "Acertou {palavra}. Custou {n} pedaço(s), mas eles já cresceram de volta.",
  "Isso! {palavra}. Tô rodando liso de novo. Sessenta quadros por segundo.",
  "Vitória! {palavra}. Meu backup foi restaurado com sucesso.",
  "{palavra}, claro! Estava na cara. Na minha cara, que agora tá inteira de novo.",
  "Mandou bem. {palavra}. Pode comemorar, eu deixo.",
  "Acertou! Recompilei. Eu sou tipo lagartixa: o rabo cresce de novo. No caso, a orelha.",
  "{palavra}! Com {n} erro(s) no caminho, mas chegou. É isso que importa.",
  "Palavra salva, mascote salvo. {palavra}!",
  "Olha eu inteiro de novo! Obrigado, {palavra}. E obrigado, você.",
  "Deu bom! {palavra}. Minha resolução voltou pro máximo."
],
forcaGanhouSofrido: [
  "{palavra}… com {n} erros. Ganhou, mas eu vou precisar de terapia.",
  "Acertou, mas olha o estado que eu fiquei antes. {n} erros! Foi vitória de Pirro.",
  "{palavra}. Deu certo, no sufoco. Eu tava praticamente em modo de segurança.",
  "Ufa. {palavra}. Com {n} erros, mas ganhou. Meu coração de pixel quase parou.",
  "Vitória sofrida! {n} erros. Quase me mandou pro lixo eletrônico.",
  "{palavra}! Recompilei, mas lembro de tudo. Principalmente do que você fez com o Jorge.",
  "Ganhou raspando. Eu tava tão quebrado que já tava negociando com o antivírus.",
  "Acertou {palavra} depois de me desmontar quase todo. Emoção é contigo mesmo.",
  "{n} erros e uma vitória. Parece placar de jogo de várzea. Mas valeu.",
  "Venceu! Eu me reconstruí, mas vou ficar com um tique no olho por uns dias.",
  "{palavra}, finalmente! Tava parecendo que você ia testar o alfabeto inteiro.",
  "Ganhou, mas com muito drama. Eu gosto de drama. Mas não comigo."
],
forcaGanhouUltimaVida: [
  "NA ÚLTIMA VIDA! {palavra}! Eu já tava vendo a luz azul no fim do túnel!",
  "{palavra} com uma vida só! Meu coração 404 voltou a bater!",
  "Acertou no último suspiro! Eu já tava com a boca em 404! Que filme!",
  "{palavra}! Por um pixel! Um pixel! Eu vou precisar sentar. Eu não tenho perna. Mas vou sentar.",
  "Salvou no último segundo! Isso foi final de campeonato nos pênaltis.",
  "Uma vida restando e você fez {palavra}. Meu backup nem precisou ser usado. Por pouco.",
  "Eu já tava carregando a tela azul! Cancelei no último instante! {palavra}!",
  "Vitória no limite! Eu tava tão quebrado que já tinha escrito meu nome no testamento do Fliperama.",
  "No fio da navalha! {palavra}! Tô tremendo. Não é mais o scanline, é emoção.",
  "Ganhou com uma vida. Isso é coisa de protagonista de anime.",
  "{palavra}! Última vida, última chance, última letra. Poesia.",
  "Eu já tava me despedindo do Jorge lá no chão. Voltamos todos! {palavra}!"
],
forcaPerdeu: [
  "Tela azul. Era {palavra}. Bugado.exe parou de funcionar. Obrigado por isso.",
  "Travei. A palavra era {palavra}. Vou reiniciar e fingir que nada aconteceu.",
  "Era {palavra}! {palavra}! Eu tava tão perto de sobreviver.",
  "Game over. Eu virei tela azul e a palavra era {palavra}. Belo trabalho em equipe. Da tua parte, não.",
  "Crash total. {palavra}. Coletando informações do erro… o erro foi você.",
  "Era {palavra}. Eu morri, mas volto na próxima. Eu sempre volto. É meu defeito.",
  "Me deletou. A palavra era {palavra}. Vou lembrar disso na próxima atualização.",
  "Fim da linha. {palavra}. Minha última palavra antes de travar foi “404”. Poético.",
  "Perdeu. Era {palavra}. Olha pra mim: tela azul. É isso que você queria?",
  "Bugado parou de responder. Motivo: {palavra}. Deseja aguardar? Não adianta.",
  "Era {palavra}. Tá tudo bem, eu me reinicio. Mas eu vou reiniciar magoado.",
  "Tela azul da morte. A palavra era {palavra}. Anota pra não esquecer. Eu não vou esquecer.",
  "A forca venceu. {palavra}. Eu vou voltar, e com mais orelhas.",
  "Não deu. {palavra}. Se serve de consolo, eu também não teria acertado. Mentira, teria.",
  "Sistema travou. {palavra} era a resposta. Pode me desligar e ligar de novo.",
  "Morri. Era {palavra}. Pelo menos foi uma morte bonita, azulzinha.",
  "Erro fatal: {palavra} não encontrada no teu cérebro. Reinicie e tente novamente.",
  "Era {palavra}! Tudo bem. Eu fui formatado, mas meu rancor ficou salvo na nuvem.",
  "Travamento geral. {palavra}. Tô vendo meu corpo de fora. Tá tudo azul.",
  "Era {palavra}. Descansa em paz, Bugado versão 1.0. A versão 1.1 vem com mais sarcasmo."
],

/* ---------- sequências (Infinito) ---------- */
forcaSequencia: [
  "Sequência de {n}! Tá embalado, hein?",
  "{n} seguidas! Eu tô recompilando tanto que já tô ficando bom nisso.",
  "{n} palavras sem perder. Quem é você e o que fez com o jogador de antes?",
  "Sequência {n}! Pode subir no sofá e comemorar. Com cuidado.",
  "Tá em chamas! {n} seguidas! Eu tô até com medo de estragar falando.",
  "{n} de sequência. Isso já é hábito. Hábito saudável, pela primeira vez.",
  "Mais uma! Sequência de {n}. Tô anotando no meu caderninho de lendas.",
  "{n} seguidas! Se continuar, eu vou ter que pedir aumento pro dono do Fliperama.",
  "Sequência de {n} e subindo. Tipo o preço do café.",
  "{n} vitórias em fila! Aquece, mas não esquenta, que é aí que a gente erra.",
  "Tá numa sequência de {n}. Eu vou ficar quietinho pra não dar azar. Tá. Já falei. Desculpa.",
  "Sequência {n}! Se fosse videogame, tava tocando música de chefe.",
  "{n} palavras seguidas. Minha estrutura agradece a constância.",
  "Olha a sequência: {n}! Eu já tô acostumando a ter orelha."
],
forcaSequenciaMarco: [
  "SEQUÊNCIA DE {n}! Vitória registrada no Fliperama! Eu vou te colocar no quadro de funcionário do mês!",
  "{n} seguidas! Isso vale vitória oficial. Pode ligar pra tua mãe.",
  "Marco de {n}! Ganhou uma vitória e o meu respeito. O respeito é temporário.",
  "{n}! Número redondo! Soltei confete com o que sobrou do Jorge. Mentira, ele tá bem.",
  "Sequência {n} batida! Isso aqui já é carreira profissional de forca.",
  "{n} seguidas é marco histórico. Vou escrever nos anais do Fliperama. Não ri."
],
forcaSequenciaPerdida: [
  "E lá se foi uma sequência de {n}. Eu senti essa mais que a tela azul.",
  "Sequência de {n} zerada. É o ciclo da vida. Da vida triste.",
  "Perdeu uma sequência de {n}. Eu vou guardar luto por ela. E pelo Jorge.",
  "{n} seguidas… e acabou. Tava tão bonito.",
  "Zerou a sequência de {n}. Não chora. Eu choro por nós dois.",
  "Sequência de {n} pro espaço. Da próxima, respira antes de chutar consoante estranha.",
  "Tchau, sequência de {n}. Foi boa enquanto durou. Tipo novela das nove.",
  "A sequência de {n} morreu junto comigo. Pelo menos fomos juntos."
],
forcaPulou: [
  "Pulou? Covarde. Era {palavra}. Que eu nem ia te contar, mas contei.",
  "Desistiu dessa. Era {palavra}. Eu tava torcendo por você. Pouco, mas tava.",
  "Pulou a palavra. Era {palavra}. Isso conta como derrota, viu? Eu anoto tudo.",
  "Fugiu! Era {palavra}. A forca ficou esperando com cara de tacho.",
  "Nova palavra no lugar de {palavra}. Pulou antes de me desmontar. Obrigado, no fundo.",
  "Skip! Era {palavra}. Nem vou comentar. Já comentei.",
  "Desistência registrada. Era {palavra}. Minha orelha tá decepcionada.",
  "Trocou de palavra. A antiga era {palavra}. Ela mandou dizer que tá magoada."
],
forcaTrocouCategoria: [
  "Mudou pra {cat}. Nova categoria, novas formas de me destruir.",
  "{cat}, é? Gostei. Vamos ver se aqui você erra menos.",
  "Trocou pra {cat}. Cada categoria tem sua sequência, não vai misturar as coisas.",
  "Agora é {cat}. Muda o chip, ajusta o cérebro e cuidado com as consoantes.",
  "{cat}! Ótima escolha. Ou péssima. A gente descobre em sete erros.",
  "Categoria {cat} carregada. Eu tô carregado também. De ansiedade.",
  "Beleza, {cat}. Eu me preparo emocionalmente de novo.",
  "{cat}! Vou esquentar meus pixels."
],

/* ---------- Desafio do Dia ---------- */
forcaDiarioProxima: [
  "Palavra {i} de 5 no forno. Me reconstruí todinho, bora de novo.",
  "Próxima! Rodada {i} de 5. Orelhas no lugar, Jorge flutuando, confiança média.",
  "Rodada {i}. Esquece a anterior. Eu já esqueci. Mentira, eu lembro de tudo.",
  "Vamos pra palavra {i}. Eu fiz alongamento de pixel entre uma e outra.",
  "Rodada {i} de 5. Nova categoria, novo sofrimento.",
  "Palavra {i}. Eu tô zerado de novo. Tipo videogame quando você morre, só que eu que morro.",
  "Bora pra {i}ª! Se a última foi ruim, essa pode ser pior. Brincadeira. Ou não.",
  "Próxima vítima: eu, na rodada {i}.",
  "Rodada {i}! Respira e começa pelas vogais, que é o que os profissionais fazem.",
  "Palavra {i} de 5. Eu tenho fé. Pouca, mas é fé."
],
forcaDiarioFeito: [
  "Desafio do Dia encerrado: {n}/5. Volta amanhã que eu tô com novas orelhas.",
  "Fechou o dia com {n} de 5. Já pode compartilhar e se gabar. Ou esconder.",
  "{n}/5 no desafio. Eu vou reiniciar e te espero amanhã, com palavras novas.",
  "Diário concluído: {n} de 5. Agora o Infinito tá aberto pra você continuar me maltratando.",
  "Placar do dia: {n}/5. Anota aí, que amanhã eu quero revanche.",
  "Acabou o desafio de hoje. {n} de 5. Não é o fim do mundo. É o fim do dia, só.",
  "{n}/5! Joga o resultado no grupo e espera o pessoal passar vergonha também.",
  "Cinco rodadas, {n} acertos e um mascote que sobreviveu. Mais ou menos.",
  "Desafio encerrado. {n} de 5. Eu vou pro spa de pixels me recuperar.",
  "Dia fechado: {n}/5. Amanhã tem mais. Eu não posso fugir, moro aqui."
],
forcaDiarioPerfeito: [
  "5 DE 5! O desafio inteiro! Eu vou mandar fazer uma estátua de você no saguão do Fliperama.",
  "Cinco de cinco! Isso é o que eu chamo de dia produtivo. Pena que é num jogo de forca.",
  "Gabaritou o Desafio do Dia! Eu tô inteiro, feliz e levemente assustado com teu poder.",
  "5/5. Perfeito. Compartilha isso agora, antes que alguém duvide.",
  "Todas as cinco! Pode colocar no currículo: “especialista em salvar mascote”."
],
forcaDiarioRuim: [
  "{n}/5… Hoje não foi teu dia. Nem o meu. Eu morri várias vezes.",
  "Desafio encerrado com {n} de 5. Eu vou fingir que o sorteio foi difícil. Foi fácil.",
  "{n}/5. Amanhã é outro dia. Com outras palavras. E eu com outras orelhas.",
  "Terminou com {n}. Eu não vou mentir: foi feio. Mas foi com estilo. Não, nem estilo.",
  "{n} de 5. Tudo bem. Até o Goku perdeu umas lutas. Poucas. Mas perdeu."
],
forcaDiarioJaFeito: [
  "O Desafio de hoje já foi. Se quiser mais, o Infinito tá logo ali.",
  "Hoje você já jogou o diário. Quer me ver sofrer mais? Vai no Infinito.",
  "Desafio concluído hoje. Eu tô de folga. Mas no Infinito eu faço hora extra.",
  "Já fez o diário. Amanhã tem outro. Enquanto isso, Infinito, meu consagrado.",
  "O diário tá feito. Pode ficar olhando pro resultado, ou jogar Infinito que é mais produtivo.",
  "Já jogou hoje! Palavras novas só amanhã. Eu não mando no calendário."
],

/* ---------- comentários de fim específicos por categoria ---------- */
forcaFimPokemon: [
  "Olha aí o {palavra} em carne e osso. Em pixel e arte oficial, no caso.",
  "{palavra}! Essa é a arte oficial. Bonito, né? Eu sou mais.",
  "Esse é o {palavra}. Agora você nunca mais esquece. Ou esquece amanhã.",
  "Apresento: {palavra}. Ele mandou um oi. Eu traduzi.",
  "{palavra} tá aí pra você admirar. Tira print, ele gosta.",
  "Pokédex atualizada: {palavra}. Um dos mais de mil. Você só precisava lembrar desse.",
  "A cara do {palavra} quando descobriu que virou palavra de forca.",
  "{palavra}! Se ele soubesse que custou pedaços meus, pediria desculpa. Pokémon é educado.",
  "Olha o {palavra}. Queria ter essas cores. Eu sou só azul-piscina.",
  "{palavra} na tela. Se ele evoluir, a palavra fica mais difícil. Pensa nisso."
],
forcaFimDB: [
  "Esse é o {palavra}. Nível de poder? Mais alto que o teu na forca.",
  "{palavra} apareceu pra dar um tchauzinho. Ou um Kamehameha. Depende.",
  "Olha o {palavra}! Eu reconheceria esse cabelo em qualquer lugar.",
  "{palavra}, direto da dublagem brasileira pro teu coração.",
  "Aí está: {palavra}. Ele treinou muito pra aparecer nessa tela.",
  "{palavra}! Se juntar as sete esferas, dá pra pedir mais uma rodada dessas.",
  "Esse é o {palavra}. Tem gente que só lembra dele por meme. Tudo bem.",
  "{palavra}. Personagem clássico ou lado B? Você decide.",
  "Olha o {palavra} aí. Ele ficou feliz de ser lembrado. Tá sorrindo por dentro.",
  "{palavra}! Se ele soubesse jogar forca, já tinha acertado com um olhar."
],
forcaFimConexo: [
  "{palavra}, do grupo “{tema}”. Lá no Conexo ela tem mais três amigas.",
  "Essa veio do Conexo: {palavra}. O tema era “{tema}”. Faz sentido agora?",
  "{palavra}! Se aparecer no Conexo, você já sabe onde encaixar.",
  "“{tema}”: {palavra}. Anota que isso pode cair na prova. A prova é o Conexo.",
  "{palavra}. Palavra de grupo do Conexo. Ela é sociável.",
  "O Conexo mandou lembrança: {palavra}. Grupo “{tema}”."
],

/* ---------- menus / botões ---------- */
forcaAjuda: [
  "Manual de sobrevivência aberto. Lê com atenção, minha vida depende disso.",
  "Ah, a ajuda. Resumo: acerta letras, não me destrói. Simples.",
  "Leu? Então agora não tem desculpa quando eu virar tela azul.",
  "Regras na tela. Eu escrevi com as orelhas que ainda tenho.",
  "Tá tudo aí explicadinho. Até o Jorge entendeu.",
  "Leia com carinho. É basicamente meu testamento com regras de jogo."
],
forcaStats: [
  "Tuas estatísticas. Olha quantas vezes você me matou. Registrado.",
  "Números não mentem. Diferente de você quando diz que sabia a palavra.",
  "Aqui estão teus recordes. Alguns bons, outros… existem.",
  "Estatísticas na mesa. Eu contei todas as minhas mortes. Uma por uma.",
  "Olha que bonito teu histórico. E feio. Mas bonito.",
  "Contabilidade do Bugado: palavras salvas, mascotes perdidos, Jorges derrubados."
],
forcaCompartilhou: [
  "Copiado! Manda no grupo e espera alguém fazer pior.",
  "Resultado copiado. Pode colar e fingir que foi fácil.",
  "Tá na área de transferência. Esses quadradinhos contam a nossa história de amor e ódio.",
  "Copiei! Agora é só jogar na roda e ver quem aguenta.",
  "Resultado pronto pra compartilhar. Não esquece de me marcar. Eu não tenho rede social."
],
forcaParadoMeio: [
  "Travou no meio da palavra? Eu também travo às vezes. Mas eu tenho desculpa: sou um bug.",
  "Tá pensando ou dormiu? Tô aqui, sem orelha, esperando.",
  "Olha as letras que faltam. Visualiza. Visualizou? Agora chuta.",
  "O silêncio tá me deixando nervoso. E eu tenho poucos pixels pra ficar nervoso.",
  "Vai, uma letra. Qualquer uma. Não, qualquer uma não. Uma boa.",
  "Tá difícil? Relê a dica. Às vezes ela tá gritando e você não ouve.",
  "Pensa nas letras mais comuns: A, E, O, S, R… de nada. Eu sou um mascote consultor.",
  "Enquanto você pensa, eu fico aqui recolhendo meus pixels do chão.",
  "Não tem pressa. Mas o Jorge tá ficando entediado. Ele pisca mais quando tá entediado.",
  "Tá parado há tanto tempo que eu já tô achando que você tá torcendo pra eu virar tela azul sozinho."
],
forcaCutucarGrande: [
  "Ei! Esse é o meu corpo principal! Cutuca com cuidado, ele tá em manutenção.",
  "Não precisa cutucar o eu grande. O eu pequeno ali em cima atende também.",
  "Isso faz cócegas nos meus pixels.",
  "Cutucar o desenho não revela letra. Eu já testei. Várias vezes.",
  "Tá me apertando pra ver se eu apito? Eu apito. Mas só quando você erra.",
  "Me cutucou! Agora vou ficar com essa marquinha de dedo na tela.",
  "Cuidado, eu tô frágil. Qualquer toque e cai outra orelha. Mentira. Mas cuidado.",
  "Oi! Eu sou o Bugado versão ampliada. Mesma chatice, mais resolução.",
  "Se você cutucar o Jorge, ele pisca mais rápido. Viu? Não viu. Nem eu.",
  "Tá testando se eu sou de verdade? Sou de SVG. É quase a mesma coisa.",
  "Cutucou o mascote grande. Eu dei pulinho. Você viu o pulinho?",
  "Ei, não é aqui que chuta letra. É no teclado lá embaixo. Eu sou decoração com opinião."
],

/* ---------- cutucar o mascote pequeno ---------- */
cutucarForca: [
  "Para de me cutucar e chuta uma letra! Eu tô com a vida por um fio aqui.",
  "Me cutucar não conta como letra. Nem como carinho, do jeito que você faz.",
  "Ai! Cuidado que eu já tô desmontando sozinho, não precisa ajudar.",
  "O eu pequeno aqui é só o narrador. O que sofre é o eu grande ali. A gente divide a dor.",
  "Cutucou! Agora eu vou lembrar disso quando você errar uma vogal.",
  "Não precisa me apertar, eu já tô sob pressão. Literalmente numa forca.",
  "Psiu, a palavra tá ouvindo! Disfarça e chuta um E.",
  "Cutucando o mascote em vez de pensar na palavra? Clássico.",
  "Eu sei a resposta. Você sabe que eu sei. E eu não vou contar. Nem com cutucada.",
  "Toda vez que você me cutuca, uma vogal fica triste.",
  "Se cutucar mascote desse vida extra, você já tava invencível.",
  "Ai! Tá querendo me tirar a orelha antes da hora?",
  "Cutucou o Bugado. Efeito: nenhum. Efeito colateral: eu fiquei irritado.",
  "Não sou tecla, sou mascote. As teclas ficam lá embaixo. As bonitinhas.",
  "Tá procurando dica em mim? A dica tá escrita ali em cima. Com letra e tudo.",
  "Sou meio gato, meio fantasma, e cem por cento contra cutucada.",
  "Me cutuca que eu te conto um segredo: não tem W. Provavelmente. Talvez tenha.",
  "O Jorge viu você me cutucando. Ele vai contar pra todo mundo.",
  "Tá me cutucando porque tá nervoso? Normal. Eu também tô. Eu que vou ser apagado.",
  "Ei! Eu tenho direitos trabalhistas. Acho. Vou ver com o sindicato dos mascotes.",
  "Cada cutucada é uma letra que você não chutou. Pensa nisso.",
  "Se você gastasse essa energia nas vogais, já tinha terminado.",
  "Eu fico aqui em cima narrando a tragédia. Não me cutuca, me respeita.",
  "Opa! Achei que era o fim. Era só você mesmo.",
  "Me cutucar não reconstrói minha orelha. Eu já tentei pedir.",
  "Você tá tratando o mascote como botão de elevador. Apertar mais não faz vir mais rápido.",
  "Toc toc. Quem é? A letra que você devia estar chutando.",
  "Quer saber qual letra chutar? Uma que você ainda não chutou. De nada.",
  "Cutucada registrada. Protocolo 404. Aguarde atendimento.",
  "Aqui é o SAC do Bugado. Sua reclamação é importante. Ela vai pro lixo.",
  "Eu tô vendo tudo daqui de cima. Inclusive você hesitando no teclado.",
  "Se me cutucar sete vezes eu viro tela azul? Não. Mas quase fiquei tentado.",
  "Isso não é botão de dica! O botão de dica tá no teclado e custa um pedaço meu.",
  "Cutucar mascote é sinal de tédio. Ou de carinho. Vou escolher acreditar no carinho.",
  "Pode cutucar, mas cutuca com fé, pra ver se sai alguma letra certa.",
  "Chega! Eu vou te dar uma letra de presente: a letra que você não chutou. Qual? Não sei.",
  "Ai, meu pixel! Tá bom, tá bom, eu tô ouvindo. Pouco, sem orelha, mas tô.",
  "Me cutucou bem na hora que eu ia dar uma dica. Agora esqueci.",
  "Meu eu grande ali tá sofrendo e você aqui cutucando o pequeno. Prioridades.",
  "Se cutucada fosse letra, a palavra já tinha umas trinta.",
  "Não me distrai. Eu tô torcendo muito forte, isso exige concentração.",
  "Você é a pessoa que aperta o botão do micro-ondas antes de acabar, né? Tô vendo."
],

/* ---------- aleatórias temáticas (somadas ao 'aleatorio' geral) ---------- */
forcaAleatorio: [
  "Curiosidade: na forca tradicional o boneco é de palito. Eu sou de SVG. Evolução, né?",
  "A letra mais comum no português é o A. Depois E, O, S. Tô te dando o ouro aqui.",
  "Sabia que o W e o K só voltaram oficialmente pro alfabeto em 2009? Eu fui contra.",
  "Eu tenho um pesadelo recorrente: uma palavra só de consoantes. Tipo “PSST”.",
  "O Jorge flutua do meu lado desde que eu fui desenhado. Nunca me disse uma palavra. Ótimo ouvinte.",
  "Eu já fiz backup de mim num disquete. Hoje não tem mais onde ler disquete. Tô perdido pra sempre.",
  "Às vezes eu olho pra forca e penso: quem desenhou isso tava bem?",
  "Tem palavra em português com as cinco vogais: “sequoia”, “eucalipto”, “educativo”. Eu decorei pra impressionar. Funcionou?",
  "Se eu virar tela azul, alguém me reinicia com carinho? Com Ctrl+Alt+Del, sem violência.",
  "Minha orelha esquerda sempre foi mais sensível. Ela já caiu tantas vezes que tem trauma.",
  "Eu não sou supersticioso, mas nunca chuto a letra X numa sexta-feira.",
  "Fato aleatório: “paralelepípedo” tem três letras E. Não pergunta por que eu contei.",
  "Tem gente que começa a forca pela letra Z. Essas pessoas não têm amor pelo mascote.",
  "Se eu fosse uma palavra, eu seria “bugado”. Seis letras, duas vogais, um ego.",
  "Eu queria uma orelha reserva. Tipo pneu estepe. Fica a sugestão pros desenvolvedores.",
  "Uma vez um jogador acertou tudo sem errar nenhuma. Eu chorei. Eram lágrimas azuis.",
  "O Jorge e eu estamos pensando em abrir um canal. “Pixel e Fantasma”. Já tem nome.",
  "Fun fact: “forca” com cedilha vira “força”. Uma perninha muda tudo. Igual minha orelha.",
  "Sabe o que é pior que tela azul? Tela azul com atualização pendente.",
  "Palavras com Y em português são raras. Mas nome de Pokémon é uma festa de Y.",
  "Se o teclado tivesse sentimento, a tecla W seria a mais solitária.",
  "Eu já perdi as duas orelhas mais vezes que o Kuririn morreu. E olha que ele morreu muito.",
  "Tô pensando em fazer um curso de primeiros socorros pra mascote. Seria útil aqui.",
  "Quem inventou o jogo da forca era meio dramático. Me identifico.",
  "Toda vez que você acerta uma vogal, um pixel meu faz festa.",
  "Sabia que em inglês “forca” se chama “hangman”? O homem pendurado. Aqui é o gato pixelado.",
  "Minha resolução original é 120 por 120. Aqui eu tô em tamanho família.",
  "Se um dia faltar letra no teclado, a primeira a sumir vai ser o Q. Ninguém sente falta.",
  "A letra Q quase sempre vem com U. É o casal mais grudento do alfabeto.",
  "Eu me pergunto se o Jorge tem um pixel de estimação também. Pixelception.",
  "Já tentei aprender a desenhar forca. Saiu um gato. Saiu eu.",
  "O A é a vogal mais popular do português. É tipo o Neymar das letras.",
  "Se eu perder a boca, eu falo 404. Se perder o 404, eu falo em código Morse.",
  "Estatística bugada: 73% das pessoas chutam A primeiro. Os outros 27% chutam E e se acham diferentes.",
  "Cada vez que eu viro tela azul, eu volto um pouco mais sarcástico. Isso explica muita coisa.",
  "Tenho saudade da época em que a forca era no papel e o boneco não reclamava.",
  "Eu tenho seis pontos de vida e um Jorge. É mais que muito chefão de videogame.",
  "O ç é um C com rabinho. Eu sou um gato com rabinho. Somos parecidos. Ele é mais útil.",
  "A letra H não tem som no começo das palavras. É a letra mais tímida do alfabeto.",
  "Meu sonho é uma rodada perfeita por dia. Seria tipo vitamina pra mascote.",
  "Se a palavra tiver hífen, eu mostro de graça. Sou generoso com pontuação.",
  "Um dia vou pedir pro Shenlong: “quero orelhas indestrutíveis”. Ele vai rir de mim."
],
forcaParado: [
  "Tá difícil? Eu ficaria parado também, mas eu tô literalmente pendurado aqui.",
  "Enquanto você pensa, eu colo minhas orelhas com fita crepe.",
  "Pode pensar. Eu não vou a lugar nenhum. Eu não tenho perna.",
  "Olha o teclado. As teclas brancas são as que você ainda não tentou. Dica de graça.",
  "Silêncio… só se ouve o chiado da minha antena.",
  "Pensando na próxima letra? Pensa numa vogal. As vogais nunca decepcionam. Quase nunca.",
  "Eu tô aqui, pendurado, esperando. Tipo roupa no varal.",
  "Tá tudo bem aí? Pisca se a palavra estiver difícil.",
  "O Jorge dormiu de tédio. Olha ele piscando devagar.",
  "Se você ficar parado muito tempo, a palavra não se revela sozinha. Eu já testei.",
  "Parado assim você me deixa nervoso. Nervoso é pior que errar. Quase.",
  "Enquanto isso, na Forca Bugada: nada. Absolutamente nada.",
  "Ei, ainda tá aí? A palavra perguntou por você.",
  "Eu tenho todo o tempo do mundo. O servidor não. Brincadeira. Tem sim.",
  "Tá pensando ou tá num loop infinito? Eu entendo de loop infinito."
]
};

/* ---------- falas específicas de palavras (ditas no fim da rodada) ---------- */
window.FALAS_FORCA_PALAVRAS = {
  pikachu: "Pikachu! O rato mais famoso do mundo depois do Mickey. E muito mais elétrico.",
  charizard: "Charizard! O dragão que não é dragão. Tipo fogo e voador, pra confundir criança.",
  magikarp: "Magikarp! O Pokémon mais inútil que vira o mais assustador. Tipo eu depois do café.",
  bulbasaur: "Bulbasaur! O inicial que ninguém escolhe e todo mundo respeita.",
  squirtle: "Squirtle! Óculos escuros e esquadrão. Eu queria esse estilo.",
  charmander: "Charmander! Se a chama do rabo apagar, ele morre. Pressão parecida com a minha aqui.",
  mewtwo: "Mewtwo! Criado em laboratório, cheio de trauma. Somos parecidos, eu e ele.",
  psyduck: "Psyduck! Vive com dor de cabeça. Ele jogou forca comigo antes, com certeza.",
  snorlax: "Snorlax! Meu ídolo. Dorme, come e bloqueia estrada. Vida perfeita.",
  eevee: "Eevee! O Pokémon que não decide o que quer ser. Tipo eu escolhendo pastel.",
  jigglypuff: "Jigglypuff! Canta pra todo mundo dormir e fica bravo quando dormem. Artista incompreendido.",
  gengar: "Gengar! Um fantasma roxo e sorridente. É basicamente meu primo de outra cor.",
  ditto: "Ditto! Se transforma em qualquer coisa. Eu só me transformo em tela azul.",
  slowpoke: "Slowpoke! Demora cinco segundos pra sentir dor. Queria isso quando perco as orelhas.",
  meowth: "Meowth! O gato que fala. Plágio de mim, claramente.",
  lucario: "Lucario! O favorito de metade da internet. A outra metade gosta do Gardevoir.",
  onix: "Onix! Uma cobra de pedra gigante. Imagina o tamanho da forca pra ele.",
  mew: "Mew! Três letras e um mistério inteiro. Palavra pequena, Pokémon lendário.",
  goku: "Goku! O cara come por dez e salva o universo por hobby.",
  vegeta: "Vegeta! O príncipe dos Saiyajins. Orgulhoso igual eu quando você acerta sem erro.",
  kuririn: "Kuririn! O homem que mais morreu no anime. Eu me identifico demais.",
  piccolo: "Piccolo! Verde, alto, de capa e o melhor pai do Gohan. Sem discussão.",
  gohan: "Gohan! Potencial infinito, preferiu estudar. Respeito a escolha.",
  freeza: "Freeza! O vilão mais educado e mais cruel. Fala “por favor” antes de explodir planetas.",
  cell: "Cell! Quatro letras e uma saga inteira. Palavra curta, vilão comprido.",
  majinboo: "Majin Boo! Transforma gente em chocolate. Eu queria esse poder no café da tarde.",
  bulma: "Bulma! Sem ela, ninguém achava esfera nenhuma. A verdadeira protagonista.",
  yamcha: "Yamcha! O eterno derrotado. Coloca uma flor na pose dele, por respeito.",
  mestrekame: "Mestre Kame! Criou o Kamehameha e mora numa ilha rosa. Vida resolvida.",
  mrsatan: "Mr. Satan! O campeão mundial que nunca ganhou luta de verdade. Ícone.",
  bills: "Bills! Deus da destruição que mata por causa de pudim. Justo, eu mataria por pastel.",
  whis: "Whis! Anjo, treinador e crítico gastronômico. Um currículo invejável.",
  trunks: "Trunks! Veio do futuro com espada e jaqueta. Que entrada, hein?",
  broly: "Broly! Grita, fica gigante e grita mais. Parece eu quando perco a orelha.",
  shenlong: "Shenlong! Realiza desejos. Eu pediria orelhas extras.",
  chichi: "Chi-Chi! A única pessoa que o Goku teme. Mulher de respeito.",
  gato: "Gato! Olha que coisa, eu sou meio gato. Obrigado pela homenagem.",
  fantasma: "Fantasma! Eu sou meio fantasma. Você acabou de soletrar meu sobrenome.",
  robo: "Robô! Eu sou meio robô também, se contar os bugs.",
  zumbi: "Zumbi! Tipo eu depois da tela azul: volto, mas meio torto.",
  pizza: "Pizza! Redonda, vem na caixa quadrada, cortada em triângulo. Até hoje não superei.",
  cafe: "Café! O combustível oficial de quem joga forca de madrugada.",
  pastel: "Pastel! O de feira é o melhor. Não aceito discussão.",
  brigadeiro: "Brigadeiro! A moeda oficial das festas de criança.",
  computador: "Computador! Minha casa. Meu lar. Meu local de trabalho. Meu tudo.",
  celular: "Celular! Provavelmente é onde você tá me jogando agora. Oi, tela pequena!",
  sogra: "Sogra! Palavra que dá medo em muita gente. Mais que a tela azul.",
  careca: "Careca! Eu sem as orelhas fico basicamente assim.",
  pudim: "Pudim! O Bills destruiria um planeta por um desses.",
  internet: "Internet! Onde eu nasci, cresci e fui zoado pela primeira vez.",
  senha: "Senha! Tem cinco letras, mas a tua tem 12 e um ponto de exclamação no fim. Espero.",
  videogame: "Videogame! A coisa mais bonita que a humanidade inventou. Depois do pastel.",
  preguica: "Preguiça! A palavra que eu mais vivo. Depois de “bug”.",
  saudade: "Saudade! A palavra que não tem tradução. Tipo o que eu sinto das minhas orelhas.",
  flamengo: "Flamengo! Metade do Brasil comemorou agora. A outra metade fechou o jogo.",
  cebolinha: "Cebolinha! O plano infalível dele nunca funciona. O teu, pelo visto, funcionou.",
  miojo: "Miojo! Três minutos de preparo, vinte anos de estudante.",
  domingo: "Domingo! Aquele dia que começa bom e termina com a musiquinha do Fantástico.",
  tartaruga: "Tartaruga! Lenta, mas vence a lebre. Igual você nessa rodada.",
  dinossauro: "Dinossauro! Foram extintos por um meteoro. Eu sou extinto por letras erradas.",
  dragao: "Dragão! Se for o Shenlong, pede orelhas pra mim."
};

(function(){
  const F = window.FALAS_FORCA;
  if (!window.Bugado) return;
  const own = Object.assign({}, F);
  // falas específicas viram categorias de 1 fala cada
  const W = window.FALAS_FORCA_PALAVRAS || {};
  for (const k in W) own['forcaW_' + k] = [W[k]];
  // as temáticas somam nas categorias gerais (tagarelice do chatter)
  const extra = { aleatorio: own.forcaAleatorio, parado: own.forcaParado };
  delete own.forcaAleatorio; delete own.forcaParado;
  Bugado.addLines(own);
  Bugado.extendLines(extra);
})();
