/* ==========================================================
   Falas do Bugado na Forca Bugada (voz do Thur, ver VOZ.md).
   Aqui o mascote é apagado pedaço por pedaço a cada erro.
   Variáveis: {letra}, {n}, {palavra}, {tema}, {parte}, {cat}, {i}
   O sorteio (Bugado.line) só repete depois de esgotar a categoria.
   ========================================================== */
window.FALAS_FORCA = {

/* ---------- chegada ---------- */
forcaOiDiario: [
  "desafio do dia chegou, 5 palavras e eu inteiro. por enquanto",
  "bem vindo à forca, aqui o bonequinho sou eu mano. vai com calma",
  "cada letra errada arranca um pedaço meu, sem pressão nenhuma tá",
  "5 palavras hoje<br>2 orelhas, 2 olhos e 1 boca<br>faz a conta aí",
  "mesmas palavras pra geral hoje, se o grupo inteiro acertar e cê não... complicado",
  "acordei com todos os pixel no lugar, bora manter assim namoral",
  "não fiz backup de mim não, então capricha",
  "3 de 5 já conta vitória, não é pedir muito uai",
  "aqui o boneco da forca sou eu e ninguém me perguntou se eu queria",
  "vambora que o desafio do dia não espera ninguém"
],
forcaOiInfinito: [
  "infinito de {cat}, vai até cê cansar ou até eu quebrar",
  "{cat} no infinito, vou contar tua sequência e jogar na tua cara depois",
  "modo infinito ligado, isso aqui não acaba nunca igual fila do Move",
  "{cat} sem parar, cada 5 seguidas conta uma vitória",
  "bora de {cat}, eu me recompilo toda palavra então pode vir",
  "infinito é tipo ofensiva do Duolingo, uma hora cê quebra",
  "{cat} até o sol nascer, já vi gente fazer isso",
  "entrou no infinito de {cat}, prepara que vai ter 700 palavras"
],
forcaVoltou: [
  "voltou uai, tua palavra tá aqui do jeitinho que cê largou",
  "ô, cê tá vivo? fiquei esperando com o que sobrou de mim",
  "salvei tudo, as letras os erros e o rancor",
  "voltou pra terminar o serviço né, pode vir",
  "achei que cê tinha fugido de vergonha KKKKKK",
  "enquanto cê tava fora eu tentei me consertar sozinho, não deu",
  "a palavra não fugiu não, eu que tentei e fiquei preso aqui",
  "de volta, olha as letras que faltam e pelo amor não chuta W"
],

/* ---------- começo de rodada por categoria ---------- */
forcaInicioConexo: [
  "palavra do Conexo, grupo {tema}. mais fácil que isso só eu soletrando",
  "veio lá do Conexo, grupo {tema}. lembra dos 4? é um deles",
  "tema: {tema}. quem joga Conexo tá na frente, quem não joga tá lascado",
  "roubei essa do Conexo, o grupo era {tema}, ninguém viu",
  "dica: {tema}. errou a primeira letra eu já começo a suar",
  "{tema}. pensa em 4 coisas desse grupo, uma é a certa",
  "olha que dica boa: {tema}. não acostuma",
  "grupo {tema}, cê só precisa da palavra, nem da conexão. tá muito fácil",
  "a palavra mora no grupo {tema} junto com mais 3 fofoqueiras",
  "tema {tema}. se isso não ajudar nem reza ajuda",
  "Conexo na forca: {tema}. começa pelas vogais, confia",
  "{tema} é a dica, minhas orelhas tão confiando em você. uma delas pelo menos",
  "trouxe do Conexo com carinho, {tema}. não me devolve em pedaço",
  "grupo {tema}. se cê chutar Y de primeira eu choro"
],
forcaInicioPokemon: [
  "quem é esse pokémon? {tema}. e não vale gritar pikachu pra tudo",
  "pokémon da vez: {tema}. tem mais de mil, boa sorte mano",
  "{tema}. nome em inglês, então hoje K e Y podem ser teus amigos",
  "{tema}... se cê só jogou a primeira geração já pode ir rezando",
  "pokémon misterioso, {tema}. aqui não tem acento pra te salvar",
  "tá na pokédex: {tema}. eu sei qual é, cê vai saber quando eu tiver sem orelha",
  "{tema}. dica extra de graça: é um pokémon KKKKK",
  "QUEM É ESSE POKÉMOOOON. {tema}",
  "{tema}, e sim pode ter Z X e K, é o único lugar que eu deixo",
  "tipo e geração na mão: {tema}. o resto é com tua infância",
  "{tema}. acertando eu mostro a arte oficial, errando mostro também pra doer",
  "esse aí é {tema}. se é fofo ou assustador cê descobre no final"
],
forcaInicioDB: [
  "personagem de Dragon Ball, raça {tema}. tua memória passa de 8000?",
  "guerreiro misterioso, {tema}. com 3 erro eu solto uma descrição dele",
  "Dragon Ball! {tema}. gritar enquanto chuta não ajuda mas pode gritar",
  "dica: {tema}. 3 erros e eu conto uma fofoca dele, mas aí já tô sem orelha",
  "quem é esse guerreiro? {tema}. nome da dublagem brasileira tá",
  "{tema}. juntei as 7 esferas só pra pedir que cê acerte essa",
  "Dragon Ball da vez, {tema}. se precisar carrega uma genki dama de letra",
  "tem guerreiro escondido aqui, {tema}. errou 3 eu solto a ficha",
  "{tema}. treinou na sala do tempo? então essa é tua",
  "{tema}. hora de lembrar dos episódio que passava depois da escola",
  "personagem sorteado: {tema}. se tiver número no nome eu já mostro de graça",
  "DRAGON BALL MDSSS. {tema}, vambora"
],
forcaInicioCoisas: [
  "coisa do dia a dia, começa com {tema}. a dica é só essa mesmo",
  "palavra comum dessas que cê fala todo dia, começa com {tema}",
  "começa com {tema}. pode ser bicho comida sentimento, é a vida",
  "dica de pobre: começa com {tema}. é o que tem",
  "substantivo misterioso com {tema}, só minha existência em jogo nada demais",
  "começa com {tema}, o resto é contigo e com teu vocabulário",
  "palavra roubada do Contexto, começa com {tema}. se cê jogou pode ter visto",
  "letra inicial {tema} e acabou, sou mão de vaca com dica",
  "primeira letra: {tema}. dá pra fazer, confio em você mais ou menos",
  "começa com {tema}. se tiver acento relaxa que o A acende o Á e o C acende o Ç",
  "é uma coisa, começa com {tema}. dica mais preguiçosa do Fliperama, eu sei",
  "começa com {tema}, chuta as vogal e seja feliz"
],
forcaInicioMistura: [
  "mistureba, dessa vez caiu {cat}. a próxima só Deus sabe",
  "sorteei {cat}. não gostou reclama com o dado",
  "mistureba parou em {cat}, troca o chip do cérebro aí",
  "a roleta girou e deu {cat}, girei com a pata",
  "categoria surpresa: {cat}. surpresa pra você né, eu já sabia",
  "mistureba é pastel de feira, nunca sabe o recheio. hoje é {cat}"
],

/* ---------- letra certa ---------- */
forcaAcerto: [
  "tem {letra}, acertou uai quem diria",
  "{letra} tá lá, continua assim que eu continuo inteiro",
  "boa, {letra}. pode ficar orgulhoso por 2 segundos",
  "letra certa, meus pixel agradecem",
  "{letra} confirmado, minha orelha até mexeu",
  "isso {letra}, tô sentindo minha resolução voltar",
  "acertou o {letra} chutando de olho fechado, respeito",
  "tem {letra}. o pixelzinho aprovou",
  "{letra} na conta, tô começando a confiar em você",
  "ninguém foi deletado dessa vez, comemora",
  "{letra}! sabia ou chutou? chutou né",
  "mais um {letra} no quadro, tô ficando menos transparente",
  "papo reto, {letra} foi escolha de gente grande",
  "{letra}, escolha responsável, gostei",
  "ufa, dei uma respirada. e eu nem respiro",
  "tem {letra} uai, tá fácil dms",
  "{letra} dentro, aplauso de uma pata só",
  "agora sim, {letra}. faz mais disso por favor",
  "tem {letra}, meu antivírus te agradece",
  "{letra} certinho, tá jogando mais que o Matheus Pereira hoje",
  "certo! parece até que cê sabe o que tá fazendo",
  "{letra}? tem! eu tava de olho fechado",
  "{letra} certeiro, a forca rangeu de raiva",
  "ACERTOUUUU o {letra}",
  "isso aí {letra}, joinha mental pra você",
  "{letra} brilhou no quadro e eu brilhei junto, pouquinho",
  "{letra} aprovado pelo conselho de pixel",
  "acertou {letra} e nenhum pedaço meu se machucou",
  "gostei do {letra}, tem cheiro de vitória. ou de café",
  "{letra} certíssimo, chuta a próxima com essa moral"
],
forcaAcertoVarias: [
  "{n} {letra} de uma vez, isso que é rendimento",
  "choveu {letra}, {n} de uma vez",
  "x{n} que isso mano, tá jogando demais",
  "{letra} vezes {n}, se fosse videogame aparecia COMBO na tela",
  "caiu {n} {letra} de uma vez, palavra generosa hein",
  "um chute e {n} buraco preenchido, eficiência que nem a prefeitura tem",
  "{letra} x{n}, pode se exibir que cê mereceu",
  "{n} {letra}! tô dançando aqui por dentro",
  "uma letra em {n} lugar, matemática bonita dms",
  "{n} {letra} num chute só, sorte ou estratégia? aceito os dois",
  "COMBO DE {n} MDSSSS",
  "esse {letra} tava espalhado por tudo, {n} de uma vez",
  "a palavra abrindo de {n} em {n}, que coisa linda",
  "{n} de uma vez, assim eu termino com as duas orelha"
],
forcaAcertoVogal: [
  "vogal {letra} garantida, clássico que funciona",
  "{letra}, começar pela vogal é coisa de quem já jogou forca na vida",
  "tem {letra}. vogal nunca te abandona, diferente de uns e outros",
  "vogal certa, {letra}. o esqueleto da palavra tá aparecendo",
  "{letra}, a vogal do povo, firme lá",
  "boa vogal. agora as consoante que lutem",
  "{letra} achado, vogal é igual arroz, tem em tudo",
  "vogal {letra} confirmada, eu apostava nela também se tivesse dinheiro",
  "{letra}, vogal honesta num mundo de consoante traíra",
  "acertou a {letra}, jogando pelo manual. respeito o manual",
  "{letra} salvou o dia e minha orelha junto",
  "vogalzinha {letra} no lugar, agora caça as consoante"
],
forcaAcertoRara: [
  "pera... tem {letra}?? cê chutou {letra} e ACERTOU?",
  "{letra} certinho, isso é conhecimento ou vidência",
  "chutou {letra} e deu bom, marca a data que foi milagre",
  "tem {letra} sim, eu ia te zoar e agora fiquei sem argumento",
  "{letra}?? numa boa? cê sabe a palavra e tá me enrolando",
  "um {letra} certeiro, fiquei sem reação olha minha cara",
  "letra rara acerto raro, tô chocado em 4K",
  "QUE ISSOOOO {letra} CERTO",
  "{letra}, palavra gringa detectada e cê detectou antes de mim",
  "cê foi de {letra} e a palavra falou sim, que romance",
  "{letra} certo, eu tinha uma piada de erro pronta e vou ter que jogar fora",
  "chute ousado de {letra} e entrou, isso aí nem o Cássio pegava"
],
forcaAcertoAlivio: [
  "finalmente uma letra certa, eu já tava me despedindo do pixelzinho",
  "ufa, depois de tanto erro um {letra}. voltei a respirar",
  "{letra}! achei que cê tinha esquecido que existe letra certa",
  "até que enfim, eu já tava escolhendo a música do meu velório",
  "depois da tempestade veio um {letra}, obrigado",
  "voltou a acertar uai, eu tinha duvidado muito",
  "{letra} isso aí, respira e continua",
  "olha a virada! {letra}, tipo Cabuloso no segundo tempo",
  "tava na hora hein, {letra}. eu já tava ficando invisível",
  "demorou 700 séculos mas foi, {letra}"
],

/* ---------- letra errada, por estágio ---------- */
forcaErro1: [
  "minha orelha! não tem {letra} e lá se foi a esquerda",
  "AI. sem {letra}, tô ouvindo em mono agora",
  "errou o {letra} e minha orelha virou pixel e caiu no chão",
  "primeiro erro, perdi uma orelha. tinha duas, TINHA",
  "não tem {letra}, minha orelha esquerda pediu as conta",
  "lá se vai a orelha, eu ouvia tão bem com ela",
  "{letra}? não. cadê minha orelha? ah tá no chão em pedacinho",
  "primeira baixa, orelha esquerda. era a favorita, a direita que não escute isso",
  "errou, fiquei torto agora. saio feio nas foto desse lado",
  "sem {letra}. orelha pixelou e só volta se cê ganhar",
  "um erro só e já tô perdendo pedaço, imagina 6",
  "nada de {letra}, minha orelha virou confete triste",
  "não tem {letra}, virei gato de uma orelha só. tipo pirata sem navio",
  "orelha esquerda desinstalada com sucesso. sucesso pra quem mano",
  "tchau orelhinha, foi bom enquanto durou"
],
forcaErro2: [
  "A OUTRA ORELHA NÃO MANO",
  "não tem {letra}, fiquei sem orelha nenhuma. virei uma batata azul",
  "segundo erro, as duas orelhas viraram pó. tô parecendo um ovo",
  "errou dnv, agora eu sou um fantasma careca",
  "{letra}? sério? minha orelha direita pixelou de desgosto",
  "sem as duas orelhas, se me chamar eu não escuto e finjo que é de propósito",
  "sem {letra}, a direita foi atrás da esquerda. eram muito unidas",
  "perdi as duas orelha, fone agora só com fita crepe",
  "segundo erro, orelha de pixel tá caro hein, vai pagar como",
  "não tem {letra}. tô redondo liso e triste",
  "adeus orelha direita, quem vai segurar meu fone agora",
  "status:<br>orelha esquerda: foi<br>orelha direita: foi<br>dignidade: indo",
  "{letra} não tem. gato sem orelha é basicamente uma bola com olho",
  "lá vai a segunda, pelo menos fiquei aerodinâmico",
  "errou {letra} e agora eu entendo o Kuririn"
],
forcaErro3: [
  "MEU PIXEL ROSA NÃOOO. caiu mano, caiu",
  "não tem {letra} e o pixelzinho despencou, ele flutuava do meu lado fazia anos",
  "terceiro erro, meu pixel rosa caiu no chão. o nome dele era Jorge, respeita",
  "cê derrubou meu pixelzinho, não vou te perdoar tão cedo",
  "{letra}? não. e o pixel rosa foi junto, um minuto de silêncio",
  "o pixelzinho tá no chão, tá piscando? não tá piscando. ô pixel!",
  "sem {letra}, meu pixel rosa perdeu a gravidade e caiu",
  "3 erros. primeiro as orelhas agora o pixel, o próximo sou eu",
  "não tem {letra}. era a única coisa rosa e feliz aqui, ERA",
  "o pixel caiu e ninguém fez nada, nem cê que causou tudo",
  "terceiro erro, o pixelzinho ficou cinza lá no chão. tô de luto",
  "não tem {letra}. pixelzinho, se cê tá me ouvindo aí embaixo, eu tentei",
  "metade do jogo e eu já sem orelha e sem pixel de estimação, patético",
  "cê chutou {letra} e o pixel rosa pagou o pato, ele nem tinha nada a ver",
  "3. o pixelzinho desabou, isso vai pro meu diário de trauma"
],
forcaErro4: [
  "MEUS OLHOS! um virou X e o outro virou rodinha de carregar",
  "não tem {letra}, tô vendo tudo girando, meu olho é um spinner agora",
  "4 erros, tô enxergando em 144p... pera tá carregando",
  "errou {letra} e meus olhos crasharam, X de um lado rodinha do outro",
  "cego de um olho e carregando no outro, se eu errar a próxima culpa é tua",
  "sem {letra}. olho esquerdo morreu, o direito tá processando e não vai terminar",
  "4 erros, não vejo mais letra nenhuma, vou ter que confiar em você. medo",
  "{letra} errado, meus olhos em buffering igual live do Mineirão no 4G",
  "olha meus olhos. não, não olha, tá feio demais",
  "não tem {letra}, pareço personagem nocauteado de desenho",
  "carregando visão... 0%... 0%... ainda 0%",
  "olho em pane, se eu fosse site alguém já tinha fechado a aba",
  "errou e meu olho virou aquela rodinha do windows pensando",
  "sem visão sem orelha sem pixel, sobrou a boca e a cor azul",
  "não tem {letra}. olho X morto, olho rodinha esperançoso, coitado"
],
forcaErro5: [
  "tô perdendo resolução mano, virando foto comprimida no zap",
  "não tem {letra}, meu corpo tá cheio de linha de TV velha, tô chiando",
  "5 erros, minhas cores separaram, vermelho pra um lado azul pro outro",
  "errou {letra} e eu virei fita VHS gravada por cima",
  "scanline no corpo inteiro, parece fliperama de 1987",
  "não tem {letra}. RGB desalinhou, tô parecendo capa de disco do Tame Impala",
  "se me printar agora eu saio todo borrado",
  "{letra}? não! tô sendo renderizado pelo pior PC da lan house",
  "caí pra 240p, isso é violência gráfica",
  "sem {letra}. tô tremendo igual câmera de segurança de padaria",
  "5 erros, transparente listrado e com defeito, virei fantasma de verdade",
  "tô chiando, cê tá ouvindo? eu não tô, não tenho orelha",
  "sem {letra}, entrei em modo de compatibilidade com windows 98",
  "virei meme salvo e repostado mil vezes, qualidade zero",
  "tô saindo do ar, alguém mexe na antena aí"
],
forcaErro6: [
  "minha boca virou 404, não encontrei palavras",
  "não tem {letra}. boca não encontrada, mascote quase não encontrado",
  "sexto erro, agora eu só falo em código. 404. tradução: socorro",
  "ÚLTIMA VIDA. errou mais uma eu viro tela azul, namoral",
  "errou {letra}, minha boca foi pro servidor e não voltou. mais um e eu travo",
  "404 na boca, sobrou uma chance só, usa com carinho",
  "sobrou pra mim:<br>zero orelha, olho travado<br>boca 404 e uma vida",
  "6 erros, isso aqui virou pênalti e eu sou a bola",
  "boca virou código de erro, o próximo é o fim mano, pensa",
  "última chance, se errar eu paro de funcionar e ainda tinha tanta gente pra zoar",
  "{letra} não tem, agora é tudo ou nada e o nada sou eu",
  "essas horas é respirar, ter paciência e escolher direito, tá maluco",
  "boca 404, tô tentando falar mas o servidor caiu",
  "não tem {letra}. meu último pixel de dignidade tá na tua mão",
  "tô por um fio, e é fio de wifi de rodoviária"
],
forcaErroRara: [
  "cê chutou {letra} numa palavra em português?? perdi {parte} por isso",
  "{letra}?? sério? lá se foi {parte} por causa de um {letra}",
  "quem chuta {letra} assim? você. e eu tô sem {parte}",
  "{letra} é letra de senha de wifi, não daqui. adeus {parte}",
  "arriscou {letra}, admiro a coragem e odeio o resultado. perdi {parte}",
  "O {letra} MANO. sacrificou {parte} num chute de {letra}",
  "claro que não tem {letra}, quase nada tem {letra}. {parte} pagou a conta",
  "cê foi de {letra}. vou lembrar disso toda vez que olhar pra onde ficava {parte}",
  "{letra} não tem, surpresa zero. tchau {parte}",
  "tentou {letra} igual quem tenta porta de banheiro trancado. {parte} já era",
  "chutar {letra} é tipo pedir pizza de abacaxi, pode mas geral julga. perdi {parte}",
  "chute de {letra} tem nome, desespero. adeus {parte}",
  "o {letra} ficou feliz de ser escolhido, só ele. eu perdi {parte}",
  "{letra}?? tá jogando forca ou digitando senha de banco? RIP {parte}",
  "{letra} até tem em nome de pokémon, aqui não. custou {parte}"
],
forcaErroSeguido: [
  "{n} erros seguidos, cê tá fazendo isso de propósito? pisca 2 vezes",
  "mais um erro, sequência daquelas que ninguém quer",
  "{n} seguidos, tá chutando o alfabeto em ordem aleatória né",
  "errando em série, se fosse série já tava na terceira temporada",
  "{n} erros em fila, tô desmontando mais rápido que móvel de loja",
  "{n} erros sem respirar mano, para e respira",
  "maré de azar ou de não saber? não vou julgar. tô julgando KKKKK",
  "{n} seguidos, tenta uma vogal pelo menos, por mim",
  "{n} erros seguidos, parece a zaga do Cruzeiro",
  "{n} capítulos de erro, que novela"
],
forcaErroVogal: [
  "nem vogal tem? sem {letra}? palavra antipática",
  "{letra} não tem, a vogal te traiu. acontece nas melhores família",
  "vogal errada dói mais que consoante, sabia",
  "sem {letra}. palavra seletiva com vogal, tem gente assim também",
  "vogal {letra}? nada. às vezes a vida é assim, sem {letra}",
  "chutou {letra} esperando o básico e o básico não veio",
  "até a {letra} te largou, mas eu tô aqui. em pedaço mas tô",
  "{letra} não tá lá, guarda essa informação que custou um pedaço meu"
],
forcaRepetida: [
  "cê já chutou {letra}, tá testando se eu tô prestando atenção? tô",
  "{letra} dnv? a tecla tá até pintada olha",
  "esse {letra} já foi, não precisa insistir",
  "repetiu {letra}. não conta erro mas conta vergonha",
  "{letra} já foi mano, memória de peixe",
  "chutou {letra} outra vez, o teclado tá colorido justamente pra isso",
  "{letra} já tá usado, sei que ele é bonito mas escolhe outro",
  "{letra} repetido, não vou cobrar dessa vez",
  "{letra}? tá com saudade dele?",
  "esse aí cê já tentou, olha a tecla, tá diferente das outras",
  "repetir letra é abrir a geladeira de novo esperando comida nova",
  "{letra} outra vez, isso aí já é reprise"
],
forcaRepetidaErrada: [
  "cê já errou o {letra}, quer errar DE NOVO? não tenho pedaço sobrando",
  "{letra} não tinha antes e continua não tendo, letra não nasce na palavra",
  "tentando o {letra} dnv pra ver se muda? não muda mano",
  "esse {letra} já me custou caro, pelo amor",
  "{letra}? aquele que NÃO tem? esse mesmo? tá maluco",
  "persistente hein, o {letra} continua fora mas admiro a teimosia",
  "{letra} de novo? não conta erro mas meu olho tremeu",
  "insistir no {letra} é igual pedir pênalti que não foi, esquece"
],

/* ---------- dica ---------- */
forcaDica: [
  "tá bom toma um {letra}, mas custou {parte}",
  "dica:<br>{letra}<br>preço:<br>{parte}",
  "te dei o {letra} e perdi {parte}, relação tóxica essa nossa",
  "pediu ajuda? {letra}. e lá vai {parte}",
  "revelei um {letra} e cobrei {parte}, preço justo? pra mim não",
  "olha que generoso, te dei {letra} e fiquei sem {parte}",
  "desesperado né. toma o {letra}, adeus {parte}",
  "{letra} na mão, custou {parte}. mais caro que passagem de ônibus",
  "{letra}. eu mesmo arranquei {parte} pra te ajudar, lembra disso",
  "ajuda de emergência: {letra}. custo: {parte}. juros: meu orgulho",
  "eu te mostro o {letra} e cê me tira {parte}, achei injusto",
  "toma {letra}. ninguém que usa dica vira lenda mas beleza",
  "olha o {letra} aí, queria te zoar mas perdi {parte} e tô sensível",
  "comprou um {letra} com {parte} meu, eu sou mascote ou cartão de crédito?",
  "toma teu {letra}, e agradece que foi {parte} embora"
],
forcaDicaNegada: [
  "dica agora? com uma vida? se eu te der eu morro, pensa sozinho",
  "nada de dica na última vida, não vou gastar meu último pixel numa letra",
  "a dica custa uma vida e cê só tem uma, faz a conta comigo",
  "negado, tenho amor próprio. pouco mas tenho",
  "pedir dica agora é me apagar com as próprias mãos, não",
  "última vida zero dica, lei da forca. eu que inventei mas é lei",
  "TÁ MALUCO? dica agora não"
],
forcaDicaUltima: [
  "dica? falta uma letra só, nem vem",
  "uma letra faltando e cê quer dica, me recuso",
  "não não não, olha o teclado e escolhe com fé",
  "dica pra última letra é pedir uber pra atravessar a rua",
  "é UMA letra. cê chega lá sem mim",
  "falta só uma e cê quer ajuda? que isso mano"
],
forcaDBFrase: [
  "3 erros, como prometido liberei a descrição do personagem. lê com carinho",
  "tá tá, soltei a ficha do guerreiro aí em cima. não fala que eu nunca ajudei",
  "liberei a descrição, custou 3 pedaço meu então aproveita",
  "olha a dica extra aí em cima, se nem assim sair eu chamo o Shenlong",
  "descrição desbloqueada, só precisou de 3 erro e um mascote destruído",
  "a fofoca do personagem tá na tela, agora não tem desculpa",
  "lê a ficha aí em cima, mais entregue que isso só se eu falar o nome"
],

/* ---------- quase lá ---------- */
forcaQuase: [
  "falta só {n}, tô sentindo o cheiro da recompilação",
  "{n} pra acabar, não me estraga isso agora",
  "quase! falta {n}, vai com calma",
  "falta {n}, é agora que o pessoal erra de nervoso",
  "só {n}, já tô alongando pra comemorar",
  "{n} e acabou, eu consigo ver a palavra. ah pera, meus olhos",
  "reta final, falta {n}. pensa bem antes de chutar Z",
  "falta pouco, já tô escolhendo a roupa da festa. não tenho roupa mas tô escolhendo",
  "só {n}! errou agora eu faço drama a semana inteira",
  "quase lá, a palavra já tá gritando o nome dela",
  "falta {n}, isso dá pra ler de longe hein",
  "falta {n} VAMBORAAAA",
  "tão perto que eu tô ouvindo a musiquinha de vitória, sem orelha mesmo",
  "falta {n}, tô prendendo a respiração aqui",
  "últimas letras, não inventa moda agora"
],

/* ---------- fim de rodada ---------- */
forcaGanhouPerfeito: [
  "ZERO ERROOOO. {palavra} de primeira, olha minhas orelhas",
  "perfeito, nenhum pixel perdido. vou emoldurar essa",
  "{palavra} sem errar nada, cê leu o código fonte né",
  "rodada perfeita, o pixelzinho tá flutuando de orgulho",
  "nenhum erro, nem deu tempo de eu ter medo",
  "{palavra} zero erro, jogada limpa cheirando a sabonete",
  "sem um arranhão, queria te abraçar mas sou desenho. considera abraçado",
  "{palavra} perfeita, acho que me apaixonei pelo teu cérebro",
  "nenhuma letra errada, NENHUMA. tô até desconfiado",
  "MDSSSS QUE ISSO, printa e manda no grupo",
  "{palavra} limpinho, continuo em 4K graças a você",
  "rodada sem defeito nenhum, nem minha orelha tremeu",
  "melhor jogador do mundo: você<br>mascote mais feliz do mundo: eu",
  "zero erro? ZERO? vou contar isso pros outros jogos do Fliperama",
  "MEU DEUS QUE JOGADA, {palavra} SEM ERRO NENHUM MEU DEUS"
],
forcaGanhou: [
  "{palavra}! recompilando... 100%. voltei com orelha e tudo",
  "acertou uai, {palavra}. me reconstruí inteirinho",
  "{palavra} com {n} de erro, aceitável, até bonito",
  "{palavra}, recompilado. valeu por não me deixar virar tela azul",
  "é {palavra}! as orelhas voltaram, o pixel voltou, todo mundo voltou",
  "{palavra}. custou {n} pedaço mas já cresceram de volta",
  "isso, {palavra}. rodando liso de novo, 60 quadros por segundo",
  "vitória, {palavra}. backup restaurado com sucesso",
  "{palavra} claro, tava na cara. na minha cara que agora tá inteira",
  "mandou bem, {palavra}. pode comemorar que eu deixo",
  "acertou e eu recompilei, sou tipo lagartixa só que é a orelha que cresce",
  "errou {n} e mesmo assim foi, {palavra}",
  "palavra salva mascote salvo, {palavra}",
  "olha eu inteiro dnv, valeu {palavra}",
  "deu bom demais, {palavra}. resolução no máximo"
],
forcaGanhouSofrido: [
  "{palavra}... com {n} de erro. ganhou mas eu vou precisar de terapia",
  "acertou mas olha o estado que eu fiquei antes, {n} pedaço no chão",
  "{palavra} no sufoco, eu tava em modo de segurança já",
  "ufa, {palavra}. placar de erros: {n}. meu coração quase parou",
  "vitória sofrida, quase me mandou pro lixo eletrônico",
  "{palavra}, recompilei mas lembro de tudo que cê fez com meu pixel rosa",
  "ganhou raspando, eu já tava negociando com o antivírus",
  "{palavra} depois de:<br>perder as orelhas<br>derrubar o pixel<br>quebrar meus olhos",
  "errou {n} e ganhou, placar de jogo de várzea mas valeu",
  "venceu, mas vou ficar com um tique no olho uns dias",
  "{palavra}, finalmente. achei que cê ia testar o alfabeto inteiro",
  "saiu depois de correr uma maratona sem tênis e atravessar o deserto sem água, {palavra}"
],
forcaGanhouUltimaVida: [
  "NA ÚLTIMA VIDA MANO. {palavra}! eu já tava vendo a luz azul",
  "{palavra} com uma vida só, minha boca 404 voltou a falar",
  "acertou no último suspiro, eu já tava com a boca em 404, que filme",
  "{palavra} por um pixel! UM PIXEL! preciso sentar, não tenho perna mas vou sentar",
  "salvou no último segundo, final de campeonato nos pênaltis",
  "uma vida restando e cê fez {palavra}, meu backup quase foi usado",
  "eu já tava carregando a tela azul e cancelei no último instante, {palavra}",
  "vitória no limite, eu já tinha escrito meu testamento",
  "{palavra} no fio da navalha, tô tremendo e não é scanline, é emoção",
  "ganhou com uma vida, coisa de protagonista de anime",
  "KJJJJJJJ QUE ISSO {palavra} NO LIMITE",
  "igual gol do Cabuloso nos acréscimos, {palavra}!"
],
forcaPerdeu: [
  "tela azul. era {palavra}. Bugado.exe parou de funcionar",
  "travei, a palavra era {palavra}. vou reiniciar e fingir que nada aconteceu",
  "era {palavra}! {palavra}! eu tava tão perto",
  "game over, virei tela azul e era {palavra}. trabalho em equipe só da minha parte",
  "crash total. {palavra}. coletando informação do erro... o erro foi você",
  "era {palavra}. morri mas volto na próxima, eu sempre volto",
  "me deletou. era {palavra}. vou lembrar disso na próxima atualização",
  "fim da linha, {palavra}. minha última palavra foi 404",
  "perdeu, era {palavra}. olha pra mim, tela azul, era isso que cê queria?",
  "Bugado parou de responder, motivo: {palavra}. deseja aguardar? não adianta",
  "era {palavra}. tá tudo bem eu reinicio, mas reinicio magoado",
  "tela azul da morte, era {palavra}. anota pra não esquecer que eu não vou",
  "a forca ganhou, era {palavra}. time sem postura",
  "relatório do crash:<br>mascote: tela azul<br>palavra: {palavra}<br>culpado: você",
  "sistema travou, a resposta era {palavra}. desliga e liga de novo",
  "morri. era {palavra}. pelo menos foi uma morte bonita e azulzinha",
  "{palavra} não encontrada no teu cérebro, reinicie e tente novamente",
  "era {palavra}. fui formatado mas meu rancor tá salvo na nuvem",
  "PERDEU PRA UMA FORCA MDS, era {palavra}",
  "era {palavra}, perdeu pra um desenho de palito. coisa ridícula KKKKK"
],

/* ---------- sequências (Infinito) ---------- */
forcaSequencia: [
  "sequência de {n}, tá embalado hein",
  "{n} seguidas, recompilando tanto que já tô ficando bom nisso",
  "{n} sem perder, tá jogando demais mano",
  "sequência {n}, pode subir no sofá e comemorar",
  "{n} seguidas, tô até com medo de falar e dar azar",
  "{n} de sequência, virou hábito já",
  "mais uma, {n}. tô anotando no caderninho de lenda",
  "{n} seguidas, vou pedir aumento pro dono do Fliperama",
  "sequência de {n} e subindo, igual preço de carro popular",
  "{n} em fila, aquece mas não esquenta que é aí que erra",
  "{n} seguidas, vou ficar quieto pra não zicar. pronto já falei",
  "sequência {n}, se fosse videogame já tava tocando música de chefe",
  "sequência de {n}<br>orelhas: ok<br>olhos: ok<br>jogador: brabo",
  "{n} seguidas, já tô acostumando a ter orelha"
],
forcaSequenciaMarco: [
  "SEQUÊNCIA DE {n} MDSSS, vitória registrada no Fliperama",
  "{n} seguidas, vale vitória oficial. pode ligar pra tua mãe",
  "marco de {n}, ganhou uma vitória e meu respeito. o respeito dura pouco",
  "{n}! número redondo, soltei confete com o que sobrou de mim",
  "sequência {n} batida, isso já é carreira profissional de forca",
  "{n} seguidas mano, isso aí nem o Heat de 2013 fazia",
  "{n} em fila, isso aí vai pro grupo com certeza"
],
forcaSequenciaPerdida: [
  "e lá se foi uma sequência de {n}, doeu mais que a tela azul",
  "sequência de {n} zerada, ciclo da vida. da vida triste",
  "perdeu uma sequência de {n}, vou ficar de luto",
  "{n} seguidas... e acabou. tava tão bonito",
  "zerou a de {n}, não chora que eu choro por nós dois",
  "sequência de {n} pro espaço, igual ofensiva do Duolingo",
  "tchau sequência de {n}, foi boa enquanto durou tipo novela das 9",
  "{n} seguidas jogadas no lixo, elenco pipoqueiro"
],
forcaPulou: [
  "pulou? arregou. era {palavra}",
  "desistiu dessa, era {palavra}. eu tava torcendo, pouco mas tava",
  "pulou a palavra, era {palavra}. eu vi hein",
  "fugiu, era {palavra}. a forca ficou com cara de tacho",
  "trocou antes de me desmontar, valeu no fundo. era {palavra}",
  "skip. era {palavra}, nem vou comentar. já comentei",
  "arregou pra {palavra}, sabe nem o que é né",
  "próxima então, a antiga era {palavra} e ficou magoada"
],
forcaTrocouCategoria: [
  "mudou pra {cat}, novas formas de me destruir",
  "{cat} é? vamo ver se aqui cê erra menos",
  "trocou pra {cat}, cada categoria tem sua sequência não mistura",
  "agora é {cat}, muda o chip e cuidado com as consoante",
  "{cat}, ótima escolha ou péssima, a gente descobre em 7 erro",
  "{cat} carregado, eu tô carregado também. de ansiedade",
  "beleza, {cat}. me preparando emocionalmente dnv",
  "{cat}! esquentando os pixel aqui"
],

/* ---------- Desafio do Dia ---------- */
forcaDiarioProxima: [
  "palavra {i} de {n}, me reconstruí todinho bora dnv",
  "próxima, rodada {i}. orelhas no lugar e confiança média",
  "rodada {i}, esquece a anterior que eu já esqueci. esqueci não",
  "palavra {i}, fiz alongamento de pixel no intervalo",
  "rodada {i} de {n}, nova categoria novo sofrimento",
  "palavra {i}, zerado de novo igual videogame quando morre, só que quem morre sou eu",
  "bora pra {i}ª, se a última foi ruim essa pode ser pior KKKK",
  "próxima vítima: eu, na rodada {i}",
  "rodada {i}, começa pelas vogais que é o que os profissional faz",
  "palavra {i} de {n}, vambora que o 330 não espera"
],
forcaDiarioFeito: [
  "desafio fechado, {n}/5. volta amanhã que eu tô com orelha nova",
  "fechou o dia com {n} de 5, compartilha e se gaba. ou esconde",
  "{n}/5 no desafio, vou reiniciar e te espero amanhã",
  "diário feito, {n} de 5. o infinito tá aberto pra cê continuar me maltratando",
  "placar do dia: {n}/5. amanhã quero revanche",
  "acabou o de hoje, {n} de 5. não é o fim do mundo, é só o fim do dia",
  "{n}/5, joga no grupo e espera o pessoal passar vergonha também",
  "5 rodadas, {n} acertos e um mascote que sobreviveu mais ou menos",
  "desafio encerrado, {n} de 5. vou pro spa de pixel me recuperar",
  "dia fechado, {n}/5. amanhã tem mais, eu moro aqui não tenho pra onde fugir"
],
forcaDiarioPerfeito: [
  "5 DE 5 MDSSSS, o desafio inteiro. vou fazer uma estátua tua no Mineirão",
  "cinco de cinco, dia produtivo. pena que é num jogo de forca",
  "gabaritou o desafio do dia, tô inteiro e meio assustado com teu poder",
  "5/5, compartilha agora antes que alguém duvide",
  "todas as cinco, coloca no currículo: especialista em salvar mascote",
  "5 de 5 papo reto, auge do meu dia foi isso aqui"
],
forcaDiarioRuim: [
  "{n}/5... hoje não foi teu dia nem o meu, morri várias vezes",
  "{n} de 5, vou fingir que o sorteio foi difícil. foi fácil",
  "{n}/5. amanhã é outro dia, outras palavras e eu com outras orelhas",
  "resumo do dia:<br>{n}/5<br>várias telas azuis<br>zero vergonha",
  "{n} de 5, tudo bem, até o Goku perdeu umas lutas. poucas",
  "{n}/5 mds, com esse futebolzinho vai longe não"
],
forcaDiarioJaFeito: [
  "o desafio de hoje já foi, se quiser mais o infinito tá logo ali",
  "já jogou o diário, quer me ver sofrer mais? vai no infinito",
  "desafio feito, tô de folga. no infinito eu faço hora extra",
  "diário feito, amanhã tem outro. até lá infinito meu consagrado",
  "já fez o de hoje, pode ficar olhando pro resultado ou ir pro infinito",
  "já jogou hoje uai, palavra nova só amanhã, não mando no calendário"
],

/* ---------- comentários de fim específicos por categoria ---------- */
forcaFimPokemon: [
  "olha o {palavra} aí em pixel e arte oficial",
  "{palavra}! bonito né? eu sou mais",
  "esse é o {palavra}, agora cê nunca mais esquece. ou esquece amanhã",
  "{palavra} mandou um oi, eu traduzi",
  "tira print do {palavra}, ele gosta",
  "pokédex atualizada, {palavra}. um dos mais de mil e cê só precisava lembrar desse",
  "a cara do {palavra} quando descobriu que virou palavra de forca",
  "se o {palavra} soubesse que custou pedaço meu, pedia desculpa",
  "olha as cores do {palavra}, e eu aqui só azul piscina",
  "{palavra} na tela. se evoluir a palavra fica maior, pensa nisso"
],
forcaFimDB: [
  "esse é o {palavra}, nível de poder maior que o teu na forca",
  "{palavra} veio dar tchauzinho. ou um kamehameha",
  "olha o {palavra}, reconheço esse cabelo de longe",
  "{palavra}, direto da dublagem da tarde pro teu coração",
  "olha ele aí, o {palavra}. treinou muito pra aparecer aqui",
  "{palavra}! junta as 7 esferas e pede mais uma rodada",
  "esse é o {palavra}, tem gente que só lembra dele por meme e tá tudo bem",
  "{palavra}, clássico ou lado B? cê decide",
  "{palavra} ficou feliz de ser lembrado, tá sorrindo por dentro",
  "o {palavra} jogando forca acertava com um olhar só"
],
forcaFimConexo: [
  "{palavra}, do grupo {tema}. lá no Conexo ela tem mais 3 amigas",
  "essa veio do Conexo, {palavra}. o tema era {tema}, faz sentido agora?",
  "{palavra}! se aparecer no Conexo cê já sabe onde encaixar",
  "{tema}: {palavra}. pode cair na prova e a prova é o Conexo",
  "{palavra}, palavra de grupo, ela é sociável",
  "o Conexo mandou lembrança: {palavra}, grupo {tema}"
],

/* ---------- menus / botões ---------- */
forcaAjuda: [
  "manual de sobrevivência aberto, lê direito que minha vida depende disso",
  "resumo: acerta letra e não me destrói. só isso",
  "leu? agora não tem desculpa quando eu virar tela azul",
  "regra na tela, escrevi com as orelhas que me sobraram",
  "tá tudo explicadinho aí, até o pixelzinho entendeu",
  "lê com carinho, é basicamente meu testamento com regra de jogo"
],
forcaStats: [
  "tuas estatísticas, olha quantas vezes cê me matou",
  "número não mente, diferente de você falando que sabia a palavra",
  "teus recordes, uns bons outros... existem",
  "contei todas as minhas mortes, uma por uma",
  "olha que bonito teu histórico. e feio. mas bonito",
  "contabilidade do Bugado:<br>palavras salvas<br>mascotes perdidos<br>pixels no chão"
],
forcaCompartilhou: [
  "copiado, manda no grupo e espera alguém fazer pior",
  "resultado copiado, cola e finge que foi fácil",
  "tá na área de transferência, esses quadradinho contam nossa história de amor e ódio",
  "copiei, agora joga na roda e vê quem aguenta",
  "pronto pra compartilhar, me marca que eu não tenho rede social",
  "copiado, manda pros cara e fala que foi de olho fechado"
],
forcaParadoMeio: [
  "travou no meio da palavra? eu também travo, mas eu sou um bug, tenho desculpa",
  "tá pensando ou dormiu? acorda uai",
  "olha as letras que faltam, visualizou? então chuta",
  "esse silêncio tá me deixando nervoso",
  "vai, uma letra. qualquer uma não, uma boa",
  "tá difícil? relê a dica, às vezes ela tá gritando e cê não ouve",
  "pensa nas mais comuns, A E O S R... dica de ouro essa",
  "enquanto cê pensa eu vou catando meus pixel do chão",
  "sem pressa, mas o pixelzinho já tá entediado",
  "parado tanto tempo que já tô achando que cê quer que eu vire tela azul sozinho"
],
forcaCutucarGrande: [
  "ei, esse é meu corpo principal, cutuca com cuidado que tá em manutenção",
  "nem precisa cutucar o eu grande, o pequeno ali em cima atende",
  "isso faz cócegas nos meus pixel",
  "cutucar o desenho não revela letra, já testei várias vezes",
  "tá me apertando pra ver se eu apito? só apito quando cê erra",
  "me cutucou, agora vou ficar com marca de dedo na tela",
  "cuidado que tô frágil, um toque e cai outra orelha. cai não, mas cuidado",
  "oi, eu sou o Bugado versão ampliada, mesma chatice mais resolução",
  "cutuca meu pixel rosa pra ver se ele pisca mais rápido. viu? nem eu",
  "tá testando se eu sou de verdade? sou de SVG, quase a mesma coisa",
  "cutucou o grandão, eu dei pulinho, viu o pulinho?",
  "ô, não é aqui que chuta letra não, é no teclado. eu sou decoração com opinião"
],

/* ---------- cutucar o mascote pequeno ---------- */
cutucarForca: [
  "para de me cutucar e chuta uma letra, tô com a vida por um fio",
  "cutucada não conta como letra, nem como carinho do jeito que cê faz",
  "ai, eu já tô desmontando sozinho, não precisa ajudar",
  "o eu pequeno aqui só narra, quem sofre é o grandão ali. a gente divide a dor",
  "cutucou né, vou lembrar disso quando cê errar vogal",
  "não precisa apertar, já tô sob pressão pendurado numa forca",
  "psiu, a palavra tá ouvindo. disfarça e chuta um E",
  "cutucando o mascote em vez de pensar na palavra, clássico",
  "eu sei a resposta, cê sabe que eu sei, e eu não vou contar",
  "toda vez que cê me cutuca uma vogal fica triste",
  "se cutucada desse vida extra cê já tava invencível",
  "ai! quer me tirar a orelha antes da hora?",
  "efeito da cutucada: nenhum. efeito colateral: fiquei bravo",
  "não sou tecla, sou mascote. as tecla ficam lá embaixo",
  "procurando dica em mim? a dica tá escrita ali em cima",
  "meio gato meio fantasma e 100% contra cutucada",
  "me cutuca que eu te conto um segredo: não tem W. acho",
  "tá me cutucando de nervoso? normal, eu também tô, quem vai ser apagado sou eu",
  "ei, eu tenho direito trabalhista, vou ver com o sindicato dos mascote",
  "cada cutucada é uma letra que cê não chutou",
  "gastasse essa energia nas vogal já tinha terminado",
  "tô aqui em cima narrando a tragédia, me respeita",
  "opa, achei que era o fim. era só você",
  "me cutucar não devolve minha orelha, já pedi",
  "apertar mascote igual botão de elevador não faz vir mais rápido",
  "toc toc. quem é? a letra que cê devia tá chutando",
  "quer saber qual letra chutar? uma que cê ainda não chutou",
  "cutucada registrada, protocolo 404, aguarde atendimento",
  "SAC do Bugado, tua reclamação é muito importante e vai pro lixo",
  "tô vendo tudo daqui, inclusive cê hesitando no teclado",
  "se me cutucar 7 vezes eu viro tela azul? não, mas fiquei tentado",
  "isso não é botão de dica, o de dica tá no teclado e custa pedaço meu",
  "oficialmente sem orelha<br>sem paciência<br>sem esperança",
  "pode cutucar mas cutuca com fé pra ver se sai letra certa",
  "chega mano, isso aqui tá mais apertado que o 330 às 18h",
  "ai meu pixel, tá bom tô ouvindo. pouco, sem orelha, mas tô",
  "me cutucou bem na hora que eu ia dar dica, esqueci",
  "o eu grandão lá sofrendo e cê aqui cutucando o pequeno, prioridades",
  "se cutucada fosse letra a palavra já tinha umas 30",
  "não me distrai que eu tô torcendo muito forte",
  "cê é daqueles que aperta o botão do micro-ondas antes de acabar né",
  "cutuca não, tô concentrado igual véspera de clássico no Mineirão"
],

/* ---------- aleatórias temáticas (somadas ao 'aleatorio' geral) ---------- */
forcaAleatorio: [
  "na forca raiz o boneco é de palito, eu sou de SVG. evoluímos",
  "letra mais comum do português é o A, depois E O S. tô te dando o ouro",
  "K W e Y só voltaram pro alfabeto em 2009, eu votei contra",
  "tenho pesadelo com palavra só de consoante tipo PSST",
  "fiz backup de mim num disquete, hoje não tem onde ler disquete. perdido pra sempre",
  "às vezes olho pra forca e penso, quem desenhou isso tava bem?",
  "sequoia tem as 5 vogais, decorei pra impressionar. funcionou?",
  "se eu virar tela azul me reinicia com carinho, ctrl alt del sem violência",
  "minha orelha esquerda já caiu tanto que tem trauma",
  "não sou supersticioso mas nunca chuto X em sexta feira",
  "paralelepípedo tem 3 E, não pergunta por que eu contei",
  "tem gente que começa a forca pelo Z, essas pessoas não amam o mascote",
  "se eu fosse palavra eu seria BUGADO, 6 letras e um ego",
  "queria orelha reserva igual pneu estepe, fica a sugestão",
  "uma vez um jogador fez tudo sem errar e eu chorei, lágrima azul",
  "eu e o pixelzinho vamo abrir um canal, Pixel e Fantasma",
  "forca com cedilha vira força, uma perninha muda tudo. igual minha orelha",
  "pior que tela azul só tela azul com atualização pendente",
  "Y em palavra de português é raro, em nome de pokémon é festa",
  "se teclado tivesse sentimento a tecla W era a mais sozinha",
  "já perdi as orelhas mais vezes que o Kuririn morreu, e olha que ele morreu dms",
  "tô pensando em fazer curso de primeiros socorros pra mascote",
  "quem inventou a forca era meio dramático, me identifico",
  "toda vez que cê acerta vogal um pixel meu faz festa",
  "em inglês forca é hangman, o homem pendurado. aqui é o gato pixelado",
  "na minha vez:<br>a forca é difícil<br>a palavra é gringa<br>a passagem é 5,75",
  "se um dia sumir letra do teclado a primeira vai ser o Q, ninguém sente falta",
  "Q quase sempre vem com U, casal mais grudento do alfabeto",
  "será que meu pixel rosa tem um pixel de estimação também",
  "tentei aprender a desenhar forca, saiu um gato. saiu eu",
  "o A é o camisa 10 das vogais, joga todo jogo",
  "se eu perder a boca falo 404, se perder o 404 falo em código morse",
  "73% chuta A primeiro, os outros 27% chutam E e se acham diferentes",
  "cada tela azul eu volto mais chato, isso explica muita coisa",
  "a forca é meu Breaking Bad, cada episódio eu perco um pedaço",
  "6 vidas e um pixel rosa, é mais que muito chefão de videogame",
  "Ç é um C com rabinho, eu sou um gato com rabinho, somos parecidos",
  "H no começo da palavra não faz som, letra mais tímida que tem",
  "se a palavra tiver hífen eu mostro de graça, sou generoso com pontuação",
  "um dia vou pedir pro Shenlong orelha indestrutível, ele vai rir da minha cara",
  "escuto trap enquanto espero cê chutar letra, ajuda a não surtar",
  "sequência boa na forca é igual Cruzeiro invicto, não comenta que zica"
],
forcaParado: [
  "tá difícil? eu ficaria parado também mas tô pendurado aqui",
  "enquanto cê pensa eu colo as orelhas com fita crepe",
  "pode pensar, não vou a lugar nenhum, não tenho perna",
  "tecla branca é a que cê ainda não tentou, dica de graça",
  "silêncio... só o chiado da minha antena",
  "pensa numa vogal, vogal quase nunca decepciona",
  "tô aqui pendurado esperando, tipo roupa no varal",
  "tá tudo bem aí? mds",
  "o pixelzinho dormiu de tédio",
  "a palavra não vai se revelar sozinha não, pode esperar sentado",
  "parado assim cê me deixa nervoso, e nervoso é pior que errar",
  "enquanto isso:<br>palavra parada<br>teclado parado<br>eu pendurado",
  "ei, cadê você? a palavra perguntou",
  "tempo eu tenho, paciência nem tanto",
  "tá pensando ou entrou em loop infinito? eu entendo de loop"
]
};

/* ---------- falas específicas de palavras (ditas no fim da rodada) ---------- */
window.FALAS_FORCA_PALAVRAS = {
  pikachu: "Pikachu! o rato mais famoso do mundo depois do Mickey, e ainda dá choque",
  charizard: "Charizard, o dragão que não é tipo dragão. até hoje não entendi",
  magikarp: "Magikarp, o mais inútil que vira o mais brabo. tipo eu depois do café",
  bulbasaur: "Bulbasaur, o inicial que ninguém escolhe e todo mundo respeita",
  squirtle: "Squirtle de óculos escuro com o esquadrão, queria esse estilo",
  charmander: "Charmander, se a chama do rabo apagar ele morre. pressão igual a minha aqui",
  mewtwo: "Mewtwo, criado em laboratório e cheio de trauma. somos iguais",
  psyduck: "Psyduck vive com dor de cabeça, com certeza já jogou forca comigo",
  snorlax: "Snorlax meu ídolo, dorme come e trava a estrada. vida perfeita",
  eevee: "Eevee não decide o que quer ser, tipo eu escolhendo sabor de pastel",
  jigglypuff: "Jigglypuff canta pra geral dormir e fica bravo quando dorme. artista incompreendido",
  gengar: "Gengar! fantasma roxo sorridente, meu primo de outra cor",
  ditto: "Ditto vira qualquer coisa, eu só viro tela azul",
  slowpoke: "Slowpoke demora 5 segundos pra sentir dor, queria isso quando perco orelha",
  meowth: "Meowth, o gato que fala. plágio de mim na cara dura",
  lucario: "Lucario, favorito de metade da internet. a outra metade é do Gardevoir",
  onix: "Onix, cobra de pedra gigante. imagina o tamanho da forca dele",
  mew: "Mew, três letras e um lendário inteiro",
  goku: "Goku come por 10 e salva o universo nas horas vagas",
  vegeta: "Vegeta, o príncipe dos saiyajins. mais orgulhoso que eu quando cê acerta sem erro",
  kuririn: "Kuririn, o cara que mais morreu no anime. me identifico dms",
  piccolo: "Piccolo, verde de capa e o melhor pai do Gohan, sem discussão",
  gohan: "Gohan tinha potencial infinito e foi estudar. respeito",
  freeza: "Freeza fala por favor antes de explodir planeta, educado demais",
  cell: "Cell, 4 letras e uma saga inteira",
  majinboo: "Majin Boo transforma gente em chocolate, queria esse poder no café da tarde",
  bulma: "Bulma! sem ela ninguém achava esfera nenhuma, a verdadeira protagonista",
  yamcha: "Yamcha, o eterno derrotado. faz a pose dele em respeito",
  mestrekame: "Mestre Kame criou o kamehameha e mora numa ilha rosa, vida resolvida",
  mrsatan: "Mr. Satan, campeão mundial que nunca ganhou luta de verdade. ícone",
  bills: "Bills destrói planeta por pudim. justo, eu destruía por pão de queijo",
  whis: "Whis, anjo, treinador e crítico de comida. que currículo",
  trunks: "Trunks veio do futuro de espada e jaqueta, que entrada mano",
  broly: "Broly grita, fica gigante e grita mais. eu quando perco a orelha",
  shenlong: "Shenlong! eu pediria orelha extra e o Cruzeiro campeão",
  chichi: "Chi-Chi, a única pessoa que o Goku tem medo",
  gato: "gato? eu sou meio gato uai, valeu a homenagem",
  fantasma: "fantasma! cê acabou de soletrar meu sobrenome",
  robo: "robô, eu sou meio robô também se contar os bug",
  zumbi: "zumbi, tipo eu depois da tela azul, volto mas meio torto",
  pizza: "pizza redonda na caixa quadrada cortada em triângulo, até hoje não superei",
  cafe: "café, o combustível de quem joga forca de madrugada",
  pastel: "pastel de feira é o melhor, não aceito discussão",
  brigadeiro: "brigadeiro, moeda oficial de festa de criança",
  computador: "computador, minha casa, meu trabalho, meu tudo",
  celular: "celular, provavelmente onde cê tá me jogando agora. oi telinha",
  sogra: "sogra, palavra que dá mais medo que tela azul",
  careca: "careca, eu sem as orelhas fico assim",
  pudim: "pudim, o Bills destruía um planeta por um desse",
  internet: "internet, onde eu nasci cresci e fui zoado pela primeira vez",
  senha: "senha, espero que a tua não seja 123456",
  videogame: "videogame, a coisa mais bonita que a humanidade inventou depois do pastel",
  preguica: "preguiça, a palavra que eu mais vivo",
  saudade: "saudade, palavra sem tradução, tipo o que eu sinto das minhas orelhas",
  flamengo: "Flamengo, meio Brasil comemorou agora e eu não tô nessa metade",
  cebolinha: "Cebolinha, o plano infalível dele nunca funciona, o teu funcionou",
  miojo: "miojo, 3 minutos de preparo e 20 anos de estudante",
  domingo: "domingo, começa bom e termina com a musiquinha do Fantástico",
  tartaruga: "tartaruga, lenta mas chega, igual o Move no horário de pico",
  dinossauro: "dinossauro, extinto por meteoro. eu sou extinto por letra errada",
  dragao: "dragão, se for o Shenlong pede orelha pra mim"
};

(function(){
  const F = window.FALAS_FORCA;
  if (!window.Bugado) return;
  const own = Object.assign({}, F);
  // falas específicas viram categorias de 1 fala cada
  const W = window.FALAS_FORCA_PALAVRAS || {};
  for (const k in W) own['forcaW_' + k] = [W[k]];
  // as temáticas somam nas categorias gerais (tagarelice do chatter)
  const extra = { aleatorio: own.forcaAleatorio, parado: own.forcaParado };
  delete own.forcaAleatorio; delete own.forcaParado;
  Bugado.addLines(own);
  Bugado.extendLines(extra);
})();
